import { beforeEach,describe,it,expect,vi } from "vitest";
const mocks=vi.hoisted(()=>({requireParent:vi.fn(),dbConfigured:vi.fn(),isSameOrigin:vi.fn(),rateLimit:vi.fn(),invitationPreferences:vi.fn(),saveInvitationPreferences:vi.fn(),parentSubscriptions:vi.fn(),saveParentSubscription:vi.fn(),removeParentSubscription:vi.fn(),pushConfiguration:vi.fn()}));
vi.mock("@/lib/auth/session",()=>({requireParent:mocks.requireParent}));vi.mock("@/lib/db/client",()=>({dbConfigured:mocks.dbConfigured}));vi.mock("@/lib/api/guard",()=>({isSameOrigin:mocks.isSameOrigin,rateLimit:mocks.rateLimit}));vi.mock("@/lib/db/notifications",()=>mocks);vi.mock("@/lib/notifications/server",()=>({pushConfiguration:mocks.pushConfiguration}));
import { GET,PUT,POST,DELETE } from "./route";
const request=(method="GET",value?:unknown)=>new Request("https://vidya.test/api/parent/notifications",{method,headers:{"content-type":"application/json"},...(value===undefined?{}:{body:JSON.stringify(value)})});
const prefs={enabled:true,weekday:4,time:"10:00",timezone:"Asia/Kolkata"};
beforeEach(()=>{vi.clearAllMocks();mocks.requireParent.mockResolvedValue({kind:"parent",userId:"owner"});mocks.dbConfigured.mockReturnValue(true);mocks.isSameOrigin.mockReturnValue(true);mocks.rateLimit.mockResolvedValue({ok:true});mocks.invitationPreferences.mockResolvedValue(prefs);mocks.parentSubscriptions.mockResolvedValue([]);mocks.pushConfiguration.mockReturnValue(null);});
describe("parent notification API",()=>{
 it("denies unknown identity and cross-origin requests before reading private state",async()=>{mocks.requireParent.mockResolvedValue(null);expect((await GET(request())).status).toBe(401);mocks.isSameOrigin.mockReturnValue(false);expect((await PUT(request("PUT",prefs))).status).toBe(403);expect(mocks.invitationPreferences).not.toHaveBeenCalled();expect(mocks.saveInvitationPreferences).not.toHaveBeenCalled();});
 it("returns private no-store settings only for authenticated parent",async()=>{const response=await GET(request());expect(response.headers.get("cache-control")).toBe("private, no-store");expect(mocks.invitationPreferences).toHaveBeenCalledWith("owner");expect(await response.json()).toMatchObject({pushAvailable:false,publicKey:null});});
 it("saves bounded validated preferences without permitting parent override",async()=>{expect((await PUT(request("PUT",{...prefs,parentId:"other"}))).status).toBe(400);expect((await PUT(request("PUT",prefs))).status).toBe(200);expect(mocks.saveInvitationPreferences).toHaveBeenCalledWith("owner",prefs);});
 it("fails closed on rate store failure",async()=>{mocks.rateLimit.mockResolvedValue({unavailable:true});expect((await PUT(request("PUT",prefs))).status).toBe(503);expect(mocks.saveInvitationPreferences).not.toHaveBeenCalled();});
 it("does not store or send subscriptions before funded-independent transport config",async()=>{expect((await POST(request("POST",{}))).status).toBe(503);expect(mocks.saveParentSubscription).not.toHaveBeenCalled();});
 it("requires explicit preferences and rejects arbitrary outbound endpoint",async()=>{mocks.pushConfiguration.mockReturnValue({publicKey:"public"});mocks.invitationPreferences.mockResolvedValue({...prefs,enabled:false});expect((await POST(request("POST",{}))).status).toBe(409);mocks.invitationPreferences.mockResolvedValue(prefs);expect((await POST(request("POST",{endpoint:"https://localhost/private",keys:{p256dh:"A".repeat(87),auth:"A".repeat(22)}}))).status).toBe(400);expect(mocks.saveParentSubscription).not.toHaveBeenCalled();});
 it("scopes deletion to caller even when supplied id is another family's",async()=>{const id="8c1f0f2e-843c-4d70-9466-2a53da75dfff";expect((await DELETE(request("DELETE",{id}))).status).toBe(200);expect(mocks.removeParentSubscription).toHaveBeenCalledWith("owner",id);});
});
