import { beforeAll,afterAll,describe,it,expect } from "vitest";
import { integrationDatabaseConfigured } from "@/test/integration-database";
import { getSql } from "./client";
import { invitationPreferences,saveInvitationPreferences,parentSubscriptions,saveParentSubscription,removeParentSubscription,claimInvitation,invitationStillEnabled,finishInvitation } from "./notifications";
const suite=integrationDatabaseConfigured()?describe:describe.skip;
const parent=`invite-parent-${Date.now()}`,other=`${parent}-other`,newSettings=`${parent}-new`;
const prefs={enabled:true,weekday:4,time:"10:00",timezone:"Asia/Kolkata"};
const sub=(n:number)=>({endpoint:`https://fcm.googleapis.com/fcm/send/synthetic-${parent}-${n}`,keys:{p256dh:"A".repeat(87),auth:"A".repeat(22)}});
suite("private weekly invitations",{timeout:60000},()=>{
 beforeAll(async()=>{await getSql()`insert into parents(id) values(${parent}),(${other}),(${newSettings})`;},60000);
 afterAll(async()=>{await getSql()`delete from parents where id in (${parent},${other},${newSettings})`;},60000);
 it("defaults on without creating settings/subscriptions, retaining a saved off setting",async()=>{await getSql()`insert into parent_invitation_preferences(parent_id) values(${newSettings})`;expect((await invitationPreferences(newSettings)).enabled).toBe(true);expect((await invitationPreferences(parent)).enabled).toBe(true);expect(await saveParentSubscription(parent,sub(0))).toBeNull();expect((await invitationPreferences(other)).enabled).toBe(true);expect(await parentSubscriptions(parent)).toEqual([]);await saveInvitationPreferences(other,{...prefs,enabled:false});expect((await invitationPreferences(other)).enabled).toBe(false);await saveInvitationPreferences(parent,prefs);});
 it("keeps subscriptions owned and enforces concurrent five-browser limit",async()=>{const ids=await Promise.all(Array.from({length:8},(_,n)=>saveParentSubscription(parent,sub(n))));expect(ids.filter(Boolean)).toHaveLength(5);await saveInvitationPreferences(other,prefs);expect(await saveParentSubscription(other,sub(ids.findIndex(Boolean)))).toBeNull();const [entry]=await parentSubscriptions(parent);await removeParentSubscription(other,entry.id);expect((await parentSubscriptions(parent)).some(item=>item.id===entry.id)).toBe(true);});
 it("claims each weekly event once across concurrent jobs and preserves minimal outcomes",async()=>{const [entry]=await parentSubscriptions(parent);const candidate={...entry,parentId:parent,subscription:sub(0),preferences:prefs};const claims=await Promise.all(Array.from({length:5},()=>claimInvitation(candidate,"2026-10-08")));expect(claims.filter(Boolean)).toHaveLength(1);await finishInvitation(entry.id,"2026-10-08","sent");expect(await claimInvitation(candidate,"2026-10-08")).toBe(false);const rows=await getSql()`select status from parent_invitation_deliveries where subscription_id=${entry.id}::uuid`;expect(rows[0].status).toBe("sent");});
 it("opt-out revokes every browser and stale candidates cannot send",async()=>{const [entry]=await parentSubscriptions(parent);const candidate={...entry,parentId:parent,subscription:sub(0),preferences:prefs};await saveInvitationPreferences(parent,{...prefs,enabled:false});expect(await parentSubscriptions(parent)).toEqual([]);expect(await invitationStillEnabled(entry.id,parent)).toBe(false);expect(await claimInvitation(candidate,"2026-10-15")).toBe(false);await saveInvitationPreferences(parent,prefs);expect(await parentSubscriptions(parent)).toEqual([]);expect(await saveParentSubscription(parent,sub(0))).not.toBeNull();});
 it("expired endpoints are retired without altering other family preferences",async()=>{const [entry]=await parentSubscriptions(parent);const candidate={...entry,parentId:parent,subscription:sub(0),preferences:prefs};expect(await claimInvitation(candidate,"2026-10-22")).toBe(true);await finishInvitation(entry.id,"2026-10-22","expired");expect(await parentSubscriptions(parent)).toEqual([]);expect((await invitationPreferences(other)).enabled).toBe(true);});
});
