import type { ActivityDomain, Bilingual, LearningActivity } from "./activity";
const pair = (en: string, hi: string): Bilingual => ({ en, hi });
type Challenge = { domain: ActivityDomain; title: Bilingual; objective: Bilingual; prompt: Bilingual; hint: Bilingual; choices: Bilingual[]; correct: number; explanation: Bilingual; interaction?: LearningActivity["interaction"] };
function challenge(domain: ActivityDomain, title: string, titleHi: string, objective: string, objectiveHi: string, prompt: string, promptHi: string, hint: string, hintHi: string, answers: string[], answersHi: string[], correct: number, explanation: string, explanationHi: string, interaction?: LearningActivity["interaction"]): Challenge {
  return { domain, title: pair(title, titleHi), objective: pair(objective, objectiveHi), prompt: pair(prompt, promptHi), hint: pair(hint, hintHi), choices: answers.map((answer, i) => pair(answer, answersHi[i])), correct, explanation: pair(explanation, explanationHi), interaction };
}
const c = challenge;
// References support specific factual checks, not board alignment or age fit.
const FACTUAL_REFERENCES: Record<string, string> = {
  "grade-2-studio-2": "https://openstax.org/books/chemistry-2e/pages/10-3-phase-transitions",
  "grade-6-studio-2": "https://openstax.org/books/chemistry-2e/pages/10-3-phase-transitions",
  "grade-11-studio-5": "https://visionbook.mit.edu/sampling_and_aliasing.html",
};
/** Each row is an authored scenario, not a cosmetic grade variant. These are bounded exploration activities, not complete board coverage. */
const GROUPS: Record<number, Challenge[]> = {
1: [
 c("numeracy","The repeating train","दोहराती रेल","Continue a two-part pattern.","दो हिस्सों का पैटर्न आगे बढ़ाना।","The train goes red, blue, red, blue. What comes next?","रेल के रंग हैं लाल, नीला, लाल, नीला। अगला रंग?","Say the colours in pairs.","रंगों की जोड़ी बोलो।",["Red","Blue","Yellow"],["लाल","नीला","पीला"],0,"Red starts the next red-blue pair.","लाल अगली लाल-नीली जोड़ी शुरू करता है।"),
 c("discovery","Shadow finder","छाया खोजो","Notice that an opaque object blocks light.","देखना कि अपारदर्शी चीज़ रोशनी रोकती है।","A torch shines on a wall. Put a book in the beam. What can appear?","टॉर्च की रोशनी दीवार पर है। बीच में किताब रखो। क्या दिख सकता है?","The book blocks some light.","किताब कुछ रोशनी रोकती है।",["A shadow","A rainbow every time","A louder sound"],["छाया","हर बार इंद्रधनुष","ज़्यादा तेज़ आवाज़"],0,"The blocked light makes a shadow. Never shine a torch into eyes.","रुकी रोशनी से छाया बनती है। आँखों में टॉर्च मत चमकाओ।"),
 c("language","First sounds","पहली आवाज़","Identify a word with the same initial sound in the selected language.","चुनी भाषा में समान शुरुआती आवाज़ वाला शब्द पहचानना।","Which word starts with the same sound as moon?","किस शब्द की शुरुआती आवाज़ माला जैसी है?","Say moon and milk slowly. Listen to the first sound.","माला और मछली धीरे बोलो। पहली आवाज़ सुनो।",["Milk","Sun","Cat"],["मछली","सूरज","बिल्ली"],0,"Milk and moon both start with the /m/ sound.","माला और मछली दोनों की शुरुआत म की आवाज़ से होती है।"),
 c("numeracy","Two basket delivery","दो टोकरियों की गिनती","Combine two small groups.","दो छोटे समूह जोड़ना।","One basket has 2 apples, another has 1. How many altogether?","एक टोकरी में 2 सेब, दूसरी में 1। कुल कितने?","Touch two fingers, then one more.","दो उँगलियाँ दिखाओ, फिर एक और।",["2","3","4"],["2","3","4"],1,"Two and one make three.","दो और एक मिलकर तीन होते हैं।"),
 c("creative","Quiet rhythm","धीमी ताल","Identify a repeating sound pattern.","दोहरती ध्वनि की ताल पहचानना।","Clap, tap, clap, tap. Which sound continues it?","ताली, थपकी, ताली, थपकी। अगली आवाज़?","Repeat the pair gently.","जोड़ी धीरे दोहराओ।",["Clap","Two taps","No repeating pattern"],["ताली","दो थपकियाँ","कोई पैटर्न नहीं"],0,"Clap begins the next pair. Try it quietly on your knees.","ताली अगली जोड़ी शुरू करती है। घुटनों पर धीरे आज़माओ।"),
 c("discovery","Shape detective","आकार की खोज","Identify a triangle by its sides.","भुजाओं से त्रिभुज पहचानना।","Which shape has exactly three straight sides?","किस आकार की ठीक तीन सीधी भुजाएँ हैं?","Count the edges, not the colour.","रंग नहीं, किनारे गिनो।",["Circle","Triangle","Square"],["वृत्त","त्रिभुज","वर्ग"],1,"A triangle has three straight sides.","त्रिभुज की तीन सीधी भुजाएँ होती हैं।"),
 c("social","A place in the game","खेल में जगह","Offer participation without forcing a friend.","बिना दबाव साथी को खेल में बुलाना।","A friend watches your game. What could you say?","एक साथी तुम्हारा खेल देख रहा है। क्या कह सकते हो?","Ask, then let them choose.","पूछो, फिर उन्हें चुनने दो।",["Want to join or watch?","You must play!","You cannot join"],["खेलना चाहोगे या देखना?","खेलना ही होगा!","तुम नहीं खेल सकते"],0,"An invitation leaves room for their choice.","निमंत्रण में साथी के चुनाव की जगह रहती है।"),
 c("real-world","Little leaf observer","पत्ते को देखो","Choose a gentle way to observe a living plant.","जीवित पौधे को ध्यान से, बिना नुकसान देखना।","You want to look closely at a leaf. What is a gentle first step?","पत्ता पास से देखना है। पहले क्या करना ठीक है?","Looking need not remove the leaf.","देखने के लिए पत्ता तोड़ना ज़रूरी नहीं।",["Look without pulling","Pull every leaf","Taste an unknown leaf"],["बिना खींचे देखना","हर पत्ता तोड़ना","अनजान पत्ता चखना"],0,"Notice colour and lines while leaving the plant growing. Do not taste unknown plants.","पौधे को बढ़ने दो और रंग व रेखाएँ देखो। अनजान पौधे मत चखो।"),
 c("language","Story before and after","पहले और बाद की कहानी","Infer a simple event from a short story.","छोटी कहानी से घटना समझना।","Ria put a seed in soil, then watered it. What did she do first?","रिया ने मिट्टी में बीज रखा, फिर पानी दिया। पहले क्या किया?","First means before the next action.","पहले का मतलब अगला काम करने से पहले।",["Watered it","Put a seed in soil","Picked a flower"],["पानी दिया","मिट्टी में बीज रखा","फूल तोड़ा"],1,"The seed went into the soil before watering.","पानी देने से पहले बीज मिट्टी में रखा गया।")
],
2: [
 c("numeracy","Paired socks","जोड़ियों वाले मोज़े","Count equal groups of two.","दो-दो के समान समूह गिनना।","There are 4 pairs of socks. How many socks?","मोज़ों की 4 जोड़ियाँ हैं। मोज़े कितने?","Each pair has two.","हर जोड़ी में दो हैं।",["4","6","8"],["4","6","8"],2,"Four groups of two make eight socks.","दो-दो के चार समूह में आठ मोज़े हैं।"),
 c("discovery","Melt or stay?","पिघलेगा या नहीं?","Distinguish an observable change caused by warmth.","गर्मी से होने वाला दिखने योग्य बदलाव पहचानना।","An ice cube sits in a bowl in a warm room. What usually happens?","गर्म कमरे में कटोरी में बर्फ रखी है। आम तौर पर क्या होगा?","Ice can become liquid water.","बर्फ तरल पानी बन सकती है।",["It melts","It becomes wood","It grows bigger forever"],["पिघलेगी","लकड़ी बनेगी","हमेशा बड़ी होगी"],0,"Warmth can melt ice into liquid water. Use a bowl and keep water away from devices.","गर्मी से बर्फ पानी बन सकती है। कटोरी लो और पानी उपकरणों से दूर रखो।"),
 c("language","Rhyme bridge","तुक का पुल","Notice rhyming endings in the selected language.","चुनी भाषा में अंत की तुक पहचानना।","Which word rhymes with cake?","किस शब्द की तुक रानी से मिलती है?","Say cake and lake slowly. Listen to their endings.","रानी और नानी धीरे बोलो। अंत की आवाज़ सुनो।",["Lake","Chair","Moon"],["नानी","कुर्सी","चाँद"],0,"Cake and lake rhyme because their ending sounds match.","रानी और नानी के अंत की आवाज़ मिलती है, इसलिए उनकी तुक मिलती है।"),
 c("numeracy","Fair fruit share","फल बराबर बाँटो","Share a small quantity equally.","छोटी संख्या को बराबर बाँटना।","Share 8 oranges equally between 2 baskets. How many per basket?","8 संतरे 2 टोकरियों में बराबर बाँटो। हर टोकरी में कितने?","Give one to each basket in turn.","बारी-बारी हर टोकरी में एक रखो।",["2","4","6"],["2","4","6"],1,"Two groups of four use all eight oranges.","चार-चार के दो समूह में आठ संतरे आ जाते हैं।"),
 c("creative","Rhythm with a rest","रुकावट वाली ताल","Recognize silence as part of a rhythm.","ताल में चुप्पी की भूमिका पहचानना।","Tap, rest, tap, rest. What fills the next place?","थपकी, विराम, थपकी, विराम। अगली जगह क्या?","A rest is a planned quiet beat.","विराम जानबूझकर शांत रहने की मात्रा है।",["Rest","Tap","Five fast claps"],["विराम","थपकी","पाँच तेज़ तालियाँ"],1,"Tap begins the next pair. The quiet rests still belong to the rhythm.","थपकी अगली जोड़ी शुरू करती है। शांत विराम भी ताल का हिस्सा है।"),
 c("discovery","Folded paper halves","कागज़ के दो आधे","Identify two equal parts as halves.","दो बराबर भागों को आधे पहचानना।","A rectangle folds so both edges meet exactly. It has two equal parts. Each is what?","आयत ऐसे मोड़ा कि किनारे ठीक मिलें। दो बराबर भाग बने। हर भाग क्या है?","Halves must be equal in size.","आधे भाग आकार में बराबर होते हैं।",["A half","A whole","A quarter"],["आधा","पूरा","चौथाई"],0,"Each of two equal parts is one half.","दो बराबर भागों में हर एक आधा होता है।"),
 c("social","Two ideas for a game","खेल के दो विचार","Try a fair way to handle different preferences.","अलग पसंद होने पर उचित रास्ता ढूँढना।","You want drawing; your friend wants building. What could you try?","तुम चित्र बनाना चाहते हो, साथी चीज़ें बनाना चाहता है। क्या कर सकते हो?","Both ideas can have a turn.","दोनों विचारों की बारी हो सकती है।",["Only my idea counts","Take turns or combine ideas","Stop speaking to them"],["बस मेरा विचार सही","बारी लें या विचार मिलाएँ","बात करना बंद करें"],1,"Taking turns or combining ideas gives both voices space.","बारी लेने या विचार मिलाने से दोनों की बात को जगह मिलती है।"),
 c("real-world","A map to the door","दरवाज़े तक नक्शा","Relate a simple map symbol to a real place.","नक्शे के संकेत को असली जगह से जोड़ना।","Your room map marks the door with a rectangle. What does that mark represent?","कमरे के नक्शे में दरवाज़ा आयत से दिखाया है। यह निशान क्या बताता है?","A map uses marks for places.","नक्शा जगहों के लिए निशान इस्तेमाल करता है।",["The door’s location","The door’s exact weight","Tomorrow’s weather"],["दरवाज़े की जगह","दरवाज़े का ठीक वजन","कल का मौसम"],0,"The symbol shows where the door is, not every fact about it.","संकेत दरवाज़े की जगह बताता है, उसके बारे में हर बात नहीं।"),
 c("language","Lost umbrella clue","छतरी का सुराग","Use a story detail to make a supported inference.","कहानी की बात से उचित अनुमान लगाना।","Aman comes inside with wet shoes and an umbrella. Which clue suggests rain?","अमन भीगे जूते और छतरी लेकर आया। बारिश का सुराग कौन सा है?","Look for water and rain equipment.","पानी और बारिश के सामान पर ध्यान दो।",["His name","Wet shoes and umbrella","The room has a chair"],["उसका नाम","भीगे जूते और छतरी","कमरे में कुर्सी"],1,"These are clues, not proof of every event. You can ask what happened.","ये सुराग हैं, हर घटना का पक्का प्रमाण नहीं। पूछ सकते हो क्या हुआ।")
],
3: [
 c("numeracy","Picnic groups","पिकनिक के समूह","Use multiplication for equal groups.","समान समूहों के लिए गुणा करना।","Five mats each seat 3 people. How many seats altogether?","पाँच चटाइयों पर हर एक में 3 जगह हैं। कुल जगहें?","Add three five times.","तीन को पाँच बार जोड़ो।",["8","15","10"],["8","15","10"],1,"5 × 3 = 15 seats.","5 × 3 = 15 जगहें।"),
 c("discovery","Sun and a drying cloth","धूप और सूखता कपड़ा","Identify a useful comparison in an investigation.","जाँच में उपयोगी तुलना पहचानना।","To compare drying in sun and shade, which should stay the same?","धूप और छाया में सूखना तुलना करने के लिए क्या समान रखें?","Change one important condition.","एक मुख्य दशा बदलो।",["Cloth size and starting wetness","One cloth dry, one soaked","Use different cloths and sizes"],["कपड़े का आकार और शुरुआती नमी","एक सूखा, एक भीगा","अलग कपड़े और आकार"],0,"Matching cloths and wetness helps compare location. Results still depend on wind and warmth.","समान कपड़े और नमी से जगह की तुलना बेहतर होती है। हवा और गर्मी भी असर डालती हैं।"),
 c("language","A message’s purpose","संदेश का उद्देश्य","Identify a purpose from concrete text.","पाठ से स्पष्ट उद्देश्य पहचानना।","A note says: Please return the library book on Friday. Its main purpose?","पर्ची कहती है: पुस्तक शुक्रवार को लौटाएँ। मुख्य उद्देश्य?","Notice the requested action.","माँगे गए काम पर ध्यान दो।",["Remind someone to return a book","Describe a mountain","Tell a joke"],["पुस्तक लौटाने की याद दिलाना","पहाड़ बताना","चुटकुला सुनाना"],0,"The note asks for a specific action and date.","पर्ची में खास काम और दिन बताया है।"),
 c("numeracy","One fourth garden","बगीचे का चौथाई","Calculate a fraction of a small whole.","छोटी पूरी संख्या का भिन्न निकालना।","A garden has 12 pots. One fourth have mint. How many mint pots?","बगीचे में 12 गमले हैं। चौथाई में पुदीना है। ऐसे गमले कितने?","Make four equal groups.","चार बराबर समूह बनाओ।",["4","3","6"],["4","3","6"],1,"12 divided into four equal groups gives 3 in each.","12 को चार बराबर समूह में बाँटने पर हर समूह में 3 हैं।"),
 c("creative","A four-beat phrase","चार मात्राओं का वाक्य","Complete a repeating four-beat rhythm.","चार मात्रा की दोहरती ताल पूरी करना।","Tap, tap, clap, rest repeats. After tap, tap, clap, what next?","थपकी, थपकी, ताली, विराम दोहरता है। थपकी, थपकी, ताली के बाद?","Count four places in the phrase.","वाक्य में चार जगह गिनो।",["Rest","Two claps","Tap"],["विराम","दो तालियाँ","थपकी"],0,"The fourth place is a rest. Replay the phrase at a comfortable volume.","चौथी जगह विराम है। आरामदायक आवाज़ में ताल दोहराओ।"),
 c("discovery","Perimeter path","किनारे की दूरी","Find a rectangle’s perimeter.","आयत का परिमाप निकालना।","A rectangle is 4 units long and 2 units wide. Distance around it?","आयत की लंबाई 4 और चौड़ाई 2 इकाई है। चारों ओर दूरी?","Add the lengths of all four sides.","चारों किनारों की दूरी जोड़ो।",["8","12","6"],["8","12","6"],1,"4 + 2 + 4 + 2 = 12 units.","4 + 2 + 4 + 2 = 12 इकाई।"),
 c("social","Seeing both sides","दोनों पक्ष देखो","Distinguish different needs in a shared situation.","साझा स्थिति में अलग ज़रूरतें पहचानना।","One friend wants quiet, another wants music. What helps first?","एक साथी शांत जगह चाहता है, दूसरा संगीत। पहले क्या मदद करेगा?","Ask about both needs before choosing.","चुनने से पहले दोनों की ज़रूरत पूछो।",["Ask and find quiet/music spaces","Call one selfish","Play louder to win"],["पूछें और अलग शांत/संगीत जगह ढूँढें","एक को स्वार्थी कहें","जीतने के लिए तेज़ बजाएँ"],0,"Different needs can coexist. Consider space, timing and consent.","अलग ज़रूरतें साथ रह सकती हैं। जगह, समय और सहमति सोचो।"),
 c("real-world","Count traffic safely","दूर से वाहनों की गिनती","Choose a safer observation method.","सुरक्षित निरीक्षण तरीका चुनना।","You want to count vehicles. Where is a safer place with a trusted adult?","वाहन गिनना चाहते हो। विश्वसनीय बड़े के साथ सुरक्षित जगह कौन सी?","Keep away from moving traffic.","चलते वाहनों से दूर रहो।",["A safe window or designated viewing area","Middle of the road","Behind a reversing car"],["सुरक्षित खिड़की या तय देखने की जगह","सड़क के बीच","पीछे जाती कार के पीछे"],0,"Observe from a safe place. Do not enter the road for an activity.","सुरक्षित जगह से देखो। गतिविधि के लिए सड़क पर मत जाओ।"),
 c("language","A reliable story summary","कहानी का सही सार","Separate a summary from an added claim.","सार और नई जोड़ी बात अलग करना।","Meena planted beans and watered them daily. Which summary stays with the text?","मीना ने सेम बोई और रोज़ पानी दिया। कौन सा सार पाठ तक रहता है?","Do not add facts not stated.","जो बताया नहीं गया, उसे मत जोड़ो।",["Meena cared for planted beans","Meena owns a huge farm","The beans were ready that day"],["मीना ने बोई सेम की देखभाल की","मीना का विशाल खेत है","उसी दिन सेम तैयार थीं"],0,"The first summary uses only the stated actions.","पहला सार केवल बताई गई घटनाएँ इस्तेमाल करता है।")
],
4: [
 c("numeracy","Bus budget","बस का खर्च","Multiply a unit price by a count.","एक की कीमत को संख्या से गुणा करना।","A ticket costs ₹12. Four tickets cost?","एक टिकट ₹12 का है। चार टिकट कितने के?","Four equal costs are added.","चार समान कीमतें जोड़ो।",["₹16","₹48","₹36"],["₹16","₹48","₹36"],1,"12 × 4 = 48 rupees.","12 × 4 = 48 रुपये।"),
 c("discovery","Plant investigation","पौधे की जाँच","Recognize a fair comparison.","उचित तुलना पहचानना।","Compare light levels for plant growth. Which setup is better?","पौधों की बढ़त पर रोशनी का असर जाँचना है। बेहतर तरीका?","Keep other conditions similar.","बाकी दशाएँ मिलती-जुलती रखो।",["Same plant type, water and soil; different light","Different species, water and soil","Only measure the taller plant"],["समान प्रकार, पानी, मिट्टी; रोशनी अलग","प्रकार, पानी, मिट्टी सब अलग","केवल बड़े पौधे को मापें"],0,"Changing mostly light makes the comparison more informative, though plants still vary.","मुख्यतः रोशनी बदलने से तुलना उपयोगी बनती है, फिर भी पौधे अलग हो सकते हैं।"),
 c("language","Fact or preference?","तथ्य या पसंद?","Distinguish a checkable count from an opinion.","जाँची जा सकने वाली गिनती और राय अलग करना।","Which statement is a preference?","कौन सा कथन व्यक्तिगत पसंद है?","A preference can differ between people.","लोगों की पसंद अलग हो सकती है।",["The box has 6 pencils","Blue is my favourite colour","There are 7 days in a week"],["डिब्बे में 6 पेंसिल हैं","नीला मेरा पसंदीदा रंग है","सप्ताह में 7 दिन हैं"],1,"A favourite colour is a personal preference, not a universal fact.","पसंदीदा रंग व्यक्तिगत पसंद है, सार्वभौमिक तथ्य नहीं।"),
 c("numeracy","Recipe halves","नुस्खे का आधा","Scale a quantity by one half.","किसी मात्रा का आधा निकालना।","A paper recipe card says 300 mL water. Half the amount is?","कागज़ पर नुस्खे में 300 mL पानी है। आधी मात्रा?","Divide by two; no cooking is needed.","दो से भाग दो; खाना पकाना ज़रूरी नहीं।",["150 mL","600 mL","30 mL"],["150 mL","600 mL","30 mL"],0,"300 ÷ 2 = 150 mL. This is a paper calculation.","300 ÷ 2 = 150 mL। यह कागज़ पर गणना है।"),
 c("creative","Rhythm rotation","ताल का घूमना","Track position within a repeated phrase.","दोहरते वाक्य में स्थान समझना।","A phrase is clap, tap, rest. The seventh beat is?","ताल है ताली, थपकी, विराम। सातवीं मात्रा?","Each phrase has three beats. Six finish two phrases.","हर वाक्य में तीन मात्राएँ हैं। छह में दो पूरे वाक्य।",["Clap","Tap","Rest"],["ताली","थपकी","विराम"],0,"Beat seven starts the third phrase with a clap.","सातवीं मात्रा तीसरा वाक्य ताली से शुरू करती है।"),
 c("discovery","Tile a rectangle","आयत में टाइलें","Calculate area using equal square tiles.","बराबर वर्गों से क्षेत्रफल निकालना।","A rectangle has 5 rows of 4 square tiles. How many tiles?","आयत में वर्ग टाइलों की 5 पंक्तियाँ हैं, हर पंक्ति में 4। कुल?","Rows times tiles in each row.","पंक्तियाँ × हर पंक्ति की टाइलें।",["9","18","20"],["9","18","20"],2,"5 × 4 = 20 square tiles.","5 × 4 = 20 वर्ग टाइलें।"),
 c("social","Who was not heard?","किसकी बात नहीं सुनी?","Invite missing perspectives into a group decision.","समूह के निर्णय में छूटी बात शामिल करना।","Two people choose the group project while others are quiet. What helps?","दो लोग परियोजना चुन रहे हैं, बाकी चुप हैं। क्या मदद करेगा?","Quiet can mean many things; invite without forcing.","चुप्पी के कई कारण हैं; बुलाओ, दबाव मत डालो।",["Offer everyone a chance to suggest","Assume silence means agreement","Remove quiet members"],["सबको विचार देने का मौका","चुप्पी को सहमति मानें","चुप सदस्यों को हटाएँ"],0,"An invitation broadens the discussion while respecting the choice to pass.","मौका देने से चर्चा बढ़ती है और न बोलने का चुनाव भी रहता है।"),
 c("real-world","Water-use record","पानी इस्तेमाल का लेखा","Use observation without claiming an unmeasured total.","बिना मापे पूरी मात्रा का दावा न करना।","You count 5 times a tap opens. What do you know?","नल 5 बार खुलते देखा। क्या जानते हो?","An event count is not a water volume.","घटनाओं की संख्या पानी की मात्रा नहीं।",["Exactly 5 litres were used","It opened 5 times during observation","The whole city’s water use"],["ठीक 5 लीटर इस्तेमाल हुए","देखते समय 5 बार खुला","पूरे शहर का पानी इस्तेमाल"],1,"You observed five openings. Volume and use outside that window remain unknown.","पाँच बार खुलना देखा। मात्रा और बाकी समय का इस्तेमाल अज्ञात है।"),
 c("language","Instruction order","निर्देशों का क्रम","Read a condition before an action.","काम से पहले शर्त पढ़ना।","Instructions say: If the paper is dry, fold it. The paper is wet. What now?","निर्देश: कागज़ सूखा हो तो मोड़ो। अभी गीला है। अब?","The condition has not been met.","शर्त अभी पूरी नहीं हुई।",["Wait until dry","Fold immediately","Ignore all conditions"],["सूखने तक रुको","तुरंत मोड़ो","सभी शर्तें छोड़ो"],0,"The instruction applies when the paper is dry.","कागज़ सूखा होने पर निर्देश लागू होता है।")
],
5: [
 c("numeracy","Bookstall change","पुस्तक खरीदने का बचा पैसा","Calculate change with decimal money.","दशमलव रकम में बचा पैसा निकालना।","A book costs ₹37.50. Pay ₹50. Change?","पुस्तक ₹37.50 की है। ₹50 दिए। कितना वापस?","Subtract price from payment.","दिए पैसे में से कीमत घटाओ।",["₹12.50","₹13.50","₹87.50"],["₹12.50","₹13.50","₹87.50"],0,"50.00 − 37.50 = 12.50 rupees.","50.00 − 37.50 = 12.50 रुपये।"),
 c("discovery","Insulation question","ऊष्मा रोकने की जाँच","Identify a controlled variable.","नियंत्रित चर पहचानना।","Compare how two coverings keep water warm. What should match?","दो आवरण पानी गर्म रखने में तुलना करने हैं। क्या समान रखें?","Starting conditions affect cooling.","शुरुआती दशाएँ ठंडा होने पर असर करती हैं।",["Starting temperature and water amount","Only the covering colour","Nothing needs to match"],["शुरुआती तापमान और पानी की मात्रा","केवल आवरण का रंग","कुछ समान न रखें"],0,"Matched starting conditions help compare coverings. Use hypothetical data; do not handle hot water.","समान शुरुआत आवरण की तुलना में मदद करती है। काल्पनिक आँकड़े लो, गर्म पानी मत छुओ।"),
 c("language","Claim and support","दावा और आधार","Identify evidence relevant to a claim.","दावे से संबंधित प्रमाण पहचानना।","Claim: this route is shorter. Which supports it?","दावा: यह रास्ता छोटा है। कौन सा आधार उपयोगी?","Distance is the quantity in the claim.","दावे में दूरी की बात है।",["Measured route lengths","A colourful map","Many people like it"],["मापी गई रास्तों की लंबाई","रंगीन नक्शा","बहुत लोग पसंद करते हैं"],0,"Measured lengths address shorter distance; popularity does not.","मापी लंबाई छोटी दूरी का आधार है; लोकप्रियता नहीं।"),
 c("numeracy","Fraction trail","भिन्नों का रास्ता","Add fractions with a common denominator.","समान हर वाले भिन्न जोड़ना।","A walk covers 2/8 km, then 3/8 km. Total?","पहले 2/8 km चले, फिर 3/8 km। कुल?","Both parts use eighths.","दोनों में आठवाँ भाग है।",["5/16 km","5/8 km","6/8 km"],["5/16 km","5/8 km","6/8 km"],1,"2 eighths plus 3 eighths make 5 eighths.","2 आठवें और 3 आठवें मिलकर 5 आठवें हैं।"),
 c("creative","Tempo and time","गति और समय","Relate tempo to beat spacing.","ताल की गति और मात्राओं की दूरी जोड़ना।","A steady tempo changes from 60 to 120 beats per minute. What happens?","ताल 60 से 120 मात्रा प्रति मिनट होती है। क्या बदलता है?","More beats fit in the same minute.","उसी मिनट में ज़्यादा मात्राएँ आएँगी।",["Beats are twice as far apart","Time between beats halves","The melody must change"],["मात्राएँ दुगनी दूर होंगी","मात्राओं के बीच समय आधा","धुन बदलना ही होगा"],1,"Doubling the tempo halves the time between steady beats.","गति दुगनी करने पर लगातार मात्राओं के बीच समय आधा होता है।"),
 c("discovery","Coordinate campsite","निर्देशांक वाला शिविर","Read ordered coordinates consistently.","निर्देशांक का क्रम पढ़ना।","Start at the origin (0,0). Positive x goes right and positive y goes up. To reach (3,2), which move?","मूल बिंदु (0,0) से चलो। धनात्मक x दाएँ और धनात्मक y ऊपर है। (3,2) तक कौन सी चाल?","The first coordinate describes the horizontal position.","पहला निर्देशांक क्षैतिज जगह बताता है।",["3 right, 2 up","2 right, 3 up","3 down, 2 left"],["3 दाएँ, 2 ऊपर","2 दाएँ, 3 ऊपर","3 नीचे, 2 बाएँ"],0,"From the origin, positive (3,2) means three right and two up.","मूल बिंदु से धनात्मक (3,2) मतलब तीन दाएँ, दो ऊपर।"),
 c("social","An agreement to share","बाँटने की सहमति","Check permission before sharing another person’s work.","दूसरे का काम बाँटने से पहले अनुमति लेना।","A friend shows a drawing privately. Before posting it, what should you do?","साथी ने चित्र निजी तौर पर दिखाया। पोस्ट करने से पहले?","Showing you is not permission to publish.","तुम्हें दिखाना प्रकाशन की अनुमति नहीं।",["Ask for clear permission","Post and ask later","Add their full address"],["स्पष्ट अनुमति पूछो","पोस्ट करके बाद में पूछो","पूरा पता जोड़ो"],0,"Ask first and respect a no. Share only what was agreed.","पहले पूछो और मना करने का सम्मान करो। जितनी सहमति मिली उतना ही बाँटो।"),
 c("real-world","A waste survey sample","कचरे का छोटा सर्वेक्षण","State the limits of a small sample.","छोटे नमूने की सीमा बताना।","You observe one classroom bin for one day. What can you report?","एक दिन एक कक्षा का कूड़ादान देखा। क्या बता सकते हो?","Name the observed place and time.","देखी जगह और समय बताओ।",["What that bin contained in that window","All school waste forever","Every household’s habits"],["उसी अवधि में उस कूड़ेदान की चीज़ें","हमेशा का पूरा स्कूल कचरा","हर घर की आदत"],0,"A sample tells about its observed window; broader claims need broader evidence. Do not handle waste.","नमूना देखी अवधि बताता है; बड़े दावों के लिए बड़ा प्रमाण चाहिए। कचरा मत छुओ।"),
 c("language","Useful revision feedback","सुधार में मददगार बात","Choose specific feedback on a draft.","मसौदे पर स्पष्ट मददगार टिप्पणी चुनना।","A story jumps from a lost key to an open door. Which feedback helps?","कहानी खोई चाबी से सीधे खुले दरवाज़े पर पहुँचती है। मददगार टिप्पणी?","Point to a gap and invite the author’s choice.","छूटी बात बताओ और लेखक को चुनने दो।",["Explain how the door opened","This is terrible","Change every word"],["दरवाज़ा कैसे खुला, बताओ","बहुत खराब है","हर शब्द बदलो"],0,"Specific feedback helps the author decide how to connect events.","स्पष्ट टिप्पणी लेखक को घटनाएँ जोड़ने का तरीका चुनने में मदद देती है।")
],
6: [
 c("numeracy","A proportional paint mix","रंग मिश्रण का अनुपात","Scale a ratio while preserving its relationship.","अनुपात का संबंध रखते हुए मात्रा बढ़ाना।","Blue:red paint is 2:3. If blue is 8 units, red is?","नीला:लाल रंग 2:3 है। नीला 8 इकाई है तो लाल?","Scale both parts by the same factor.","दोनों हिस्सों को समान गुणक से बढ़ाओ।",["9","12","16"],["9","12","16"],1,"Two becomes eight by multiplying by four; three becomes twelve.","दो को चार से गुणा करने पर आठ; तीन को चार से गुणा करने पर बारह।"),
 c("discovery","Evaporation variables","वाष्पीकरण के चर","Separate a changed variable from a measured outcome.","बदला चर और मापा परिणाम अलग करना।","In a paper investigation, equal water amounts expose 20 cm² and 40 cm² to air. Starting temperature and airflow match. Which variable differs?","कागज़ पर जाँच में समान पानी की खुली सतह 20 cm² और 40 cm² है। शुरुआती तापमान और हवा समान हैं। कौन सा चर अलग है?","Look for the setup difference.","व्यवस्था का अंतर देखो।",["Exposed surface area","Starting water amount","The observer’s name"],["खुला सतह क्षेत्र","शुरुआती पानी की मात्रा","देखने वाले का नाम"],0,"Exposed area is deliberately different; water lost over a fixed time is the measured outcome. Dish depth alone does not establish exposed area. This is a paper investigation.","खुली सतह का क्षेत्रफल अलग रखा है; तय समय में कम हुआ पानी मापा परिणाम है। केवल गहराई से खुली सतह तय नहीं होती। यह कागज़ पर जाँच है।"),
 c("language","A cautious conclusion","सावधानी वाला निष्कर्ष","Qualify a conclusion to match its evidence.","निष्कर्ष को प्रमाण की सीमा में रखना।","Two seedlings near a window grew taller this week. Which conclusion is careful?","इस सप्ताह खिड़की के पास दो पौधे बड़े हुए। सावधान निष्कर्ष?","Two plants and one week are a limited window.","दो पौधे और एक सप्ताह सीमित अवधि हैं।",["Window plants always grow fastest","These two grew taller during this week","Light is the only cause of all growth"],["खिड़की वाले हमेशा सबसे तेज़ बढ़ते हैं","इस सप्ताह ये दो पौधे बड़े हुए","हर बढ़त का केवल रोशनी कारण है"],1,"State what was observed and leave wider causal claims open.","जो देखा वही बताओ; बड़े कारण संबंधी दावे खुले रखो।"),
 c("numeracy","Percentage discount","प्रतिशत की छूट","Find a percentage of a whole.","पूरी मात्रा का प्रतिशत निकालना।","A ₹200 item has a 10% discount. How much is the discount?","₹200 की चीज़ पर 10% छूट है। छूट कितनी?","Ten percent is one tenth.","दस प्रतिशत दसवाँ हिस्सा है।",["₹10","₹20","₹180"],["₹10","₹20","₹180"],1,"10% of 200 is 20. The price after discount would be 180.","200 का 10% बीस है। छूट के बाद कीमत 180 होगी।"),
 c("creative","Layer without overload","परतें बिना शोर","Use complementary rhythm roles.","ताल की अलग, पूरक भूमिकाएँ समझना।","A composition has a steady drum pulse. What is a useful first layering experiment?","रचना में ढोल की स्थिर मात्रा है। पहली उपयोगी परत-जाँच?","Keep the pulse recognizable and listen.","मुख्य मात्रा पहचानने योग्य रखकर सुनो।",["Add one contrasting pattern, then listen","Put every sound at maximum volume","Assume more layers always improve it"],["एक अलग पैटर्न जोड़कर सुनो","हर आवाज़ पूरी तेज़ करो","मानो ज़्यादा परतें हमेशा बेहतर"],0,"One layer at a time lets you hear its contribution. Creative choices have no universal best arrangement.","एक-एक परत से उसका योगदान सुन पाते हो। हर रचना का एक ही सर्वश्रेष्ठ तरीका नहीं।"),
 c("discovery","Net of a box","डिब्बे का जाल","Recognize the number of faces of a cube.","घन के फलकों की संख्या पहचानना।","A closed cube’s paper net needs how many square faces?","बंद घन के कागज़ी जाल में कितने वर्ग फलक चाहिए?","Count top, bottom and four sides.","ऊपर, नीचे और चार तरफ गिनो।",["4","6","8"],["4","6","8"],1,"A cube has six square faces. Not every arrangement of six squares folds into a cube.","घन के छह वर्ग फलक हैं। छह वर्गों का हर विन्यास घन नहीं बनाता।"),
 c("social","Consent can change","सहमति बदल सकती है","Respect withdrawal of sharing permission.","साझा करने की अनुमति वापस लेने का सम्मान करना।","A friend first agreed to share a project, then asks to remove it. What helps?","साथी ने पहले परियोजना बाँटने की अनुमति दी, फिर हटाने को कहा। क्या मदद?","Permission is not a permanent obligation.","अनुमति हमेशा की बाध्यता नहीं।",["Respect the request and review the shared copy","Ignore them because they once agreed","Publish their private notes too"],["बात मानकर साझा प्रति की समीक्षा","पुरानी सहमति के कारण अनदेखा","निजी नोट भी प्रकाशित"],0,"Review and remove where you can, explain copies you cannot control, and avoid further sharing.","जहाँ कर सको हटाओ, जिन प्रतियों पर नियंत्रण नहीं उन्हें समझाओ और आगे मत बाँटो।"),
 c("real-world","A timetable conflict","समय-सारिणी का टकराव","Identify overlapping commitments.","एक समय पर आने वाले काम पहचानना।","Art runs 4:00–4:45; practice runs 4:30–5:00. They overlap for?","कला 4:00–4:45; अभ्यास 4:30–5:00 है। कितना समय टकराता है?","The shared interval starts at 4:30 and ends at 4:45.","साझा अवधि 4:30 से 4:45 है।",["15 minutes","30 minutes","45 minutes"],["15 मिनट","30 मिनट","45 मिनट"],0,"The shared interval is fifteen minutes. Adjust the plan rather than pretending both fit.","साझा अवधि पंद्रह मिनट है। दोनों को पूरा मानने की जगह योजना बदलो।"),
 c("language","Search words that help","काम के खोज शब्द","Choose specific terms for an information search.","जानकारी खोजने के लिए स्पष्ट शब्द चुनना।","You need to learn how roots absorb water. Which search is most specific?","जड़ों के पानी सोखने की जानकारी चाहिए। कौन सी खोज सबसे स्पष्ट?","Name the part and process.","हिस्से और प्रक्रिया का नाम लो।",["Interesting things","How plant roots absorb water","All stuff"],["दिलचस्प बातें","पौधों की जड़ें पानी कैसे सोखती हैं","सारी चीज़ें"],1,"Specific terms improve relevance. You still need to check the source and claim.","स्पष्ट शब्द संबंधित नतीजे देते हैं। फिर भी स्रोत और दावा जाँचना होगा।")
],
7: [
 c("numeracy","An equation for supplies","सामान के लिए समीकरण","Solve a one-step linear equation.","एक चरण वाला रैखिक समीकरण हल करना।","Three identical packs contain 24 pencils in total. If each has x, then x=?","तीन समान पैकेटों में कुल 24 पेंसिल हैं। हर पैकेट में x है, तो x=?","3x = 24.","3x = 24।",["6","8","21"],["6","8","21"],1,"Divide both sides by three: x = 8.","दोनों तरफ तीन से भाग: x = 8।"),
 c("discovery","Correlation is a clue","सहसंबंध एक सुराग","Avoid inferring cause from an association alone.","केवल संबंध से कारण न निकालना।","Ice-cream sales and fan use rise on hot days. Does ice-cream cause fan use?","गर्म दिनों में आइसक्रीम बिक्री और पंखे का उपयोग बढ़ते हैं। क्या आइसक्रीम पंखा चलवाती है?","Consider a shared third factor.","एक साझा तीसरा कारण सोचो।",["Yes, association proves cause","Not established; heat can influence both","Fans prove ice-cream is unsafe"],["हाँ, संबंध कारण साबित करता है","सिद्ध नहीं; गर्मी दोनों को प्रभावित करती है","पंखे आइसक्रीम को असुरक्षित साबित करते हैं"],1,"A shared factor can explain an association. More evidence is needed for causation.","साझा कारण संबंध समझा सकता है। कारण साबित करने के लिए और प्रमाण चाहिए।"),
 c("language","Recognize a source gap","स्रोत की कमी पहचानो","Identify a claim that needs attribution.","ऐसा दावा पहचानना जिसे स्रोत चाहिए।","A poster says 90% of everyone prefers this game but names no survey. What is missing?","पोस्टर कहता है 90% लोग यह खेल पसंद करते हैं, पर सर्वेक्षण नहीं बताता। क्या कमी?","Ask who, where, when and how many.","पूछो कौन, कहाँ, कब और कितने।",["Survey source and sample details","More exclamation marks","A brighter background"],["सर्वेक्षण स्रोत और नमूने का विवरण","और विस्मयादिबोधक चिन्ह","चमकीली पृष्ठभूमि"],0,"Without source and sample, the population claim is not verified.","स्रोत और नमूने बिना पूरी आबादी का दावा सत्यापित नहीं।"),
 c("numeracy","Chance in a bag","थैले में संभावना","Calculate probability from equally likely items.","समान संभावना वाली चीज़ों से प्रायिकता निकालना।","A bag has 3 red and 2 blue same-sized tokens. Assume each token is equally likely to be drawn. What is the probability of red?","थैले में समान आकार के 3 लाल और 2 नीले टोकन हैं। हर टोकन के चुने जाने की संभावना समान मानो। लाल की प्रायिकता?","Favourable tokens divided by all tokens.","लाल टोकन की संख्या ÷ कुल टोकन।",["3/5","2/3","1/5"],["3/5","2/3","1/5"],0,"Three of five equally likely tokens are red. Use large tokens only if trying with supervision.","समान संभावना वाले पाँच में तीन लाल हैं। करके देखें तो निगरानी में बड़े टोकन लें।"),
 c("creative","Rhythms meeting again","तालें फिर मिलें","Find a repeat point for two cycles.","दो चक्रों का साझा दोहराव बिंदु निकालना।","One pattern repeats every 3 beats, another every 4. Starting together, after how many beats will their starts first align again?","एक पैटर्न 3, दूसरा 4 मात्राओं में दोहरता है। साथ शुरू होकर कितनी मात्राओं के बाद दोनों फिर पहली बार साथ शुरू होंगे?","Find the smallest common multiple.","सबसे छोटा साझा गुणज खोजो।",["7 beats","12 beats","24 beats"],["7 मात्राएँ","12 मात्राएँ","24 मात्राएँ"],1,"The least common multiple of 3 and 4 is 12.","3 और 4 का लघुत्तम समापवर्त्य 12 है।"),
 c("discovery","Scale drawing","पैमाने का चित्र","Convert a scale length to represented length.","चित्र के पैमाने से असली लंबाई निकालना।","A plan uses 1 cm for 2 m. A wall is 3 cm on the plan. Real length?","नक्शे में 1 cm का अर्थ 2 m है। दीवार चित्र में 3 cm है। असली लंबाई?","Apply the same factor to each centimetre.","हर सेंटीमीटर पर वही गुणक लगाओ।",["1.5 m","5 m","6 m"],["1.5 m","5 m","6 m"],2,"3 × 2 = 6 metres.","3 × 2 = 6 मीटर।"),
 c("social","Disagree with an idea","विचार से असहमत होना","Critique reasoning without attacking a person.","व्यक्ति पर हमला किए बिना तर्क पर बात करना।","A teammate’s plan has a timing problem. Which feedback is useful?","साथी की योजना में समय की समस्या है। उपयोगी टिप्पणी?","Name the problem, not a label for the person.","समस्या बताओ, व्यक्ति पर आरोप मत लगाओ।",["Criticize the teammate without naming the timing problem","These two tasks overlap; can we adjust them?","I will hide your work"],["समय की समस्या बताए बिना साथी की आलोचना करें","दो काम एक साथ हैं; बदल सकते हैं?","तुम्हारा काम छिपाऊँगा"],1,"Specific concerns leave space for collaboration and revision.","स्पष्ट बात सहयोग और सुधार की जगह रखती है।"),
 c("real-world","Mean of observations","निरीक्षणों का औसत","Compute a mean and retain the measurement window.","औसत निकालकर माप की अवधि याद रखना।","Observed waiting times are 2, 4 and 6 minutes. Mean?","देखे प्रतीक्षा समय 2, 4, 6 मिनट हैं। औसत?","Add and divide by the number of observations.","जोड़कर निरीक्षणों की संख्या से भाग दो।",["3 minutes","4 minutes","6 minutes"],["3 मिनट","4 मिनट","6 मिनट"],1,"(2+4+6)/3 = 4. Three observations do not describe all future waits.","(2+4+6)/3 = 4। तीन निरीक्षण भविष्य की हर प्रतीक्षा नहीं बताते।"),
 c("language","Qualify the headline","शीर्षक को सीमित करो","Avoid generalizing a small study in a headline.","शीर्षक में छोटे अध्ययन को सब पर लागू न करना।","Ten volunteers liked a prototype. Which headline fits?","दस स्वयंसेवकों को नमूना पसंद आया। उचित शीर्षक?","Name the sample and the prototype.","नमूना और परीक्षण स्पष्ट करो।",["Everyone loves our app","Ten volunteers reported liking this prototype","Learning doubled for all children"],["हर कोई ऐप पसंद करता है","दस स्वयंसेवकों ने नमूना पसंद बताया","सब बच्चों का सीखना दुगना"],1,"The bounded headline matches the observed report, not unmeasured learning.","सीमित शीर्षक देखी रिपोर्ट से मिलता है, बिना मापे सीखने से नहीं।")
],
8: [
 c("numeracy","Linear journey","रैखिक यात्रा","Evaluate a linear expression.","रैखिक व्यंजक का मान निकालना।","A model gives distance d = 5t + 2. At t = 4, d=?","मॉडल में दूरी d = 5t + 2 है। t = 4 पर d=?","Substitute four, then multiply and add.","चार रखो, गुणा फिर जोड़ो।",["22","28","11"],["22","28","11"],0,"5 × 4 + 2 = 22 model units.","5 × 4 + 2 = 22 मॉडल इकाई।"),
 c("discovery","A simulation’s limit","अनुकरण की सीमा","Distinguish a model prediction from an observation.","मॉडल अनुमान और वास्तविक निरीक्षण अलग करना।","A simulation predicts 20 seedlings survive. What does this establish?","अनुकरण कहता है 20 पौधे बचेंगे। इससे क्या स्थापित होता है?","A model depends on assumptions and inputs.","मॉडल मान्यताओं और जानकारी पर निर्भर है।",["All real gardens will match","A prediction under the model’s assumptions","No real observations are needed"],["हर असली बगीचा वैसा होगा","मॉडल की मान्यताओं में अनुमान","असली निरीक्षण चाहिए ही नहीं"],1,"Test the prediction against observations and revise the model when needed.","अनुमान की वास्तविक निरीक्षण से जाँच करो और ज़रूरत पर मॉडल बदलो।"),
 c("language","Quotation in context","संदर्भ में उद्धरण","Check context before interpreting a quoted phrase.","उद्धरण समझने से पहले संदर्भ जाँचना।","A report is quoted as it may help, but the next sentence states only a small trial. What should a summary keep?","रिपोर्ट कहती है मदद हो सकती है; अगला वाक्य केवल छोटा परीक्षण बताता है। सार में क्या रखें?","Uncertainty and study size affect meaning.","अनिश्चितता और अध्ययन का आकार अर्थ बदलते हैं।",["The uncertainty and trial limit","A claim that it always works","Only the most exciting phrase"],["अनिश्चितता और परीक्षण की सीमा","हमेशा काम करने का दावा","सिर्फ रोमांचक वाक्य"],0,"Keep the qualification so the quote does not become a stronger claim.","सीमा रखो ताकि उद्धरण बड़ा दावा न बन जाए।"),
 c("numeracy","Percentage change","प्रतिशत बदलाव","Calculate percentage increase relative to the initial value.","शुरुआती मान के सापेक्ष प्रतिशत वृद्धि निकालना।","A count rises from 40 to 50. Percentage increase?","संख्या 40 से 50 हुई। प्रतिशत वृद्धि?","The increase is ten, compared with forty.","वृद्धि दस है, तुलना चालीस से।",["10%","20%","25%"],["10%","20%","25%"],2,"10/40 × 100 = 25%.","10/40 × 100 = 25%।"),
 c("creative","Sample and ownership","ध्वनि और अधिकार","Check rights before distributing sampled sound.","ध्वनि बाँटने से पहले अधिकार जाँचना।","You want to publish a track using someone’s recording. First?","किसी की रिकॉर्डिंग से बनी धुन प्रकाशित करनी है। पहले?","Public availability is not a reuse licence.","सार्वजनिक होना पुनः इस्तेमाल की अनुमति नहीं।",["Check the licence and permissions","Assume every online sound is free","Remove the creator’s credit"],["लाइसेंस और अनुमति जाँचें","हर ऑनलाइन ध्वनि मुफ्त मानें","रचनाकार का नाम हटाएँ"],0,"Use original or appropriately licensed sounds and meet attribution conditions.","मौलिक या उपयुक्त लाइसेंस वाली ध्वनि लो और श्रेय की शर्तें पूरी करो।"),
 c("discovery","Volume builder","आयतन बनाओ","Find the volume of a rectangular prism.","घनाभ का आयतन निकालना।","A box is 3 × 4 × 2 units. Volume?","डिब्बा 3 × 4 × 2 इकाई है। आयतन?","Count layers of the base area.","आधार क्षेत्र की परतें गिनो।",["9 cubic units","24 cubic units","18 cubic units"],["9 घन इकाई","24 घन इकाई","18 घन इकाई"],1,"3 × 4 × 2 = 24 cubic units.","3 × 4 × 2 = 24 घन इकाई।"),
 c("social","A boundary in teamwork","समूह में अपनी सीमा","Set a clear respectful boundary.","स्पष्ट सम्मानजनक सीमा बताना।","A group asks you to share a private diary for a project. A useful reply?","समूह परियोजना के लिए निजी डायरी माँगता है। उपयोगी जवाब?","You can contribute without sharing everything.","सब कुछ बाँटे बिना योगदान दे सकते हो।",["I can offer a fictional example; my diary stays private","I must share all private details","I will publish everyone’s diary"],["काल्पनिक उदाहरण दे दूँ; मेरी डायरी निजी रहेगी","सारी निजी बातें देना ही होगा","सबकी डायरी प्रकाशित कर दूँ"],0,"A boundary can coexist with a constructive alternative.","रचनात्मक विकल्प के साथ निजी सीमा भी रह सकती है।"),
 c("real-world","Design for access","सबके लिए उपयोगी डिज़ाइन","Include an alternative to a fine-motor interaction.","बारीक हाथ की चाल का विकल्प देना।","A puzzle requires precise dragging. Which change widens access?","पहेली में बिल्कुल सही खींचना पड़ता है। किससे पहुँच बढ़ेगी?","Different people use different inputs.","लोग अलग तरीकों से नियंत्रण करते हैं।",["Tap and keyboard alternatives","Smaller targets","Drag faster to unlock help"],["टैप और कीबोर्ड विकल्प","छोटे लक्ष्य","मदद के लिए जल्दी खींचो"],0,"Equivalent alternatives preserve the learning goal without requiring one motor skill.","बराबर विकल्प सीखने का उद्देश्य रखते हैं, एक ही शारीरिक कौशल ज़रूरी नहीं करते।"),
 c("language","Versioned instructions","निर्देशों का संस्करण","Identify which instructions apply to a saved task.","सहेजे काम पर लागू निर्देश पहचानना।","You saved version 1; version 2 changes a step. For resuming the exact old task, which record helps?","संस्करण 1 सहेजा था; 2 में चरण बदला। ठीक पुराना काम शुरू करने में क्या मदद?","Identity alone is not a revision.","केवल नाम संस्करण नहीं बताता।",["The original task ID and revision","Only the newest title","The colour of a button"],["मूल काम का ID और संस्करण","केवल नया शीर्षक","बटन का रंग"],0,"Stable identity plus revision identifies the saved instructions.","स्थिर पहचान और संस्करण से सहेजे निर्देश मिलते हैं।")
],
9: [
 c("numeracy","A quadratic area","द्विघात क्षेत्रफल","Evaluate a quadratic expression from a given model.","दिए मॉडल में द्विघात व्यंजक निकालना।","A square has side x+1. At x=3, its area is?","वर्ग की भुजा x+1 है। x=3 पर क्षेत्रफल?","Find the side, then square it.","पहले भुजा, फिर उसका वर्ग।",["8","16","10"],["8","16","10"],1,"The side is 4; area is 4²=16 square units.","भुजा 4 है; क्षेत्रफल 4²=16 वर्ग इकाई।"),
 c("discovery","Control group reasoning","नियंत्रण समूह का तर्क","Identify why a comparison group matters.","तुलना समूह की भूमिका समझना।","A new study method is tested. Why keep a comparable group using the existing method?","नई अध्ययन विधि जाँची जाती है। पुरानी विधि वाला तुलनीय समूह क्यों?","Improvement might happen for other reasons.","सुधार दूसरे कारणों से भी हो सकता है।",["To separate the new method from other changes","To guarantee the new method wins","To exclude every differing result"],["नई विधि को बाकी बदलावों से अलग देखने","नई विधि की जीत तय करने","हर अलग नतीजा हटाने"],0,"A comparable group improves interpretation, but assignment, sample size and measurement still matter.","तुलनीय समूह समझने में मदद करता है; समूह बाँटना, आकार और माप अभी भी ज़रूरी हैं।"),
 c("language","A counterexample matters","विरोधी उदाहरण का महत्व","Use a counterexample against a universal claim.","सार्वभौमिक दावे पर विरोधी उदाहरण इस्तेमाल करना।","Claim: every rectangle is a square. Which observation challenges it?","दावा: हर आयत वर्ग है। कौन सा उदाहरण इसे चुनौती देता है?","A universal claim can fail in one valid case.","हर का दावा एक सही विपरीत उदाहरण से टूट सकता है।",["A rectangle with sides 2 and 5","A square with side 3","A triangle"],["2 और 5 भुजा वाला आयत","3 भुजा वाला वर्ग","त्रिभुज"],0,"A 2-by-5 rectangle has unequal adjacent sides and is not a square.","2-बाय-5 आयत की पास वाली भुजाएँ असमान हैं, इसलिए वह वर्ग नहीं।"),
 c("numeracy","Scale and area","पैमाना और क्षेत्रफल","Relate a length scale factor to area.","लंबाई के गुणक से क्षेत्रफल जोड़ना।","A drawing’s lengths double. Its corresponding area becomes?","चित्र की सभी लंबाइयाँ दुगनी हों। संबंधित क्षेत्रफल?","Both dimensions are scaled.","दोनों विमाएँ बढ़ती हैं।",["Twice","Four times","Unchanged"],["दुगना","चार गुना","समान"],1,"Area scales by the square of the length factor: 2²=4.","क्षेत्रफल लंबाई के गुणक के वर्ग से बदलता है: 2²=4।"),
 c("creative","Audio clipping","ऑडियो का कटना","Recognize why excessive digital level can distort sound.","बहुत अधिक डिजिटल स्तर से विकृति समझना।","A signal’s peaks exceed the maximum level its output format can represent. What can happen?","संकेत के शिखर आउटपुट प्रारूप में दिख सकने वाले अधिकतम स्तर से बड़े हैं। क्या हो सकता है?","Peaks outside the output range may be clipped.","आउटपुट सीमा से बाहर शिखर कट सकते हैं।",["Clipping and distortion","Guaranteed higher quality","A longer song automatically"],["कटना और विकृति","निश्चित बेहतर गुणवत्ता","अपने आप लंबा गीत"],0,"Peak clipping can distort sound. Lower gain and compare at a comfortable listening level.","शिखर कटने से ध्वनि बिगड़ सकती है। गेन घटाओ और आरामदायक स्तर पर तुलना करो।"),
 c("discovery","Slope from two points","दो बिंदुओं से ढलान","Compute a line’s slope.","रेखा की ढलान निकालना।","A line passes through (1,2) and (3,6). Slope?","रेखा (1,2) और (3,6) से जाती है। ढलान?","Change in y divided by change in x.","y में बदलाव ÷ x में बदलाव।",["1","2","4"],["1","2","4"],1,"(6−2)/(3−1)=4/2=2.","(6−2)/(3−1)=4/2=2।"),
 c("social","A group’s private details","समूह की निजी बातें","Distinguish project sharing from personal-data sharing.","परियोजना और निजी जानकारी साझा करना अलग करना।","A project result can be public. Which should still need separate permission?","परियोजना का नतीजा सार्वजनिक हो सकता है। किसे अलग अनुमति चाहिए?","A project agreement does not cover every personal detail.","परियोजना की सहमति हर निजी बात नहीं ढकती।",["Members’ private contact details","A deliberately public project title","A public diagram whose licence permits this use"],["सदस्यों की निजी संपर्क जानकारी","जानबूझकर सार्वजनिक शीर्षक","इस उपयोग की अनुमति वाला सार्वजनिक चित्र"],0,"Share only agreed material; keep private contact information out of public projects.","केवल सहमत सामग्री बाँटो; निजी संपर्क जानकारी सार्वजनिक परियोजना से बाहर रखो।"),
 c("real-world","Budget with a reserve","खर्च और बचत की जगह","Account for a reserve before allocating resources.","संसाधन बाँटने से पहले बचत की जगह रखना।","A project has ₹500 and keeps ₹100 as reserve. Maximum planned spending?","परियोजना में ₹500 हैं; ₹100 आरक्षित हैं। नियोजित खर्च की सीमा?","Subtract the reserve first.","पहले आरक्षित राशि घटाओ।",["₹400","₹500","₹600"],["₹400","₹500","₹600"],0,"The available planned amount is 500−100=400. This is a fictional budget exercise.","नियोजित उपलब्ध राशि 500−100=400 है। यह काल्पनिक बजट अभ्यास है।"),
 c("language","Debug the condition","शर्त की त्रुटि खोजो","Trace an if-condition accurately.","यदि वाली शर्त ठीक से समझना।","Rule: if score is at least 10, show ready. Score is 10. Output?","नियम: अंक कम से कम 10 हों तो तैयार दिखाओ। अंक 10 हैं। परिणाम?","At least includes the boundary.","कम से कम में सीमा भी शामिल है।",["Ready","Not ready","No valid output"],["तैयार","तैयार नहीं","कोई सही परिणाम नहीं"],0,"10 satisfies score ≥10. Boundary cases help test conditions.","10, अंक ≥10 की शर्त पूरी करता है। सीमा के उदाहरण शर्त जाँचते हैं।")
],
10: [
 c("numeracy","Two unknowns","दो अज्ञात","Solve a simple simultaneous-equation system.","सरल युगपत समीकरण हल करना।","x+y=7 and x−y=1. What is x?","x+y=7 और x−y=1। x क्या है?","Adding equations eliminates y.","समीकरण जोड़ने पर y हटता है।",["3","4","6"],["3","4","6"],1,"2x=8, so x=4 and y=3.","2x=8, इसलिए x=4 और y=3।"),
 c("discovery","Repeated measurements","दोहराए माप","Understand why measurements are repeated.","माप दोहराने का कारण समझना।","Why measure a quantity more than once under similar conditions?","मिलती-जुलती दशाओं में मात्रा बार-बार क्यों मापें?","A single reading can be unrepresentative.","एक माप बाकी मापों से अलग हो सकता है।",["To examine variation and reduce random-error effects","To erase all systematic bias","To choose only a favourite result"],["फैलाव देखें और यादृच्छिक त्रुटि का असर घटाएँ","हर व्यवस्थित पक्षपात मिटाएँ","सिर्फ पसंद का नतीजा चुनें"],0,"Repetition helps characterize variation; a biased instrument can remain biased.","दोहराव से फैलाव समझ आता है; पक्षपाती यंत्र फिर भी पक्षपाती रह सकता है।"),
 c("language","Recognize selective evidence","चुनिंदा प्रमाण पहचानना","Recognize cherry-picking in an argument.","तर्क में केवल पसंद का प्रमाण चुनना पहचानना।","A review includes only positive trials and omits comparable negative trials. Concern?","समीक्षा में केवल सकारात्मक परीक्षण हैं; तुलनीय नकारात्मक छूटे। चिंता?","Ask what evidence was left out.","पूछो कौन सा प्रमाण छोड़ दिया।",["Selection bias in the evidence","Proof that every trial succeeded","No need to examine methods"],["प्रमाण चुनने में पक्षपात","हर परीक्षण की सफलता का प्रमाण","विधि जाँचना अनावश्यक"],0,"Comparable opposing results should be considered with their methods and limits.","तुलनीय विपरीत नतीजे उनकी विधि और सीमाओं के साथ देखना चाहिए।"),
 c("numeracy","Independent coin trials","स्वतंत्र सिक्का परीक्षण","Calculate probability for independent events.","स्वतंत्र घटनाओं की प्रायिकता निकालना।","A fair coin is tossed twice independently. Probability of two heads?","निष्पक्ष सिक्का दो बार स्वतंत्र उछले। दोनों बार चित की संभावना?","Multiply one half by one half.","आधा × आधा।",["1/2","1/4","3/4"],["1/2","1/4","3/4"],1,"P(HH)=1/2×1/2=1/4 under the stated fair, independent model.","बताए निष्पक्ष, स्वतंत्र मॉडल में P(HH)=1/2×1/2=1/4।"),
 c("creative","Tempo stretch","ताल की समय खिंचावट","Relate fixed beat count and tempo to duration.","स्थिर मात्राओं और गति से अवधि जोड़ना।","A 60-beat phrase plays at 120 beats/minute. Its duration?","60 मात्रा की ताल 120 मात्रा/मिनट पर चले। अवधि?","Duration = beats divided by beats per minute.","अवधि = मात्राएँ ÷ प्रति मिनट मात्राएँ।",["30 seconds","60 seconds","120 seconds"],["30 सेकंड","60 सेकंड","120 सेकंड"],0,"60/120 minute = 0.5 minute = 30 seconds.","60/120 मिनट = 0.5 मिनट = 30 सेकंड।"),
 c("discovery","Quadratic roots","द्विघात के मूल","Solve a factorable quadratic.","गुणनखंड वाले द्विघात को हल करना।","x²−5x+6=0. Which pair gives its roots?","x²−5x+6=0। मूलों की जोड़ी?","Find two numbers multiplying to six and summing to five.","दो संख्याएँ खोजो: गुणनफल छह, योग पाँच।",["1 and 6","2 and 3","−2 and −3"],["1 और 6","2 और 3","−2 और −3"],1,"(x−2)(x−3)=0, so roots are 2 and 3.","(x−2)(x−3)=0, इसलिए मूल 2 और 3।"),
 c("social","Different comfort with AI","AI के साथ अलग सहजता","Respect a teammate’s choice about optional AI use.","वैकल्पिक AI पर साथी की पसंद का सम्मान करना।","A teammate prefers to write without AI. A fair project approach?","साथी AI के बिना लिखना पसंद करता है। उचित तरीका?","Agree on goals and offer genuine alternatives.","लक्ष्य तय करें और वास्तविक विकल्प दें।",["Offer a non-AI contribution path","Exclude them automatically","Upload their private notes to AI"],["बिना AI योगदान का रास्ता दें","तुरंत बाहर करें","निजी नोट AI को भेजें"],0,"Optional tools should not require surrendering privacy or participation.","वैकल्पिक साधनों के लिए गोपनीयता या भागीदारी छोड़ना ज़रूरी नहीं।"),
 c("real-world","Capacity planning","क्षमता की योजना","Identify a feasible plan with stated capacity.","दी गई क्षमता में संभव योजना पहचानना।","You have 90 minutes. Tasks need 40 and 35; a break needs 10. Do they fit?","90 मिनट उपलब्ध हैं। काम 40 और 35, विराम 10 मिनट। समाएँगे?","Include the break in the sum.","जोड़ में विराम भी लो।",["Yes, 85 minutes total","No, 95 minutes total","Only if the break is hidden"],["हाँ, कुल 85 मिनट","नहीं, कुल 95 मिनट","विराम छिपाने पर ही"],0,"40+35+10=85, leaving five minutes. Estimates may change, so keep the plan editable.","40+35+10=85, पाँच मिनट बचेंगे। अनुमान बदल सकते हैं; योजना बदलने योग्य रखो।"),
 c("language","Report method and limits","विधि और सीमाएँ बताओ","Choose details that make a result interpretable.","नतीजा समझने के लिए ज़रूरी विवरण चुनना।","A project reports success. Which details make that claim useful?","परियोजना सफलता बताती है। कौन सा विवरण इसे उपयोगी बनाता है?","Define success and how it was measured.","सफलता का अर्थ और माप बताओ।",["Method, sample, measured outcome and limitations","Only a celebration image","An unverified world-best claim"],["विधि, नमूना, मापा परिणाम और सीमाएँ","केवल उत्सव का चित्र","बिना प्रमाण दुनिया में सर्वोत्तम का दावा"],0,"Specific evidence supports assessment while leaving uncertainty visible.","स्पष्ट प्रमाण आकलन में मदद करता है और अनिश्चितता दिखती रहती है।")
],
11: [
 c("numeracy","Rate from a curve","वक्र से बदलाव की दर","Evaluate a given derivative at a point.","दिए अवकलज का बिंदु पर मान निकालना।","For f(t)=t², the rate is f′(t)=2t. At t=3, rate?","f(t)=t² के लिए दर f′(t)=2t है। t=3 पर दर?","Substitute into the given rate expression.","दिए दर व्यंजक में मान रखो।",["3","6","9"],["3","6","9"],1,"2×3=6 units of output per unit of t.","2×3=6, t की प्रति इकाई पर परिणाम की इकाई।"),
 c("discovery","Uncertainty interval","अनिश्चितता की सीमा","Interpret a measurement interval without false precision.","झूठी सटीकता बिना माप सीमा समझना।","A measurement is reported as 10.0 ±0.2 units. What interval does this notation state?","माप 10.0 ±0.2 इकाई है। बताई सीमा?","Subtract and add the stated uncertainty.","बताई अनिश्चितता घटाओ और जोड़ो।",["9.8 to 10.2","0.2 to 10.0","Exactly 10.000 forever"],["9.8 से 10.2","0.2 से 10.0","हमेशा ठीक 10.000"],0,"The stated interval is 9.8–10.2. Its statistical meaning depends on the method used.","बताई सीमा 9.8–10.2 है। सांख्यिकीय अर्थ माप की विधि पर निर्भर है।"),
 c("language","Necessary or sufficient?","ज़रूरी या पर्याप्त?","Distinguish a necessary condition from a guarantee.","ज़रूरी शर्त और निश्चित नतीजा अलग करना।","Water is needed for this plant to grow. Does water alone guarantee growth?","इस पौधे की बढ़त के लिए पानी चाहिए। क्या अकेला पानी बढ़त तय करता है?","A necessary ingredient may not be sufficient.","ज़रूरी चीज़ अपने आप पर्याप्त नहीं होती।",["Yes, nothing else matters","No; other conditions also matter","Water is never relevant"],["हाँ, और कुछ मायने नहीं","नहीं; बाकी दशाएँ भी ज़रूरी","पानी कभी उपयोगी नहीं"],1,"A necessary condition must hold, but other conditions may still be required.","ज़रूरी शर्त पूरी होनी चाहिए, पर दूसरी शर्तें भी आवश्यक हो सकती हैं।"),
 c("numeracy","Weighted mean","भारित औसत","Calculate a weighted average.","भारित औसत निकालना।","A model gives scores 60 and 80 weights of 25% and 75%, respectively. Weighted mean?","मॉडल 60 को 25% और 80 को 75% भार देता है। भारित औसत?","Use 0.25×60 + 0.75×80.","0.25×60 + 0.75×80 लो।",["65","75","140"],["65","75","140"],1,"15+60=75. The weights add to 100%. A chosen weight is a modelling decision, not a universal value judgement.","15+60=75। भारों का योग 100% है। भार चुनना मॉडल का निर्णय है, सार्वभौमिक मूल्यांकन नहीं।"),
 c("creative","Sampling bandwidth","नमूना दर और आवृत्ति","Apply a stated sampling condition.","दी गई नमूना शर्त लागू करना।","For an ideal band-limited signal with maximum frequency 5 kHz, the sampling theorem requires a rate greater than?","आदर्श सीमित-बैंड संकेत की अधिकतम आवृत्ति 5 kHz है। नमूना प्रमेय में दर किससे अधिक?","More than twice the maximum frequency.","अधिकतम आवृत्ति के दुगने से अधिक।",["2.5 kHz","5 kHz","10 kHz"],["2.5 kHz","5 kHz","10 kHz"],2,"Greater than 10 kHz satisfies this idealized condition; real filters and systems have additional constraints.","10 kHz से अधिक इस आदर्श शर्त को पूरा करता है; वास्तविक फ़िल्टर और तंत्रों की और सीमाएँ हैं।"),
 c("discovery","Exponential steps","घातीय चरण","Recognize multiplicative rather than additive growth.","जोड़ की जगह गुणन वाली बढ़त पहचानना।","A model doubles each step: 3,6,12. Next value?","मॉडल हर चरण दुगना: 3,6,12। अगला मान?","Multiply the latest value by two.","आखिरी मान को दो से गुणा करो।",["18","24","15"],["18","24","15"],1,"The next model value is 24. Real growth rarely follows unlimited doubling.","अगला मॉडल मान 24 है। वास्तविक बढ़त अनंत दुगनेपन जैसी बहुत कम होती है।"),
 c("social","Credit shared work","साझा काम का श्रेय","Recognize contributions without exposing private information.","निजी जानकारी बिना योगदान को श्रेय देना।","A team publishes a project. Which attribution is useful?","समूह परियोजना प्रकाशित करता है। उपयोगी श्रेय?","Agree on how each person wants to be credited.","पूछो हर व्यक्ति कैसा श्रेय चाहता है।",["Agreed names or pseudonyms and contribution roles","Private contact information by default","Claim one person did everything"],["सहमत नाम/उपनाम और योगदान भूमिकाएँ","निजी संपर्क जानकारी अपने आप","एक व्यक्ति ने सब किया कहें"],0,"Credit can respect both contribution and privacy.","योगदान और गोपनीयता दोनों का सम्मान करते हुए श्रेय दिया जा सकता है।"),
 c("real-world","Trade-off record","विकल्पों का लेखा","Make constraints and trade-offs explicit.","सीमाएँ और समझौते स्पष्ट करना।","Two designs differ in cost and accessibility. Before choosing, record what?","दो डिज़ाइन खर्च और पहुँच में अलग हैं। चुनने से पहले क्या दर्ज करें?","Different perspectives may value different outcomes.","अलग नज़रिए अलग परिणामों को महत्व दे सकते हैं।",["Criteria, evidence, constraints and unresolved uncertainty","Only the cheapest label","Only the newest technology"],["मानदंड, प्रमाण, सीमाएँ और बाकी अनिश्चितता","केवल सबसे सस्ते का नाम","केवल नई तकनीक"],0,"A decision record makes the trade-off reviewable rather than hiding it.","निर्णय का लेखा समझौते को छिपाने की जगह जाँचने योग्य करता है।"),
 c("language","Reproducible explanation","दोहराकर जाँचा जा सकने वाला विवरण","Identify information needed to reproduce a calculation.","गणना दोहराने के लिए ज़रूरी जानकारी पहचानना।","To check a reported calculation, what should accompany the answer?","बताई गणना जाँचना हो तो जवाब के साथ क्या चाहिए?","Someone else needs the same inputs and steps.","दूसरे को वही जानकारी और चरण चाहिए।",["Inputs, units, method and version","Only the final number","An impressive title"],["इनपुट, इकाइयाँ, विधि और संस्करण","केवल आखिरी संख्या","प्रभावशाली शीर्षक"],0,"Documented inputs and steps enable checking; private inputs should be redacted or replaced with safe examples.","दर्ज जानकारी और चरण जाँच संभव करते हैं; निजी जानकारी हटाएँ या सुरक्षित उदाहरण दें।")
],
12: [
 c("numeracy","Accumulation from a rate","दर से संचय","Calculate accumulation for a constant rate.","स्थिर दर से कुल संचय निकालना।","A model’s constant rate is 4 units/minute for 3 minutes. Accumulated quantity?","मॉडल की दर 4 इकाई/मिनट, अवधि 3 मिनट है। कुल मात्रा?","For a constant rate, multiply by duration.","स्थिर दर को अवधि से गुणा करो।",["7 units","12 units","4/3 units"],["7 इकाई","12 इकाई","4/3 इकाई"],1,"4×3=12, the area under this constant rate-time graph.","4×3=12, इस स्थिर दर-समय ग्राफ के नीचे का क्षेत्रफल।"),
 c("discovery","Before seeing the results","नतीजे देखने से पहले","Recognize a benefit of predefining an evaluation.","पहले से मूल्यांकन तय करने का लाभ समझना।","Why define the main outcome and analysis before seeing results?","नतीजे देखने से पहले मुख्य परिणाम और विश्लेषण क्यों तय करें?","It makes selective changes easier to identify.","इससे चुनिंदा बदलाव पहचानना आसान होता है।",["To reduce undisclosed cherry-picking","To guarantee a positive result","To forbid every justified update"],["छिपे चुनिंदा विश्लेषण घटाने","सकारात्मक नतीजा तय करने","हर उचित बदलाव रोकने"],0,"A predefined plan improves transparency; justified deviations should be recorded, not concealed.","पूर्व योजना पारदर्शिता बढ़ाती है; उचित बदलाव दर्ज करें, छिपाएँ नहीं।"),
 c("language","A cited claim’s boundary","स्रोत वाले दावे की सीमा","Match a claim to what a source actually supports.","दावे को स्रोत के वास्तविक समर्थन से मिलाना।","A source studies adults in one city. Can it prove an effect for every child worldwide?","स्रोत एक शहर के वयस्कों का अध्ययन करता है। क्या हर बच्चे पर विश्व भर का असर साबित है?","Population and setting limit generalization.","आबादी और जगह व्यापक निष्कर्ष सीमित करते हैं।",["Yes, a citation proves every claim","No; that broader population was not studied","Only the source title matters"],["हाँ, स्रोत हर दावा साबित करता है","नहीं; उस व्यापक आबादी का अध्ययन नहीं","केवल स्रोत का शीर्षक ज़रूरी"],1,"A citation must support the exact claim, population and context; transfer remains an uncertainty.","स्रोत ठीक दावे, आबादी और संदर्भ को समर्थन दे; दूसरे संदर्भ में लागू होना अनिश्चित है।"),
 c("numeracy","Compound model","चक्रवृद्धि मॉडल","Apply repeated percentage growth in a fictional model.","काल्पनिक मॉडल में दोहरती प्रतिशत बढ़त लगाना।","A model starts at 100 and grows by 10% each step for two steps. Final value?","मॉडल 100 से शुरू होकर दो चरण हर बार 10% बढ़ता है। अंतिम मान?","Use 100×1.1×1.1.","100×1.1×1.1 लो।",["120","121","110"],["120","121","110"],1,"The model value is 121, not 120; the second increase uses the new base. This is not an investment forecast.","मॉडल 121 है, 120 नहीं; दूसरी बढ़त नई आधार राशि पर है। यह निवेश अनुमान नहीं।"),
 c("creative","A digital sound budget","डिजिटल ध्वनि का आकार","Calculate an uncompressed recording size from given units.","दी इकाइयों से असंपीड़ित रिकॉर्डिंग का आकार निकालना।","A mono signal uses 1000 samples/s and 2 bytes/sample for 10s. Data bytes?","मोनो संकेत 1000 नमूने/सेकंड, 2 बाइट/नमूना, 10 सेकंड है। डेटा बाइट?","Multiply rate, bytes per sample and duration.","दर × हर नमूने की बाइट × अवधि।",["2000","20000","10000"],["2000","20000","10000"],1,"1000×2×10=20000 bytes, excluding headers. This low sample-rate example is arithmetic, not a high-quality audio recommendation.","1000×2×10=20000 बाइट, हेडर छोड़कर। कम नमूना दर का यह उदाहरण गणना है, अच्छी ध्वनि की सिफारिश नहीं।"),
 c("discovery","Feedback in a model","मॉडल में प्रतिक्रिया","Identify feedback that opposes a deviation.","बदलाव का विरोध करने वाली प्रतिक्रिया पहचानना।","A temperature controller reduces heating when temperature rises above target. This is?","तापमान लक्ष्य से ऊपर जाए तो नियंत्रक गर्मी कम करता है। यह क्या है?","The response opposes the deviation.","प्रतिक्रिया बदलाव की विपरीत दिशा में है।",["Negative feedback","Unlimited positive reinforcement","No feedback"],["नकारात्मक प्रतिक्रिया","अनंत सकारात्मक बढ़ावा","कोई प्रतिक्रिया नहीं"],0,"It opposes the rise. Negative feedback does not guarantee stability; real controllers also depend on delays, sensors and tuning.","यह बढ़त का विरोध करता है। नकारात्मक प्रतिक्रिया स्थिरता की गारंटी नहीं; असली नियंत्रक विलंब, सेंसर और समायोजन पर भी निर्भर हैं।"),
 c("social","Human and AI judgement","मानव और AI का निर्णय","Keep AI advice open to verification and human choice.","AI सलाह को जाँच और मानव चुनाव के लिए खुला रखना।","An AI confidently gives a surprising answer. A constructive next step?","AI आत्मविश्वास से आश्चर्यजनक जवाब देता है। अच्छा अगला कदम?","Confidence is not evidence.","आत्मविश्वास प्रमाण नहीं।",["Check sources and reasoning, then decide","Treat every confident answer as perfect","Share private details to win its approval"],["स्रोत और तर्क जाँचकर तय करें","हर आत्मविश्वासी जवाब पूर्ण मानें","उसकी मंज़ूरी के लिए निजी बातें दें"],0,"Use AI as a fallible tool. Human agency and independent evidence remain important.","AI को गलती कर सकने वाला साधन मानो। मानव चुनाव और स्वतंत्र प्रमाण ज़रूरी रहते हैं।"),
 c("real-world","A bounded pilot","सीमित परीक्षण","Define an evaluable pilot without claiming universal success.","सर्वव्यापी सफलता बिना जाँचा जा सकने वाला परीक्षण तय करना।","A learning pilot needs a clear evaluation. What belongs in its plan?","सीखने के छोटे परीक्षण का स्पष्ट मूल्यांकन चाहिए। योजना में क्या हो?","Specify who, what, when, safety and success criteria.","कौन, क्या, कब, सुरक्षा और सफलता के मानदंड बताओ।",["Participants, purpose, measures, limits and review date","An unlimited world-best promise","Collect every private detail just in case"],["प्रतिभागी, उद्देश्य, माप, सीमाएँ और समीक्षा दिन","असीम दुनिया में श्रेष्ठ वादा","संभव काम के लिए सारी निजी बातें लें"],0,"A bounded plan supports honest assessment and protects participants from unnecessary data collection.","सीमित योजना ईमानदार आकलन देती है और अनावश्यक जानकारी लेने से बचाती है।"),
 c("language","Change without losing history","इतिहास खोए बिना बदलाव","Explain why revisions are retained.","संस्करण सँभालने का कारण बताना।","A published lesson is improved. Why retain the previous revision?","प्रकाशित पाठ सुधारा गया। पुराना संस्करण क्यों रखें?","Saved work refers to the instructions used then.","सहेजा काम उस समय के निर्देशों से जुड़ा है।",["To resume and interpret historical work correctly","To pretend nothing ever changed","To duplicate completion rewards"],["पुराना काम ठीक समझें और जारी रखें","मानें कुछ बदला ही नहीं","पूर्णता पुरस्कार दुगने दें"],0,"Revision history protects continuity and makes changes inspectable without duplicating learning evidence.","संस्करण इतिहास निरंतरता और बदलाव की जाँच रखता है, सीखने के प्रमाण की नक़ल नहीं करता।")
],
};
const CREATION_BRIEFS: Record<number, { title: Bilingual; objective: Bilingual; draft: Bilingual; revise: Bilingual; hint: Bilingual }> = {
  1: { title:pair("My repeating colour garden","मेरा दोहरता रंग बगीचा"), objective:pair("Construct and extend a two-colour pattern.","दो रंगों का पैटर्न बनाना और बढ़ाना।"), draft:pair("Choose two colours. Paint six cells in one row, alternating the colours.","दो रंग चुनो। एक पंक्ति में छह खाने बारी-बारी दोनों रंगों से भरो।"), revise:pair("Paint a second row with the same pattern. Point to the part that repeats. You may change your design.","दूसरी पंक्ति में वही पैटर्न बनाओ। दोहरता हिस्सा दिखाओ। चाहो तो अपना चित्र बदलो।"), hint:pair("Try teal, red, teal, red. A repeated pair makes the pattern.","हरा, लाल, हरा, लाल आज़माओ। दोहरती जोड़ी से पैटर्न बनता है।") },
  2: { title:pair("Mirror-wing maker","दर्पण पंख बनाओ"), objective:pair("Construct a picture with matching reflected halves.","दो प्रतिबिंबित हिस्सों वाला चित्र बनाना।"), draft:pair("The canvas has eight columns. Paint a wing in the left four columns.","चित्र में आठ स्तंभ हैं। बाएँ चार स्तंभों में एक पंख बनाओ।"), revise:pair("Make its mirror in the right four columns. Check the matching cells equally far from the middle.","दाएँ चार स्तंभों में उसका दर्पण बनाओ। बीच से बराबर दूर वाले खाने मिलाओ।"), hint:pair("Column 1 pairs with 8, 2 with 7, 3 with 6, and 4 with 5.","स्तंभ 1 का जोड़ा 8, 2 का 7, 3 का 6 और 4 का 5 है।") },
  3: { title:pair("An imaginary park map","काल्पनिक पार्क का नक्शा"), objective:pair("Represent different spaces and an accessible route with a simple visual key.","संकेतों से अलग जगहें और पहुँच वाला रास्ता बनाना।"), draft:pair("Make an imaginary park. Use different colours for plants, play space and a quiet area. Do not draw your real address.","काल्पनिक पार्क बनाओ। पौधों, खेल और शांत जगह के लिए अलग रंग लो। असली पता मत बनाओ।"), revise:pair("Add a connected path from the edge to all three areas. Check whether someone can reach every area without crossing plants.","किनारे से तीनों जगह तक जुड़ा रास्ता बनाओ। देखो कि पौधों पर गए बिना हर जगह पहुँचना संभव है।"), hint:pair("Use one colour as a key for paths. Adjacent cells can show a connected route.","रास्ते के लिए एक रंग तय करो। पास-पास के खाने जुड़े रास्ते दिखा सकते हैं।") },
  4: { title:pair("Twenty-tile floor","बीस टाइलों का फ़र्श"), objective:pair("Build a rectangle and compare area with perimeter.","आयत बनाकर क्षेत्रफल और परिमाप की तुलना करना।"), draft:pair("Paint a rectangle four rows tall and five columns wide. Count its twenty cells.","चार पंक्ति ऊँचा और पाँच स्तंभ चौड़ा आयत रंगो। बीस खाने गिनो।"), revise:pair("Use a second colour on the boundary cells. Trace the outer edges and explain why counting edge lengths differs from counting all tiles.","सीमा के खाने दूसरे रंग से भरो। बाहर के किनारे देखो और बताओ कि किनारे की लंबाई और सारी टाइलें गिनना अलग क्यों है।"), hint:pair("Area is 4×5=20 square cells. Perimeter is 4+5+4+5=18 unit edges. A corner cell has two exposed outer edges.","क्षेत्रफल 4×5=20 वर्ग खाने है। परिमाप 4+5+4+5=18 इकाई किनारे है। कोने के खाने के दो बाहरी किनारे हैं।") },
  5: { title:pair("Fraction quilt design","भिन्नों की रजाई"), objective:pair("Represent equal fractions of a 64-cell grid.","64 खानों में बराबर भिन्न दिखाना।"), draft:pair("The grid has 64 cells. Colour one quarter (16 cells) in teal. Arrange those cells in any pattern.","जाली में 64 खाने हैं। एक चौथाई (16 खाने) हरे रंग से भरो। कोई भी पैटर्न बनाओ।"), revise:pair("Paint 16 previously blank cells red, leaving the 16 teal cells unchanged. Explain why these two non-overlapping quarters make one half even when arranged differently.","पहले खाली 16 खाने लाल रंगो; हरे 16 खाने वैसे ही रहने दो। समझाओ कि बिना एक-दूसरे पर आए ये दो चौथाई अलग विन्यास में भी आधे क्यों हैं।"), hint:pair("Count the cells in each part: 16+16=32, which is half of 64.","हर हिस्से के खाने गिनो: 16+16=32, जो 64 का आधा है।") },
  6: { title:pair("Tile without gaps","बिना खाली जगह टाइलें"), objective:pair("Repeat a unit tile and inspect gaps and overlap.","एक टाइल दोहराकर खाली जगह और ओवरलैप देखना।"), draft:pair("Design a 2-by-2 coloured tile in the top-left of the grid. Choose a recognizable colour arrangement.","ऊपर बाएँ 2-बाय-2 रंगीन टाइल बनाओ। पहचानने योग्य रंग व्यवस्था चुनो।"), revise:pair("Repeat the tile across an area of the grid. Check that copies touch without gaps or overlap; describe the horizontal and vertical shifts.","टाइल को जाली के हिस्से में दोहराओ। प्रतियाँ बिना खाली जगह या ओवरलैप मिलें; दाएँ और नीचे खिसकना बताओ।"), hint:pair("A two-column horizontal shift and two-row vertical shift reproduce the unit.","दो स्तंभ दाएँ और दो पंक्ति नीचे खिसकने पर इकाई दोहरती है।") },
  7: { title:pair("Coordinates in colour","रंगों में निर्देशांक"), objective:pair("Plot and describe positions on a discrete coordinate grid.","खानों की जाली पर निर्देशांक दिखाना और समझाना।"), draft:pair("Treat the bottom-left cell as (1,1). Paint (3,2) in teal and (6,4) in red.","नीचे बायाँ खाना (1,1) मानो। (3,2) हरा और (6,4) लाल रंगो।"), revise:pair("Choose one more point. Explain its x and y positions and the shift from one painted point to another.","एक और बिंदु चुनो। उसके x और y स्थान और एक रंगे बिंदु से दूसरे तक बदलाव समझाओ।"), hint:pair("x counts columns from the left; y counts rows from the bottom.","x बाएँ से स्तंभ गिनता है; y नीचे से पंक्ति।") },
  8: { title:pair("An icon with a budget","सीमित खानों का चिन्ह"), objective:pair("Design a communicative image under explicit constraints.","स्पष्ट सीमाओं में अर्थ वाला चित्र बनाना।"), draft:pair("Design an icon for reading, music or nature. Use at most two colours and at most 32 painted cells.","पढ़ने, संगीत या प्रकृति का चिन्ह बनाओ। अधिकतम दो रंग और 32 रंगे खाने लो।"), revise:pair("Review the cell budget and contrast. Ask whether the idea is recognizable without a caption, then revise your image.","खानों की सीमा और रंग का अंतर जाँचो। बिना शीर्षक अर्थ समझ आता है या नहीं पूछो, फिर चित्र सुधारो।"), hint:pair("Empty space can carry meaning. Simpler contours may communicate better.","खाली जगह भी अर्थ दे सकती है। सरल रूपरेखा बेहतर बता सकती है।") },
  9: { title:pair("Scale and area studio","पैमाना और क्षेत्रफल स्टूडियो"), objective:pair("Construct two scaled squares and compare their areas.","दो अलग पैमाने के वर्ग बनाकर उनके क्षेत्रफलों की तुलना करना।"), draft:pair("Paint a 2-by-2 square in the left half. Paint a 4-by-4 square in the right half using another colour.","बाएँ हिस्से में 2-बाय-2 वर्ग और दाएँ में दूसरे रंग का 4-बाय-4 वर्ग बनाओ।"), revise:pair("Count their cells. Explain why doubling the side changes four cells into sixteen, then add a visual key without overlapping the squares.","दोनों के खाने गिनो। भुजा दुगनी होने पर चार से सोलह क्यों होते हैं, समझाओ; वर्गों पर आए बिना संकेत जोड़ो।"), hint:pair("A length factor of two acts in both dimensions: 2×2=4 for area.","दो का लंबाई गुणक दोनों विमाओं पर है: क्षेत्रफल में 2×2=4।") },
  10: { title:pair("Reflection transformation","प्रतिबिंब परिवर्तन"), objective:pair("Represent a reflected pattern and explain preserved properties.","प्रतिबिंबित पैटर्न और समान रहने वाले गुण समझाना।"), draft:pair("Create a small asymmetric pattern in the left four columns. Use a second colour to reflect it across the middle line.","बाएँ चार स्तंभों में छोटा असममित पैटर्न बनाओ। दूसरे रंग से मध्य रेखा के पार प्रतिबिंब बनाओ।"), revise:pair("Check equal distances from the middle. Explain what changes (orientation) and what stays the same (cell count and shape). Correct any mismatch.","बीच से समान दूरी जाँचो। दिशा बदलना और खानों की संख्या व आकार समान रहना समझाओ। असंगति सुधारो।"), hint:pair("Reflection reverses left and right without changing the size of the pattern.","प्रतिबिंब बाएँ-दाएँ पलटता है, पैटर्न का आकार नहीं।") },
  11: { title:pair("Binary pixel message","द्विआधारी पिक्सेल संदेश"), objective:pair("Represent a binary pattern and compare repeated structure.","द्विआधारी पैटर्न और दोहरती संरचना तुलना करना।"), draft:pair("Use blank cells for 0 and one colour for 1. Encode 10110010 across the first row.","खाली खाना 0 और एक रंग 1 मानो। पहली पंक्ति में 10110010 बनाओ।"), revise:pair("Encode 10110010 on another row, then create your own eight-bit pattern. Describe what a receiver needs to decode it reliably.","दूसरी पंक्ति में 10110010 दोहराओ, फिर अपना आठ-बिट पैटर्न बनाओ। ठीक समझने के लिए प्राप्तकर्ता को क्या चाहिए, बताओ।"), hint:pair("Agree on the 0/1 mapping, row boundaries and reading direction before decoding.","समझने से पहले 0/1 संकेत, पंक्ति सीमा और पढ़ने की दिशा तय करो।") },
  12: { title:pair("Prototype a visual identity","दृश्य पहचान का नमूना"), objective:pair("Prototype, critique and revise a visual communication design.","दृश्य संवाद का नमूना, समीक्षा और सुधार करना।"), draft:pair("Design a two-colour symbol for a fictional public learning project. Avoid real names, addresses and copied brand marks.","काल्पनिक सार्वजनिक सीखने की परियोजना का दो-रंग चिन्ह बनाओ। असली नाम, पता और नकल किए ब्रांड चिह्न मत लो।"), revise:pair("Review recognition, contrast and cultural interpretation from more than one perspective. Change one feature and explain the trade-off; the app saves the picture, not proof of design quality.","पहचान, रंग का अंतर और सांस्कृतिक अर्थ कई नज़रियों से देखो। एक गुण बदलकर समझौता बताओ; ऐप चित्र सँभालता है, गुणवत्ता का प्रमाण नहीं।"), hint:pair("Ask what the symbol communicates, what could be misread, and what remains uncertain.","पूछो चिन्ह क्या बताता है, गलत अर्थ क्या हो सकता है और क्या अनिश्चित है।") },
};
function creation(grade: number, base: LearningActivity): LearningActivity {
  const brief = CREATION_BRIEFS[grade];
  return { ...base, domain:"creative", title:brief.title, objective:brief.objective, interaction:"creation", completion:"saved-creation", steps:[brief.draft,brief.revise].map(instruction => ({instruction,hint:brief.hint,items:[],feedback:pair("Your design was saved. You can explain, revise or leave it as it is; saving does not prove understanding.","चित्र सहेजा गया। समझाओ, बदलो या वैसा रहने दो; सहेजना समझ का प्रमाण नहीं।")})) };
}

const CHOICE_ACTIVITY_EXPANSION: LearningActivity[] = Object.entries(GROUPS).flatMap(([grade, entries]) => entries.map((entry, index) => ({
  id: `grade-${grade}-studio-${index + 1}`, revision: 1, placements: [`school:${grade}`], domain: entry.domain,
  title: entry.title, objective: entry.objective, interaction: entry.interaction ?? "investigation",
  steps: [{ instruction: entry.prompt, hint: entry.hint, items: entry.choices.map((label, i) => ({ id: `choice-${i}`, picture: String(i + 1), label })), answer: `choice-${entry.correct}`, feedback: entry.explanation }],
  offline: pair("Explain your choice to someone or sketch how you could investigate it away from the screen.", "अपना चुनाव किसी को समझाओ या बिना स्क्रीन जाँच का चित्र बनाओ।"),
  caregiver: pair("Offer help if requested, leave room to disagree or stop, and use only safe everyday materials. No activity requires heat, tasting plants, road access or personal disclosure.", "मदद माँगने पर सहयोग दो, असहमति या रुकने की जगह रखो और सुरक्षित रोज़मर्रा सामान लो। गर्मी, पौधे चखना, सड़क पर जाना या निजी बातें बताना ज़रूरी नहीं।"),
  alignment: "general-exploration", source: `Original curriculum-neutral guided exploration; stated arithmetic, investigation and language reasoning reviewed editorially.${FACTUAL_REFERENCES[`grade-${grade}-studio-${index + 1}`] ? ` Factual reference: ${FACTUAL_REFERENCES[`grade-${grade}-studio-${index + 1}`]}` : ""}`, rights: "original-text-and-system-emoji",
  review: { status: "reviewed", method: "source-grounded-editorial", date: "2026-10-08", checks: ["factual: explicit arithmetic or bounded everyday observation; causal uncertainty retained", "developmental: short prompts, optional narration, no timer or forced personal disclosure", "language: separately authored English and Hindi prompts; phonics and rhyme use only the selected language", "accessibility: named choices, text/narration, tap and keyboard alternatives; canvas gaps recorded", "rights: original wording and system-rendered symbols; source facts paraphrased"], limits: "Editorial review by the implementing agent; not a claim of independent educator validation, complete board coverage or child usability research. Choice-led investigations are not full scientific simulations. Narration availability varies by device. Colour/coordinate canvas tasks need per-cell colour and row/column announcements before publication; keyboard buttons alone do not complete that accessibility review. This collection remains unintegrated draft preparation." },
  completion: "participated-in-all-steps",
})));

export const SCHOOL_ACTIVITY_EXPANSION: LearningActivity[] = CHOICE_ACTIVITY_EXPANSION.map(activity => {
  const grade = Number(activity.placements[0].slice(7));
  const index = Number(activity.id.split("-").at(-1));
  if (index === 9) return creation(grade, activity);
  const feedback = activity.steps[0].feedback;
  return { ...activity, steps: [...activity.steps, { instruction:pair(`Explain the connection: ${feedback.en} You can point, speak or sketch. Choose a next step that helps you investigate further.`, `संबंध समझाओ: ${feedback.hi} इशारा, बोलना या चित्र चुन सकते हो। आगे जाँचने का अगला कदम चुनो।`), hint:pair("Choose an action you could explain. You do not need to type or share a private response.","ऐसा काम चुनो जिसे समझा सको। लिखना या निजी जवाब बाँटना ज़रूरी नहीं।"), items:[{id:"explain",picture:"💬",label:pair("Explain with an example","उदाहरण से समझाओ")},{id:"draw",picture:"✏️",label:pair("Sketch a model","चित्र से समझाओ")},{id:"revisit",picture:"🔎",label:pair("Revisit the evidence","प्रमाण फिर देखो")}], feedback:pair("You chose a next step. Carry it out if you wish; this choice is participation, not evidence that the explanation happened.","अगला कदम चुना। चाहो तो करो; चुनाव भागीदारी है, समझाना हो जाने का प्रमाण नहीं।") }] };
});

/** Concrete counting uses one named marker per represented object. Numeric IDs match the existing counting player's contract. */
for (const [grade, index, total, picture, name, nameHi] of [[1,4,3,"🍎","Apple","सेब"],[2,1,8,"🔵","One sock marker","एक मोज़े का संकेत"]] as const) {
  const activity = SCHOOL_ACTIVITY_EXPANSION.find(a => a.id === `grade-${grade}-studio-${index}`)!;
  const first = activity.steps[0];
  activity.interaction = "counting";
  const previousAnswer = first.items.find(item => item.id === first.answer)!;
  first.items = first.items.map(item => ({ ...item, id:item.label.en, picture:item.label.en }));
  first.answer = previousAnswer.label.en;
  first.countingObjects = Array.from({length:total},() => ({picture,label:pair(name,nameHi)}));
  if (grade === 2) first.instruction = pair(`${first.instruction.en} Each blue marker represents one sock.`, `${first.instruction.hi} हर नीला संकेत एक मोज़े के लिए है।`);
}
const SOUND_ORDERS: Record<number, { first: Bilingual[]; next: Bilingual[] }> = {
  1:{first:[pair("Clap","ताली"),pair("Tap knees","घुटनों पर थपकी"),pair("Rest","विराम")],next:[pair("Rest","विराम"),pair("Clap","ताली"),pair("Tap knees","घुटनों पर थपकी")]},
  2:{first:[pair("Soft tap","धीमी थपकी"),pair("Rest","विराम"),pair("Clap","ताली")],next:[pair("Clap","ताली"),pair("Soft tap","धीमी थपकी"),pair("Rest","विराम")]},
};
for (const grade of [1,2]) {
  const activity = SCHOOL_ACTIVITY_EXPANSION.find(a => a.id === `grade-${grade}-studio-5`)!;
  activity.interaction = "sequence";
  activity.title = pair(grade === 1 ? "Build a sound phrase" : "Change a sound phrase",grade === 1 ? "ध्वनि का वाक्य बनाओ" : "ध्वनि का वाक्य बदलो");
  activity.objective = pair("Arrange pictured actions in a stated order, then explore a changed order.","चित्र वाले काम बताए क्रम में रखो, फिर बदला क्रम देखो।");
  activity.steps = [SOUND_ORDERS[grade].first,SOUND_ORDERS[grade].next].map((labels,index) => ({
    instruction:pair(`Arrange these actions: ${labels.map(l=>l.en).join(", ")}. After arranging, try the phrase gently if you wish.`, `काम इस क्रम में रखो: ${labels.map(l=>l.hi).join(", ")}। चाहो तो क्रम के बाद धीरे ताल आज़माओ।`),
    hint:pair("Select the pictured actions in the spoken/text order. A rest is a planned pause.","बोले/लिखे क्रम में चित्र चुनो। विराम जानबूझकर रुकना है।"),
    items:[2,0,1].map(i => ({id:`beat-${i}`,picture:labels[i].en.includes("Clap")?"👏":labels[i].en.includes("Rest")?"⏸️":"🦵",label:labels[i]})),
    answer:"beat-0|beat-1|beat-2",feedback:pair(index === 0 ? "The pictured order is ready. Next you will rearrange the phrase." : "You explored a different order. The app recorded ordering choices; it did not measure rhythm performance.",index === 0 ? "चित्रों का क्रम तैयार है। अब वाक्य का क्रम बदलेंगे।" : "अलग क्रम देखा। ऐप ने क्रम के चुनाव दर्ज किए; असली ताल प्रदर्शन नहीं मापा।"),
  }));
}
