import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

// ESLint 9 flat config. Replaces .eslintrc.json, which extended
// "next/core-web-vitals" without eslint-config-next ever being installed —
// so `npm run lint` and the build's lint step failed silently until 2026-08-10.
const config = [
  {
    // next-env.d.ts is generated by Next on every build and always trips
    // @typescript-eslint/triple-slash-reference. Never hand-edited.
    ignores: [
      ".next/**", "node_modules/**", "public/**",
      "skills/**", ".agents/**", ".claude/**",
      "next-env.d.ts",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
];

export default config;
