import { describe,it,expect } from "vitest";
import { allowedPushEndpoint,preferenceSchema,invitationDueKey,INVITATION_PAYLOAD,DEFAULT_INVITATION_PREFERENCES } from "./contracts";
describe("default-on invitation boundaries",()=>{
 it("defaults on and validates exact bounded scheduling inputs",()=>{expect(DEFAULT_INVITATION_PREFERENCES.enabled).toBe(true);expect(preferenceSchema.safeParse({...DEFAULT_INVITATION_PREFERENCES,timezone:"Asia/Kolkata"}).success).toBe(true);for(const bad of [{weekday:7},{time:"24:00"},{timezone:"not/a/zone"},{childName:"Private"}])expect(preferenceSchema.safeParse({...DEFAULT_INVITATION_PREFERENCES,...bad}).success).toBe(false);});
 it.each(["https://fcm.googleapis.com/fcm/send/opaque","https://updates.push.services.mozilla.com/wpush/v2/opaque","https://updates-push.services.mozaws.net/push/opaque","https://web.push.apple.com/opaque","https://wns2-db5p.notify.windows.com/w/?invalid"])('reviews provider endpoint %s',value=>{expect(allowedPushEndpoint(value)).toBe(!value.includes("?"));});
 it.each(["http://fcm.googleapis.com/a","https://127.0.0.1/a","https://[::1]/a","https://localhost/a","https://fcm.googleapis.com.attacker.test/a","https://attacker.test/push.apple.com/a","https://push.apple.com.attacker.test/a","https://user:pass@fcm.googleapis.com/a","https://fcm.googleapis.com:444/a","https://fcm.googleapis.com/a#token","https://fcm.googleapis.com/a?url=https://localhost","https://fcm.googleapis.com/","https://notify.windows.com/a"])("rejects arbitrary outbound target %s",value=>expect(allowedPushEndpoint(value)).toBe(false));
 it("uses actual timezone/day and does not fire early or for disabled preferences",()=>{const p={...DEFAULT_INVITATION_PREFERENCES,enabled:true,weekday:4,time:"10:00"};expect(invitationDueKey(p,new Date("2026-10-08T04:29:00Z"))).toBeNull();expect(invitationDueKey(p,new Date("2026-10-08T04:30:00Z"))).toBe("2026-10-08");expect(invitationDueKey(p,new Date("2026-10-09T04:30:00Z"))).toBe("2026-10-08");expect(invitationDueKey(p,new Date("2026-10-10T04:31:00Z"))).toBeNull();expect(invitationDueKey({...p,enabled:false},new Date("2026-10-08T04:30:00Z"))).toBeNull();});
 it("handles DST with calendar dates, retaining one weekly identity",()=>{const p={enabled:true,weekday:0,time:"01:30",timezone:"America/New_York"};expect(invitationDueKey(p,new Date("2026-11-01T05:30:00Z"))).toBe("2026-11-01");expect(invitationDueKey(p,new Date("2026-11-01T06:30:00Z"))).toBe("2026-11-01");});
 it("has only fixed generic content and a parent destination",()=>{expect(INVITATION_PAYLOAD.url).toBe("/parent");expect(Object.keys(INVITATION_PAYLOAD)).toEqual(["type","title","body","url","tag"]);});
});
