import { beforeEach,describe,it,expect,vi } from "vitest";
import { createECDH } from "node:crypto";
const db=vi.hoisted(()=>({deliveryCandidates:vi.fn(),claimInvitation:vi.fn(),invitationStillEnabled:vi.fn(),finishInvitation:vi.fn()}));
vi.mock("../db/notifications",()=>db);
vi.mock("web-push",()=>({default:{sendNotification:vi.fn()}}));
import { pushConfiguration,cronAuthorized,dispatchInvitations } from "./server";
const subscription={endpoint:"https://fcm.googleapis.com/fcm/send/synthetic",keys:{p256dh:"A".repeat(87),auth:"A".repeat(22)}};
const candidate={id:"synthetic",parentId:"synthetic-parent",subscription,preferences:{enabled:true,weekday:4,time:"10:00",timezone:"Asia/Kolkata"}};
beforeEach(()=>{vi.clearAllMocks();vi.unstubAllEnvs();db.deliveryCandidates.mockResolvedValue([candidate]);db.claimInvitation.mockResolvedValue(true);db.invitationStillEnabled.mockResolvedValue(true);db.finishInvitation.mockResolvedValue(undefined);});
describe("closed and bounded reminder transport",()=>{
 it("requires explicit enabled config and matching VAPID pair",()=>{expect(pushConfiguration()).toBeNull();const key=createECDH("prime256v1");key.generateKeys();vi.stubEnv("VIDYA_WEB_PUSH_ENABLED","true");vi.stubEnv("VIDYA_VAPID_PUBLIC_KEY",key.getPublicKey().toString("base64url"));vi.stubEnv("VIDYA_VAPID_PRIVATE_KEY",key.getPrivateKey().toString("base64url"));vi.stubEnv("VIDYA_VAPID_SUBJECT","mailto:support@example.com");expect(pushConfiguration()?.publicKey).toBe(key.getPublicKey().toString("base64url"));vi.stubEnv("VIDYA_VAPID_PRIVATE_KEY","A".repeat(43));expect(pushConfiguration()).toBeNull();});
 it("authenticates cron via long bearer secret only",()=>{vi.stubEnv("CRON_SECRET","a".repeat(32));expect(cronAuthorized(new Request("https://vidya.test/api/cron/family-invitations",{headers:{authorization:`Bearer ${"a".repeat(32)}`}}))).toBe(true);expect(cronAuthorized(new Request("https://vidya.test/api/cron/family-invitations",{headers:{"user-agent":"vercel-cron/1.0"}}))).toBe(false);vi.stubEnv("CRON_SECRET","short");expect(cronAuthorized(new Request("https://vidya.test"))).toBe(false);});
 it("sends only due claimed invitations and deduplicates repeated cron",async()=>{const transport=vi.fn().mockResolvedValue(undefined);expect(await dispatchInvitations(new Date("2026-10-08T04:30:00Z"),transport)).toMatchObject({sent:1});db.claimInvitation.mockResolvedValue(false);await dispatchInvitations(new Date("2026-10-08T04:30:00Z"),transport);expect(transport).toHaveBeenCalledTimes(1);expect(db.finishInvitation).toHaveBeenCalledWith("synthetic","2026-10-08","sent");});
 it("respects opt-out after claim without sending",async()=>{db.invitationStillEnabled.mockResolvedValue(false);const transport=vi.fn();expect(await dispatchInvitations(new Date("2026-10-08T04:30:00Z"),transport)).toMatchObject({cancelled:1});expect(transport).not.toHaveBeenCalled();});
 it.each([404,410,500])("records bounded outcome for provider %s without provider content",async statusCode=>{const transport=vi.fn().mockRejectedValue({statusCode,body:"PRIVATE PROVIDER DATA"});await dispatchInvitations(new Date("2026-10-08T04:30:00Z"),transport);expect(db.finishInvitation).toHaveBeenCalledWith("synthetic","2026-10-08",statusCode===500?"failed":"expired");});
 it("never calls transport for an arbitrary endpoint or off preference",async()=>{db.deliveryCandidates.mockResolvedValue([{...candidate,subscription:{...subscription,endpoint:"https://localhost/private"}},{...candidate,preferences:{...candidate.preferences,enabled:false}}]);const transport=vi.fn();await dispatchInvitations(new Date("2026-10-08T04:30:00Z"),transport);expect(transport).not.toHaveBeenCalled();});
});
