import type { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata = { title: "Privacy | Vidya", description: "How Vidya uses parent sign-in and family learning information." };

export default function PrivacyPage() {
  return <main className="mx-auto min-h-screen max-w-3xl px-5 py-10 text-[var(--text)]">
    <Link href="/parent" className="inline-flex min-h-11 items-center underline underline-offset-4">Back to parent space</Link>
    <header className="my-8"><p className="learning-eyebrow">Updated 8 October 2026</p><h1 className="mt-2 font-display text-4xl font-bold">Your family’s privacy</h1><p className="mt-4 leading-relaxed">Vidya is operated by Ekansh Jain, CTO of TechBird IT. This notice describes the current service at vidyagyan.study and parents.vidyagyan.study.</p></header>
    <div className="space-y-8 leading-relaxed">
      <section><h2 className="mb-3 text-xl font-bold">Parent sign-in</h2><p>Clerk manages parent authentication, verification, sessions and account recovery. Email sign-in is available. Social sign-in, when enabled, is optional and intended for parents and grown-ups. Children use a device code issued by their parent and do not need a Google account or their own email address.</p><p className="mt-3">If you choose Google sign-in, Google shares your account identifier, email address and basic profile information, including your name and profile picture, with Clerk for authentication. Vidya uses your verified identity to connect your parent account to your family. We request only sign-in scopes: openid, email and profile. We do not request Gmail messages, contacts, Drive files or your Google activity. Google sign-in information is used for authentication and account display, not advertising or behavioural profiling.</p></section>
      <section><h2 className="mb-3 text-xl font-bold">Learning and family information</h2><p>We store the parent account identifier and email, learner names and declared placement, linked devices, saved practice, activity progress, creations and family settings. This supports saving, returning to learning and showing the parent an observed practice summary. Device linking establishes which family can access a learner’s saved information.</p><p className="mt-3">New creations are private unless the child chooses to share them. Private reflections are excluded from routine parent reports. Reports do not expose AI transcripts or click histories. Approved friend circles share only selected project cards, pseudonymous names and preset reactions with the approved families. Pseudonyms do not make linked family records anonymous.</p></section>
      <section><h2 className="mb-3 text-xl font-bold">Storage and service providers</h2><p>Clerk processes authentication information. Neon provides the application database, and Vercel hosts the application and its APIs. These services process data needed to run and secure Vidya. Hosting and authentication services may retain operational logs, such as request metadata and IP addresses, under their own policies. Vidya does not sell Google sign-in or family learning information.</p><p className="mt-3">Your browser stores session information, preferences and a local copy of learner progress to support recovery and offline use. Eligible public books and activity assets can be cached. Parent, administrator and private API responses are excluded from the app’s offline content cache. Logging out does not necessarily remove every local browser copy; use care on shared devices.</p><p className="mt-3">Provider details: <a className="underline underline-offset-4" href="https://clerk.com/legal/privacy">Clerk privacy</a>, <a className="underline underline-offset-4" href="https://neon.com/privacy-policy">Neon privacy</a>, <a className="underline underline-offset-4" href="https://vercel.com/legal/privacy-policy">Vercel privacy</a>, and <a className="underline underline-offset-4" href="https://policies.google.com/privacy">Google privacy</a>.</p></section>
      <section><h2 className="mb-3 text-xl font-bold">Optional notifications and AI</h2><p>Weekly invitation preferences start enabled for new settings, but browser notifications require your explicit permission and a device subscription. We store the subscription endpoint, browser delivery keys and invitation preferences to send a generic family reminder. Your browser’s push provider processes delivery. You can turn invitations off and remove subscribed browsers in parent Controls. Installation reminders are optional and can be dismissed.</p><p className="mt-3">Learner-facing external AI is currently paused pending reviewed eligibility, consent, provider safeguards and funding. Configuring a provider does not enable learner AI by itself. Authored guidance remains available. We do not collect new click-tracking, heatmaps or personality scores.</p></section>
      <section><h2 className="mb-3 text-xl font-bold">Your choices and requests</h2><p>Parents can correct learner placement, revoke linked devices and manage notification preferences. Children choose which new creations to share and can leave approved circles. Google is an optional parent sign-in method; email sign-in remains available. Removing Vidya’s Google connection from your Google account does not automatically delete your Clerk or Vidya family records.</p><p className="mt-3">Saved family records are currently retained to support return visits and recovery. A universal automatic deletion deadline and a self-service family deletion workflow are not yet implemented. For access, export, correction or deletion requests, contact <a className="underline underline-offset-4" href="mailto:ekansh.jain@techbirdit.in">ekansh.jain@techbirdit.in</a>. We will verify account ownership before acting. Do not email passwords, device codes or private child reflections. Provider logs and backups may have separate retention schedules.</p></section>
      <section><h2 className="mb-3 text-xl font-bold">Support and safeguarding</h2><p>Authorized owner support can access family records needed to resolve a specific issue. Private reflections are not part of routine support browsing. Information may need to be disclosed when required by law or to address a concrete safeguarding or security concern. This is not a promise of secret monitoring or absolute confidentiality.</p><p className="mt-3">Material changes to how Google or family information is used will be disclosed here and in the relevant flow before a new use requiring consent is enabled.</p></section>
    </div>
  </main>;
}
