// ICSE Class 6 Exam Packs — verified May 2026 against icsesolutions, knowledgeboat, shaalaa.
// IMPORTANT: Cl 6 covers ANCIENT India, North + South America, pre-atomic-structure chemistry.
// Do NOT teach medieval / Asia-Africa / valency / atomic structure here — those are Cl 7+.

import type { ExamPack } from "../exam-pack";

// ============ MATHS — Selina, 34 chapters ============
export const ICSE6_MATHS: ExamPack = {
  subjectId: "icse-maths",
  grade: 6,
  title: "Mathematics — Class 6 ICSE",
  context: "Selina Concise · 34 chapters",
  highlights: [
    { label: "Textbook", value: "Selina Concise Mathematics 6" },
    { label: "Chapters", value: "34" },
  ],
  reference: { label: "Selina Class 6 (Shaalaa)", url: "https://www.shaalaa.com/textbook-solutions/selina-solutions-mathematics-english-class-6_162" },
  plan: [
    { title: "Walk the units (numbers · ratio · algebra · geometry · mensuration · data)", hint: "Tag confidence" },
    { title: "Key definitions", hint: "Sets, integers, fractions" },
    { title: "Practice questions", hint: "Mixed across units" },
    { title: "Common mistakes", hint: "Avoid common slips" },
    { title: "Cheat sheet", hint: "Formulas + signs" },
  ],
  topics: [
    { id: "num", num: 1, title: "Number system & place value",
      blurb: "Numberness, estimation, Indian vs International system, place value, natural & whole numbers, patterns.",
      syllabus: [
        "Digits, numerals; Indian (lakh, crore) vs International (million, billion) systems; commas placement.",
        "Face value vs place value; expanded form.",
        "Natural numbers (1, 2, …) vs whole numbers (0, 1, 2, …).",
        "Estimation: rounding off to nearest 10, 100, 1000.",
        "Number patterns and sequences.",
      ],
    },
    { id: "neg", num: 2, title: "Integers & number line",
      blurb: "Negatives, ordering, addition/subtraction on number line.",
      syllabus: [
        "Integers = …, -3, -2, -1, 0, 1, 2, 3, …",
        "Ordering on number line; absolute value.",
        "Add/subtract integers on number line.",
        "Real-life: temperature, sea level, profit/loss.",
      ],
    },
    { id: "hcflcm", num: 3, title: "HCF & LCM",
      blurb: "Factors, multiples, HCF, LCM by prime factorisation & division.",
      syllabus: [
        "Factor vs multiple; even/odd; prime/composite.",
        "Prime factorisation by factor tree.",
        "HCF (Highest Common Factor) by prime factorisation OR division method.",
        "LCM (Lowest Common Multiple) by prime factorisation OR division method.",
        "HCF × LCM = product of two numbers.",
      ],
    },
    { id: "div", num: 4, title: "Playing with numbers / divisibility",
      blurb: "Divisibility tests for 2, 3, 4, 5, 6, 8, 9, 10, 11.",
      syllabus: [
        "÷2 → last digit even; ÷5 → last 0 or 5; ÷10 → last 0.",
        "÷3 → digit sum divisible by 3; ÷9 → digit sum divisible by 9.",
        "÷4 → last two digits divisible by 4.",
        "÷11 → difference of alternate digit sums is 0 or multiple of 11.",
      ],
    },
    { id: "sets", num: 5, title: "Sets (intro)",
      blurb: "Well-defined collection of objects.",
      syllabus: [
        "Notation { }; element belongs (∈).",
        "Empty set ∅, singleton, finite, infinite.",
        "Subset ⊆; universal set.",
        "Roster vs set-builder form.",
      ],
    },
    { id: "ratio", num: 6, title: "Ratio & proportion (intro)",
      blurb: "Comparison and equality of ratios.",
      syllabus: [
        "Ratio a:b — same units, simplest form.",
        "Equivalent ratios.",
        "Proportion: a:b :: c:d; product of extremes = product of means.",
        "Word problems: mixing, scaling, sharing.",
      ],
    },
    { id: "unit", num: 7, title: "Unitary method · speed/distance/time",
      blurb: "Find one, then many. Speed = distance ÷ time.",
      syllabus: [
        "If 5 pens cost ₹25, find cost of 12: one pen ₹5; 12 × 5 = ₹60.",
        "Direct variation.",
        "Speed = distance ÷ time; units km/h or m/s.",
        "Convert km/h ↔ m/s by multiplying or dividing by 5/18.",
      ],
    },
    { id: "frac", num: 8, title: "Fractions",
      blurb: "Proper, improper, mixed, equivalent, four operations.",
      syllabus: [
        "Types: proper (n<d), improper (n≥d), mixed (whole + proper), unit (1/d).",
        "Equivalent fractions; lowest terms.",
        "LCM for unlike denominators in addition/subtraction.",
        "Multiplication and division of fractions; reciprocal.",
      ],
    },
    { id: "dec", num: 9, title: "Decimal fractions",
      blurb: "Place value, ordering, operations.",
      syllabus: [
        "Tenths, hundredths, thousandths.",
        "Add/subtract by lining up decimal points.",
        "Multiply by 10, 100, 1000 = shift decimal right.",
        "Divide by 10, 100, 1000 = shift decimal left.",
        "Convert decimal ↔ fraction.",
      ],
    },
    { id: "pc", num: 10, title: "Percent (intro)",
      blurb: "Per hundred. Convert between %, fraction, decimal.",
      syllabus: [
        "% means per 100; 50% = 1/2 = 0.5.",
        "% of a quantity.",
        "Express one quantity as % of another.",
      ],
    },
    { id: "alg", num: 11, title: "Algebra basics",
      blurb: "Variables, constants, expressions, simple equations.",
      syllabus: [
        "Variable (letter) vs constant (number).",
        "Term, coefficient, like/unlike terms.",
        "Add/subtract algebraic expressions (combine like terms).",
        "Substitute a value for the variable.",
        "Form and solve simple linear equations: x + a = b, ax = b.",
      ],
    },
    { id: "geo", num: 12, title: "Geometry fundamentals",
      blurb: "Point, line, ray, plane, angles, triangles, quadrilaterals, circle.",
      syllabus: [
        "Point (no dimension), line (no end), ray, line segment.",
        "Angles: acute (<90°), right (=90°), obtuse (>90° and <180°), straight (180°), reflex (>180°).",
        "Triangles by sides (scalene, isosceles, equilateral) and by angles.",
        "Quadrilaterals: square, rectangle, rhombus, parallelogram, trapezium.",
        "Circle: centre, radius, diameter (=2r), chord, arc.",
      ],
    },
    { id: "sym", num: 13, title: "Symmetry & 3D recognition",
      blurb: "Lines of symmetry. Faces, edges, vertices.",
      syllabus: [
        "Line symmetry — fold so halves match.",
        "Lines of symmetry: square 4, equilateral triangle 3, rectangle 2, circle infinite.",
        "3D shapes: cube, cuboid, cylinder, cone, sphere, prism, pyramid.",
        "Cube: 6 faces, 12 edges, 8 vertices. Cuboid: 6, 12, 8. Cylinder: 2 flat faces + 1 curved.",
      ],
    },
    { id: "mens", num: 14, title: "Mensuration — perimeter & area",
      blurb: "Plane figures only at Class 6.",
      syllabus: [
        "Perimeter = sum of all sides.",
        "Square perimeter = 4 × side; area = side².",
        "Rectangle perimeter = 2(l + b); area = l × b.",
        "Triangle perimeter = sum of sides; area = ½ × base × height.",
      ],
    },
    { id: "data", num: 15, title: "Data handling — pictograph, bar graph, mean & median",
      blurb: "Collecting, organising, displaying data.",
      syllabus: [
        "Pictograph — picture per unit.",
        "Bar graph — bars of equal width.",
        "Mean = sum of observations ÷ number of observations.",
        "Median = middle value of ordered data (or average of two middle values if even count).",
      ],
    },
  ],
  flashcards: [
    { term: "Natural number", def: "Counting numbers starting from 1: 1, 2, 3, …" },
    { term: "Whole number", def: "0 together with all natural numbers: 0, 1, 2, 3, …" },
    { term: "Integer", def: "A number with no fractional part: …, -2, -1, 0, 1, 2, …" },
    { term: "Place value", def: "Value of a digit because of its position in a numeral (e.g. 5 in 753 has place value 50)." },
    { term: "Factor", def: "A number that divides another exactly leaving no remainder." },
    { term: "Multiple", def: "Result of multiplying a number by a natural number." },
    { term: "Prime number", def: "A natural number greater than 1 with exactly two factors — 1 and itself." },
    { term: "HCF", def: "Highest Common Factor of two or more numbers." },
    { term: "LCM", def: "Lowest Common Multiple of two or more numbers." },
    { term: "Set", def: "A well-defined collection of distinct objects." },
    { term: "Empty set", def: "A set with no elements, written ∅ or { }." },
    { term: "Ratio", def: "Comparison of two quantities of the same kind, in the form a : b." },
    { term: "Proportion", def: "Two equal ratios; in a : b :: c : d, the product of extremes = product of means." },
    { term: "Unitary method", def: "Find value of one thing, then of many." },
    { term: "Fraction", def: "A part of a whole, written as numerator over denominator." },
    { term: "Decimal", def: "A number written with a decimal point separating whole and fractional parts." },
    { term: "Percent", def: "Per hundred. 25% means 25 out of 100." },
    { term: "Variable", def: "A symbol (usually a letter) that stands for an unknown number." },
    { term: "Equation", def: "A statement that two expressions are equal." },
    { term: "Acute angle", def: "An angle less than 90°." },
    { term: "Right angle", def: "An angle of exactly 90°." },
    { term: "Equilateral triangle", def: "A triangle with all three sides equal and all three angles equal to 60°." },
    { term: "Mean (average)", def: "Sum of all observations divided by the number of observations." },
    { term: "Median", def: "Middle value of an ordered data set." },
  ],
  questions: [
    { id: "i6m-1", topic: "num", q: "Place value of 7 in 8,73,456?", opts: ["7", "70", "7,000", "70,000"], a: "70,000", model: "7 sits in the ten-thousands place. Value = 7 × 10,000 = 70,000." },
    { id: "i6m-2", topic: "neg", q: "Which is greater: -3 or -8?", opts: ["-3", "-8", "They are equal", "Cannot tell"], a: "-3", model: "On the number line, -3 is to the right of -8, so it is greater." },
    { id: "i6m-3", topic: "hcflcm", q: "HCF of 12 and 18?", opts: ["2", "3", "6", "36"], a: "6", model: "Common factors of 12 and 18 are 1, 2, 3, 6. Highest = 6." },
    { id: "i6m-4", topic: "hcflcm", q: "LCM of 4 and 6?", opts: ["8", "10", "12", "24"], a: "12", model: "Multiples: 4 → 4, 8, 12; 6 → 6, 12. LCM = 12." },
    { id: "i6m-5", topic: "div", q: "Which is divisible by 9?", opts: ["123", "234", "236", "345"], a: "234", model: "Digit sum of 234 = 2+3+4 = 9. Divisible by 9." },
    { id: "i6m-6", topic: "sets", q: "Which is an empty set?", opts: ["{a, b}", "{0}", "{ }", "{1, 2, 3}"], a: "{ }", model: "Empty set has zero elements. {0} is a singleton with one element (0)." },
    { id: "i6m-7", topic: "ratio", q: "Simplify ratio 24 : 36.", opts: ["3 : 4", "2 : 3", "4 : 6", "6 : 9"], a: "2 : 3", model: "Divide both by HCF(24,36) = 12 → 2:3." },
    { id: "i6m-8", topic: "frac", q: "Which is equivalent to 2/3?", opts: ["3/4", "4/6", "5/8", "6/8"], a: "4/6", model: "2/3 = 4/6 (multiply numerator and denominator by 2)." },
    { id: "i6m-9", topic: "dec", q: "0.5 × 100 = ?", opts: ["5", "50", "500", "5000"], a: "50", model: "Multiplying by 100 shifts decimal 2 places right." },
    { id: "i6m-10", topic: "pc", q: "50% of 80 = ?", opts: ["20", "30", "40", "50"], a: "40", model: "50% = 1/2. Half of 80 is 40." },
    { id: "i6m-11", topic: "alg", q: "Solve: x + 7 = 12.", opts: ["x = 4", "x = 5", "x = 19", "x = 7"], a: "x = 5", model: "x = 12 − 7 = 5." },
    { id: "i6m-12", topic: "geo", q: "An angle of 90° is called?", opts: ["Acute", "Right", "Obtuse", "Straight"], a: "Right", model: "Right angle = 90°. Acute < 90°. Obtuse 90°–180°. Straight = 180°." },
    { id: "i6m-13", topic: "sym", q: "Number of edges in a cube?", opts: ["6", "8", "10", "12"], a: "12", model: "Cube: 6 faces, 8 vertices, 12 edges." },
    { id: "i6m-14", topic: "mens", q: "Perimeter of a square of side 9 cm?", opts: ["18 cm", "27 cm", "36 cm", "81 cm"], a: "36 cm", model: "Perimeter = 4 × side = 4 × 9 = 36 cm." },
    { id: "i6m-15", topic: "data", q: "Find the mean of 5, 7, 8, 10, 10.", opts: ["7", "8", "9", "10"], a: "8", model: "Sum = 40. Mean = 40 ÷ 5 = 8." },
  ],
  mistakes: [
    { mistake: "Forgetting commas in Indian vs International system.", fix: "Indian: 12,34,567 (after thousands group by 2). International: 1,234,567 (group by 3)." },
    { mistake: "Counting 0 as a natural number.", fix: "Natural starts at 1. Whole starts at 0." },
    { mistake: "Saying -5 > -3.", fix: "Negative numbers — the closer to zero, the greater. -3 > -5." },
    { mistake: "Confusing HCF and LCM.", fix: "HCF = Highest (smaller answer). LCM = Lowest multiple (bigger answer). LCM ≥ HCF." },
    { mistake: "Adding fractions by adding numerators only.", fix: "Find LCM of denominators first; rewrite as equivalent fractions; then add numerators." },
    { mistake: "Forgetting units (cm, m, cm²) in mensuration.", fix: "Perimeter — length units. Area — square units. Always write the unit." },
  ],
  cheat: [
    { heading: "Place value (Indian system)",
      bullets: [
        "Units · Tens · Hundreds · Thousands · Ten-Thousands · Lakhs · Ten-Lakhs · Crores.",
        "Commas after thousands, then after every two digits going left.",
      ],
    },
    { heading: "HCF / LCM shortcuts",
      bullets: [
        "Prime factorise both numbers.",
        "HCF = product of COMMON primes (lowest power).",
        "LCM = product of ALL primes (highest power).",
        "HCF × LCM = product of the two numbers.",
      ],
    },
    { heading: "Divisibility tests",
      bullets: [
        "2 → last digit even.",
        "3 → digit sum divisible by 3.",
        "4 → last two digits divisible by 4.",
        "5 → last digit 0 or 5.",
        "9 → digit sum divisible by 9.",
        "10 → last digit 0.",
        "11 → alternating digit-sum difference is 0 or multiple of 11.",
      ],
    },
    { heading: "Angles & shapes",
      bullets: [
        "Triangle angle sum = 180°. Square has 4 lines of symmetry.",
        "Square: side², 4×side perimeter. Rectangle: l×b, 2(l+b). Triangle: ½ × base × height.",
        "Cube: 6 faces, 8 vertices, 12 edges.",
      ],
    },
    { heading: "Exam moves",
      bullets: [
        "Read the question twice. Underline what is asked.",
        "Show all working (steps earn marks).",
        "Always write the unit.",
        "Re-check signs and decimal points at the end.",
      ],
    },
  ],
};

// ============ PHYSICS — Selina, 6 chapters ============
export const ICSE6_PHYSICS: ExamPack = {
  subjectId: "icse-physics",
  grade: 6,
  title: "Physics — Class 6 ICSE",
  context: "Selina Concise · 6 chapters",
  highlights: [
    { label: "Textbook", value: "Selina Concise Physics 6" },
    { label: "Chapters", value: "6" },
  ],
  reference: { label: "Selina Physics 6 (KnowledgeBoat)", url: "https://www.knowledgeboat.com/learn/class-6-icse-concise-physics-selina/content" },
  plan: [
    { title: "6 chapters", hint: "Matter → Magnetism" },
    { title: "Definitions", hint: "Density, force, machines" },
    { title: "Practice", hint: "Calculate density, name machines" },
    { title: "Common mistakes", hint: "Units!" },
    { title: "Cheat sheet", hint: "Formulas + facts" },
  ],
  topics: [
    { id: "1-matter", num: 1, title: "Matter",
      blurb: "Anything that has mass and occupies space.",
      syllabus: [
        "Three states: solid (fixed shape & volume), liquid (volume only), gas (neither).",
        "Inter-particle space increases: solid → liquid → gas.",
        "Inter-particle attraction decreases: solid → liquid → gas.",
        "Properties: solids resist deformation; liquids flow; gases fill any container.",
        "Brownian motion shows particles in gases move.",
      ],
    },
    { id: "2-measure", num: 2, title: "Physical quantities & measurement",
      blurb: "SI units; length, mass, time, area, volume, density.",
      syllabus: [
        "Physical quantity = numerical value + unit.",
        "SI units: length metre (m), mass kilogram (kg), time second (s).",
        "Area = length × breadth; volume of cuboid = l × b × h; cube = side³.",
        "Volume of irregular solid by water displacement.",
        "Density = mass ÷ volume; units g/cm³ or kg/m³. Float vs sink.",
      ],
    },
    { id: "3-force", num: 3, title: "Force",
      blurb: "A push or pull. Changes motion or shape.",
      syllabus: [
        "Effects of force: start motion, stop, change speed, change direction, change shape.",
        "Types: muscular, gravitational, magnetic, electric, frictional, mechanical.",
        "Contact forces (muscular, friction) vs non-contact (gravity, magnetism, electric).",
        "Friction opposes motion between surfaces.",
        "Gravity = pull of Earth on every object.",
      ],
    },
    { id: "4-machines", num: 4, title: "Simple machines",
      blurb: "Devices that make work easier.",
      syllabus: [
        "Lever — first class (fulcrum middle, e.g. seesaw), second class (load middle, e.g. wheelbarrow), third class (effort middle, e.g. broom).",
        "Pulley — fixed (only changes direction) and movable (reduces effort).",
        "Inclined plane — sloping surface, reduces effort.",
        "Wheel and axle — rotates together.",
        "Mechanical advantage (intro): load ÷ effort.",
      ],
    },
    { id: "5-light", num: 5, title: "Light",
      blurb: "A form of energy that allows us to see.",
      syllabus: [
        "Luminous (sun, bulb, fire) vs non-luminous (moon, book).",
        "Transparent (glass), translucent (butter paper), opaque (wood, metal).",
        "Light travels in straight lines → shadows form behind opaque objects.",
        "Shadows: shape but no colour (silhouette).",
        "Reflection — bouncing back of light from polished surface (mirror).",
      ],
    },
    { id: "6-magnet", num: 6, title: "Magnetism",
      blurb: "Property by which a material attracts iron.",
      syllabus: [
        "Magnetic materials: iron, nickel, cobalt.",
        "Non-magnetic: plastic, wood, copper, paper.",
        "Magnets have two poles: North (N) and South (S).",
        "Like poles repel, unlike poles attract.",
        "Magnet ALWAYS has both poles — break it and each piece still has N and S.",
        "Methods of making a magnet: stroking, electric (electromagnet briefly).",
      ],
    },
  ],
  flashcards: [
    { term: "Matter", def: "Anything that has mass and occupies space." },
    { term: "Mass", def: "The amount of matter in an object; measured in kilograms (kg)." },
    { term: "Volume", def: "The space an object occupies; measured in m³ (or cm³, litres)." },
    { term: "Density", def: "Mass per unit volume; ρ = m/V. Units g/cm³ or kg/m³." },
    { term: "Force", def: "A push or pull that can start, stop, slow, speed up, change direction, or change the shape of an object." },
    { term: "Friction", def: "A force that opposes motion between two surfaces in contact." },
    { term: "Gravity", def: "The pull of Earth (or any planet) on objects toward its centre." },
    { term: "Lever", def: "A rigid bar that turns around a fixed point called a fulcrum." },
    { term: "Pulley", def: "A wheel with a grooved rim around which a rope passes; lifts loads." },
    { term: "Luminous body", def: "An object that gives out its own light (sun, fire, bulb)." },
    { term: "Opaque", def: "Does not let light pass through (wood, metal)." },
    { term: "Transparent", def: "Allows light to pass through completely (clear glass, water)." },
    { term: "Translucent", def: "Allows some light to pass but you cannot see clearly through it (butter paper)." },
    { term: "Shadow", def: "A dark patch formed behind an opaque object when light is blocked." },
    { term: "Magnet", def: "A piece of iron (or another magnetic material) that attracts iron and points N–S when free." },
    { term: "Magnetic pole", def: "The end of a magnet where its strength is greatest; N and S poles exist in a pair." },
  ],
  questions: [
    { id: "i6p-1", topic: "1-matter", q: "Which has a fixed shape and a fixed volume?", opts: ["Solid", "Liquid", "Gas", "Plasma"], a: "Solid", model: "Solids resist changes in both shape and volume." },
    { id: "i6p-2", topic: "2-measure", q: "SI unit of mass?", opts: ["Newton", "Gram", "Kilogram", "Pound"], a: "Kilogram", model: "Kilogram (kg) is the SI unit. Gram is a smaller related unit." },
    { id: "i6p-3", topic: "2-measure", q: "Mass = 120 g, Volume = 40 cm³. Density?", opts: ["2 g/cm³", "3 g/cm³", "4 g/cm³", "30 g/cm³"], a: "3 g/cm³", model: "ρ = m/V = 120/40 = 3 g/cm³." },
    { id: "i6p-4", topic: "3-force", q: "Which is a non-contact force?", opts: ["Friction", "Muscular", "Gravity", "Pulling a string"], a: "Gravity", model: "Gravity acts at a distance without contact. Friction & muscular forces need contact." },
    { id: "i6p-5", topic: "4-machines", q: "A seesaw is which class of lever?", opts: ["First", "Second", "Third", "Not a lever"], a: "First", model: "First class: fulcrum is between effort and load — like a seesaw." },
    { id: "i6p-6", topic: "4-machines", q: "Which machine reduces the effort needed to lift a heavy load straight up?", opts: ["Inclined plane", "Wheel & axle", "Pulley", "Lever only"], a: "Pulley", model: "Pulleys are used for lifting loads vertically." },
    { id: "i6p-7", topic: "5-light", q: "Which object is luminous?", opts: ["Moon", "Book", "Sun", "Tree"], a: "Sun", model: "Sun produces its own light. Moon only reflects sunlight." },
    { id: "i6p-8", topic: "5-light", q: "Which material is translucent?", opts: ["Clear glass", "Butter paper", "Wood", "Metal"], a: "Butter paper", model: "Butter paper lets some light through but you cannot see clearly through it." },
    { id: "i6p-9", topic: "6-magnet", q: "Which material is attracted by a magnet?", opts: ["Copper", "Plastic", "Iron", "Wood"], a: "Iron", model: "Magnetic materials: iron, nickel, cobalt. Copper is NOT magnetic." },
    { id: "i6p-10", topic: "6-magnet", q: "Two south poles brought together will?", opts: ["Attract", "Repel", "Stick", "Nothing"], a: "Repel", model: "Like poles repel, unlike poles attract." },
  ],
  mistakes: [
    { mistake: "Confusing mass with weight.", fix: "Mass = amount of matter (kg). Weight = force of gravity on that mass (newtons). Mass stays same; weight depends on where you are." },
    { mistake: "Saying friction is always bad.", fix: "Friction lets us walk, hold things, write. It's only a problem when it wastes energy or wears parts." },
    { mistake: "Forgetting that magnets always have BOTH poles.", fix: "Break a magnet in half — each piece still has its own N and S. You can't get a single pole." },
    { mistake: "Calling the moon luminous.", fix: "The moon is non-luminous; it only reflects sunlight." },
    { mistake: "Mixing transparent and translucent.", fix: "Transparent = see clearly. Translucent = light passes but image is blurry. Opaque = no light through." },
  ],
  cheat: [
    { heading: "Formulas to know",
      bullets: [
        "Density ρ = m / V (g/cm³ or kg/m³).",
        "Volume cuboid = l × b × h. Cube = side³.",
        "Volume of liquid by measuring cylinder (lower meniscus).",
        "Volume of irregular solid by displacement.",
      ],
    },
    { heading: "Force checklist",
      bullets: [
        "Contact: muscular, friction, mechanical.",
        "Non-contact: gravitational, magnetic, electric.",
        "Effects: start, stop, speed up/down, change direction, change shape.",
      ],
    },
    { heading: "Simple machines",
      bullets: [
        "Lever — 3 classes by fulcrum/load/effort position.",
        "Pulley — fixed (change direction) vs movable (reduce effort).",
        "Inclined plane — slope.",
        "Wheel & axle — co-rotating.",
      ],
    },
    { heading: "Light quick-ref",
      bullets: [
        "Luminous = own light (sun, bulb).",
        "Travels in straight lines → shadows.",
        "Transparent · Translucent · Opaque.",
        "Reflection bounces off polished surfaces.",
      ],
    },
    { heading: "Magnetism quick-ref",
      bullets: [
        "Magnetic: iron, nickel, cobalt.",
        "Two poles: N and S — always together.",
        "Like poles repel, unlike attract.",
        "Earth itself acts like a giant magnet — compass needle aligns N–S.",
      ],
    },
  ],
};

// ============ CHEMISTRY — Selina, 7 chapters (NO atomic structure at Cl 6) ============
export const ICSE6_CHEMISTRY: ExamPack = {
  subjectId: "icse-chemistry",
  grade: 6,
  title: "Chemistry — Class 6 ICSE",
  context: "Selina Concise · 7 chapters",
  highlights: [
    { label: "Textbook", value: "Selina Concise Chemistry 6" },
    { label: "Chapters", value: "7" },
  ],
  reference: { label: "Selina Chemistry 6 (KnowledgeBoat)", url: "https://www.knowledgeboat.com/learn/class-6-icse-concise-chemistry-selina/content" },
  plan: [
    { title: "7 chapters", hint: "Intro → Water" },
    { title: "Lab apparatus", hint: "Memorise names" },
    { title: "Separation methods", hint: "Sieve · filter · evaporate · magnet" },
    { title: "Practice", hint: "Air & water" },
    { title: "Cheat sheet", hint: "Names + properties" },
  ],
  topics: [
    { id: "1-intro", num: 1, title: "Introduction to chemistry",
      blurb: "What chemistry is; branches; importance.",
      syllabus: [
        "Chemistry = study of matter and the changes it undergoes.",
        "Branches: organic, inorganic, physical, analytical, biochemistry.",
        "Importance: medicines, agriculture, materials, food.",
        "Famous Indian chemists — C.V. Raman (Nobel 1930), Asima Chatterjee, Prafulla Chandra Ray.",
      ],
    },
    { id: "2-lab", num: 2, title: "Common laboratory apparatus & safety",
      blurb: "Names, uses, do's and don'ts.",
      syllabus: [
        "Beaker — heating, mixing.",
        "Conical (Erlenmeyer) flask — mixing without splashing.",
        "Test tube — small reactions.",
        "Measuring cylinder — measure volumes.",
        "Bunsen burner — heating; blue flame is hottest.",
        "Tripod stand + wire gauze — supports vessels during heating.",
        "Safety: tie hair back, no tasting, no pointing at others when heating, wear apron.",
      ],
    },
    { id: "3-matter", num: 3, title: "Matter — chemistry viewpoint",
      blurb: "States, particle theory, change of state.",
      syllabus: [
        "Three states + changes (intro at chemistry level).",
        "Melting (solid→liquid), freezing (liquid→solid).",
        "Vaporisation (liquid→gas) and condensation (gas→liquid).",
        "Sublimation (solid→gas directly, e.g. camphor).",
      ],
    },
    { id: "4-elem", num: 4, title: "Elements, compounds, symbols, formulae",
      blurb: "Pure substances; basic symbols only — no valency yet.",
      syllabus: [
        "Element = pure substance made of one type of atom (H, O, Cu, Fe).",
        "Compound = two or more elements chemically combined in a fixed ratio (H₂O, CO₂, NaCl).",
        "Symbol = 1 or 2 letters; first capital, second small (Na not NA).",
        "Common symbols: H, O, N, C, Na, K, Mg, Ca, Al, Fe, Cu, Ag, Au, Zn, Cl, S.",
        "Common formulae: H₂O water, CO₂ carbon dioxide, NaCl salt, CaCO₃ chalk, H₂SO₄ sulphuric acid.",
        "DO NOT teach valency / criss-cross / balancing — that's Class 7.",
      ],
    },
    { id: "5-sep", num: 5, title: "Pure substances, mixtures & separation",
      blurb: "Mixtures vs pure substances; how to separate.",
      syllabus: [
        "Pure substance = single kind of particle (element OR compound).",
        "Mixture = two or more substances physically mixed; can be separated.",
        "Sieving — separates solids of different sizes (flour from bran).",
        "Filtration — separates an insoluble solid from a liquid (sand from water).",
        "Evaporation — recovers a solid from a solution (salt from sea water).",
        "Magnetic separation — picks magnetic component (iron filings from sulphur).",
        "Decantation, sedimentation, hand picking, winnowing.",
      ],
    },
    { id: "6-air", num: 6, title: "Air & atmosphere",
      blurb: "Composition, properties, importance.",
      syllabus: [
        "Air is a mixture of gases — N₂ 78%, O₂ 21%, others 1% (Ar, CO₂, water vapour, dust).",
        "Properties of air: takes space, has weight, exerts pressure.",
        "O₂ supports respiration and combustion; CO₂ is used by plants in photosynthesis.",
        "Layers of atmosphere (intro): troposphere (weather), stratosphere (ozone), mesosphere, thermosphere, exosphere.",
        "Air pollution — smoke, dust, harmful gases; can be reduced by trees, cleaner fuels, public transport.",
      ],
    },
    { id: "7-water", num: 7, title: "Water",
      blurb: "Sources, properties, water cycle, purification.",
      syllabus: [
        "Sources: rain, rivers, lakes, ponds, wells, glaciers, oceans (salt water).",
        "Properties: tasteless, colourless, odourless in pure form. Universal solvent.",
        "Water cycle: evaporation → condensation → precipitation → run-off back to seas.",
        "Purification: filtration, boiling, chlorination, distillation.",
        "Water conservation: rainwater harvesting, fix leaks, drip irrigation.",
      ],
    },
  ],
  flashcards: [
    { term: "Chemistry", def: "The branch of science that studies matter and the changes it undergoes." },
    { term: "Element", def: "A pure substance made of only one type of atom." },
    { term: "Compound", def: "A pure substance made of two or more elements chemically combined in a fixed ratio." },
    { term: "Mixture", def: "Two or more substances physically combined that can be separated by physical means." },
    { term: "Symbol (chemistry)", def: "A short way to write an element — 1 or 2 letters, first capital, second small." },
    { term: "Formula (chemistry)", def: "A short way to write a compound, showing the elements and number of atoms." },
    { term: "Filtration", def: "Separation of an insoluble solid from a liquid using filter paper." },
    { term: "Evaporation", def: "Liquid turning into vapour, leaving any dissolved solids behind." },
    { term: "Sublimation", def: "A solid changing directly into a gas without becoming liquid (e.g. camphor)." },
    { term: "Magnetic separation", def: "Using a magnet to remove a magnetic component from a mixture." },
    { term: "Air", def: "A mixture of gases — mainly nitrogen (78%) and oxygen (21%) plus small amounts of others." },
    { term: "Water cycle", def: "Continuous movement of water on Earth: evaporation → condensation → precipitation → run-off." },
    { term: "Universal solvent", def: "Water — it dissolves more substances than any other liquid." },
    { term: "Combustion", def: "A chemical reaction with oxygen that releases heat and light (burning)." },
  ],
  questions: [
    { id: "i6c-1", topic: "1-intro", q: "Chemistry is the study of?", opts: ["Living things", "Matter and its changes", "Stars and planets", "Only liquids"], a: "Matter and its changes", model: "Chemistry studies what things are made of and how they change." },
    { id: "i6c-2", topic: "2-lab", q: "Which apparatus is used to measure a specific volume of liquid?", opts: ["Beaker", "Measuring cylinder", "Test tube", "Funnel"], a: "Measuring cylinder", model: "Measuring cylinder has accurate volume markings. Beakers are approximate." },
    { id: "i6c-3", topic: "3-matter", q: "Camphor going directly from solid to vapour is an example of?", opts: ["Evaporation", "Condensation", "Sublimation", "Freezing"], a: "Sublimation", model: "Solid → gas with no liquid step = sublimation." },
    { id: "i6c-4", topic: "4-elem", q: "Which is a compound?", opts: ["O₂", "Fe", "H₂O", "Cu"], a: "H₂O", model: "H₂O has two elements (H and O) combined. O₂ is an element (just oxygen)." },
    { id: "i6c-5", topic: "4-elem", q: "Correct symbol for sodium?", opts: ["So", "Sd", "Na", "Sa"], a: "Na", model: "Many element symbols come from Latin names — sodium = natrium → Na." },
    { id: "i6c-6", topic: "5-sep", q: "Best method to separate sand from water?", opts: ["Sieving", "Evaporation", "Filtration", "Magnetic separation"], a: "Filtration", model: "Sand is insoluble in water — filter paper traps sand, water passes." },
    { id: "i6c-7", topic: "5-sep", q: "Best method to get salt from sea water?", opts: ["Filtration", "Sieving", "Evaporation", "Magnetic separation"], a: "Evaporation", model: "Salt dissolves in water — evaporate the water and the salt remains." },
    { id: "i6c-8", topic: "6-air", q: "Air is approximately what % nitrogen?", opts: ["21%", "50%", "78%", "98%"], a: "78%", model: "N₂ ≈ 78%, O₂ ≈ 21%, rest ≈ 1%." },
    { id: "i6c-9", topic: "7-water", q: "Which step of the water cycle changes water vapour back to liquid water?", opts: ["Evaporation", "Condensation", "Precipitation", "Filtration"], a: "Condensation", model: "Cooling vapour into droplets is condensation." },
    { id: "i6c-10", topic: "7-water", q: "Which method kills germs in drinking water at home?", opts: ["Filtering with cloth", "Boiling", "Decanting", "Adding sugar"], a: "Boiling", model: "Boiling kills most germs. Filtering removes dirt but not all germs." },
  ],
  mistakes: [
    { mistake: "Writing element symbols all in capitals (NA, CU).", fix: "Only the first letter is capital. Sodium = Na, Copper = Cu." },
    { mistake: "Calling air a compound.", fix: "Air is a mixture — gases keep their own properties; no chemical bond between them." },
    { mistake: "Saying salt water is a pure substance.", fix: "It's a homogeneous mixture (solution) — pure substance has only one kind of particle." },
    { mistake: "Trying to balance equations or assign valency at Class 6.", fix: "That's Class 7+. Class 6 only needs the names, common symbols and simple formulae." },
    { mistake: "Confusing filtration and decantation.", fix: "Filtration uses filter paper to trap insoluble solid. Decantation pours off the clear liquid after solid settles." },
  ],
  cheat: [
    { heading: "Common symbols", bullets: [
      "H, O, N, C, S, P (non-metals).",
      "Na sodium, K potassium, Mg magnesium, Ca calcium, Al aluminium, Fe iron, Cu copper, Zn zinc, Ag silver, Au gold.",
      "Cl chlorine, I iodine, He helium, Ne neon.",
    ]},
    { heading: "Common formulae", bullets: [
      "H₂O water · CO₂ carbon dioxide · O₂ oxygen · N₂ nitrogen.",
      "NaCl salt · CaCO₃ chalk · HCl hydrochloric acid · H₂SO₄ sulphuric acid · NH₃ ammonia.",
    ]},
    { heading: "Separation method picks", bullets: [
      "Solids of different sizes → sieving.",
      "Insoluble solid in liquid → filtration.",
      "Soluble solid in liquid → evaporation.",
      "Magnetic from non-magnetic → magnet.",
      "Two miscible liquids of different boiling points → distillation (intro).",
    ]},
    { heading: "Air & water", bullets: [
      "Air: N₂ 78%, O₂ 21%, others 1%.",
      "Water cycle: evaporation → condensation → precipitation → run-off.",
      "Purification at home: boil (kills germs); filter (removes dirt); chlorinate (kills germs at scale).",
    ]},
  ],
};

// ============ BIOLOGY — Selina, 8 chapters ============
export const ICSE6_BIOLOGY: ExamPack = {
  subjectId: "icse-biology",
  grade: 6,
  title: "Biology — Class 6 ICSE",
  context: "Selina Concise · 8 chapters",
  highlights: [
    { label: "Textbook", value: "Selina Concise Biology 6" },
    { label: "Chapters", value: "8" },
  ],
  reference: { label: "Selina Biology 6 (KnowledgeBoat)", url: "https://www.knowledgeboat.com/learn/class-6-icse-concise-biology-selina/content" },
  plan: [
    { title: "8 chapters", hint: "Leaf → Habitat" },
    { title: "Cell parts", hint: "Plant vs animal" },
    { title: "Body systems", hint: "Digestion · breathing · circulation" },
    { title: "Practice", hint: "MCQs + labelling" },
    { title: "Cheat sheet", hint: "System functions" },
  ],
  topics: [
    { id: "1-leaf", num: 1, title: "The leaf",
      blurb: "Parts, types of venation, functions.",
      syllabus: [
        "Parts: petiole (stalk), lamina (blade), midrib, veins, leaf base.",
        "Venation — reticulate (net-like, dicots e.g. mango) vs parallel (monocots e.g. grass).",
        "Functions: photosynthesis (food-making), transpiration (water loss), exchange of gases.",
        "Stomata — tiny pores in the leaf for gas exchange.",
      ],
    },
    { id: "2-flower", num: 2, title: "The flower",
      blurb: "Parts, functions, types.",
      syllabus: [
        "Four whorls: calyx (sepals, green), corolla (petals, coloured), androecium (stamens, male), gynoecium (carpels/pistils, female).",
        "Stamen = anther + filament. Anther makes pollen.",
        "Pistil = stigma + style + ovary. Ovary contains ovules.",
        "Bisexual flower has both whorls (hibiscus). Unisexual has only one (papaya).",
        "Pollination — transfer of pollen from anther to stigma. Self vs cross-pollination.",
      ],
    },
    { id: "3-cell", num: 3, title: "The cell — structure & functions",
      blurb: "Basic unit of life. Plant vs animal cell.",
      syllabus: [
        "Robert Hooke (1665) named the cell after looking at cork.",
        "Plant cell: cell wall + cell membrane + cytoplasm + nucleus + chloroplasts + large central vacuole.",
        "Animal cell: cell membrane + cytoplasm + nucleus + small vacuoles. No cell wall, no chloroplasts.",
        "Nucleus = control centre. Cytoplasm = jelly-like material. Mitochondria = power house (energy).",
        "Unicellular (Amoeba, bacteria) vs multicellular (plants, animals).",
      ],
    },
    { id: "4-digestion", num: 4, title: "Digestive system",
      blurb: "Mouth to anus; mechanical + chemical digestion.",
      syllabus: [
        "Alimentary canal: mouth → oesophagus → stomach → small intestine → large intestine → rectum → anus.",
        "Mouth: teeth grind, saliva starts digesting starch.",
        "Stomach: HCl + pepsin break down proteins.",
        "Small intestine: most absorption of nutrients into blood; bile from liver + enzymes from pancreas.",
        "Large intestine: absorbs water; forms faeces.",
      ],
    },
    { id: "5-resp", num: 5, title: "Respiratory system",
      blurb: "Breathing in O₂, breathing out CO₂.",
      syllabus: [
        "Nose → pharynx → larynx → trachea → bronchi → lungs → alveoli.",
        "Inhalation: diaphragm pulls down + ribs lift up; chest expands; air rushes in.",
        "Exhalation: diaphragm relaxes; chest shrinks; air pushed out.",
        "Gas exchange in alveoli — O₂ enters blood, CO₂ leaves blood.",
        "Breathing rate ≈ 12–20 per minute at rest.",
      ],
    },
    { id: "6-circ", num: 6, title: "Circulatory system",
      blurb: "Heart, blood, blood vessels.",
      syllabus: [
        "Heart has 4 chambers: 2 atria (upper) + 2 ventricles (lower).",
        "Blood: red cells (carry O₂), white cells (fight germs), platelets (clotting), plasma (fluid).",
        "Vessels: arteries carry blood AWAY from heart (red), veins carry blood TO heart (blue), capillaries connect them.",
        "Pulse = beat of artery; normal child pulse ≈ 70–100/min.",
        "Double circulation — blood passes through heart twice per cycle (body + lungs).",
      ],
    },
    { id: "7-disease", num: 7, title: "Disease & hygiene",
      blurb: "Causes, prevention.",
      syllabus: [
        "Communicable (infectious) — spread by germs: bacteria, virus, fungi, protozoa, worms (e.g. cold, flu, malaria, TB).",
        "Non-communicable — not spread: diabetes, cancer, heart disease, asthma.",
        "Modes of spread: air, water, food, contact, vectors (mosquitoes carry malaria).",
        "Personal hygiene: wash hands, bathe daily, cut nails, brush teeth, cover sneezes.",
        "Vaccinations protect from polio, measles, TB, etc.",
      ],
    },
    { id: "8-habitat", num: 8, title: "Habitat & adaptation",
      blurb: "Where organisms live and how they fit in.",
      syllabus: [
        "Habitat = natural home of an organism.",
        "Terrestrial: forest, grassland, desert, mountain, polar.",
        "Aquatic: freshwater (river, pond) and marine (sea).",
        "Adaptation = special feature for survival. Camel — hump for fat, padded feet, long eyelashes against sand.",
        "Fish — gills, streamlined body, fins.",
        "Polar bear — thick fur, white camouflage, fat layer.",
        "Cactus — thick stem stores water, leaves reduced to spines.",
      ],
    },
  ],
  flashcards: [
    { term: "Petiole", def: "The stalk of a leaf that joins the leaf blade to the stem." },
    { term: "Lamina", def: "The flat, green part of a leaf." },
    { term: "Stomata", def: "Tiny pores on the underside of a leaf for gas exchange and transpiration." },
    { term: "Photosynthesis", def: "Process by which green plants make food using sunlight, CO₂ and water." },
    { term: "Stamen", def: "Male part of a flower — anther + filament; produces pollen." },
    { term: "Pistil (carpel)", def: "Female part of a flower — stigma + style + ovary; ovary contains ovules." },
    { term: "Pollination", def: "Transfer of pollen from anther to stigma." },
    { term: "Cell", def: "The smallest structural and functional unit of all living things." },
    { term: "Cell wall", def: "A rigid outer layer in plant cells (made of cellulose); not present in animal cells." },
    { term: "Nucleus", def: "Control centre of the cell; contains genetic material (DNA)." },
    { term: "Chloroplast", def: "Plant cell organelle containing chlorophyll; the site of photosynthesis." },
    { term: "Vacuole", def: "Storage sac in a cell; large central one in plant cells, small ones in animal cells." },
    { term: "Mitochondria", def: "Cell organelle that releases energy from food — the cell's powerhouse." },
    { term: "Artery", def: "Blood vessel that carries blood AWAY from the heart, usually oxygen-rich." },
    { term: "Vein", def: "Blood vessel that carries blood TO the heart, usually oxygen-poor." },
    { term: "Alveolus", def: "Tiny air sac in the lungs where gas exchange happens." },
    { term: "Communicable disease", def: "An illness caused by germs that spreads from one person to another (cold, flu, malaria)." },
    { term: "Adaptation", def: "A special feature of an organism that helps it survive in its habitat." },
  ],
  questions: [
    { id: "i6b-1", topic: "1-leaf", q: "Tiny pores on a leaf for gas exchange are called?", opts: ["Veins", "Stomata", "Petioles", "Lamina"], a: "Stomata", model: "Stomata are mostly on the underside of the leaf." },
    { id: "i6b-2", topic: "1-leaf", q: "Type of venation found in grass?", opts: ["Reticulate", "Parallel", "Both", "Neither"], a: "Parallel", model: "Monocot leaves like grass have parallel venation." },
    { id: "i6b-3", topic: "2-flower", q: "Male reproductive part of a flower?", opts: ["Petal", "Stamen", "Stigma", "Sepal"], a: "Stamen", model: "Stamen = anther + filament; produces pollen." },
    { id: "i6b-4", topic: "3-cell", q: "Who first observed cells (1665)?", opts: ["Charles Darwin", "Robert Hooke", "Louis Pasteur", "Gregor Mendel"], a: "Robert Hooke", model: "Robert Hooke saw cells in cork and named them." },
    { id: "i6b-5", topic: "3-cell", q: "Which is found in plant cells but NOT in animal cells?", opts: ["Nucleus", "Cell wall", "Cytoplasm", "Mitochondria"], a: "Cell wall", model: "Cell wall (cellulose) is unique to plants. Animals only have cell membrane." },
    { id: "i6b-6", topic: "4-digestion", q: "Most absorption of nutrients happens in?", opts: ["Mouth", "Stomach", "Small intestine", "Large intestine"], a: "Small intestine", model: "Small intestine is long and lined with villi to absorb nutrients into blood." },
    { id: "i6b-7", topic: "5-resp", q: "Tiny air sacs in the lungs where O₂ enters blood?", opts: ["Alveoli", "Bronchi", "Trachea", "Larynx"], a: "Alveoli", model: "Alveoli have thin walls and a rich blood supply for gas exchange." },
    { id: "i6b-8", topic: "6-circ", q: "Heart has how many chambers?", opts: ["2", "3", "4", "5"], a: "4", model: "Two atria (upper) + two ventricles (lower) = 4 chambers." },
    { id: "i6b-9", topic: "6-circ", q: "Arteries usually carry blood that is?", opts: ["Oxygen-rich", "Oxygen-poor", "Mixed", "Without oxygen"], a: "Oxygen-rich", model: "Most arteries carry oxygenated blood away from the heart. (Exception: pulmonary artery.)" },
    { id: "i6b-10", topic: "7-disease", q: "Which is a communicable disease?", opts: ["Diabetes", "Cancer", "Malaria", "Asthma"], a: "Malaria", model: "Malaria spreads via mosquito bite — communicable. Diabetes/cancer/asthma do not spread person-to-person." },
    { id: "i6b-11", topic: "8-habitat", q: "Camel's hump stores?", opts: ["Water", "Fat", "Blood", "Air"], a: "Fat", model: "The hump stores fat that the camel can break down for energy and metabolic water when food is scarce." },
  ],
  mistakes: [
    { mistake: "Saying camel's hump stores water.", fix: "It stores FAT. Water comes indirectly from the fat being used up." },
    { mistake: "Confusing artery and vein.", fix: "A → Away from heart (artery). V → Visits the heart (vein)." },
    { mistake: "Claiming all arteries carry oxygenated blood.", fix: "Most do — but the pulmonary artery carries oxygen-poor blood from the heart to the lungs." },
    { mistake: "Naming cell wall in animal cells.", fix: "Only plants have a cell wall. Animals have just a cell membrane." },
    { mistake: "Mixing stomata and stoma.", fix: "Stoma = singular (one pore). Stomata = plural." },
  ],
  cheat: [
    { heading: "Cell quick-compare", bullets: [
      "Plant cell ONLY: cell wall, chloroplasts, large central vacuole.",
      "Animal cell ONLY: small vacuoles (or none), centrioles.",
      "BOTH: cell membrane, cytoplasm, nucleus, mitochondria.",
    ]},
    { heading: "Flower parts", bullets: [
      "Calyx → sepals (green protector).",
      "Corolla → petals (attract insects).",
      "Androecium → stamens (male — anther + filament).",
      "Gynoecium → pistils (female — stigma + style + ovary).",
    ]},
    { heading: "Body systems map", bullets: [
      "Digestion → break food into absorbable molecules.",
      "Respiration → take in O₂, release CO₂.",
      "Circulation → transport O₂, nutrients, waste, hormones.",
      "Excretion → remove urea (kidneys), CO₂ (lungs), sweat (skin).",
    ]},
    { heading: "Vessels rule", bullets: [
      "Arteries — Away from heart, thick walls, no valves, fast flow.",
      "Veins — Visit heart, thin walls, valves to prevent backflow.",
      "Capillaries — thinnest, allow exchange.",
    ]},
    { heading: "Adaptation flash", bullets: [
      "Camel — hump, padded feet, long lashes.",
      "Cactus — fleshy stem, spiny leaves, waxy skin.",
      "Polar bear — thick fur, fat layer, white camo.",
      "Fish — gills, fins, streamlined body.",
    ]},
  ],
};

// ============ HISTORY & CIVICS — Class 6 ICSE (Ancient India) ============
export const ICSE6_HISTORY: ExamPack = {
  subjectId: "icse-history-civics",
  grade: 6,
  title: "History & Civics — Class 6 ICSE",
  context: "Ancient world · Local self-government",
  highlights: [
    { label: "History scope", value: "Ancient India + world civilisations" },
    { label: "Civics", value: "Rural + Urban local government" },
  ],
  reference: { label: "ICSE 6 History (icsesolutions)", url: "https://icsesolutions.com/icse-solutions-class-6-history-and-civics/" },
  plan: [
    { title: "Ancient civilisations", hint: "Mesopotamia · Egypt · Indus · China" },
    { title: "Vedic to Gupta", hint: "Vedic → Mauryan → Gupta" },
    { title: "Local government", hint: "Panchayat · Municipality" },
    { title: "Practice MCQs", hint: "Dates + rivers + rulers" },
    { title: "Cheat sheet", hint: "Civilisation timeline" },
  ],
  topics: [
    { id: "1-intro", num: 1, title: "History — an introduction",
      blurb: "What history is; sources.",
      syllabus: [
        "History = the study of past events of human society.",
        "Sources: archaeological (tools, pottery, coins, buildings) and literary (manuscripts, inscriptions).",
        "Calendars: BCE (Before Common Era) vs CE (Common Era). 500 BCE is OLDER than 200 BCE.",
        "Pre-history — before writing was invented. History begins with writing.",
      ],
    },
    { id: "2-early", num: 2, title: "Early humans",
      blurb: "From cave-dwellers to farmers.",
      syllabus: [
        "Old Stone Age (Palaeolithic) — hunting and gathering, stone tools, cave shelters.",
        "Middle Stone Age (Mesolithic) — smaller microliths, beginning of domestication of animals.",
        "New Stone Age (Neolithic) — agriculture, pottery, settled villages, polished tools.",
        "Discovery of fire, the wheel, agriculture changed human life.",
      ],
    },
    { id: "3-mesopotamia", num: 3, title: "Mesopotamian, Egyptian & Chinese civilisations",
      blurb: "Three of the great river-valley civilisations.",
      syllabus: [
        "Mesopotamia — between Tigris and Euphrates (modern Iraq). City-states like Ur, Uruk. Cuneiform script. Ziggurats.",
        "Egypt — along the Nile. Pyramids (Pharaoh's tomb), Sphinx, mummies, hieroglyphics. Pharaoh = king.",
        "China — along the Hwang Ho (Yellow) river. Great Wall, silk, paper, gunpowder. Dynasties — Shang, Zhou.",
      ],
    },
    { id: "4-indus", num: 4, title: "Indus Valley civilisation",
      blurb: "India's oldest urban civilisation (~3300–1300 BCE).",
      syllabus: [
        "Along the Indus river; sites: Harappa, Mohenjo-daro, Dholavira, Lothal, Kalibangan, Rakhigarhi.",
        "Planned cities — grid roads, brick houses, underground drains, Great Bath at Mohenjo-daro.",
        "Crafts: pottery, beads, seals (steatite), metals (bronze, gold).",
        "Trade — with Mesopotamia. Famous bronze 'Dancing Girl'.",
        "Script not yet deciphered.",
        "Decline ~1300 BCE — possibly climate change, river shifts, or invasions.",
      ],
    },
    { id: "5-vedic", num: 5, title: "Vedic civilisation",
      blurb: "Early ~1500 BCE and Later ~1000–500 BCE.",
      syllabus: [
        "Aryans settled in the Saptasindhu (land of seven rivers).",
        "Four Vedas: Rig (oldest hymns), Sama (chants), Yajur (rituals), Atharva.",
        "Society: Brahmin (priest), Kshatriya (warrior), Vaishya (trader/farmer), Shudra (worker) — varna system.",
        "Early Vedic — pastoral, simple, women had a strong place.",
        "Later Vedic — agricultural, varna became hereditary caste, kingdoms emerged.",
      ],
    },
    { id: "6-mb", num: 6, title: "Mahavira & Buddha",
      blurb: "Two great teachers of the 6th century BCE.",
      syllabus: [
        "Mahavira (c. 599–527 BCE) — 24th Tirthankara of Jainism. Born at Vaishali. Taught the Five Vows — ahimsa (non-violence), satya (truth), asteya (no stealing), brahmacharya (celibacy), aparigraha (no possession).",
        "Buddha (c. 563–483 BCE) — born Siddhartha at Lumbini. Attained enlightenment under the Bodhi tree at Bodh Gaya. Taught Four Noble Truths and the Eightfold Path.",
        "Both rejected caste and ritual, used common languages (Prakrit, Pali).",
      ],
    },
    { id: "7-magadha", num: 7, title: "Rise of kingdoms & republics (Mahajanapadas)",
      blurb: "16 Mahajanapadas; Magadha became dominant.",
      syllabus: [
        "16 Mahajanapadas (great kingdoms) emerged around the 6th century BCE.",
        "Magadha grew strongest — capital Rajagriha, later Pataliputra.",
        "Reasons: fertile Ganga plains, iron ore, river trade, ambitious kings (Bimbisara, Ajatashatru).",
        "Republics (gana-sanghas) like Vaishali existed — assemblies took decisions.",
      ],
    },
    { id: "8-maurya", num: 8, title: "Mauryan Empire",
      blurb: "First Indian empire — Chandragupta to Ashoka.",
      syllabus: [
        "Chandragupta Maurya (321 BCE) — defeated Nanda king with help of Chanakya (Kautilya); wrote Arthashastra (statecraft).",
        "Capital: Pataliputra (modern Patna).",
        "Bindusara — extended the empire south.",
        "Ashoka (268–232 BCE) — grandson of Chandragupta. After the Kalinga war (~261 BCE) he embraced Buddhism. Spread it via missionaries (Sri Lanka, Central Asia). Famous rock and pillar edicts. Lion Capital of Sarnath is India's national emblem.",
      ],
    },
    { id: "9-gupta", num: 9, title: "Gupta Empire",
      blurb: "The 'Golden Age' of ancient India.",
      syllabus: [
        "Founder: Chandragupta I (~320 CE). Capital Pataliputra.",
        "Samudragupta — great warrior, called 'Indian Napoleon'.",
        "Chandragupta II (Vikramaditya) — peak. Court of Navratnas including Kalidasa, Aryabhata.",
        "Achievements: zero & decimal system (Aryabhata), value of pi, planetary motion. Sanskrit literature (Kalidasa's Shakuntala). Temple architecture begins. Ajanta cave paintings.",
        "Trade flourished with Roman empire.",
      ],
    },
    { id: "10-rural", num: 10, title: "Civics — Rural local self-government",
      blurb: "Panchayati Raj system.",
      syllabus: [
        "Three-tier Panchayati Raj established by 73rd Amendment (1992):",
        "1. Gram Panchayat (village level) — Sarpanch + Panches.",
        "2. Panchayat Samiti (block level).",
        "3. Zilla Parishad (district level).",
        "Gram Sabha — meeting of ALL adult voters of the village.",
        "Functions: water supply, sanitation, primary schools, roads, registration of births and deaths.",
      ],
    },
    { id: "11-urban", num: 11, title: "Civics — Urban local self-government",
      blurb: "Municipalities and Corporations.",
      syllabus: [
        "Municipal Corporation — large cities (Mumbai, Pune, Delhi). Headed by Mayor.",
        "Municipal Council — smaller cities and towns. Headed by a President/Chairperson.",
        "Nagar Panchayat — town in transition from rural.",
        "Sources of income: house tax, water tax, vehicle tax, market tolls, government grants.",
        "Functions: water supply, sewerage, roads, street lighting, public health, parks.",
      ],
    },
  ],
  flashcards: [
    { term: "BCE / CE", def: "Before Common Era / Common Era. 500 BCE is OLDER than 200 BCE." },
    { term: "Pre-history", def: "Period before writing was invented; known only from artefacts." },
    { term: "Mesopotamia", def: "Land between the Tigris and Euphrates rivers — one of the world's earliest civilisations." },
    { term: "Hieroglyphics", def: "Picture writing of ancient Egypt." },
    { term: "Cuneiform", def: "Wedge-shaped writing on clay tablets used in Mesopotamia." },
    { term: "Indus Valley civilisation", def: "Bronze Age urban civilisation along the Indus river, ~3300–1300 BCE; known for planned cities like Harappa and Mohenjo-daro." },
    { term: "Great Bath", def: "Famous tank-like structure at Mohenjo-daro — early evidence of public bathing & drainage." },
    { term: "Vedas", def: "Four sacred texts of Aryan society — Rig, Sama, Yajur, Atharva — the oldest religious literature of India." },
    { term: "Mahavira", def: "24th Tirthankara of Jainism (c. 599–527 BCE); taught ahimsa and the Five Vows." },
    { term: "Buddha", def: "Born Siddhartha at Lumbini (c. 563 BCE); founder of Buddhism; preached Four Noble Truths and Eightfold Path." },
    { term: "Mahajanapadas", def: "Sixteen major kingdoms / republics that emerged in northern India around the 6th century BCE." },
    { term: "Magadha", def: "The most powerful Mahajanapada, with capital first at Rajagriha and later Pataliputra." },
    { term: "Chandragupta Maurya", def: "Founded the Mauryan empire in 321 BCE with help of his teacher Chanakya." },
    { term: "Ashoka", def: "Mauryan emperor (c. 268–232 BCE) who embraced Buddhism after the Kalinga war and spread it widely." },
    { term: "Lion Capital of Sarnath", def: "Sculpture from an Ashokan pillar; modern India's national emblem." },
    { term: "Gupta empire", def: "Indian dynasty (~320–550 CE) often called India's 'Golden Age' for advances in maths, science, art, and literature." },
    { term: "Aryabhata", def: "Mathematician-astronomer of the Gupta period; gave the concept of zero and the value of pi." },
    { term: "Gram Sabha", def: "Assembly of all adult voters of a village in the Panchayati Raj system." },
    { term: "Panchayat", def: "Village-level body of elected representatives responsible for local administration." },
    { term: "Mayor", def: "The head of a Municipal Corporation (large city local government)." },
  ],
  questions: [
    { id: "i6h-1", topic: "1-intro", q: "Which is older?", opts: ["500 CE", "100 CE", "200 BCE", "500 BCE"], a: "500 BCE", model: "BCE counts backwards from year 0 — 500 BCE is the oldest." },
    { id: "i6h-2", topic: "3-mesopotamia", q: "Mesopotamia lay between which two rivers?", opts: ["Nile and Tigris", "Tigris and Euphrates", "Indus and Saraswati", "Hwang Ho and Yangtze"], a: "Tigris and Euphrates", model: "Modern Iraq sits where these two rivers run." },
    { id: "i6h-3", topic: "3-mesopotamia", q: "Pyramids are associated with which civilisation?", opts: ["Indus", "Egypt", "China", "Mesopotamia"], a: "Egypt", model: "Egyptian Pharaohs built pyramids as tombs (the Great Pyramid of Giza)." },
    { id: "i6h-4", topic: "4-indus", q: "Famous artefact from Mohenjo-daro?", opts: ["Lion Capital", "Dancing Girl bronze", "Iron Pillar", "Ashoka Chakra"], a: "Dancing Girl bronze", model: "The bronze 'Dancing Girl' is one of the most famous Indus Valley artefacts." },
    { id: "i6h-5", topic: "4-indus", q: "Largest Indus Valley site in India?", opts: ["Harappa", "Mohenjo-daro", "Rakhigarhi", "Lothal"], a: "Rakhigarhi", model: "Rakhigarhi (Haryana) is now believed to be the largest Indus Valley site in India." },
    { id: "i6h-6", topic: "5-vedic", q: "Oldest of the four Vedas?", opts: ["Sama Veda", "Yajur Veda", "Rig Veda", "Atharva Veda"], a: "Rig Veda", model: "Rig Veda contains the oldest hymns." },
    { id: "i6h-7", topic: "6-mb", q: "Where did Buddha attain enlightenment?", opts: ["Lumbini", "Sarnath", "Bodh Gaya", "Kushinagar"], a: "Bodh Gaya", model: "Under the Bodhi tree at Bodh Gaya in modern Bihar." },
    { id: "i6h-8", topic: "8-maurya", q: "Capital of the Mauryan empire?", opts: ["Ujjain", "Pataliputra", "Hastinapur", "Indraprastha"], a: "Pataliputra", model: "Pataliputra (modern Patna) was the Mauryan capital." },
    { id: "i6h-9", topic: "8-maurya", q: "After which war did Ashoka embrace Buddhism?", opts: ["Hydaspes", "Kalinga", "Mahabharata", "Panipat"], a: "Kalinga", model: "Witnessing the bloodshed at Kalinga (~261 BCE) led Ashoka to Buddhism and non-violence." },
    { id: "i6h-10", topic: "9-gupta", q: "Who gave the concept of zero?", opts: ["Aryabhata", "Brahmagupta", "Varahamihira", "Kalidasa"], a: "Aryabhata", model: "Aryabhata of the Gupta period gave zero and the decimal place-value system." },
    { id: "i6h-11", topic: "10-rural", q: "Head of a Gram Panchayat?", opts: ["Mayor", "Sarpanch", "Block Officer", "Collector"], a: "Sarpanch", model: "Sarpanch leads the Gram Panchayat. Panches assist." },
    { id: "i6h-12", topic: "11-urban", q: "Local body of a very large city?", opts: ["Gram Panchayat", "Municipal Council", "Municipal Corporation", "Nagar Panchayat"], a: "Municipal Corporation", model: "Large cities (Mumbai, Pune) are run by Municipal Corporations headed by a Mayor." },
  ],
  mistakes: [
    { mistake: "Saying medieval rulers like Akbar or Babur in Class 6.", fix: "They come in Class 7 (Medieval India). Cl 6 stops at the Gupta period." },
    { mistake: "Treating BCE like CE — counting forwards.", fix: "BCE counts BACKWARDS from 0. 500 BCE is older than 300 BCE." },
    { mistake: "Confusing Mahavira (Jainism) and Buddha (Buddhism).", fix: "Mahavira — Jainism — 5 vows. Buddha — Buddhism — 4 Noble Truths + 8-fold Path." },
    { mistake: "Saying Mayor heads a Gram Panchayat.", fix: "Sarpanch heads the village. Mayor heads a Municipal Corporation (city)." },
  ],
  cheat: [
    { heading: "Ancient civilisation rivers",
      bullets: [
        "Mesopotamia — Tigris & Euphrates.",
        "Egypt — Nile.",
        "Indus Valley — Indus.",
        "China — Hwang Ho (Yellow).",
      ],
    },
    { heading: "Indus quick-facts",
      bullets: [
        "~3300 – 1300 BCE.",
        "Sites: Harappa, Mohenjo-daro, Lothal (port), Dholavira, Kalibangan, Rakhigarhi.",
        "Great Bath at Mohenjo-daro. Bronze Dancing Girl.",
        "Script not yet deciphered.",
      ],
    },
    { heading: "Mauryans & Guptas",
      bullets: [
        "Mauryan founder Chandragupta Maurya 321 BCE; advised by Chanakya.",
        "Ashoka → Buddhism after Kalinga (~261 BCE).",
        "Lion Capital of Sarnath = National Emblem.",
        "Gupta founder Chandragupta I ~320 CE. Golden Age.",
        "Aryabhata → zero, decimal system.",
      ],
    },
    { heading: "Local government tiers",
      bullets: [
        "Rural: Gram Panchayat → Panchayat Samiti → Zilla Parishad.",
        "Urban: Nagar Panchayat → Municipal Council → Municipal Corporation.",
        "Gram Sabha = ALL village adults.",
        "73rd Amendment 1992 institutionalised Panchayati Raj.",
      ],
    },
  ],
};

// ============ GEOGRAPHY — Voyage / Oxford (11 chapters; Cl 6 covers N+S America) ============
export const ICSE6_GEOGRAPHY: ExamPack = {
  subjectId: "icse-geography",
  grade: 6,
  title: "Geography — Class 6 ICSE",
  context: "Voyage / Oxford · 11 chapters",
  highlights: [
    { label: "Textbook", value: "Voyage Geography 6 (Oxford)" },
    { label: "Continents", value: "North + South America" },
  ],
  reference: { label: "Voyage Cl 6 (Shaalaa)", url: "https://www.shaalaa.com/textbook-solutions/oxford-university-press-solutions-voyage-geography-english-class-6_161" },
  plan: [
    { title: "Maps & elements", hint: "Scale · key · direction" },
    { title: "Landforms & water bodies", hint: "Mountain · plateau · plain" },
    { title: "Agriculture & crops", hint: "Rice · wheat · cotton" },
    { title: "Americas", hint: "North & South America" },
    { title: "Cheat sheet", hint: "Continent facts" },
  ],
  topics: [
    { id: "1-maps", num: 1, title: "Maps & diagrams",
      blurb: "Types and uses.",
      syllabus: [
        "Map = flat drawing of Earth's surface.",
        "Types: physical (relief), political (boundaries), thematic (specific topic — rainfall, population).",
        "Globe = a small model of Earth showing both land and water in correct proportion.",
        "Diagrams = simplified drawings showing one aspect (e.g. a river system).",
      ],
    },
    { id: "2-elements", num: 2, title: "Elements of a map",
      blurb: "Title, scale, direction, conventional signs, key.",
      syllabus: [
        "Title — what the map is about.",
        "Scale — relationship of map distance to real distance (1 cm = 1 km).",
        "Direction — compass rose (N E S W and intermediates).",
        "Conventional signs — international agreed symbols (railway = ladder symbol).",
        "Key/Legend — explains the symbols and colours.",
      ],
    },
    { id: "3-landforms", num: 3, title: "Major landforms of the Earth",
      blurb: "Mountain, plateau, plain.",
      syllabus: [
        "Mountain — high steep landform > 600 m. Types: fold (Himalayas), block, volcanic.",
        "Plateau — flat-topped highland with steep sides (Deccan plateau).",
        "Plain — flat low land below 200 m (Indo-Gangetic plain). Highly fertile.",
        "Coast = where land meets sea; islands sit in water.",
      ],
    },
    { id: "4-water", num: 4, title: "Major water bodies",
      blurb: "Oceans, seas, rivers, lakes.",
      syllabus: [
        "Five oceans: Pacific (largest), Atlantic, Indian, Arctic, Southern.",
        "Seas are smaller and partly enclosed by land (Arabian Sea).",
        "Rivers flow from highlands to seas/oceans.",
        "Lakes are inland water bodies, can be freshwater or salty.",
      ],
    },
    { id: "5-agri", num: 5, title: "Types of agriculture",
      blurb: "Subsistence, commercial, plantation.",
      syllabus: [
        "Subsistence — farmers grow food mainly for their own family.",
        "Commercial — large-scale, food grown for selling.",
        "Plantation — single cash crop on large estate (tea, coffee, rubber).",
        "Shifting agriculture — slash-and-burn farming, used in forests.",
      ],
    },
    { id: "6-crops", num: 6, title: "Major crops",
      blurb: "Rice, wheat, cotton, sugarcane, tea, coffee.",
      syllabus: [
        "Rice — kharif crop; high rainfall + warmth; West Bengal, UP, Punjab.",
        "Wheat — rabi crop; cool growing + warm ripening; Punjab, Haryana, UP.",
        "Cotton — warm climate + light rainfall; Maharashtra, Gujarat, Telangana.",
        "Sugarcane — tropical; UP, Maharashtra.",
        "Tea — hill slopes; Assam, Darjeeling, Nilgiris.",
        "Coffee — Karnataka, Kerala.",
      ],
    },
    { id: "7-minerals", num: 7, title: "Minerals & ores",
      blurb: "What we mine.",
      syllabus: [
        "Mineral = a naturally occurring substance with definite chemical composition.",
        "Ore = a rock from which a metal can be extracted economically.",
        "Metallic minerals: iron, copper, aluminium, gold, silver.",
        "Non-metallic: limestone, mica, salt, gypsum.",
        "Energy: coal, petroleum, natural gas, uranium.",
      ],
    },
    { id: "8-na-phys", num: 8, title: "North America — location & physical features",
      blurb: "Geography of the third-largest continent.",
      syllabus: [
        "Position: Northern + Western hemisphere. Bordered by Arctic Ocean (north), Atlantic (east), Pacific (west).",
        "Countries: USA, Canada, Mexico + Central America (Cuba, Jamaica).",
        "Mountains: Rocky Mountains (west), Appalachian Mountains (east).",
        "Plains: Great Plains, Mississippi Basin.",
        "Rivers: Mississippi-Missouri (longest), Rio Grande.",
        "Great Lakes — Superior, Huron, Erie, Michigan, Ontario.",
      ],
    },
    { id: "9-na-climate", num: 9, title: "North America — climate & resources",
      blurb: "Climate types, vegetation, resources.",
      syllabus: [
        "Climate types: tundra (north), temperate, hot desert (Mexico), tropical (Central America).",
        "Vegetation: tundra → coniferous forest → grasslands (prairies) → deciduous → tropical.",
        "Wildlife: bison on prairies, polar bears in tundra, alligators in Florida.",
        "Resources: oil (Texas), iron ore (Lake Superior), coal, copper.",
        "Niagara Falls — between USA & Canada.",
      ],
    },
    { id: "10-sa-phys", num: 10, title: "South America — location & physical features",
      blurb: "Geography of the fourth-largest continent.",
      syllabus: [
        "Position: mostly Southern + Western hemisphere. Pacific Ocean (west), Atlantic (east).",
        "Countries: Brazil (largest), Argentina, Chile, Peru, Colombia, Venezuela.",
        "Mountains: Andes (longest mountain range in the world, west coast).",
        "Plains: Amazon basin, Pampas (Argentina).",
        "Rivers: Amazon (largest by water volume).",
      ],
    },
    { id: "11-sa-climate", num: 11, title: "South America — climate & resources",
      blurb: "Amazon rainforest, Pampas grasslands.",
      syllabus: [
        "Climate: equatorial in north (hot + wet), temperate in south, desert (Atacama in Chile — driest place).",
        "Vegetation: Amazon rainforest (Selvas), Pampas grassland, mangroves, alpine in Andes.",
        "Wildlife: jaguars, anacondas, sloths, llamas, capybaras.",
        "Resources: copper (Chile), iron ore (Brazil), oil (Venezuela), coffee (Brazil — largest producer).",
      ],
    },
  ],
  flashcards: [
    { term: "Map", def: "A flat drawing showing part or all of Earth's surface." },
    { term: "Scale (map)", def: "Ratio between distance on the map and the same distance on the ground." },
    { term: "Conventional signs", def: "Standard symbols used on maps so every map can be read the same way." },
    { term: "Mountain", def: "A natural landform that rises sharply above the surrounding area, usually more than 600 metres high." },
    { term: "Plateau", def: "An elevated flat-topped land with steep sides." },
    { term: "Plain", def: "A large area of flat or gently rolling low land — usually fertile." },
    { term: "Ocean", def: "A vast body of saltwater; Earth has five — Pacific, Atlantic, Indian, Arctic, Southern." },
    { term: "Subsistence farming", def: "Farming mainly to feed the farmer's family — small scale, low surplus." },
    { term: "Commercial farming", def: "Farming on a large scale to sell the produce." },
    { term: "Plantation", def: "Large-scale cash-crop farming (tea, coffee, rubber)." },
    { term: "Mineral ore", def: "A rock from which a metal can be extracted economically." },
    { term: "Rocky Mountains", def: "Major mountain range in the west of North America." },
    { term: "Andes", def: "The longest mountain range in the world, along the west coast of South America." },
    { term: "Amazon rainforest", def: "Largest tropical rainforest on Earth, in the Amazon basin (Brazil and neighbours)." },
    { term: "Niagara Falls", def: "Famous waterfall between Canada and the USA." },
    { term: "Atacama desert", def: "Driest non-polar desert in the world, in northern Chile." },
  ],
  questions: [
    { id: "i6g-1", topic: "1-maps", q: "A map that shows only country boundaries is called?", opts: ["Physical map", "Political map", "Thematic map", "Globe"], a: "Political map", model: "Political maps focus on man-made boundaries — countries and states." },
    { id: "i6g-2", topic: "2-elements", q: "The compass rose shows?", opts: ["Scale", "Title", "Direction", "Legend"], a: "Direction", model: "Compass rose shows N, E, S, W on a map." },
    { id: "i6g-3", topic: "3-landforms", q: "A high flat-topped land is a?", opts: ["Mountain", "Plain", "Plateau", "Valley"], a: "Plateau", model: "Plateaus are elevated AND flat. The Deccan plateau covers much of South India." },
    { id: "i6g-4", topic: "4-water", q: "Largest ocean?", opts: ["Atlantic", "Indian", "Pacific", "Arctic"], a: "Pacific", model: "Pacific Ocean covers about one-third of the Earth's surface." },
    { id: "i6g-5", topic: "5-agri", q: "Tea plantations are an example of?", opts: ["Subsistence farming", "Shifting farming", "Plantation farming", "Mixed farming"], a: "Plantation farming", model: "Single cash crop on a large estate — that's a plantation." },
    { id: "i6g-6", topic: "6-crops", q: "Which is a rabi crop?", opts: ["Rice", "Wheat", "Cotton", "Sugarcane"], a: "Wheat", model: "Wheat is sown in winter (rabi season). Rice is a kharif crop." },
    { id: "i6g-7", topic: "7-minerals", q: "Which is a metallic mineral?", opts: ["Limestone", "Mica", "Iron", "Salt"], a: "Iron", model: "Iron is a metal extracted from iron ore." },
    { id: "i6g-8", topic: "8-na-phys", q: "Longest river of North America?", opts: ["Amazon", "Mississippi-Missouri", "Yangtze", "Nile"], a: "Mississippi-Missouri", model: "Mississippi-Missouri river system is the longest in North America." },
    { id: "i6g-9", topic: "8-na-phys", q: "How many Great Lakes are there?", opts: ["3", "4", "5", "6"], a: "5", model: "Superior, Huron, Erie, Michigan, Ontario (acronym SHEMO or HOMES)." },
    { id: "i6g-10", topic: "10-sa-phys", q: "Longest mountain range in the world?", opts: ["Himalayas", "Andes", "Rockies", "Alps"], a: "Andes", model: "Andes run ~7,000 km along the west coast of South America." },
    { id: "i6g-11", topic: "11-sa-climate", q: "Driest desert in the world?", opts: ["Sahara", "Gobi", "Atacama", "Thar"], a: "Atacama", model: "Atacama desert in northern Chile gets almost no rainfall." },
  ],
  mistakes: [
    { mistake: "Confusing political and physical maps.", fix: "Physical = relief, mountains, rivers. Political = boundaries of countries/states." },
    { mistake: "Treating Asia or Africa in Cl 6.", fix: "Cl 6 covers ONLY North + South America. Other continents come in Cl 7+." },
    { mistake: "Calling the Amazon a mountain range.", fix: "Amazon is a RIVER and a RAINFOREST. Andes is the mountain range nearby." },
    { mistake: "Forgetting scale or direction on a map.", fix: "Every good map needs title, scale, direction, key, and conventional signs (T-S-D-K-C)." },
  ],
  cheat: [
    { heading: "Continents quick", bullets: [
      "Largest → smallest: Asia, Africa, North America, South America, Antarctica, Europe, Australia.",
      "Cl 6 SCOPE: North America + South America only.",
    ]},
    { heading: "North America facts", bullets: [
      "Mountains: Rocky (west), Appalachian (east).",
      "Rivers: Mississippi-Missouri (longest), Rio Grande.",
      "Great Lakes (5): Superior, Huron, Erie, Michigan, Ontario.",
      "Resources: oil (Texas), iron ore (Lake Superior).",
    ]},
    { heading: "South America facts", bullets: [
      "Mountains: Andes (longest range in world).",
      "Rivers: Amazon (biggest by water volume).",
      "Forest: Amazon rainforest (Selvas).",
      "Grassland: Pampas (Argentina).",
      "Desert: Atacama (driest in world).",
      "Resources: copper (Chile), coffee (Brazil — world's largest producer).",
    ]},
    { heading: "Map essentials (T-S-D-K-C)", bullets: [
      "Title — what the map shows.",
      "Scale — distance ratio.",
      "Direction — compass rose.",
      "Key/Legend — explanation of symbols and colours.",
      "Conventional signs — international standard symbols.",
    ]},
    { heading: "Crops cheat", bullets: [
      "Kharif (monsoon, sown June-July, harvested Sep-Oct): rice, maize, cotton, jute, groundnut, sugarcane.",
      "Rabi (winter, sown Oct-Nov, harvested Mar-Apr): wheat, barley, mustard, peas.",
    ]},
  ],
};

// ============ COMPUTER STUDIES — Cl 6 (8 units) ============
export const ICSE6_COMPUTER: ExamPack = {
  subjectId: "icse-computer",
  grade: 6,
  title: "Computer Studies — Class 6 ICSE",
  context: "8 units · CISCE framework",
  highlights: [{ label: "Units", value: "8" }, { label: "Scratch + HTML intro", value: "Yes" }],
  reference: { label: "ICSE 6 Computer Studies syllabus", url: "https://www.vedantu.com/icse/icse-syllabus-class-6-computer-applications" },
  plan: [
    { title: "Computer basics + categories", hint: "Types & generations" },
    { title: "Files + Word + PPT", hint: "Office basics" },
    { title: "Scratch", hint: "Blocks, sprites" },
    { title: "HTML intro", hint: "Basic tags" },
    { title: "Internet & safety", hint: "Email, browser, etiquette" },
  ],
  topics: [
    { id: "1-cat", num: 1, title: "Categories of computers & languages",
      blurb: "Types, generations, machine vs HLL.",
      syllabus: [
        "By size: supercomputer, mainframe, mini, micro (PC, laptop, tablet, smartphone).",
        "By purpose: general (everyday) vs special (industry, ATM).",
        "Generations: 1st vacuum tubes → 2nd transistors → 3rd ICs → 4th microprocessors → 5th AI.",
        "Languages: machine (binary), assembly (mnemonics), high-level (Python, Java, C).",
      ],
    },
    { id: "2-files", num: 2, title: "File management",
      blurb: "Files, folders, organising data.",
      syllabus: [
        "File = collection of data with a name and extension (.docx, .png, .mp3).",
        "Folder/Directory = container for files.",
        "Operations: create, copy, move, rename, delete, restore from Recycle Bin.",
        "Search and sort files by name, date, size, type.",
        "Common extensions: .docx (Word), .xlsx (Excel), .pptx (PowerPoint), .pdf, .jpg/.png (image), .mp3 (audio), .mp4 (video).",
      ],
    },
    { id: "3-word", num: 3, title: "Word processor — tables",
      blurb: "Inserting and formatting tables in MS Word.",
      syllabus: [
        "Insert > Table — choose rows × columns.",
        "Add/delete rows and columns; merge & split cells.",
        "Cell border, shading, alignment, sorting in tables.",
        "Convert text to table and table to text.",
      ],
    },
    { id: "4-mail", num: 4, title: "Word — mail merge",
      blurb: "One letter, many recipients.",
      syllabus: [
        "Main document = the letter template.",
        "Data source = list of names, addresses, etc. (Excel or table).",
        "Merge fields placed in main document where data goes.",
        "Preview, then complete the merge to generate one letter per recipient.",
      ],
    },
    { id: "5-ppt", num: 5, title: "PowerPoint — visual effects",
      blurb: "Animations & transitions.",
      syllabus: [
        "Slide transitions — effect when moving between slides (fade, push, wipe).",
        "Animations — entrance, emphasis, exit, motion path on elements.",
        "Timing & order of animations.",
        "Inserting images, audio, video.",
      ],
    },
    { id: "6-scratch", num: 6, title: "Scratch programming — intro",
      blurb: "Block-based coding for games.",
      syllabus: [
        "Sprite = a character that moves and reacts.",
        "Stage = background.",
        "Block categories: motion (move, turn), looks (say, switch costume), sound, events (when green flag clicked), control (repeat, if), sensing, operators, variables.",
        "Build a simple animation or game by snapping blocks.",
      ],
    },
    { id: "7-html", num: 7, title: "HTML — an introduction",
      blurb: "Basic tags to build a simple webpage.",
      syllabus: [
        "Page skeleton: <html> <head> <title> </title> </head> <body> </body> </html>",
        "Headings <h1>…<h6>. Paragraph <p>. Line break <br>. Horizontal line <hr>.",
        "Bold <b> · Italic <i> · Underline <u>.",
        "Comment: <!-- this is a comment -->",
        "Save the file with .html extension and open in a browser.",
      ],
    },
    { id: "8-internet", num: 8, title: "Internet — online surfing & safety",
      blurb: "Email, browsing, etiquette.",
      syllabus: [
        "Internet = global network connecting computers. WWW = pages accessed via the internet.",
        "Browser = software to view pages (Chrome, Firefox, Edge, Safari).",
        "URL = web address (https://example.com/page).",
        "Search engine = tool to find pages (Google, Bing).",
        "Email parts: To, Cc, Bcc, Subject, Body, Attachment.",
        "Online safety: strong passwords, no sharing OTP, don't open unknown links, talk to an adult if anything feels wrong.",
      ],
    },
  ],
  flashcards: [
    { term: "Supercomputer", def: "The fastest, most powerful kind of computer; used for weather, space, defence research." },
    { term: "Microcomputer", def: "A small personal computer — PC, laptop, tablet, smartphone." },
    { term: "Machine language", def: "Language a computer understands directly — only 0s and 1s." },
    { term: "High-level language", def: "Programming language close to English (Python, Java, C); easier for humans." },
    { term: "File extension", def: "Letters after a dot in a file name showing the file type (.docx, .png, .mp3)." },
    { term: "Folder", def: "A container for grouping related files and other folders." },
    { term: "Recycle Bin", def: "Temporary holding place for deleted files; you can restore from here." },
    { term: "Mail merge", def: "Word feature that combines a letter template with a list of recipients to print or email many personalised copies." },
    { term: "Slide transition", def: "Visual effect when moving from one PowerPoint slide to the next." },
    { term: "Sprite", def: "A character or object in Scratch that can move and respond to events." },
    { term: "HTML", def: "Hypertext Markup Language — used to structure web pages." },
    { term: "Tag (HTML)", def: "An instruction in angle brackets like <p>, <h1>, <body>." },
    { term: "URL", def: "Uniform Resource Locator — the full address of a web page." },
    { term: "Browser", def: "Software like Chrome or Firefox that lets you view web pages." },
    { term: "Search engine", def: "Online tool such as Google or Bing that finds pages on the web." },
  ],
  questions: [
    { id: "i6cp-1", topic: "1-cat", q: "The fastest type of computer?", opts: ["Microcomputer", "Minicomputer", "Mainframe", "Supercomputer"], a: "Supercomputer", model: "Supercomputers are the most powerful — used by ISRO, weather labs, defence." },
    { id: "i6cp-2", topic: "1-cat", q: "Which is a high-level language?", opts: ["Binary", "Assembly", "Python", "Machine code"], a: "Python", model: "HLLs like Python are close to English; binary and machine code are low-level." },
    { id: "i6cp-3", topic: "2-files", q: "Which extension is a Word document?", opts: [".xlsx", ".pptx", ".docx", ".mp3"], a: ".docx", model: ".docx = Word document; .xlsx = Excel; .pptx = PowerPoint; .mp3 = audio." },
    { id: "i6cp-4", topic: "2-files", q: "Files deleted go first to?", opts: ["Cloud", "Trash CAN", "Recycle Bin", "Removed forever"], a: "Recycle Bin", model: "Recycle Bin keeps deleted files temporarily so you can restore them." },
    { id: "i6cp-5", topic: "4-mail", q: "Mail merge needs a main document and?", opts: ["Printer", "Data source", "Antivirus", "Browser"], a: "Data source", model: "The data source holds names/addresses; merge fields pull info into the main document." },
    { id: "i6cp-6", topic: "5-ppt", q: "An effect that plays when moving between slides is?", opts: ["Animation", "Transition", "Hyperlink", "Theme"], a: "Transition", model: "Transitions happen BETWEEN slides. Animations happen WITHIN a slide." },
    { id: "i6cp-7", topic: "6-scratch", q: "In Scratch, the character you control is called?", opts: ["Stage", "Sprite", "Backdrop", "Block"], a: "Sprite", model: "Sprite = character. Stage = background. Block = a coding instruction." },
    { id: "i6cp-8", topic: "7-html", q: "Which tag makes a paragraph?", opts: ["<b>", "<p>", "<h1>", "<br>"], a: "<p>", model: "<p> = paragraph. <h1> = biggest heading. <b> = bold. <br> = line break." },
    { id: "i6cp-9", topic: "7-html", q: "Save an HTML page with which extension?", opts: [".doc", ".html", ".txt", ".css"], a: ".html", model: "Browsers recognise .html (or .htm) files and render them as web pages." },
    { id: "i6cp-10", topic: "8-internet", q: "Which is a safe password practice?", opts: ["Share with friends", "Use birthday", "Use 'password'", "Long, mixed characters, unique"], a: "Long, mixed characters, unique", model: "Mix upper, lower, digits, symbols; don't reuse; never share." },
  ],
  mistakes: [
    { mistake: "Mixing animation and transition in PowerPoint.", fix: "Animation happens WITHIN a slide (entering text, images). Transition happens BETWEEN slides." },
    { mistake: "Saving HTML as .doc or .txt.", fix: "HTML must be saved with .html (or .htm) extension to be opened as a web page." },
    { mistake: "Trying to balance HTML tags by writing only opening tags.", fix: "Most tags come in pairs: <p>…</p>, <b>…</b>. Self-closing ones are <br>, <hr>, <img>." },
    { mistake: "Saying microcomputer is faster than mainframe.", fix: "Speed/size ranking: super > mainframe > mini > micro. Microcomputers (PCs) are smallest and slowest." },
  ],
  cheat: [
    { heading: "Computer ranking (slowest → fastest)", bullets: [
      "Microcomputer (PC, laptop, tablet, smartphone).",
      "Minicomputer.",
      "Mainframe.",
      "Supercomputer.",
    ]},
    { heading: "Languages stack", bullets: [
      "Machine code (binary 0/1) — directly understood by CPU.",
      "Assembly (mnemonics like ADD, MOV).",
      "High-level (Python, Java, C) — close to English.",
    ]},
    { heading: "12 HTML tags to remember", bullets: [
      "<html>, <head>, <title>, <body> — page skeleton.",
      "<h1>…<h6>, <p>, <br>, <hr> — text structure.",
      "<b> bold, <i> italic, <u> underline.",
      "<img> image, <a> link.",
    ]},
    { heading: "File extensions", bullets: [
      ".docx Word · .xlsx Excel · .pptx PowerPoint.",
      ".pdf · .txt.",
      ".jpg / .png image · .mp3 audio · .mp4 video.",
      ".html webpage · .py Python.",
    ]},
    { heading: "Online safety", bullets: [
      "Strong, unique passwords (long + mix of characters).",
      "Never share OTP, password, or personal details.",
      "Don't click unknown links or download from untrusted sites.",
      "Tell a trusted adult if something online feels wrong.",
    ]},
  ],
};

export const ICSE6_PACKS: ExamPack[] = [
  ICSE6_MATHS,
  ICSE6_PHYSICS,
  ICSE6_CHEMISTRY,
  ICSE6_BIOLOGY,
  ICSE6_HISTORY,
  ICSE6_GEOGRAPHY,
  ICSE6_COMPUTER,
];
