// Language packs for ICSE Class 6 & 7 — covers English Language, English Literature,
// Hindi and Marathi for both grades. Compact but exam-usable.

import type { ExamPack } from "../exam-pack";

// ============================================================
// ENGLISH LANGUAGE — Class 6
// ============================================================
export const ICSE6_ENGLISH_LANG: ExamPack = {
  subjectId: "icse-english-lang",
  grade: 6,
  title: "English Language — Class 6 ICSE",
  context: "Grammar · comprehension · composition",
  highlights: [{ label: "Focus", value: "Foundational grammar + writing" }],
  reference: { label: "ICSE 6 English (Vedantu)", url: "https://www.vedantu.com/icse/icse-class-6-english-syllabus" },
  plan: [
    { title: "Parts of speech", hint: "All 8 categories" },
    { title: "Tenses (intro)", hint: "Past · present · future" },
    { title: "Sentence types", hint: "Simple · compound" },
    { title: "Composition", hint: "Letter · paragraph · story" },
    { title: "Cheat sheet", hint: "Common errors" },
  ],
  topics: [
    { id: "1-pos", num: 1, title: "Parts of speech",
      blurb: "The eight categories of English words.",
      syllabus: [
        "Noun — naming word (Pune, dog, joy). Types: common, proper, collective, abstract.",
        "Pronoun — replaces a noun (he, she, it, they, this).",
        "Verb — action or being (run, jump, is, am, are).",
        "Adjective — describes a noun (red, tall, beautiful).",
        "Adverb — describes a verb / adjective / another adverb (quickly, very, well).",
        "Preposition — relates noun to other words (in, on, under, between).",
        "Conjunction — joins words/clauses (and, but, or, because).",
        "Interjection — sudden feeling (Wow!, Oh!, Alas!).",
      ],
    },
    { id: "2-noun", num: 2, title: "Nouns — types and number",
      blurb: "Common, proper, collective, abstract; singular vs plural.",
      syllabus: [
        "Common noun — general (girl, city, river).",
        "Proper noun — specific name, always capital (Maya, Mumbai, Ganga).",
        "Collective noun — group (herd, flock, swarm, team).",
        "Abstract noun — feeling, idea (love, honesty, sadness).",
        "Singular → plural: +s; +es after sh/ch/x/s; -y → -ies; -f/-fe → -ves.",
        "Irregular plurals: man → men, foot → feet, child → children, mouse → mice.",
      ],
    },
    { id: "3-articles", num: 3, title: "Articles",
      blurb: "A, an, the.",
      syllabus: [
        "Indefinite: a (before consonant sound), an (before vowel sound).",
        "Definite: the (specific or already-mentioned thing).",
        "a hour ✗ → an hour ✓ (silent h, vowel sound).",
        "a useful tool ✓ (yu sound — consonant).",
      ],
    },
    { id: "4-tenses", num: 4, title: "Tenses — present, past, future",
      blurb: "Three simple tenses + their continuous forms.",
      syllabus: [
        "Simple present — habit, fact: She walks daily.",
        "Present continuous — happening now: She is walking.",
        "Simple past — completed: She walked yesterday.",
        "Past continuous — was happening: She was walking.",
        "Simple future — will happen: She will walk.",
        "Future continuous — will be happening: She will be walking.",
        "Regular verbs add -ed; irregular: go → went, see → saw, eat → ate, run → ran.",
      ],
    },
    { id: "5-prep", num: 5, title: "Prepositions & conjunctions",
      blurb: "Words that link.",
      syllabus: [
        "Prepositions of place: in, on, under, between, beside, behind, in front of.",
        "Prepositions of time: at (clock), on (date), in (month/year).",
        "Prepositions of direction: to, into, towards, across.",
        "Conjunctions: and (adds), but (contrasts), or (choice), because (reason), so (result).",
      ],
    },
    { id: "6-sent", num: 6, title: "Sentence types",
      blurb: "Four kinds + simple/compound.",
      syllabus: [
        "Declarative (statement): I read books. — ends with full stop.",
        "Interrogative (question): Do you read books? — ends with ?",
        "Imperative (command): Read the book. — ends with full stop or !",
        "Exclamatory: What a story! — ends with !",
        "Simple sentence — one main clause.",
        "Compound sentence — two main clauses joined by and/but/or.",
      ],
    },
    { id: "7-punct", num: 7, title: "Punctuation",
      blurb: "Capitals, full stop, comma, apostrophe.",
      syllabus: [
        "Always capitalise: start of sentence, the word I, proper nouns, days, months.",
        "Full stop (.) ends a statement.",
        "Question mark (?) ends a question.",
        "Comma (,) separates list items: rice, dal, chapati and sabzi.",
        "Apostrophe (') shows possession (Ravi's bag) or contraction (don't, it's).",
      ],
    },
    { id: "8-vocab", num: 8, title: "Vocabulary",
      blurb: "Synonyms, antonyms, homophones.",
      syllabus: [
        "Synonym — same/similar meaning (happy / joyful).",
        "Antonym — opposite (big / small).",
        "Homophone — sounds the same but different meaning (their / there / they're; to / too / two).",
        "Compound words: rainbow, football, blackboard.",
      ],
    },
    { id: "9-comp", num: 9, title: "Composition — letters, paragraphs, stories",
      blurb: "Structure of formal and informal writing.",
      syllabus: [
        "Informal letter: address + date · greeting (Dear Maya,) · body · closing (Yours lovingly) · name.",
        "Formal letter: sender's address · date · receiver's address · subject · salutation (Sir/Madam) · body · closing (Yours faithfully).",
        "Paragraph = one main idea + supporting sentences + concluding sentence.",
        "Story: beginning (setting) → middle (problem) → end (solution).",
      ],
    },
  ],
  flashcards: [
    { term: "Noun", def: "A naming word — for a person, place, animal, thing, idea or feeling." },
    { term: "Proper noun", def: "A specific name; always begins with a capital letter (Maya, Mumbai, Wednesday)." },
    { term: "Pronoun", def: "A word that takes the place of a noun (he, she, it, they, this)." },
    { term: "Verb", def: "An action word or a state-of-being word (run, jump, is, are)." },
    { term: "Adjective", def: "A word that describes a noun (tall, red, brave)." },
    { term: "Adverb", def: "A word that describes a verb, adjective, or another adverb (quickly, very)." },
    { term: "Preposition", def: "A word that shows the position of one thing in relation to another (in, on, under)." },
    { term: "Conjunction", def: "A word that joins words or clauses (and, but, or, because)." },
    { term: "Interjection", def: "A short word that shows sudden feeling (Wow!, Oh!, Alas!)." },
    { term: "Article", def: "A word placed before a noun: a, an (indefinite) and the (definite)." },
    { term: "Synonym", def: "A word with the same or similar meaning as another (happy / joyful)." },
    { term: "Antonym", def: "A word with the opposite meaning of another (hot / cold)." },
    { term: "Homophone", def: "Words that sound the same but mean different things (their, there, they're)." },
    { term: "Tense", def: "The form of a verb that shows when an action happens — past, present, or future." },
  ],
  questions: [
    { id: "i6el-1", topic: "1-pos", q: "What part of speech is 'quickly'?", opts: ["Noun", "Verb", "Adjective", "Adverb"], a: "Adverb", model: "It describes HOW an action is done." },
    { id: "i6el-2", topic: "2-noun", q: "Plural of 'child'?", opts: ["Childs", "Children", "Childes", "Childen"], a: "Children", model: "Irregular plural — child → children." },
    { id: "i6el-3", topic: "2-noun", q: "Which is an abstract noun?", opts: ["Pune", "Honesty", "Lion", "Pen"], a: "Honesty", model: "Honesty is a quality you can't touch — abstract." },
    { id: "i6el-4", topic: "3-articles", q: "Choose the correct: ___ honest man.", opts: ["A", "An", "The", "No article"], a: "An", model: "'Honest' starts with a vowel sound (h is silent) — use 'an'." },
    { id: "i6el-5", topic: "4-tenses", q: "Past tense of 'go'?", opts: ["Goed", "Went", "Gone", "Going"], a: "Went", model: "Irregular: go → went → gone." },
    { id: "i6el-6", topic: "4-tenses", q: "'She is reading' is which tense?", opts: ["Simple present", "Present continuous", "Simple past", "Future"], a: "Present continuous", model: "is/am/are + verb-ing = present continuous." },
    { id: "i6el-7", topic: "5-prep", q: "Choose the correct preposition: We met ___ Monday.", opts: ["in", "at", "on", "of"], a: "on", model: "'On' is used with days and dates." },
    { id: "i6el-8", topic: "6-sent", q: "'What a goal!' is which sentence type?", opts: ["Declarative", "Interrogative", "Imperative", "Exclamatory"], a: "Exclamatory", model: "Strong feeling + ! → exclamatory." },
    { id: "i6el-9", topic: "7-punct", q: "Which uses an apostrophe correctly?", opts: ["Ravi's bag", "Ravis bag", "Ravis' bag", "Ravi bag's"], a: "Ravi's bag", model: "Apostrophe before s shows the bag belongs to Ravi." },
    { id: "i6el-10", topic: "8-vocab", q: "Antonym of 'ancient'?", opts: ["Old", "Modern", "Big", "Slow"], a: "Modern", model: "Ancient = very old. Modern = new — opposite." },
    { id: "i6el-11", topic: "9-comp", q: "Closing for a FORMAL letter?", opts: ["Lots of love", "Yours faithfully", "Bye", "Cheers"], a: "Yours faithfully", model: "Formal letters: 'Yours faithfully' (unknown receiver) or 'Yours sincerely' (known)." },
  ],
  mistakes: [
    { mistake: "Forgetting capital letters on proper nouns (pune, monday).", fix: "Always capitalise names, places, days, months, and the word I." },
    { mistake: "Using 'an hour' as 'a hour'.", fix: "Listen to the SOUND, not the letter. 'Hour' starts with a vowel sound → an." },
    { mistake: "Writing 'their' instead of 'there' (or 'they're').", fix: "Their = belongs to them. There = that place. They're = they are." },
    { mistake: "Adding -ed to all past tenses (goed, runned).", fix: "Memorise irregular verbs: go → went, run → ran, eat → ate, see → saw." },
    { mistake: "Comma splices — joining two sentences with only a comma.", fix: "Use a full stop, OR add a conjunction (and/but/or/because): It rained, AND we got wet." },
  ],
  cheat: [
    { heading: "Eight parts of speech", bullets: [
      "Noun · Pronoun · Verb · Adjective · Adverb · Preposition · Conjunction · Interjection.",
    ]},
    { heading: "Tenses chart", bullets: [
      "Present simple: I walk. — habit/fact.",
      "Present continuous: I am walking. — happening now.",
      "Past simple: I walked. — completed.",
      "Past continuous: I was walking. — was happening.",
      "Future simple: I will walk.",
    ]},
    { heading: "Articles", bullets: [
      "a → consonant sound (a book, a unicorn).",
      "an → vowel sound (an apple, an hour).",
      "the → specific or already known.",
    ]},
    { heading: "Preposition choice", bullets: [
      "at + clock time (at 5 pm)",
      "on + day or date (on Monday, on 26 January)",
      "in + month / year / season (in June, in 2026, in winter)",
    ]},
    { heading: "Letter formats", bullets: [
      "Informal: Dear …, body, Yours lovingly, name.",
      "Formal: Sir/Madam, Subject:, body, Yours faithfully, name.",
    ]},
  ],
};

// ============================================================
// ENGLISH LITERATURE — Class 6
// ============================================================
export const ICSE6_ENGLISH_LIT: ExamPack = {
  subjectId: "icse-english-lit",
  grade: 6,
  title: "English Literature — Class 6 ICSE",
  context: "Prose · poetry · drama",
  highlights: [{ label: "Skill", value: "Reading + analysis" }],
  reference: { label: "ICSE 6 English literature notes", url: "https://www.englishchatterbox.com/class/6/subject/english-7/category/literature" },
  plan: [
    { title: "Story elements", hint: "Setting · plot · characters" },
    { title: "Poetry devices", hint: "Rhyme · rhythm · imagery" },
    { title: "Comprehension tips", hint: "How to answer Q-and-A" },
    { title: "Practice", hint: "Identify devices" },
    { title: "Cheat sheet", hint: "Definitions" },
  ],
  topics: [
    { id: "1-story", num: 1, title: "Story elements",
      blurb: "What every story has.",
      syllabus: [
        "Setting — where and when the story happens.",
        "Characters — protagonist (main), antagonist (opposes), minor characters.",
        "Plot — sequence of events: beginning → rising action → climax → falling action → ending.",
        "Conflict — the problem (person vs person, vs nature, vs self).",
        "Theme — the message or lesson of the story.",
      ],
    },
    { id: "2-poetry", num: 2, title: "Poetry — basics",
      blurb: "Lines, stanzas, rhyme.",
      syllabus: [
        "Line — a single row of a poem.",
        "Stanza — a group of lines (like a paragraph in poetry).",
        "Rhyme — words that sound alike at the end of lines (cat / mat).",
        "Rhyme scheme — pattern of rhyming lines (ABAB, AABB).",
        "Rhythm — the beat of the poem.",
      ],
    },
    { id: "3-devices", num: 3, title: "Figures of speech",
      blurb: "Tools poets and writers use.",
      syllabus: [
        "Simile — comparing with 'like' or 'as' (brave as a lion).",
        "Metaphor — direct comparison without 'like'/'as' (he is a lion).",
        "Personification — giving non-human things human qualities (the wind whispered).",
        "Alliteration — same starting sound (slithering snake; busy bees buzzed).",
        "Onomatopoeia — words that sound like the meaning (buzz, splash, crash).",
        "Repetition — repeating a word for effect.",
      ],
    },
    { id: "4-genres", num: 4, title: "Genres of literature",
      blurb: "Types of writing.",
      syllabus: [
        "Fiction — imagined (Panchatantra, fairy tales).",
        "Non-fiction — true (biography, autobiography, news).",
        "Drama — written to be performed; has acts, scenes, dialogues, stage directions.",
        "Poetry — uses rhythm, rhyme, imagery.",
        "Folktale — passed down orally (the Crow and the Pitcher, Tenali Raman).",
      ],
    },
    { id: "5-comp", num: 5, title: "Comprehension skills",
      blurb: "Reading carefully and answering well.",
      syllabus: [
        "Read the passage twice. Underline keywords.",
        "Read the question carefully — what is being asked?",
        "Answer in complete sentences. Use words from the question.",
        "Refer to the text for direct evidence.",
        "For 'why' or 'how' — give a reason, not a one-word answer.",
      ],
    },
  ],
  flashcards: [
    { term: "Setting", def: "Where and when the story takes place." },
    { term: "Protagonist", def: "The main character of a story." },
    { term: "Antagonist", def: "The character who opposes the protagonist." },
    { term: "Plot", def: "The sequence of events that make up a story." },
    { term: "Conflict", def: "The main problem or struggle in a story." },
    { term: "Theme", def: "The central message or lesson of a story." },
    { term: "Stanza", def: "A group of lines in a poem, like a paragraph in prose." },
    { term: "Rhyme", def: "Words with matching end-sounds in poetry." },
    { term: "Rhyme scheme", def: "The pattern of rhymed lines (e.g. AABB, ABAB)." },
    { term: "Simile", def: "A comparison using 'like' or 'as' — She runs like the wind." },
    { term: "Metaphor", def: "A direct comparison without 'like' or 'as' — Time is a thief." },
    { term: "Personification", def: "Giving a non-human thing human qualities — The wind whispered." },
    { term: "Alliteration", def: "Repetition of the same starting sound in nearby words — busy bees buzzed." },
    { term: "Onomatopoeia", def: "Words that sound like what they mean — buzz, splash, crash." },
    { term: "Drama", def: "A piece written to be performed; uses dialogue and stage directions." },
  ],
  questions: [
    { id: "i6lt-1", topic: "1-story", q: "Where and when a story happens is the?", opts: ["Plot", "Setting", "Theme", "Climax"], a: "Setting", model: "Setting = where + when. Plot = events. Theme = message." },
    { id: "i6lt-2", topic: "2-poetry", q: "A group of lines in a poem is a?", opts: ["Verse", "Stanza", "Couplet", "Quatrain"], a: "Stanza", model: "Stanzas are like paragraphs in poetry." },
    { id: "i6lt-3", topic: "3-devices", q: "'Brave as a lion' is an example of?", opts: ["Metaphor", "Simile", "Personification", "Alliteration"], a: "Simile", model: "Uses 'as' — simile. Metaphors do NOT use like/as." },
    { id: "i6lt-4", topic: "3-devices", q: "'The wind whispered her name' is?", opts: ["Simile", "Metaphor", "Personification", "Onomatopoeia"], a: "Personification", model: "Wind is given a human action (whispering)." },
    { id: "i6lt-5", topic: "3-devices", q: "'Buzz of bees' uses?", opts: ["Simile", "Alliteration", "Onomatopoeia", "Both alliteration and onomatopoeia"], a: "Both alliteration and onomatopoeia", model: "'Buzz' imitates the sound (onomatopoeia); 'buzz' + 'bees' share starting B-sound (alliteration)." },
    { id: "i6lt-6", topic: "4-genres", q: "Which is a non-fiction genre?", opts: ["Fairy tale", "Biography", "Fable", "Folk song"], a: "Biography", model: "Biography is a true story of someone's life — non-fiction." },
  ],
  mistakes: [
    { mistake: "Calling a simile a metaphor.", fix: "Simile uses LIKE or AS. Metaphor doesn't. Time is LIKE a thief = simile. Time IS a thief = metaphor." },
    { mistake: "Confusing setting and theme.", fix: "Setting = where/when (Pune in 1990). Theme = the message (friendship matters)." },
    { mistake: "Giving one-word answers to comprehension questions.", fix: "Use complete sentences and refer to the passage. Even 'Yes' or 'No' should be followed by a reason." },
  ],
  cheat: [
    { heading: "Story map", bullets: [
      "Setting (where, when)",
      "Characters (main + supporting)",
      "Plot: beginning → middle (problem) → end (solution).",
      "Theme — the lesson.",
    ]},
    { heading: "Figures of speech quick-card", bullets: [
      "Simile uses LIKE/AS.",
      "Metaphor is a direct comparison.",
      "Personification gives human qualities.",
      "Alliteration: same starting sound.",
      "Onomatopoeia: sound = meaning.",
    ]},
    { heading: "Comprehension steps", bullets: [
      "Read passage twice.",
      "Underline keywords.",
      "Re-read the question.",
      "Answer in full sentences.",
      "Quote from the text for evidence.",
    ]},
  ],
};

// ============================================================
// HINDI — Class 6
// ============================================================
export const ICSE6_HINDI: ExamPack = {
  subjectId: "icse-hindi",
  grade: 6,
  title: "हिंदी — Class 6 ICSE",
  context: "व्याकरण · पद्य · गद्य",
  highlights: [{ label: "द्वितीय भाषा", value: "ICSE" }],
  reference: { label: "ICSE 6 Hindi", url: "https://byjus.com/icse/icse-class-6-hindi-syllabus/" },
  plan: [
    { title: "संज्ञा · सर्वनाम · विशेषण · क्रिया", hint: "मूल बातें" },
    { title: "लिंग · वचन · काल", hint: "व्याकरण" },
    { title: "विलोम · पर्यायवाची · मुहावरे", hint: "शब्दभंडार" },
    { title: "अभ्यास प्रश्न", hint: "MCQ" },
    { title: "रचना · पत्र-लेखन", hint: "लिखावट" },
  ],
  topics: [
    { id: "1-sangya", num: 1, title: "संज्ञा",
      blurb: "किसी व्यक्ति, स्थान, वस्तु या भाव का नाम.",
      syllabus: [
        "व्यक्तिवाचक संज्ञा — विशेष नाम (राम, मुंबई).",
        "जातिवाचक संज्ञा — पूरी जाति (लड़का, नगर, नदी).",
        "भाववाचक संज्ञा — भाव/गुण (सुंदरता, ईमानदारी).",
        "समूहवाचक संज्ञा — समूह (सेना, सभा, परिवार).",
        "द्रव्यवाचक संज्ञा — पदार्थ (पानी, सोना, दूध).",
      ],
    },
    { id: "2-sarvanam", num: 2, title: "सर्वनाम",
      blurb: "संज्ञा के स्थान पर प्रयुक्त शब्द.",
      syllabus: [
        "पुरुषवाचक — मैं, तू, वह.",
        "निश्चयवाचक — यह, वह.",
        "अनिश्चयवाचक — कोई, कुछ.",
        "प्रश्नवाचक — कौन, क्या.",
        "संबंधवाचक — जो, वह.",
        "निजवाचक — स्वयं, आप.",
      ],
    },
    { id: "3-visheshan", num: 3, title: "विशेषण",
      blurb: "संज्ञा या सर्वनाम की विशेषता बताने वाला शब्द.",
      syllabus: [
        "गुणवाचक — गुण/दोष (अच्छा, बुरा, लंबा).",
        "संख्यावाचक — संख्या (दो, चार, पहला).",
        "परिमाणवाचक — मात्रा (थोड़ा, बहुत, कम).",
        "सार्वनामिक — यह, वह (जब विशेषण की तरह प्रयोग हो).",
      ],
    },
    { id: "4-kriya", num: 4, title: "क्रिया · काल",
      blurb: "कार्य बताने वाला शब्द; तीन काल.",
      syllabus: [
        "सकर्मक क्रिया — कर्म वाली (वह पुस्तक पढ़ता है).",
        "अकर्मक क्रिया — बिना कर्म के (वह सोता है).",
        "वर्तमान काल — हो रहा है (वह जाता है).",
        "भूत काल — हो चुका है (वह गया).",
        "भविष्य काल — होगा (वह जाएगा).",
      ],
    },
    { id: "5-ling", num: 5, title: "लिंग · वचन",
      blurb: "नाम का लिंग और संख्या.",
      syllabus: [
        "पुल्लिंग — लड़का, घोड़ा, राजा.",
        "स्त्रीलिंग — लड़की, घोड़ी, रानी.",
        "एकवचन — एक (किताब, बच्चा).",
        "बहुवचन — एक से अधिक (किताबें, बच्चे).",
      ],
    },
    { id: "6-vilom", num: 6, title: "विलोम · पर्यायवाची · मुहावरे",
      blurb: "विपरीतार्थक · समानार्थक शब्द · वाक्प्रचार.",
      syllabus: [
        "विलोम (विरुद्ध): दिन ↔ रात, अमीर ↔ गरीब, सत्य ↔ असत्य, ऊँचा ↔ नीचा.",
        "पर्यायवाची (समान): पानी = जल, नीर; आग = अग्नि, अनल; सूरज = रवि, भानु.",
        "मुहावरा — विशेष अर्थ देने वाला वाक्यांश: आँखों का तारा (बहुत प्यारा), नौ दो ग्यारह होना (भागना), कान भरना (चुगली करना).",
      ],
    },
    { id: "7-rachna", num: 7, title: "रचना · पत्र-लेखन",
      blurb: "अनुच्छेद, पत्र, कहानी.",
      syllabus: [
        "अनौपचारिक पत्र: स्थान-तिथि, संबोधन (प्रिय/प्रिय भाई), विषय, समाप्ति (तुम्हारा/तुम्हारी), नाम.",
        "औपचारिक पत्र: प्रेषक का पता, तिथि, प्राप्तकर्ता, विषय, महोदय/महोदया, समाप्ति (भवदीय), नाम.",
        "अनुच्छेद — एक विषय पर 80–100 शब्द.",
        "कहानी-लेखन: प्रारंभ → समस्या → समाधान → शिक्षा.",
      ],
    },
  ],
  flashcards: [
    { term: "संज्ञा", def: "किसी व्यक्ति, स्थान, वस्तु या भाव का नाम बताने वाला शब्द." },
    { term: "व्यक्तिवाचक संज्ञा", def: "किसी विशेष व्यक्ति, स्थान या वस्तु का नाम — राम, मुंबई." },
    { term: "जातिवाचक संज्ञा", def: "किसी पूरी जाति या वर्ग का बोध कराने वाला शब्द — लड़का, नदी." },
    { term: "भाववाचक संज्ञा", def: "गुण, भाव या स्थिति का बोध कराने वाला शब्द — सुंदरता, क्रोध." },
    { term: "सर्वनाम", def: "संज्ञा के स्थान पर प्रयुक्त शब्द — मैं, तू, वह, यह." },
    { term: "विशेषण", def: "संज्ञा या सर्वनाम की विशेषता बताने वाला शब्द — अच्छा, लंबा." },
    { term: "क्रिया", def: "किसी कार्य या स्थिति का बोध कराने वाला शब्द — खाना, सोना." },
    { term: "लिंग", def: "संज्ञा का स्त्री या पुरुष होने का बोध — लड़का (पुल्लिंग), लड़की (स्त्रीलिंग)." },
    { term: "वचन", def: "एक या एक से अधिक का बोध — एकवचन (किताब), बहुवचन (किताबें)." },
    { term: "काल", def: "क्रिया के होने का समय — वर्तमान, भूत, भविष्य." },
    { term: "विलोम", def: "विपरीत अर्थ देने वाला शब्द — दिन ↔ रात." },
    { term: "पर्यायवाची", def: "समान अर्थ देने वाला शब्द — पानी = जल = नीर." },
    { term: "मुहावरा", def: "विशेष अर्थ देने वाला शब्द-समूह — आँखों का तारा (बहुत प्रिय)." },
  ],
  questions: [
    { id: "i6h-1", topic: "1-sangya", q: "'मुंबई' किस प्रकार की संज्ञा है?", opts: ["जातिवाचक", "व्यक्तिवाचक", "भाववाचक", "समूहवाचक"], a: "व्यक्तिवाचक", model: "विशेष नाम → व्यक्तिवाचक." },
    { id: "i6h-2", topic: "1-sangya", q: "'मिठास' किस प्रकार की संज्ञा है?", opts: ["जातिवाचक", "व्यक्तिवाचक", "भाववाचक", "द्रव्यवाचक"], a: "भाववाचक", model: "गुण/भाव → भाववाचक." },
    { id: "i6h-3", topic: "2-sarvanam", q: "'कौन' कौन-सा सर्वनाम है?", opts: ["पुरुषवाचक", "निश्चयवाचक", "प्रश्नवाचक", "संबंधवाचक"], a: "प्रश्नवाचक", model: "प्रश्न पूछने वाला शब्द → प्रश्नवाचक." },
    { id: "i6h-4", topic: "3-visheshan", q: "'दो लड़के' में 'दो' कौन-सा विशेषण है?", opts: ["गुणवाचक", "संख्यावाचक", "परिमाणवाचक", "सार्वनामिक"], a: "संख्यावाचक", model: "संख्या बता रहा → संख्यावाचक विशेषण." },
    { id: "i6h-5", topic: "4-kriya", q: "'वह गया' किस काल का वाक्य है?", opts: ["वर्तमान", "भूत", "भविष्य", "अपूर्ण"], a: "भूत", model: "क्रिया हो चुकी → भूतकाल." },
    { id: "i6h-6", topic: "5-ling", q: "'घोड़ा' का स्त्रीलिंग रूप?", opts: ["घोड़ी", "घोड़े", "घोड़न", "अश्व"], a: "घोड़ी", model: "घोड़ा (पुल्लिंग) → घोड़ी (स्त्रीलिंग)." },
    { id: "i6h-7", topic: "6-vilom", q: "'सत्य' का विलोम?", opts: ["झूठ", "सच", "असत्य", "गलत"], a: "असत्य", model: "विलोम = असत्य (सत्य का विपरीत)." },
    { id: "i6h-8", topic: "6-vilom", q: "'जल' का पर्यायवाची?", opts: ["आग", "नीर", "हवा", "मिट्टी"], a: "नीर", model: "जल = पानी = नीर = अंबु." },
    { id: "i6h-9", topic: "6-vilom", q: "'नौ दो ग्यारह होना' का अर्थ?", opts: ["गिनती करना", "भाग जाना", "हँसना", "खाना"], a: "भाग जाना", model: "मुहावरा — चुपचाप भाग जाना." },
  ],
  mistakes: [
    { mistake: "क्रिया और विशेषण को मिला देना.", fix: "क्रिया = कार्य (पढ़ना). विशेषण = गुण (अच्छा)." },
    { mistake: "भाववाचक और जातिवाचक संज्ञा में भ्रम.", fix: "जातिवाचक — पूरी जाति (लड़का). भाववाचक — भाव/गुण (बचपन)." },
    { mistake: "अनौपचारिक पत्र में 'भवदीय' लिखना.", fix: "औपचारिक = भवदीय/भवदीया. अनौपचारिक = तुम्हारा/तुम्हारी." },
  ],
  cheat: [
    { heading: "व्याकरण के मुख्य अंग", bullets: [
      "संज्ञा · सर्वनाम · विशेषण · क्रिया · क्रियाविशेषण · संबंधसूचक · समुच्चयबोधक · विस्मयादिबोधक.",
    ]},
    { heading: "संज्ञा के प्रकार", bullets: [
      "व्यक्तिवाचक — विशेष नाम.",
      "जातिवाचक — पूरी जाति.",
      "भाववाचक — गुण/भाव.",
      "समूहवाचक — समूह.",
      "द्रव्यवाचक — पदार्थ.",
    ]},
    { heading: "काल", bullets: [
      "वर्तमान — अभी हो रहा (पढ़ता है).",
      "भूत — हो चुका (पढ़ा / पढ़ रहा था).",
      "भविष्य — होगा (पढ़ेगा).",
    ]},
    { heading: "जाना-पहचाना", bullets: [
      "विलोम: दिन-रात, अंधेरा-उजाला, सुख-दुख, अमीर-गरीब.",
      "पर्यायवाची: जल = पानी, नीर; अग्नि = आग, अनल; पुष्प = फूल, सुमन.",
      "मुहावरे: आँखों का तारा, नौ दो ग्यारह होना, कान भरना.",
    ]},
  ],
};

// ============================================================
// MARATHI — Class 6
// ============================================================
export const ICSE6_MARATHI: ExamPack = {
  subjectId: "icse-marathi",
  grade: 6,
  title: "मराठी — Class 6",
  context: "बालभारती सुलभभारती इयत्ता ६",
  highlights: [{ label: "अनिवार्य", value: "MH Compulsory Marathi Act 2020" }],
  reference: { label: "Balbharati Std 6 Marathi (Shaalaa)", url: "https://www.shaalaa.com/textbook-solutions/balbharati-solutions-marathi-sulabhbharati-6-standard-maharashtra-state-board_278" },
  plan: [
    { title: "नाम · सर्वनाम · विशेषण · क्रियापद", hint: "व्याकरणाची मूळ" },
    { title: "लिंग · वचन · काळ", hint: "रूप" },
    { title: "समानार्थी · विरुद्धार्थी · म्हणी", hint: "शब्दभांडार" },
    { title: "सराव प्रश्न", hint: "MCQ" },
    { title: "रचना · पत्र-लेखन", hint: "लिहिणे" },
  ],
  topics: [
    { id: "1-nam", num: 1, title: "नाम",
      blurb: "व्यक्ती, वस्तू, स्थान किंवा भाव यांच्या नावाला नाम म्हणतात.",
      syllabus: [
        "विशेषनाम — विशिष्ट नाव (राम, पुणे, गंगा).",
        "सामान्यनाम — संपूर्ण जातीचे (मुलगा, नदी, शहर).",
        "भाववाचक नाम — गुण/भाव (सत्य, धैर्य, गोडवा).",
        "समूहवाचक नाम — समूह (सेना, सभा, गुच्छ).",
      ],
    },
    { id: "2-sarvanam", num: 2, title: "सर्वनाम",
      blurb: "नामाऐवजी वापरलेले शब्द.",
      syllabus: [
        "पुरुषवाचक — मी, तू, तो/ती/ते.",
        "दर्शक — हा/ही/हे.",
        "अनिश्चित — कोणी, काही.",
        "प्रश्नार्थक — कोण, काय, कुठे.",
        "संबंधी — जो, जी, जे.",
      ],
    },
    { id: "3-visheshan", num: 3, title: "विशेषण",
      blurb: "नामाची विशेषता दाखवणारा शब्द.",
      syllabus: [
        "गुणवाचक — गुण/दोष (चांगला, लाल, उंच).",
        "संख्यावाचक — संख्या (दोन, पहिला).",
        "परिमाणवाचक — परिमाण/मात्रा (थोडे, खूप).",
        "सार्वनामिक — हा, तो (विशेषण म्हणून).",
      ],
    },
    { id: "4-kriyapad", num: 4, title: "क्रियापद · काळ",
      blurb: "कृती दाखवणारा शब्द; तीन काळ.",
      syllabus: [
        "सकर्मक क्रियापद — कर्म असलेले (तो पुस्तक वाचतो).",
        "अकर्मक क्रियापद — कर्म नसलेले (तो झोपतो).",
        "वर्तमानकाळ — आता (तो जातो).",
        "भूतकाळ — झाले (तो गेला).",
        "भविष्यकाळ — होईल (तो जाईल).",
      ],
    },
    { id: "5-ling", num: 5, title: "लिंग · वचन",
      blurb: "नामाचे लिंग आणि संख्या.",
      syllabus: [
        "पुल्लिंगी — मुलगा, घोडा, राजा.",
        "स्त्रीलिंगी — मुलगी, घोडी, राणी.",
        "नपुंसकलिंगी — पुस्तक, घर, पाणी.",
        "एकवचन — एक (मुलगा, फूल).",
        "अनेकवचन — अनेक (मुलगे, फुले).",
      ],
    },
    { id: "6-samanarthi", num: 6, title: "समानार्थी · विरुद्धार्थी · म्हणी",
      blurb: "अर्थाची ओळख.",
      syllabus: [
        "समानार्थी: सूर्य = रवी = भास्कर; पाणी = जल = उदक; घर = निवास = सदन.",
        "विरुद्धार्थी: दिवस ↔ रात्र, उजेड ↔ अंधार, मोठा ↔ लहान, सत्य ↔ असत्य.",
        "म्हणी: 'अति तेथे माती', 'थेंबे थेंबे तळे साचे', 'अंथरूण पाहून पाय पसरावे', 'नाचता येईना अंगण वाकडे'.",
      ],
    },
    { id: "7-rachna", num: 7, title: "रचना · पत्र-लेखन",
      blurb: "निबंध, पत्र, संवाद.",
      syllabus: [
        "अनौपचारिक पत्र: ठिकाण-तारीख, संबोधन (प्रिय), मजकूर, समाप्ती (तुझा/तुझी), नाव.",
        "औपचारिक पत्र: पाठविणाऱ्याचा पत्ता, तारीख, प्राप्तकर्ता, विषय, महोदय/महोदया, समाप्ती (आपला/आपली), नाव.",
        "निबंध — एक विषयावर ८०–१०० शब्दांत प्रारंभ-विषय-समारोप.",
        "संवाद — दोन व्यक्तींमधील बोलणे; डायलॉग टॅगसह.",
      ],
    },
  ],
  flashcards: [
    { term: "नाम", def: "व्यक्ती, वस्तू, स्थान किंवा भाव यांच्या नावाला नाम म्हणतात." },
    { term: "विशेषनाम", def: "विशिष्ट व्यक्ती, स्थान किंवा वस्तूचे नाव — राम, पुणे." },
    { term: "सामान्यनाम", def: "संपूर्ण जाती किंवा वर्गाला दर्शविणारे नाम — मुलगा, नदी." },
    { term: "भाववाचक नाम", def: "गुण किंवा भाव दर्शविणारे नाम — गोडवा, धैर्य." },
    { term: "सर्वनाम", def: "नामाऐवजी वापरलेला शब्द — मी, तू, तो." },
    { term: "विशेषण", def: "नामाची विशेषता दाखवणारा शब्द — चांगला, लांब." },
    { term: "क्रियापद", def: "कृती किंवा स्थिती दाखवणारा शब्द — खाणे, झोपणे." },
    { term: "लिंग", def: "नामाचे पुल्लिंगी / स्त्रीलिंगी / नपुंसकलिंगी असण्याचा प्रकार." },
    { term: "वचन", def: "एक किंवा अनेक यांचा बोध — एकवचन (फूल), अनेकवचन (फुले)." },
    { term: "काळ", def: "क्रिया घडण्याचा वेळ — वर्तमान, भूत, भविष्य." },
    { term: "समानार्थी शब्द", def: "एकाच अर्थाचे वेगवेगळे शब्द — सूर्य = रवी = भास्कर." },
    { term: "विरुद्धार्थी शब्द", def: "उलट अर्थाचे शब्द — दिवस ↔ रात्र." },
    { term: "म्हण", def: "अनुभवातून आलेले छोटे, सुंदर वाक्य — अति तेथे माती." },
  ],
  questions: [
    { id: "i6mr-1", topic: "1-nam", q: "'पुणे' हे कोणते नाम आहे?", opts: ["सामान्यनाम", "विशेषनाम", "भाववाचक", "समूहवाचक"], a: "विशेषनाम", model: "विशिष्ट स्थळ → विशेषनाम." },
    { id: "i6mr-2", topic: "1-nam", q: "'गोडवा' हे कोणते नाम आहे?", opts: ["विशेषनाम", "सामान्यनाम", "भाववाचक नाम", "समूहवाचक नाम"], a: "भाववाचक नाम", model: "गुण/भाव → भाववाचक नाम." },
    { id: "i6mr-3", topic: "2-sarvanam", q: "'कोण?' हे कोणत्या प्रकारचे सर्वनाम आहे?", opts: ["दर्शक", "प्रश्नार्थक", "अनिश्चित", "संबंधी"], a: "प्रश्नार्थक", model: "प्रश्न विचारणारा शब्द → प्रश्नार्थक." },
    { id: "i6mr-4", topic: "4-kriyapad", q: "'तो खेळला' या वाक्याचा काळ?", opts: ["वर्तमानकाळ", "भूतकाळ", "भविष्यकाळ", "नाही"], a: "भूतकाळ", model: "क्रिया झाली → भूतकाळ." },
    { id: "i6mr-5", topic: "5-ling", q: "'पुस्तक' कोणत्या लिंगाचे आहे?", opts: ["पुल्लिंगी", "स्त्रीलिंगी", "नपुंसकलिंगी", "नाही"], a: "नपुंसकलिंगी", model: "पुस्तक — नपुंसकलिंगी (मराठीत तीन लिंगे)." },
    { id: "i6mr-6", topic: "5-ling", q: "'मुलगा' चे अनेकवचन?", opts: ["मुलगी", "मुले", "मुलगे", "मुलगा"], a: "मुलगे", model: "मुलगा (एकवचन) → मुलगे (अनेकवचन)." },
    { id: "i6mr-7", topic: "6-samanarthi", q: "'दिवस' चा विरुद्धार्थी शब्द?", opts: ["सकाळ", "रात्र", "दुपार", "संध्याकाळ"], a: "रात्र", model: "दिवस ↔ रात्र." },
    { id: "i6mr-8", topic: "6-samanarthi", q: "'पाणी' चा समानार्थी शब्द?", opts: ["वारा", "जल", "अग्नी", "वायू"], a: "जल", model: "पाणी = जल = उदक." },
    { id: "i6mr-9", topic: "6-samanarthi", q: "'अति तेथे माती' म्हणीचा अर्थ?", opts: ["खूप पाऊस", "अति केल्यास नुकसान", "मातीवर बसणे", "खूप काम"], a: "अति केल्यास नुकसान", model: "कोणतीही गोष्ट जास्त केली तर हानी होते." },
  ],
  mistakes: [
    { mistake: "मराठीत दोनच लिंगे आहेत असे मानणे.", fix: "मराठीत तीन लिंगे आहेत — पुल्लिंगी, स्त्रीलिंगी, नपुंसकलिंगी." },
    { mistake: "अनौपचारिक पत्रात 'आपला' लिहिणे.", fix: "औपचारिक = आपला/आपली. अनौपचारिक = तुझा/तुझी." },
    { mistake: "विशेषनाम लहान अक्षरात लिहिणे.", fix: "विशेषनाम मराठीत मोठ्या अक्षराने सुरू होत नसले तरी देवनागरीत स्पष्ट लिहावे — राम, पुणे, गंगा." },
  ],
  cheat: [
    { heading: "व्याकरणाचे मूळ", bullets: [
      "नाम · सर्वनाम · विशेषण · क्रियापद · क्रियाविशेषण · शब्दयोगी · उभयान्वयी · केवलप्रयोगी.",
    ]},
    { heading: "नामाचे प्रकार", bullets: [
      "विशेषनाम — विशिष्ट नाव.",
      "सामान्यनाम — संपूर्ण जाती.",
      "भाववाचक नाम — गुण/भाव.",
      "समूहवाचक नाम — समूह.",
    ]},
    { heading: "लिंग (तीन)", bullets: [
      "पुल्लिंगी: मुलगा, घोडा, राजा.",
      "स्त्रीलिंगी: मुलगी, घोडी, राणी.",
      "नपुंसकलिंगी: पुस्तक, घर, पाणी.",
    ]},
    { heading: "काळ", bullets: [
      "वर्तमानकाळ — आता (तो जातो).",
      "भूतकाळ — झाले (तो गेला).",
      "भविष्यकाळ — होईल (तो जाईल).",
    ]},
    { heading: "जाणीव", bullets: [
      "समानार्थी: सूर्य = रवी = भास्कर; पाणी = जल = उदक.",
      "विरुद्धार्थी: दिवस-रात्र, सत्य-असत्य, उजेड-अंधार.",
      "म्हणी: 'अति तेथे माती', 'थेंबे थेंबे तळे साचे'.",
    ]},
  ],
};

// ============================================================
// Class 7 — same subjects, deeper content
// ============================================================
export const ICSE7_ENGLISH_LANG: ExamPack = {
  subjectId: "icse-english-lang",
  grade: 7,
  title: "English Language — Class 7 ICSE",
  context: "Grammar · clauses · voice · composition",
  highlights: [{ label: "Focus", value: "Active/passive · direct/indirect · clauses" }],
  reference: { label: "ICSE 7 English (Vedantu)", url: "https://www.vedantu.com/icse/icse-class-7-english-syllabus" },
  plan: [
    { title: "Tenses (all 12 forms)", hint: "Simple · continuous · perfect" },
    { title: "Active vs passive", hint: "Voice change" },
    { title: "Direct vs indirect speech", hint: "Reporting" },
    { title: "Clauses & sentence types", hint: "Simple · compound · complex" },
    { title: "Composition", hint: "Notice · letter · essay" },
  ],
  topics: [
    { id: "1-tenses", num: 1, title: "All 12 tenses",
      blurb: "Simple · continuous · perfect · perfect continuous in past/present/future.",
      syllabus: [
        "Simple present: She writes. — habit/fact.",
        "Present continuous: She is writing. — happening now.",
        "Present perfect: She has written. — completed action with present relevance.",
        "Present perfect continuous: She has been writing. — started in past, still going.",
        "Past simple: She wrote. Past continuous: She was writing. Past perfect: She had written. Past perfect continuous: She had been writing.",
        "Future simple: She will write. Future continuous: She will be writing. Future perfect: She will have written.",
      ],
    },
    { id: "2-voice", num: 2, title: "Active and passive voice",
      blurb: "Subject does (active) vs subject receives (passive).",
      syllabus: [
        "Active: Subject + verb + object — The teacher praised Maya.",
        "Passive: Object becomes subject + 'be' + past participle + by — Maya was praised by the teacher.",
        "Steps to change active → passive: swap subject and object, use be + V3 (past participle), keep the tense, add 'by' before the original subject.",
        "Passive used when the doer is unknown / unimportant / obvious.",
      ],
    },
    { id: "3-speech", num: 3, title: "Direct and indirect speech",
      blurb: "Quoting vs reporting.",
      syllabus: [
        "Direct: 'I am tired,' said Raj.",
        "Indirect (reported): Raj said that he was tired.",
        "Tense shifts back: present → past; will → would; can → could.",
        "Pronouns change to match the reporter (I → he/she).",
        "Time/place words change: now → then; today → that day; here → there.",
      ],
    },
    { id: "4-clauses", num: 4, title: "Phrases & clauses",
      blurb: "Phrase = no verb, clause = has subject + verb.",
      syllabus: [
        "Phrase — group of words without a subject-verb pair (in the garden, very tall).",
        "Clause — has its own subject + verb. Main clause (independent) can stand alone; sub-clause (dependent) cannot.",
        "Simple sentence — one main clause.",
        "Compound — two main clauses joined by and/but/or.",
        "Complex — one main clause + one or more sub-clauses joined by because/although/when/if.",
      ],
    },
    { id: "5-modal", num: 5, title: "Modal verbs",
      blurb: "Helping verbs that show ability, permission, necessity.",
      syllabus: [
        "Can — ability, informal permission.",
        "Could — past ability, polite permission.",
        "May — permission, possibility.",
        "Might — small possibility.",
        "Must — necessity / strong advice.",
        "Should — advice.",
        "Will — future, willingness.",
        "Would — polite request, hypothetical.",
      ],
    },
    { id: "6-comp", num: 6, title: "Composition — notice, formal letter, essay",
      blurb: "Standard formats.",
      syllabus: [
        "Notice: NAME OF ORGANISATION + box + heading NOTICE + date + body (what/when/where/who) + name of writer + designation.",
        "Formal letter: sender address · date · receiver · subject · salutation · body · Yours faithfully · name.",
        "Essay: introduction → 2–3 body paragraphs (each with one main idea) → conclusion. ~150–200 words.",
      ],
    },
  ],
  flashcards: [
    { term: "Active voice", def: "Subject performs the action — The cat chased the mouse." },
    { term: "Passive voice", def: "Subject receives the action — The mouse was chased by the cat." },
    { term: "Direct speech", def: "Exact words of the speaker inside quotation marks." },
    { term: "Indirect speech", def: "Reported version of what someone said, usually without quotation marks." },
    { term: "Phrase", def: "A group of words without a subject-verb pair (in the garden, very fast)." },
    { term: "Clause", def: "A group of words with its own subject and verb." },
    { term: "Main clause", def: "A clause that can stand alone as a complete sentence." },
    { term: "Subordinate clause", def: "A clause that cannot stand alone; depends on a main clause." },
    { term: "Modal verb", def: "Helping verb that shows mood — can, could, may, might, must, should, will, would." },
    { term: "Present perfect", def: "Tense formed with has/have + past participle (has eaten); a completed action with present relevance." },
    { term: "Past perfect", def: "Tense formed with had + past participle (had eaten); action completed BEFORE another past action." },
    { term: "Notice", def: "Brief formal announcement put up by an organisation, dated and signed by a designated person." },
  ],
  questions: [
    { id: "i7el-1", topic: "1-tenses", q: "'They have finished the homework.' is which tense?", opts: ["Past simple", "Present continuous", "Present perfect", "Future"], a: "Present perfect", model: "have/has + past participle = present perfect." },
    { id: "i7el-2", topic: "2-voice", q: "Change to passive: 'Maya wrote a letter.'", opts: ["A letter was written by Maya.", "A letter is written by Maya.", "Maya wrote a letter by herself.", "A letter writes Maya."], a: "A letter was written by Maya.", model: "Past tense → was/were + past participle (written). Add 'by Maya'." },
    { id: "i7el-3", topic: "3-speech", q: "Direct: He said, 'I am happy.' Choose the indirect form.", opts: ["He said that he is happy.", "He said that he was happy.", "He told that I am happy.", "He says that he was happy."], a: "He said that he was happy.", model: "Tense shifts back: am → was. Pronoun I → he." },
    { id: "i7el-4", topic: "4-clauses", q: "'When the bell rang, the children ran out.' is what type of sentence?", opts: ["Simple", "Compound", "Complex", "Exclamatory"], a: "Complex", model: "One main + one subordinate clause (When the bell rang) = complex." },
    { id: "i7el-5", topic: "5-modal", q: "Choose the modal for polite permission: '___ I leave early today?'", opts: ["Can", "May", "Will", "Must"], a: "May", model: "'May' is the most polite for permission." },
    { id: "i7el-6", topic: "6-comp", q: "Closing of a FORMAL letter to an unknown receiver?", opts: ["Yours lovingly", "Yours sincerely", "Yours faithfully", "Cheers"], a: "Yours faithfully", model: "Unknown receiver (Sir/Madam) → Yours faithfully. Known → Yours sincerely." },
  ],
  mistakes: [
    { mistake: "Forgetting to shift tense in indirect speech.", fix: "Present → past, will → would, can → could, today → that day, here → there." },
    { mistake: "Writing 'by Maya' in active voice.", fix: "'By' is only in passive. Active just has subject + verb + object." },
    { mistake: "Mixing 'May' and 'Can' for permission.", fix: "May = polite/formal. Can = informal/ability." },
    { mistake: "Using past participle instead of simple past (I have went).", fix: "Have/has needs the past participle (gone), not simple past (went). I have gone." },
  ],
  cheat: [
    { heading: "12 tenses chart", bullets: [
      "Simple: V / V2 / will V.",
      "Continuous: am-is-are V-ing / was-were V-ing / will be V-ing.",
      "Perfect: has-have V3 / had V3 / will have V3.",
      "Perfect continuous: has-have been V-ing / had been V-ing / will have been V-ing.",
    ]},
    { heading: "Active → Passive steps", bullets: [
      "Find subject (S), verb (V), object (O).",
      "Swap S and O.",
      "Add a form of 'be' that matches the tense.",
      "Change V to past participle (V3).",
      "Add 'by + old subject' (if needed).",
    ]},
    { heading: "Reporting tense shifts", bullets: [
      "am/is/are → was/were.",
      "have/has → had.",
      "will → would. can → could. may → might.",
      "today → that day. tomorrow → the next day. yesterday → the previous day.",
      "this → that. here → there.",
    ]},
    { heading: "Letter formats", bullets: [
      "Formal: 'Yours faithfully' (unknown), 'Yours sincerely' (known).",
      "Informal: 'Yours lovingly', 'With love'.",
    ]},
  ],
};

export const ICSE7_ENGLISH_LIT: ExamPack = {
  subjectId: "icse-english-lit",
  grade: 7,
  title: "English Literature — Class 7 ICSE",
  context: "Prose · poetry · drama",
  highlights: [{ label: "Common texts", value: "Canterville Ghost · Three Questions · Blue Umbrella" }],
  reference: { label: "ICSE 7 English literature notes", url: "https://www.englishchatterbox.com/class/7/subject/english-7/category/literature" },
  plan: [
    { title: "Common prescribed prose", hint: "Canterville · Three Questions · Blue Umbrella" },
    { title: "Common poems", hint: "Palm Trees · Television" },
    { title: "Literary devices", hint: "Beyond Class 6 — irony, satire" },
    { title: "Comprehension", hint: "Inference questions" },
    { title: "Cheat sheet", hint: "Author + theme map" },
  ],
  topics: [
    { id: "1-prose", num: 1, title: "Commonly prescribed prose",
      blurb: "Famous short stories in ICSE Cl 7 readers.",
      syllabus: [
        "'The Canterville Ghost' (Oscar Wilde, abridged) — humorous twist on classic ghost tale; the Otis family vs Sir Simon.",
        "'The Three Questions' (Leo Tolstoy) — a king asks three questions; a hermit answers through experience.",
        "'The Blue Umbrella' (Ruskin Bond) — Binya's leopard umbrella in a Himachal village.",
        "'Marie Curie: A Radiant Life' — biographical piece on the scientist who discovered polonium and radium.",
      ],
    },
    { id: "2-poetry", num: 2, title: "Commonly prescribed poems",
      blurb: "Classic poems studied at Cl 7.",
      syllabus: [
        "'Palm Trees' (Rabindranath Tagore) — palm tree dreams of the sky.",
        "'Television' (Roald Dahl) — funny but pointed criticism of children watching too much TV.",
        "Mood, tone, theme, rhyme scheme analysis.",
      ],
    },
    { id: "3-devices", num: 3, title: "Literary devices (deeper)",
      blurb: "Beyond simile and metaphor.",
      syllabus: [
        "Irony — opposite of what is expected (Sir Simon trying to scare the Otises ends up scared).",
        "Satire — using humour to criticise (Roald Dahl satirising TV).",
        "Foreshadowing — hints at what's to come.",
        "Symbolism — object stands for an idea (umbrella = pride/possession).",
        "Imagery — vivid descriptive language appealing to the senses.",
        "Hyperbole — deliberate exaggeration.",
      ],
    },
    { id: "4-types", num: 4, title: "Drama & playscript basics",
      blurb: "Reading and analysing plays.",
      syllabus: [
        "Act = a major division (like a chapter).",
        "Scene = a sub-division of an act.",
        "Dialogue = the words spoken by characters.",
        "Stage directions = instructions in italics or brackets.",
        "Monologue = one character speaking alone; soliloquy = thoughts spoken aloud to oneself.",
      ],
    },
    { id: "5-comp", num: 5, title: "Comprehension — inference questions",
      blurb: "Going beyond literal answers.",
      syllabus: [
        "Literal questions — answer directly from the passage.",
        "Inferential questions — read between the lines; what does the author imply?",
        "Vocabulary in context — define a word from how it is used in the passage.",
        "Author's purpose / tone questions.",
      ],
    },
  ],
  flashcards: [
    { term: "Irony", def: "A contrast between what is expected and what actually happens." },
    { term: "Satire", def: "Use of humour and exaggeration to criticise or expose foolishness." },
    { term: "Foreshadowing", def: "Hint about something that will happen later in the story." },
    { term: "Symbolism", def: "When an object or action represents an idea (a dove can symbolise peace)." },
    { term: "Imagery", def: "Vivid descriptive language that appeals to the five senses." },
    { term: "Hyperbole", def: "Deliberate exaggeration for emphasis — 'I've told you a million times'." },
    { term: "Theme", def: "The underlying message or lesson of a piece of literature." },
    { term: "Tone", def: "The author's attitude toward the subject (serious, humorous, sarcastic)." },
    { term: "Mood", def: "The feeling the reader experiences (suspense, joy, sadness)." },
    { term: "Act", def: "A major division of a play." },
    { term: "Scene", def: "A subdivision of an act in a play." },
    { term: "Soliloquy", def: "A speech in a play where a character thinks aloud, alone on stage." },
    { term: "Stage directions", def: "Author's instructions in a playscript, often in italics or brackets." },
    { term: "Biography", def: "The story of a real person's life written by someone else." },
    { term: "Autobiography", def: "The story of a real person's life written by themselves." },
  ],
  questions: [
    { id: "i7lt-1", topic: "1-prose", q: "Who wrote 'The Canterville Ghost'?", opts: ["Charles Dickens", "Oscar Wilde", "Roald Dahl", "Ruskin Bond"], a: "Oscar Wilde", model: "Oscar Wilde — Irish author, late 1800s." },
    { id: "i7lt-2", topic: "1-prose", q: "Who is the central character of 'The Blue Umbrella'?", opts: ["Bingo", "Binya", "Rakesh", "Maya"], a: "Binya", model: "Binya, the little girl whose leopard umbrella catches the eye of the shopkeeper." },
    { id: "i7lt-3", topic: "2-poetry", q: "Who wrote 'Television'?", opts: ["Tagore", "Wordsworth", "Roald Dahl", "Frost"], a: "Roald Dahl", model: "Dahl satirises children watching too much TV in this poem from Charlie and the Chocolate Factory." },
    { id: "i7lt-4", topic: "3-devices", q: "'The classroom was a zoo' is which figure of speech?", opts: ["Simile", "Metaphor", "Personification", "Hyperbole"], a: "Metaphor", model: "Direct comparison without 'like'/'as' — classroom IS a zoo (chaos)." },
    { id: "i7lt-5", topic: "3-devices", q: "'I've told you a thousand times' is?", opts: ["Personification", "Hyperbole", "Irony", "Imagery"], a: "Hyperbole", model: "Deliberate exaggeration for emphasis." },
    { id: "i7lt-6", topic: "4-types", q: "Author's instructions in a play, usually in italics, are called?", opts: ["Dialogue", "Stage directions", "Soliloquy", "Monologue"], a: "Stage directions", model: "Stage directions tell actors what to do." },
  ],
  mistakes: [
    { mistake: "Confusing tone and mood.", fix: "Tone = author's attitude. Mood = reader's feeling." },
    { mistake: "Saying biography and autobiography are the same.", fix: "Biography is by SOMEONE ELSE. Autobiography is by the SAME person." },
    { mistake: "Calling all comparisons similes.", fix: "Only comparisons using LIKE or AS are similes. 'He IS a lion' = metaphor." },
  ],
  cheat: [
    { heading: "Authors map", bullets: [
      "'The Canterville Ghost' — Oscar Wilde.",
      "'The Three Questions' — Leo Tolstoy.",
      "'The Blue Umbrella' — Ruskin Bond.",
      "'Marie Curie' — biographical piece (often by Eve Curie).",
      "'Palm Trees' — Rabindranath Tagore.",
      "'Television' — Roald Dahl.",
    ]},
    { heading: "Literary device quick-card", bullets: [
      "Irony — opposite outcome.",
      "Satire — humour with a point.",
      "Foreshadowing — hint of future.",
      "Symbolism — object = idea.",
      "Imagery — sensory description.",
      "Hyperbole — extreme exaggeration.",
    ]},
    { heading: "Comprehension levels", bullets: [
      "Literal — directly from the text.",
      "Inferential — read between the lines.",
      "Vocabulary in context — meaning from usage.",
      "Author's tone / purpose — why was this written?",
    ]},
  ],
};

export const ICSE7_HINDI: ExamPack = {
  subjectId: "icse-hindi",
  grade: 7,
  title: "हिंदी — Class 7 ICSE",
  context: "व्याकरण · पद्य · गद्य",
  highlights: [{ label: "द्वितीय भाषा", value: "ICSE" }],
  reference: { label: "ICSE 7 Hindi", url: "https://byjus.com/icse/icse-class-7-hindi-syllabus/" },
  plan: [
    { title: "संधि · समास · अलंकार", hint: "उच्च व्याकरण" },
    { title: "उपसर्ग · प्रत्यय", hint: "शब्द-निर्माण" },
    { title: "वाक्य-रूपांतरण", hint: "विधि · आज्ञा · प्रश्न" },
    { title: "रचना", hint: "निबंध · पत्र · संवाद" },
    { title: "अभ्यास", hint: "MCQ" },
  ],
  topics: [
    { id: "1-sandhi", num: 1, title: "संधि",
      blurb: "दो वर्णों या ध्वनियों का मेल.",
      syllabus: [
        "स्वर संधि — स्वर + स्वर: विद्या + आलय = विद्यालय (दीर्घ).",
        "व्यंजन संधि — व्यंजन + स्वर/व्यंजन: सत् + जन = सज्जन.",
        "विसर्ग संधि — विसर्ग + स्वर/व्यंजन: नि: + आहार = निराहार.",
      ],
    },
    { id: "2-samas", num: 2, title: "समास",
      blurb: "दो शब्दों का संक्षिप्त रूप.",
      syllabus: [
        "तत्पुरुष — राजपुत्र (राजा का पुत्र).",
        "द्वंद्व — माता-पिता (माता और पिता).",
        "बहुव्रीहि — दशानन (दस आनन वाला = रावण).",
        "द्विगु — त्रिलोक (तीन लोक).",
        "कर्मधारय — महापुरुष (महान पुरुष).",
        "अव्ययीभाव — यथाशक्ति (शक्ति के अनुसार).",
      ],
    },
    { id: "3-alankar", num: 3, title: "अलंकार",
      blurb: "काव्य में सौंदर्य बढ़ाने वाले प्रयोग.",
      syllabus: [
        "अनुप्रास — एक ही वर्ण की आवृत्ति (चारु चंद्र की चंचल किरणें).",
        "यमक — एक ही शब्द भिन्न अर्थ में (कनक कनक ते सौ गुनी).",
        "उपमा — एक की दूसरे से समानता (सीता-सी सुंदर).",
        "रूपक — उपमेय में उपमान का आरोप (चरण-कमल).",
        "उत्प्रेक्षा — संभावना (मानो / जैसे).",
      ],
    },
    { id: "4-upsarg", num: 4, title: "उपसर्ग · प्रत्यय",
      blurb: "शब्द के आगे या पीछे जुड़कर अर्थ बदलने वाले अंश.",
      syllabus: [
        "उपसर्ग शब्द के पहले: अ + सत्य = असत्य; प्र + गति = प्रगति; उप + वन = उपवन.",
        "प्रत्यय शब्द के बाद: सुंदर + ता = सुंदरता; पढ़ + ना = पढ़ना.",
        "कृत प्रत्यय (क्रिया से बने): पढ़ने, लिखावट.",
        "तद्धित प्रत्यय (संज्ञा से बने): मानवता, बचपन.",
      ],
    },
    { id: "5-vakya", num: 5, title: "वाक्य के प्रकार · रूपांतरण",
      blurb: "रचना और अर्थ के आधार पर.",
      syllabus: [
        "रचना: साधारण (एक उद्देश्य-विधेय), संयुक्त (दो स्वतंत्र वाक्य जुड़े), मिश्र (मुख्य + आश्रित).",
        "अर्थ: विधानवाचक (हाँ), निषेधवाचक (नहीं), प्रश्नवाचक (?), विधि-सूचक (आज्ञा), विस्मयादिबोधक (!), इच्छावाचक.",
        "वाच्य परिवर्तन: कर्तृवाच्य ↔ कर्मवाच्य ↔ भाववाच्य.",
      ],
    },
  ],
  flashcards: [
    { term: "संधि", def: "दो वर्णों का मेल — विद्या + आलय = विद्यालय." },
    { term: "समास", def: "दो शब्दों का संक्षेप — राजपुत्र = राजा का पुत्र." },
    { term: "तत्पुरुष समास", def: "उत्तर पद प्रधान — राजपुत्र, गंगाजल." },
    { term: "द्वंद्व समास", def: "दोनों पद समान, 'और' लगाया जाता है — माता-पिता." },
    { term: "बहुव्रीहि समास", def: "दोनों पदों से इतर अर्थ — दशानन = रावण." },
    { term: "उपसर्ग", def: "शब्द के आगे लगने वाला अंश — अ, प्र, उप, अनु, परा." },
    { term: "प्रत्यय", def: "शब्द के बाद लगने वाला अंश — ता, पन, इक, वान." },
    { term: "अलंकार", def: "काव्य में सौंदर्य बढ़ाने वाले प्रयोग — अनुप्रास, यमक, उपमा, रूपक." },
    { term: "अनुप्रास", def: "एक ही व्यंजन की बार-बार आवृत्ति — 'चारु चंद्र की चंचल किरणें'." },
    { term: "उपमा अलंकार", def: "एक की दूसरे से समानता — 'सीता-सी सुंदर'." },
    { term: "साधारण वाक्य", def: "एक उद्देश्य और एक विधेय वाला वाक्य." },
    { term: "मिश्र वाक्य", def: "एक मुख्य + एक या अधिक आश्रित उपवाक्य." },
  ],
  questions: [
    { id: "i7h-1", topic: "1-sandhi", q: "'विद्या + आलय' की संधि?", opts: ["विद्यालय", "विदयालय", "विद्यालया", "विद्या आलय"], a: "विद्यालय", model: "स्वर संधि (आ + आ = आ) → विद्यालय." },
    { id: "i7h-2", topic: "2-samas", q: "'राजपुत्र' किस समास का उदाहरण है?", opts: ["द्वंद्व", "तत्पुरुष", "बहुव्रीहि", "द्विगु"], a: "तत्पुरुष", model: "राजा का पुत्र — उत्तर पद प्रधान → तत्पुरुष." },
    { id: "i7h-3", topic: "2-samas", q: "'दशानन' किस समास का उदाहरण है?", opts: ["तत्पुरुष", "बहुव्रीहि", "द्वंद्व", "कर्मधारय"], a: "बहुव्रीहि", model: "दस आनन वाला = रावण — दोनों पदों से अलग अर्थ → बहुव्रीहि." },
    { id: "i7h-4", topic: "3-alankar", q: "'सीता-सी सुंदर' किस अलंकार का उदाहरण है?", opts: ["अनुप्रास", "उपमा", "रूपक", "यमक"], a: "उपमा", model: "एक की दूसरे से समानता दिखाना — उपमा." },
    { id: "i7h-5", topic: "4-upsarg", q: "'असत्य' में उपसर्ग क्या है?", opts: ["अ", "अस", "त्य", "नहीं"], a: "अ", model: "अ + सत्य = असत्य. 'अ' निषेधसूचक उपसर्ग." },
    { id: "i7h-6", topic: "5-vakya", q: "'राम पढ़ता है और सीता गाती है' किस प्रकार का वाक्य है?", opts: ["साधारण", "संयुक्त", "मिश्र", "विस्मय"], a: "संयुक्त", model: "दो स्वतंत्र वाक्य 'और' से जुड़े → संयुक्त वाक्य." },
  ],
  mistakes: [
    { mistake: "तत्पुरुष और बहुव्रीहि में भ्रम.", fix: "तत्पुरुष — उत्तर पद प्रधान (राजपुत्र = पुत्र). बहुव्रीहि — कोई तीसरा अर्थ (दशानन = रावण)." },
    { mistake: "उपसर्ग और प्रत्यय की जगह भूलना.", fix: "उपसर्ग पहले (अ+सत्य), प्रत्यय बाद में (सुंदर+ता)." },
    { mistake: "संयुक्त और मिश्र वाक्य मिलाना.", fix: "संयुक्त — दो स्वतंत्र वाक्य (और/परंतु). मिश्र — मुख्य + आश्रित (क्योंकि/जब/अगर)." },
  ],
  cheat: [
    { heading: "समास के छह प्रकार", bullets: [
      "तत्पुरुष — उत्तर पद प्रधान.",
      "द्वंद्व — दोनों पद समान.",
      "बहुव्रीहि — तीसरा अर्थ.",
      "कर्मधारय — विशेषण + विशेष्य.",
      "द्विगु — संख्यावाचक.",
      "अव्ययीभाव — पहला पद अव्यय.",
    ]},
    { heading: "अलंकार के मुख्य प्रकार", bullets: [
      "अनुप्रास — व्यंजन की आवृत्ति.",
      "यमक — शब्द की पुनरावृत्ति, अर्थ भिन्न.",
      "उपमा — समानता (सी/जैसा).",
      "रूपक — आरोप (बिना सी/जैसा).",
      "उत्प्रेक्षा — मानो/जैसे.",
    ]},
    { heading: "उपसर्ग व प्रत्यय", bullets: [
      "मुख्य उपसर्ग: अ, अन, अप, अधि, अनु, अव, उप, परा, प्र, सम्.",
      "मुख्य प्रत्यय: ता, पन, ई, इक, वान, मय.",
    ]},
    { heading: "वाक्य के तीन रूप", bullets: [
      "साधारण — एक उद्देश्य-विधेय.",
      "संयुक्त — और/परंतु/या से जुड़े दो स्वतंत्र वाक्य.",
      "मिश्र — मुख्य + आश्रित (क्योंकि/जब/अगर/यद्यपि).",
    ]},
  ],
};

export const ICSE7_MARATHI: ExamPack = {
  subjectId: "icse-marathi",
  grade: 7,
  title: "मराठी — Class 7",
  context: "बालभारती सुलभभारती इयत्ता ७",
  highlights: [{ label: "अनिवार्य", value: "MH Compulsory Marathi Act 2020" }],
  reference: { label: "Balbharati Std 7 Marathi (Shaalaa)", url: "https://www.shaalaa.com/textbook-solutions/balbharati-solutions-marathi-sulabhbharati-7-standard-maharashtra-state-board_283" },
  plan: [
    { title: "व्याकरण: नाम · सर्वनाम · विशेषण · क्रियापद", hint: "उजळणी" },
    { title: "लिंग · वचन · विभक्ती · काळ", hint: "रूप" },
    { title: "समानार्थी · विरुद्धार्थी · म्हणी · वाक्प्रचार", hint: "शब्दसामर्थ्य" },
    { title: "रचना", hint: "निबंध · पत्र · संवाद" },
    { title: "सराव", hint: "MCQ" },
  ],
  topics: [
    { id: "1-grammar", num: 1, title: "व्याकरण उजळणी",
      blurb: "इयत्ता ६ चे विस्तार.",
      syllabus: [
        "नामाचे प्रकार — विशेषनाम, सामान्यनाम, भाववाचक, समूहवाचक.",
        "सर्वनामे — पुरुषवाचक, दर्शक, अनिश्चित, प्रश्नार्थक, संबंधी, सामान्य.",
        "विशेषण — गुणवाचक, संख्यावाचक, परिमाणवाचक, सार्वनामिक.",
        "क्रियापदे — सकर्मक, अकर्मक.",
      ],
    },
    { id: "2-vibhakti", num: 2, title: "विभक्ती",
      blurb: "नामाच्या आठ रूपांची ओळख.",
      syllabus: [
        "विभक्ती म्हणजे नाम/सर्वनाम यांच्या वेगवेगळ्या रूपातून त्यांचा वाक्यातील अर्थ सांगणे.",
        "आठ विभक्ती: प्रथमा, द्वितीया, तृतीया, चतुर्थी, पंचमी, षष्ठी, सप्तमी, संबोधन.",
        "प्रथमा — कर्ता (मुलगा खेळतो).",
        "द्वितीया — कर्म (राम सीतेला पाहतो — सीतेला).",
        "षष्ठी — संबंध (रामचा).",
        "सप्तमी — स्थान (शाळेत).",
      ],
    },
    { id: "3-kal", num: 3, title: "काळ — विस्तार",
      blurb: "तीन काळ + उपप्रकार.",
      syllabus: [
        "वर्तमानकाळ: साधा (तो जातो), अपूर्ण (तो जात आहे), पूर्ण (तो गेला आहे), रीत (तो जात असतो).",
        "भूतकाळ: साधा (तो गेला), अपूर्ण (तो जात होता), पूर्ण (तो गेला होता), रीत (तो जात असे).",
        "भविष्यकाळ: साधा (तो जाईल), अपूर्ण (तो जात असेल), पूर्ण (तो गेला असेल), रीत (तो जात असेल).",
      ],
    },
    { id: "4-samas", num: 4, title: "समास",
      blurb: "दोन शब्दांचा संक्षिप्त रूप.",
      syllabus: [
        "तत्पुरुष — राजपुत्र (राजाचा पुत्र).",
        "द्वंद्व — आई-वडील (आई आणि वडील).",
        "बहुव्रीही — दशानन (दहा आनन असलेला).",
        "कर्मधारय — महापुरुष (महान पुरुष).",
        "द्विगु — त्रिभुवन (तीन भुवने).",
        "अव्ययीभाव — यथाशक्ती (शक्तीप्रमाणे).",
      ],
    },
    { id: "5-mhani", num: 5, title: "समानार्थी · विरुद्धार्थी · म्हणी · वाक्प्रचार",
      blurb: "शब्दभांडार विस्तार.",
      syllabus: [
        "समानार्थी: सूर्य = रवी = भास्कर = दिनकर; पाणी = जल = उदक = नीर.",
        "विरुद्धार्थी: सत्य ↔ असत्य, उदय ↔ अस्त, स्तुती ↔ निंदा.",
        "म्हणी: 'अति तेथे माती', 'हात ओला तर मित्र भला', 'थेंबे थेंबे तळे साचे', 'अंथरूण पाहून पाय पसरावे'.",
        "वाक्प्रचार: 'डोळे फिरवणे' (राग येणे), 'पाठ थोपटणे' (कौतुक करणे), 'कान धरणे' (शिकवण देणे).",
      ],
    },
    { id: "6-rachna", num: 6, title: "रचना",
      blurb: "निबंध, पत्र, संवाद.",
      syllabus: [
        "औपचारिक पत्र: पत्ता, तारीख, पत्ता, विषय, महोदय/महोदया, मजकूर, आपला/आपली, नाव.",
        "अनौपचारिक पत्र: ठिकाण-तारीख, संबोधन (प्रिय), मजकूर, तुझा/तुझी, नाव.",
        "निबंध (८०–१२० शब्द): प्रस्तावना, मुख्य भाग, समारोप.",
        "संवाद: दोन व्यक्तींमधील स्वाभाविक बोलणे.",
      ],
    },
  ],
  flashcards: [
    { term: "विभक्ती", def: "नाम किंवा सर्वनामाच्या वाक्यातील अर्थ दाखविणारे आठ रूप." },
    { term: "प्रथमा विभक्ती", def: "वाक्यातील कर्ता दर्शविणारी विभक्ती (मुलगा खेळतो)." },
    { term: "षष्ठी विभक्ती", def: "संबंध दर्शविणारी विभक्ती — रामचा, मायेची." },
    { term: "समास", def: "दोन शब्दांचा संक्षिप्त रूप — राजपुत्र = राजाचा पुत्र." },
    { term: "तत्पुरुष समास", def: "उत्तर पद प्रधान — राजपुत्र, गंगाजल." },
    { term: "द्वंद्व समास", def: "दोन्ही पद समान — आई-वडील, खाणे-पिणे." },
    { term: "बहुव्रीही समास", def: "दोन्ही पदांहून भिन्न अर्थ — दशानन = रावण." },
    { term: "वाक्प्रचार", def: "विशिष्ट अर्थ देणारा शब्द-समूह — डोळे फिरवणे, पाठ थोपटणे." },
    { term: "म्हण", def: "अनुभवातून आलेले छोटे, सुंदर वाक्य — अति तेथे माती." },
    { term: "वर्तमान साधा काळ", def: "आता सहज होणारी क्रिया — तो जातो, ती लिहिते." },
    { term: "भूत पूर्ण काळ", def: "क्रिया केव्हाच पूर्ण झालेली — तो गेला होता." },
  ],
  questions: [
    { id: "i7mr-1", topic: "2-vibhakti", q: "'रामचा भाऊ' मध्ये 'रामचा' कोणत्या विभक्तीचे रूप आहे?", opts: ["प्रथमा", "द्वितीया", "षष्ठी", "सप्तमी"], a: "षष्ठी", model: "संबंध दाखवणारी विभक्ती → षष्ठी (-चा/-ची/-चे)." },
    { id: "i7mr-2", topic: "3-kal", q: "'तो जात होता' कोणत्या काळातले वाक्य?", opts: ["वर्तमानकाळ", "भूत अपूर्ण काळ", "भूत पूर्ण काळ", "भविष्यकाळ"], a: "भूत अपूर्ण काळ", model: "क्रिया भूतकाळात चालू होती → अपूर्ण भूतकाळ." },
    { id: "i7mr-3", topic: "4-samas", q: "'आई-वडील' कोणता समास?", opts: ["तत्पुरुष", "द्वंद्व", "बहुव्रीही", "द्विगु"], a: "द्वंद्व", model: "आई आणि वडील — दोन्ही पद समान → द्वंद्व समास." },
    { id: "i7mr-4", topic: "4-samas", q: "'दशानन' कोणता समास?", opts: ["तत्पुरुष", "द्वंद्व", "बहुव्रीही", "कर्मधारय"], a: "बहुव्रीही", model: "दहा आनन वाला = रावण; तिसरा अर्थ → बहुव्रीही." },
    { id: "i7mr-5", topic: "5-mhani", q: "'पाठ थोपटणे' या वाक्प्रचाराचा अर्थ?", opts: ["रागावणे", "कौतुक करणे", "मारणे", "विसरणे"], a: "कौतुक करणे", model: "पाठीवर हलक्या थापा देणे = प्रशंसा करणे." },
    { id: "i7mr-6", topic: "5-mhani", q: "'अति तेथे माती' म्हणीचा अर्थ?", opts: ["पाऊस येणे", "अति केल्यास नुकसान", "खूप मातीत खेळणे", "अति श्रीमंती"], a: "अति केल्यास नुकसान", model: "कोणतीही गोष्ट जास्त केली तर हानी होते." },
  ],
  mistakes: [
    { mistake: "मराठी आठ विभक्ती सहा सांगणे.", fix: "मराठीत प्रथमा, द्वितीया, तृतीया, चतुर्थी, पंचमी, षष्ठी, सप्तमी आणि संबोधन — एकूण आठ विभक्ती." },
    { mistake: "तत्पुरुष आणि बहुव्रीहीत गोंधळ.", fix: "तत्पुरुष — उत्तर पद प्रधान (राजपुत्र = पुत्र). बहुव्रीही — दोन्हींपेक्षा वेगळा अर्थ (दशानन = रावण)." },
    { mistake: "म्हण आणि वाक्प्रचार एकच मानणे.", fix: "वाक्प्रचार = विशेष अर्थ देणारा छोटा शब्द-समूह. म्हण = अनुभवातून आलेले छोटे, सुंदर वाक्य." },
  ],
  cheat: [
    { heading: "विभक्ती (८)", bullets: [
      "१ प्रथमा — कर्ता.",
      "२ द्वितीया — कर्म.",
      "३ तृतीया — साधन/करण.",
      "४ चतुर्थी — संप्रदान.",
      "५ पंचमी — अपादान.",
      "६ षष्ठी — संबंध.",
      "७ सप्तमी — अधिकरण/स्थान.",
      "८ संबोधन — संबोधन.",
    ]},
    { heading: "समासाचे ६ मुख्य प्रकार", bullets: [
      "तत्पुरुष · द्वंद्व · बहुव्रीही · कर्मधारय · द्विगु · अव्ययीभाव.",
    ]},
    { heading: "काळाचे चार उपप्रकार (प्रत्येक काळी)", bullets: [
      "साधा (तो जातो / तो गेला / तो जाईल).",
      "अपूर्ण (तो जात आहे / होता / असेल).",
      "पूर्ण (तो गेला आहे / होता / असेल).",
      "रीत (तो जात असतो / असे / असेल).",
    ]},
    { heading: "रोजच्या म्हणी", bullets: [
      "अति तेथे माती.",
      "थेंबे थेंबे तळे साचे.",
      "अंथरूण पाहून पाय पसरावे.",
      "हात ओला तर मित्र भला.",
      "नाचता येईना अंगण वाकडे.",
    ]},
  ],
};

export const ICSE_LANGUAGE_PACKS = [
  ICSE6_ENGLISH_LANG, ICSE6_ENGLISH_LIT, ICSE6_HINDI, ICSE6_MARATHI,
  ICSE7_ENGLISH_LANG, ICSE7_ENGLISH_LIT, ICSE7_HINDI, ICSE7_MARATHI,
];
