// Cambridge IGCSE Physics 0625 — Topic 4: Electricity & Magnetism (Extended).
// Built May 2026 for Nevaan's Grade 10 paper at CNS Pune.
// Tightly scoped to the topic that's on the exam tomorrow; remaining physics
// topics (Motion/Forces, Thermal, Waves, Atomic) can be added later.
//
// Verified against the Cambridge IGCSE Physics 0625 subject page
// (https://www.cambridgeinternational.org/programmes-and-qualifications/cambridge-igcse-physics-0625/).
// Question stems are original, in the style of past Paper 2/4 (Extended).

import type { ExamPack } from "../exam-pack";

export const IGCSE_PHYSICS_PACK: ExamPack = {
  subjectId: "igcse-physics",
  grade: 10,
  title: "Physics — Electricity & Magnetism · IGCSE",
  context: "Cambridge IGCSE 0625 · Extended · Topic 4 · CNS Pune",
  highlights: [
    { label: "Syllabus", value: "0625 (Extended)" },
    { label: "Topic", value: "4 · Electricity & Magnetism" },
    { label: "Subtopics", value: "4.1 – 4.4" },
  ],
  pinnedRule: {
    heading: "Marks live in the units",
    body: "Every numerical answer gets a unit (C, V, A, Ω, W, J, kWh, T). State formula → substitute → final value + unit. Method marks survive a wrong final answer; missing units do not.",
  },
  reference: {
    label: "Cambridge IGCSE Physics 0625 — subject page",
    url: "https://www.cambridgeinternational.org/programmes-and-qualifications/cambridge-igcse-physics-0625/",
  },
  plan: [
    { title: "Walk the four sub-topics", hint: "4.1 magnetism → 4.4 electromagnetism" },
    { title: "Lock the 4 core formulas", hint: "Q=It, V=IR, P=IV, E=Pt" },
    { title: "Drill series + parallel rules", hint: "Resistance, current, voltage" },
    { title: "Master the potential divider", hint: "Especially with LDR / thermistor" },
    { title: "Logic gates — recite truth tables", hint: "AND, OR, NOT, NAND, NOR" },
    { title: "Read the cheat sheet morning of test", hint: "Last 10 minutes only" },
  ],

  topics: [
    {
      id: "4-1-magnetism", num: 1, title: "4.1 Simple phenomena of magnetism",
      blurb: "Poles, induced magnetism, fields.",
      syllabus: [
        "Magnetic poles: like poles repel, unlike attract — only between magnetic poles.",
        "Magnetic materials: iron, steel, cobalt, nickel.",
        "Soft iron magnetises and demagnetises easily → temporary magnets (electromagnets).",
        "Steel retains magnetism → permanent magnets.",
        "Induced magnetism: a magnet attracts an unmagnetised magnetic material by inducing poles in it.",
        "Magnetic field = region where a magnet exerts a force; represented by field lines from N to S outside the magnet.",
        "Field lines never cross; closer lines = stronger field.",
      ],
    },
    {
      id: "4-2-quantities", num: 2, title: "4.2 Electrical quantities",
      blurb: "Charge, current, e.m.f., p.d., resistance, power.",
      syllabus: [
        "Two types of charge: positive and negative. Like charges repel, unlike attract.",
        "Conductors (metals, graphite) have free electrons; insulators (plastic, rubber, glass) do not.",
        "Electric current = rate of flow of charge. I = Q / t. Units: ampere (A), coulomb (C).",
        "Conventional current flows + → −; electron flow is opposite.",
        "e.m.f. = energy transferred from other forms to electrical, per unit charge driven round a circuit. Unit: volt (V).",
        "p.d. across a component = electrical energy transferred to other forms per unit charge. Unit: volt (V).",
        "Resistance R = V / I. Unit: ohm (Ω).",
        "For a wire at constant temperature: R ∝ length L, R ∝ 1 / cross-sectional area A.",
        "Electrical power P = IV = I²R = V²/R. Energy E = IVt = Pt. Unit: joule (J) or kWh.",
        "1 kWh = 1000 W × 3600 s = 3.6 × 10⁶ J.",
      ],
    },
    {
      id: "4-3-circuits", num: 3, title: "4.3 Electric circuits",
      blurb: "Series, parallel, components, logic gates.",
      syllabus: [
        "Circuit symbols: cell, battery, lamp, resistor (fixed/variable), ammeter (series, low R), voltmeter (parallel, high R), switch, fuse, diode, LED, LDR, thermistor, capacitor, relay.",
        "Series: current is the same everywhere; voltages add; R_total = R₁ + R₂ + ...",
        "Parallel: voltage is the same across each branch; currents add; 1/R = 1/R₁ + 1/R₂ + ...",
        "Two equal resistors R in parallel give R/2; n equal Rs in parallel give R/n.",
        "Potential divider: V_out = V_in × (R₂ / (R₁ + R₂)). Used with LDR/thermistor to make light/temperature-sensitive circuits.",
        "I–V characteristic shapes: fixed resistor → straight line; filament lamp → S-curve (R rises with temperature); diode → ≈0 below ~0.6 V forward, then steep; reverse ≈0.",
        "Thermistor: resistance falls as temperature rises (NTC). LDR: resistance falls as light intensity rises.",
        "Diode: allows current in one direction only.",
        "Relay: small current in coil switches a separate large-current circuit.",
        "Logic gates — output is HIGH (1) or LOW (0). Symbols + truth tables for NOT, AND, OR, NAND, NOR.",
        "Combinations: any logic problem can be built from NAND or NOR alone (universal gates).",
      ],
    },
    {
      id: "4-4-em-effects", num: 4, title: "4.4 Electromagnetic effects",
      blurb: "Field around a current, motor effect, induction, transformer.",
      syllabus: [
        "Right-hand grip rule: thumb along conventional current, fingers curl in direction of B field around a wire.",
        "Solenoid: field like a bar magnet; N pole is the end where current appears anticlockwise (looking on).",
        "Motor effect (Fleming's left-hand rule): F (thumb), B (first finger), I (second finger), all at right angles. Force on a current-carrying conductor in a magnetic field.",
        "DC motor: split-ring commutator reverses current every half turn so torque stays in one direction.",
        "Electromagnetic induction: an e.m.f. is induced when a conductor cuts magnetic field lines (or when flux through a coil changes).",
        "Induced e.m.f. is larger when: stronger magnet, more turns, faster motion.",
        "Lenz's law: induced current direction opposes the change that caused it (conservation of energy).",
        "AC generator: coil rotates between poles; slip rings + brushes deliver alternating current.",
        "Transformer: V_p / V_s = N_p / N_s. For an ideal transformer, I_p × V_p = I_s × V_s.",
        "Step-up: more turns on secondary → higher voltage, lower current. Step-down: opposite.",
        "Power transmission uses high voltage to reduce I²R heating loss in cables.",
      ],
    },
  ],

  flashcards: [
    { term: "Electric current", def: "Rate of flow of charge; I = Q/t. SI unit: ampere (A). 1 A = 1 C/s." },
    { term: "Charge (Q)", def: "Quantity of electricity that passes a point; Q = It. SI unit: coulomb (C)." },
    { term: "e.m.f.", def: "Energy converted from other forms to electrical, per unit charge driven round a complete circuit. Unit: volt." },
    { term: "Potential difference", def: "Energy transferred from electrical to other forms per unit charge between two points. Unit: volt." },
    { term: "Resistance", def: "R = V/I. The opposition to current flow. Unit: ohm (Ω)." },
    { term: "Ohm's law", def: "For a metallic conductor at constant temperature, current is directly proportional to p.d. (V = IR with R constant)." },
    { term: "Electrical power", def: "Rate of energy transfer; P = IV = I²R = V²/R. Unit: watt (W)." },
    { term: "Electrical energy", def: "E = Pt = IVt. Unit: joule (J) or kilowatt-hour (kWh). 1 kWh = 3.6 × 10⁶ J." },
    { term: "Series rule", def: "Same current through every component. Total p.d. = sum of p.d.s. R_total = ΣR." },
    { term: "Parallel rule", def: "Same p.d. across each branch. Total current = sum of branch currents. 1/R = Σ(1/Rᵢ)." },
    { term: "Potential divider", def: "Two resistors in series sharing the supply voltage in proportion to their resistances. V_out = V × R₂/(R₁+R₂)." },
    { term: "LDR", def: "Light-dependent resistor. Resistance decreases as light intensity increases." },
    { term: "Thermistor", def: "Temperature-dependent resistor (NTC). Resistance decreases as temperature increases." },
    { term: "Diode", def: "Component that allows current to flow in one direction only; conducts above ~0.6 V forward bias." },
    { term: "Relay", def: "An electromagnetic switch — a small current in a coil moves contacts that switch a separate higher-current circuit." },
    { term: "AND gate", def: "Output 1 only when both inputs are 1." },
    { term: "OR gate", def: "Output 1 when at least one input is 1." },
    { term: "NOT gate", def: "Output is the inverse of the single input." },
    { term: "NAND gate", def: "Output is the inverse of AND: 0 only when both inputs are 1." },
    { term: "NOR gate", def: "Output is the inverse of OR: 1 only when both inputs are 0." },
    { term: "Fleming's left-hand rule", def: "For force on a current in a magnetic field: thuMb=Motion, First finger=Field, seCond finger=Current. All mutually perpendicular." },
    { term: "Electromagnetic induction", def: "An e.m.f. is induced in a conductor that cuts magnetic field lines, or in a coil where magnetic flux is changing." },
    { term: "Lenz's law", def: "The induced current flows in a direction that opposes the change producing it (energy conservation)." },
    { term: "Transformer equation", def: "V_p/V_s = N_p/N_s. For ideal (100% efficient): I_p V_p = I_s V_s." },
    { term: "Step-up transformer", def: "More turns on secondary than primary → higher output voltage, lower output current." },
  ],

  questions: [
    // 4.2 — quantities
    { id: "ip10-1", topic: "4-2-quantities", q: "A current of 0.40 A flows for 5.0 minutes. How much charge has flowed?",
      opts: ["2.0 C", "12 C", "120 C", "1200 C"], a: "120 C",
      model: "Q = I × t = 0.40 × (5 × 60) = 0.40 × 300 = 120 C." },
    { id: "ip10-2", topic: "4-2-quantities", q: "A 12 V battery drives 0.50 A through a resistor. What is the resistance?",
      opts: ["6.0 Ω", "12 Ω", "24 Ω", "60 Ω"], a: "24 Ω",
      model: "R = V / I = 12 / 0.50 = 24 Ω." },
    { id: "ip10-3", topic: "4-2-quantities", q: "Same circuit (12 V, 0.50 A). Power dissipated?",
      opts: ["0.6 W", "6.0 W", "24 W", "60 W"], a: "6.0 W",
      model: "P = IV = 0.50 × 12 = 6.0 W. Check: P = I²R = 0.25 × 24 = 6.0 W ✓." },
    { id: "ip10-4", topic: "4-2-quantities", q: "Which statement best distinguishes e.m.f. from p.d.?",
      opts: [
        "e.m.f. is measured in joules; p.d. in volts",
        "e.m.f. is energy supplied per coulomb by the source; p.d. is energy transferred per coulomb to a component",
        "p.d. drives current; e.m.f. opposes it",
        "They are identical",
      ],
      a: "e.m.f. is energy supplied per coulomb by the source; p.d. is energy transferred per coulomb to a component",
      model: "e.m.f. = source side (battery); p.d. = component side (resistor, lamp). Both measured in volts." },
    { id: "ip10-5", topic: "4-2-quantities", q: "A 2.0 kW kettle runs at 230 V. Current drawn?",
      opts: ["0.87 A", "1.15 A", "8.7 A", "115 A"], a: "8.7 A",
      model: "I = P / V = 2000 / 230 = 8.7 A (2 s.f.)." },
    { id: "ip10-6", topic: "4-2-quantities", q: "Energy used by the kettle in 3 hours, in kWh?",
      opts: ["0.67 kWh", "2.0 kWh", "6.0 kWh", "60 kWh"], a: "6.0 kWh",
      model: "E = P × t = 2.0 kW × 3 h = 6.0 kWh." },
    { id: "ip10-7", topic: "4-2-quantities", q: "Resistance of a wire is doubled if you …",
      opts: [
        "double its length",
        "double its cross-sectional area",
        "halve its length",
        "double its temperature in °C",
      ],
      a: "double its length",
      model: "R ∝ L (and R ∝ 1/A). Doubling length doubles R; doubling area halves R." },

    // 4.3 — circuits
    { id: "ip10-8", topic: "4-3-circuits", q: "Resistors R₁ = 2.0 Ω in series with the parallel combination of R₂ = 6.0 Ω and R₃ = 3.0 Ω. Total resistance?",
      opts: ["2.0 Ω", "3.0 Ω", "4.0 Ω", "11 Ω"], a: "4.0 Ω",
      model: "Parallel: (6×3)/(6+3) = 2.0 Ω. Total = 2.0 + 2.0 = 4.0 Ω." },
    { id: "ip10-9", topic: "4-3-circuits", q: "Same circuit, 6.0 V supply. Current drawn from the cell?",
      opts: ["0.5 A", "1.0 A", "1.5 A", "3.0 A"], a: "1.5 A",
      model: "I = V / R = 6.0 / 4.0 = 1.5 A." },
    { id: "ip10-10", topic: "4-3-circuits", q: "A potential divider has a 1.0 kΩ fixed resistor in series with an LDR. V_in = 9.0 V. V_out is across the LDR. In bright light the LDR drops to 200 Ω. V_out?",
      opts: ["0.5 V", "1.5 V", "4.5 V", "7.5 V"], a: "1.5 V",
      model: "V_out = 9 × (200 / (1000+200)) = 9 × 0.1667 = 1.5 V." },
    { id: "ip10-11", topic: "4-3-circuits", q: "Same divider, but in darkness the LDR rises to 8.0 kΩ. V_out?",
      opts: ["1.0 V", "4.5 V", "8.0 V", "9.0 V"], a: "8.0 V",
      model: "V_out = 9 × (8000 / 9000) = 8.0 V." },
    { id: "ip10-12", topic: "4-3-circuits", q: "Which component lets current flow in only one direction?",
      opts: ["Resistor", "Capacitor", "Diode", "Thermistor"], a: "Diode",
      model: "Diode conducts when forward-biased (above ≈0.6 V), blocks when reverse-biased." },
    { id: "ip10-13", topic: "4-3-circuits", q: "A burglar alarm should sound only when a window is open AND the system is armed. Which gate?",
      opts: ["OR", "AND", "NOR", "NAND"], a: "AND",
      model: "Both conditions must be true → AND. Truth table: 00→0, 01→0, 10→0, 11→1." },
    { id: "ip10-14", topic: "4-3-circuits", q: "Outputs for a NAND gate with inputs (A, B) = (0,0), (0,1), (1,0), (1,1)?",
      opts: ["0,0,0,1", "1,1,1,0", "0,1,1,1", "1,0,0,0"], a: "1,1,1,0",
      model: "NAND = NOT(AND). AND gives 0,0,0,1 → invert → 1,1,1,0." },
    { id: "ip10-15", topic: "4-3-circuits", q: "Ammeters and voltmeters are connected …",
      opts: [
        "Ammeter in parallel, voltmeter in series",
        "Both in series",
        "Both in parallel",
        "Ammeter in series, voltmeter in parallel",
      ],
      a: "Ammeter in series, voltmeter in parallel",
      model: "Ammeter has tiny R (must not disturb current) → series. Voltmeter has huge R (must not draw current) → parallel across the component." },

    // 4.4 — electromagnetic effects
    { id: "ip10-16", topic: "4-4-em-effects", q: "The magnetic field around a straight wire carrying current is …",
      opts: ["Straight lines parallel to the wire", "Concentric circles around the wire", "Radial lines from the wire", "Zero"],
      a: "Concentric circles around the wire",
      model: "Right-hand grip rule: thumb in current direction, fingers curl in field direction → circles around the wire." },
    { id: "ip10-17", topic: "4-4-em-effects", q: "In a DC motor, the split-ring commutator …",
      opts: [
        "increases the current in the coil",
        "reverses current direction every half turn so the coil keeps rotating the same way",
        "converts AC to DC",
        "produces the magnetic field",
      ],
      a: "reverses current direction every half turn so the coil keeps rotating the same way",
      model: "Without the split-ring, the force would reverse direction every half turn and the coil would oscillate, not spin." },
    { id: "ip10-18", topic: "4-4-em-effects", q: "An ideal transformer has 200 turns on the primary and 1000 turns on the secondary. Input p.d. is 230 V. Output p.d.?",
      opts: ["46 V", "230 V", "1150 V", "5000 V"], a: "1150 V",
      model: "V_s = V_p × (N_s / N_p) = 230 × (1000 / 200) = 230 × 5 = 1150 V. Step-up." },
    { id: "ip10-19", topic: "4-4-em-effects", q: "Same transformer. If the primary current is 10 A (ideal), what is the secondary current?",
      opts: ["0.5 A", "2.0 A", "10 A", "50 A"], a: "2.0 A",
      model: "I_p V_p = I_s V_s → I_s = (10 × 230) / 1150 = 2.0 A. Step-up means I drops by the same factor V rises." },
    { id: "ip10-20", topic: "4-4-em-effects", q: "Why is electricity transmitted across long distances at very high voltage?",
      opts: [
        "It travels faster",
        "Less I²R energy is lost as heat in the cables for the same power",
        "Cables are cheaper to manufacture",
        "Transformers only work at high voltage",
      ],
      a: "Less I²R energy is lost as heat in the cables for the same power",
      model: "P = IV. At higher V for the same power, I is smaller → I²R loss in cables drops sharply (it's squared in I)." },

    // Extension round — added for Nevaan's last-night drill
    { id: "ip10-21", topic: "4-2-quantities", q: "Charge on a single electron is 1.6 × 10⁻¹⁹ C. How many electrons pass a point in a wire carrying 0.32 A for 1.0 s?",
      opts: ["5.0 × 10¹⁷", "2.0 × 10¹⁸", "5.0 × 10¹⁸", "2.0 × 10¹⁹"], a: "2.0 × 10¹⁸",
      model: "Q = It = 0.32 × 1.0 = 0.32 C. n = Q / e = 0.32 / 1.6×10⁻¹⁹ = 2.0 × 10¹⁸ electrons." },
    { id: "ip10-22", topic: "4-2-quantities", q: "A wire has resistance 4.0 Ω. A second wire of the same material, twice the length and half the cross-sectional area, has resistance …",
      opts: ["1.0 Ω", "4.0 Ω", "8.0 Ω", "16 Ω"], a: "16 Ω",
      model: "R ∝ L / A. New R = 4.0 × (2 / 0.5) = 4.0 × 4 = 16 Ω." },
    { id: "ip10-23", topic: "4-3-circuits", q: "Three identical 6.0 Ω lamps are connected in parallel across a 12 V supply. Current from the supply?",
      opts: ["2.0 A", "4.0 A", "6.0 A", "18 A"], a: "6.0 A",
      model: "R_parallel = 6 / 3 = 2.0 Ω. I = V / R = 12 / 2.0 = 6.0 A. (Or: each lamp draws 12/6 = 2.0 A; three lamps → 6.0 A.)" },
    { id: "ip10-24", topic: "4-3-circuits", q: "An LED in series with a resistor R is to be lit at 20 mA from a 9.0 V supply. The LED needs 2.0 V to light. R = ?",
      opts: ["100 Ω", "350 Ω", "450 Ω", "1.0 kΩ"], a: "350 Ω",
      model: "p.d. across R = 9.0 − 2.0 = 7.0 V. R = V / I = 7.0 / 0.020 = 350 Ω." },
    { id: "ip10-25", topic: "4-3-circuits", q: "The output of an OR gate is fed into a NOT gate. With inputs (A, B) = (1, 0), the final output is …",
      opts: ["0", "1", "Depends on B", "Undefined"], a: "0",
      model: "OR(1,0) = 1. NOT(1) = 0. The two-gate combo (OR then NOT) is a NOR gate." },
    { id: "ip10-26", topic: "4-3-circuits", q: "A thermistor sits in the top half of a potential divider; a fixed R is below. As the room cools, the thermistor's resistance rises. V_out (across the fixed R) does what?",
      opts: ["Rises", "Falls", "Stays the same", "Reverses sign"], a: "Falls",
      model: "V_out = V × R_fixed / (R_therm + R_fixed). R_therm rises → denominator grows → V_out falls. (If V_out were across the thermistor instead, it would rise.)" },
    { id: "ip10-27", topic: "4-4-em-effects", q: "A bar magnet is pushed N-pole first into a coil connected to a galvanometer. The needle deflects right. The magnet is then pulled out. The needle …",
      opts: ["Stays still", "Deflects right again", "Deflects left", "Oscillates wildly"], a: "Deflects left",
      model: "Lenz's law: induced current direction opposes the change. Reversing the motion reverses the induced current → opposite deflection." },
    { id: "ip10-28", topic: "4-4-em-effects", q: "A 100% efficient transformer steps 11 kV down to 230 V. If the primary has 5000 turns, how many turns on the secondary?",
      opts: ["~22 turns", "~105 turns", "~230 turns", "~5000 turns"], a: "~105 turns",
      model: "N_s = N_p × (V_s / V_p) = 5000 × (230 / 11000) = 5000 × 0.0209 ≈ 105 turns." },
  ],

  mistakes: [
    { mistake: "Forgetting units on numerical answers.", fix: "Always finish with C, V, A, Ω, W, J or kWh. Examiner gives zero for a bare number." },
    { mistake: "Confusing e.m.f. with p.d.", fix: "e.m.f. = source (energy per coulomb supplied by battery). p.d. = component (energy per coulomb transferred to it). Both in volts." },
    { mistake: "Adding parallel resistors directly.", fix: "Use 1/R = 1/R₁ + 1/R₂ + … then invert. Or for two equal Rs: parallel = R/2." },
    { mistake: "Putting the ammeter in parallel.", fix: "Ammeter has near-zero resistance — connect it in series, never across a component. Voltmeter is the opposite: parallel only." },
    { mistake: "Mixing up NAND and NOR.", fix: "NAND = NOT(AND) → output 0 only when both inputs are 1. NOR = NOT(OR) → output 1 only when both inputs are 0." },
    { mistake: "Reversing Fleming's left-hand rule.", fix: "thuMb = Motion (force), First finger = Field, seCond finger = Current. M–F–C order, all at right angles." },
    { mistake: "Calculating transformer with V_p/V_s = N_s/N_p (inverted).", fix: "Voltage ratio MATCHES the turns ratio: V_p/V_s = N_p/N_s. Current ratio is the INVERSE." },
    { mistake: "Saying transmission at high voltage is to make current 'travel faster'.", fix: "It's about reducing I²R heating loss in the cables — not speed." },
  ],

  cheat: [
    {
      heading: "The four formulas that unlock 60% of the paper",
      bullets: [
        "Q = I × t   (charge in coulombs)",
        "V = I × R   (Ohm's law)",
        "P = I × V = I²R = V²/R   (power)",
        "E = P × t = IVt   (electrical energy; in kWh if P in kW and t in hours)",
      ],
    },
    {
      heading: "Series vs parallel — say it out loud",
      bullets: [
        "Series: same I everywhere. V_total = ΣV. R_total = ΣR.",
        "Parallel: same V across each branch. I_total = ΣI. 1/R = Σ(1/Rᵢ).",
        "Two equal Rs in parallel → R/2. n equal Rs in parallel → R/n.",
      ],
    },
    {
      heading: "Potential divider",
      bullets: [
        "V_out = V_in × R₂ / (R₁ + R₂).",
        "If R₂ is the LDR/thermistor and resistance drops, V_out drops too.",
        "If R₂ is the fixed resistor, then V_out rises as the sensor's resistance falls.",
        "Always sketch the two resistors and label which side V_out comes from.",
      ],
    },
    {
      heading: "Logic gates — recite these four truth tables",
      bullets: [
        "NOT: 0→1, 1→0.",
        "AND: 00→0, 01→0, 10→0, 11→1.",
        "OR : 00→0, 01→1, 10→1, 11→1.",
        "NAND = NOT(AND): 00→1, 01→1, 10→1, 11→0.",
        "NOR  = NOT(OR) : 00→1, 01→0, 10→0, 11→0.",
      ],
    },
    {
      heading: "Electromagnetism",
      bullets: [
        "Right-hand GRIP rule → field around a current-carrying wire.",
        "Fleming's LEFT-hand rule → force on a current in a field (motors).",
        "Fleming's RIGHT-hand rule → direction of induced current (generators).",
        "Transformer: V_p/V_s = N_p/N_s. Ideal: I_p V_p = I_s V_s.",
        "Step-up V → step-down I (and vice versa).",
      ],
    },
    {
      heading: "Paper 4 — structured practice (read the working line-by-line)",
      bullets: [
        "Q1 · Lamp on mains: A filament lamp is rated 60 W, 230 V. (a) Current at full brightness? I = P/V = 60/230 = 0.26 A. (b) Resistance when hot? R = V/I = 230/0.26 = 880 Ω. (c) Why is the cold resistance lower than 880 Ω? At room temperature the filament has fewer lattice vibrations, electrons collide less, so resistance is smaller. (d) Why does the lamp usually fail at the moment it is switched on? The cold resistance is small → a large surge current flows → the thin filament heats fastest at its weakest spot and breaks.",
        "Q2 · Heater costing: A 2.0 kW heater runs 4 h per day, 30 days/month, at ₹8.50 per kWh. (a) Energy per month? 2.0 × 4 × 30 = 240 kWh. (b) Cost per month? 240 × 8.50 = ₹2,040. (c) Customer fits a 1.5 kW heater for the same 4 h × 30 days. New cost? 1.5 × 4 × 30 × 8.50 = ₹1,530. (d) Saving? ₹510/month.",
        "Q3 · Logic alarm: A fire alarm should sound when (smoke detector S = 1) OR (heat detector H = 1) AND the system is armed (A = 1). (a) Boolean expression for the buzzer B? B = (S OR H) AND A. (b) Gates needed: 1 × OR, 1 × AND. (c) Truth table for (S, H, A): all 8 rows; B = 1 only when A = 1 AND at least one of S, H = 1 → rows 001, 011, 101, 111 give 0/1/1/1; rows 000, 010, 100, 110 give 0. (d) State one reason the engineer might use NAND gates only. NAND is a universal gate — one chip type lowers cost and spare-part complexity.",
      ],
    },
    {
      heading: "Exam-day moves",
      bullets: [
        "Underline the data in the question before you start.",
        "Write formula → substitute → answer + UNIT.",
        "Sketch the circuit even if the question gives words only.",
        "If you can't finish, show the formula and substitution — method marks survive.",
        "Two pens. Working calculator. Sleep eight hours.",
      ],
    },
  ],
};
