// Cambridge IGCSE History 0470 — Core content Option B (international relations
// since 1919) plus ONE depth study.
//
// Verified 2026-08-11 against the official Cambridge IGCSE History 0470 syllabus
// for 2027 and 2028 (https://www.cambridgeinternational.org/Images/721327-2027-2028-syllabus.pdf)
// and the published specimen materials:
//   • Core content Option B key questions 1–6, with the syllabus' own focus points
//     and specified content, are reproduced faithfully in the topic bullets below.
//   • Assessment shape confirmed from the syllabus: Paper 1 (2 h, 60 marks, 40%) —
//     two questions from Section A (Core) and one from Section B (Depth studies),
//     every question split (a)/(b)/(c); Paper 2 (1 h 45, 40 marks, 30%) — ONE
//     question on a prescribed Core topic, up to seven sources, five parts; then
//     either Component 3 Coursework or Paper 4 Alternative to Coursework (1 h,
//     40 marks, 30%), two parts (a) describe / (b) discuss importance.
//   • The (a) 4 / (b) 6 / (c) 10 mark split used throughout was checked against the
//     official specimen Paper 1, and the Paper 2 part styles ("How far do these two
//     sources agree?", "Why was this source published at this time?", "How useful is
//     this source…", "How far do these sources provide convincing evidence that…?")
//     against the official specimen Paper 2 mark scheme. Paper 2 parts are NOT worth
//     equal marks — they run roughly 7–9 each to a total of 40.
//
// DEPTH STUDY: 0470 offers five (A The First World War 1914–18; B Germany 1918–45;
// C Russia 1905–41; D The United States 1919–41; E The Second World War in Europe
// and the Asia–Pacific 1939–c.1945) and every school picks its own — some centres
// write their own depth study for coursework instead. This pack covers **Depth
// Study B: Germany, 1918–45**, the most commonly taught option. If your school
// teaches Russia, the USA, the First World War or the Second World War, use Topics
// 1–7 (which every 0470 candidate needs) and ignore Topic 8.
//
// Note also that 0470 offers a nineteenth-century Core (Option A). This pack assumes
// Option B, which is what almost all centres teach.
//
// All source extracts in `questions` are ORIGINAL, written for this pack in the
// style of Paper 2, with invented but plausible provenance. No past-paper source or
// question wording is reproduced. Every date, name and treaty term was checked
// individually; anything doubtful was omitted rather than guessed (see the note at
// the bottom of `cheat`).

import type { ExamPack } from "../exam-pack";

export const IGCSE_HISTORY_PACK: ExamPack = {
  subjectId: "igcse-history",
  grade: 10,
  title: "History — Full Syllabus · IGCSE",
  context: "Cambridge IGCSE 0470 · Core Option B + Germany depth study · Papers 1, 2 & 4",
  highlights: [
    { label: "Core", value: "Option B · six key questions" },
    { label: "Depth study", value: "B · Germany, 1918–45" },
    { label: "Heaviest marks", value: "Source skills · the (c) judgement" },
  ],
  pinnedRule: {
    heading: "Answer the question that was asked",
    body: "0470 pays for explanation and judgement, never for storytelling. (a) 'Describe…' wants four separate factual points and no reasons — four sentences, four marks. (b) 'Explain why…' wants three developed reasons, each built as 'because … which meant … so …'. (c) 'How far do you agree…' wants a paragraph agreeing, a paragraph disagreeing, and a final paragraph that actually decides — 'X mattered more than Y because…'. A narrative of what happened next sits in the bottom band however much you know.",
  },
  reference: {
    label: "Cambridge IGCSE History 0470 — subject page",
    url: "https://www.cambridgeinternational.org/programmes-and-qualifications/cambridge-igcse-history-0470/",
  },
  plan: [
    { title: "Walk the six Core key questions", hint: "Versailles → Eastern Europe, 12 min each" },
    { title: "Learn the timeline as dates, not as a story", hint: "If you can't date it, you can't use it" },
    { title: "Drill the treaty table until you never muddle them", hint: "Versailles · Saint-Germain · Neuilly · Trianon · Sèvres" },
    { title: "Run NOP on three sources", hint: "Nature, origin, purpose — content alone is worth almost nothing" },
    { title: "Write one (c) answer against the clock", hint: "12 minutes: agree, disagree, decide" },
    { title: "Read the cheat sheet the morning of the exam", hint: "Timeline and treaty terms only" },
  ],

  topics: [
    {
      id: "1-peace-treaties", num: 1, title: "1. Were the peace treaties of 1919–23 fair?",
      blurb: "Versailles, the aims of the Big Three, the German reaction, and the four other treaties.",
      syllabus: [
        "Aims and motives of the Big Three at the Paris Peace Conference (January–June 1919): Clemenceau (France) wanted revenge, security and reparations; Wilson (USA) wanted his Fourteen Points, self-determination and a League of Nations; Lloyd George (Britain) wanted Germany's navy and colonies gone but Germany kept alive as a trading partner and a barrier to Bolshevism — so none of the three got everything.",
        "Terms of the Treaty of Versailles, signed 28 June 1919 in the Hall of Mirrors: Article 231 war guilt; reparations fixed at £6,600 million (132 billion gold marks) in 1921; army capped at 100,000 men with no conscription, tanks, submarines or air force and a navy of six battleships; the Rhineland permanently demilitarised and occupied by Allied troops for 15 years.",
        "Territorial terms: Alsace-Lorraine to France; the Saar under League administration for 15 years with its coal to France; Eupen-Malmédy to Belgium; North Schleswig to Denmark after a plebiscite; West Prussia and Posen to Poland, creating the Polish Corridor; Danzig a Free City under the League; all overseas colonies became League mandates; Anschluss with Austria forbidden. Germany lost about 10% of its land and 12.5% of its population.",
        "German reaction: the treaty was called a Diktat because Germany was not allowed to negotiate; the politicians who signed were branded the 'November Criminals' and the Dolchstoss (stab-in-the-back) myth spread; the Kapp Putsch followed in March 1920; after a default, French and Belgian troops occupied the Ruhr in January 1923, passive resistance followed and hyperinflation destroyed savings.",
        "The other four treaties: Saint-Germain with Austria (10 September 1919) broke up Austria–Hungary and banned Anschluss, army 30,000; Neuilly with Bulgaria (27 November 1919) took western Thrace to Greece, ending Bulgaria's access to the Aegean, army 20,000; Trianon with Hungary (4 June 1920) took Transylvania to Romania and Slovakia to Czechoslovakia, costing Hungary roughly two-thirds of its territory, army 35,000.",
        "Sèvres with Turkey (10 August 1920) dismantled the Ottoman Empire and gave Smyrna to Greece; Turkish nationalists under Mustafa Kemal rejected it and forced its replacement by the Treaty of Lausanne (24 July 1923), which returned Smyrna and eastern Thrace to Turkey — the only 1919 settlement substantially overturned, and the reason the period runs to 1923.",
      ],
    },
    {
      id: "2-league", num: 2, title: "2. To what extent was the League of Nations a success?",
      blurb: "Structure and membership, the 1920s record, humanitarian work, Manchuria and Abyssinia.",
      syllabus: [
        "Structure: the Covenant was part of the Treaty of Versailles and the League began on 10 January 1920 at Geneva. Assembly (all members, met once a year, decisions had to be unanimous); Council (permanent members Britain, France, Italy and Japan, each with a veto, plus temporary members); Secretariat; Permanent Court of International Justice at The Hague; International Labour Organisation.",
        "Weaknesses built in from the start: the USA never joined because the Senate rejected the Treaty, so the world's strongest economy was outside; Germany was excluded until 1926 and the USSR until 1934; the League had no army of its own; unanimity made decisions slow; its only weapons were condemnation, economic sanctions and — in theory — collective military action.",
        "1920s successes: the Aaland Islands (1920–21) awarded to Finland with Sweden accepting; Greece ordered out of Bulgaria in 1925 and made to pay compensation — and it obeyed. Humanitarian work was the League's strongest record: refugee resettlement and Nansen passports, campaigns against typhus and malaria, the ILO on working conditions, and action against slavery.",
        "1920s failures: Vilna (1920) — Poland seized the city from Lithuania and simply ignored the League, because France would not act against a useful ally; Corfu (1923) — after the murder of the Italian General Tellini on Greek soil, Mussolini bombarded and occupied Corfu, and the Conference of Ambassadors overruled the League so that Greece, the victim, paid Italy compensation. Big powers could break the rules and get away with it.",
        "Manchuria (1931–33): the Mukden Incident of 18 September 1931 gave Japan its excuse to overrun Manchuria and set up the puppet state of Manchukuo. The Lytton Commission took a year to report; when the League adopted the report in February 1933 Japan walked out in March 1933. No sanctions were imposed, no force was used, and the League had been defied by a permanent member of its own Council.",
        "Abyssinia (1935–36): Italy invaded on 3 October 1935. Sanctions were imposed but not on oil, coal or steel, and the Suez Canal stayed open. The Hoare–Laval Pact of December 1935, in which Britain and France secretly offered Mussolini most of Abyssinia, leaked and destroyed the League's moral authority. Addis Ababa fell in May 1936 and Haile Selassie appealed to the League in vain. The Depression from 1929 had already made states put trade and self-interest before collective security.",
      ],
    },
    {
      id: "3-collapse-1939", num: 3, title: "3. Why had international peace collapsed by 1939?",
      blurb: "Hitler's aims, the Rhineland, Anschluss, Munich, appeasement, the Nazi–Soviet Pact and Poland.",
      syllabus: [
        "Hitler's foreign policy aims: destroy the Treaty of Versailles, rearm, unite all German speakers in one Reich (Grossdeutschland), win Lebensraum in the east and destroy communism. He left the Disarmament Conference and the League in October 1933, then signed a ten-year non-aggression pact with Poland in January 1934 to look peaceful.",
        "Rearmament and the Saar: over 90% of Saar voters chose to return to Germany in the January 1935 plebiscite, which was legal under Versailles and a huge propaganda win. In March 1935 Hitler announced conscription and revealed the Luftwaffe; the Stresa Front of Britain, France and Italy protested in April and then collapsed when Britain signed the Anglo-German Naval Agreement in June 1935, allowing Germany a navy 35% the size of Britain's without consulting France.",
        "Remilitarisation of the Rhineland, 7 March 1936: a calculated bluff — German troops had orders to withdraw if France resisted. France, facing elections and unwilling to act without Britain, did nothing. Britain's view was that Hitler was only 'walking into his own back garden'. The lesson Hitler drew was that the democracies would not fight.",
        "Building the alliances: German and Italian intervention in the Spanish Civil War from 1936 tested new weapons (the Condor Legion bombed Guernica in April 1937) and pushed the two dictators together — the Rome–Berlin Axis of October 1936 and the Anti-Comintern Pact with Japan in November 1936, which Italy joined in 1937.",
        "Anschluss and Czechoslovakia: Austria was absorbed on 12 March 1938 after Schuschnigg was forced to resign and Seyss-Inquart invited German troops in. Konrad Henlein's Sudeten Germans then gave Hitler his next claim; after Chamberlain's flights to Berchtesgaden and Bad Godesberg, the Munich Agreement of 29–30 September 1938 handed the Sudetenland to Germany — with Czechoslovakia not in the room and the USSR not invited. On 15 March 1939 Hitler took the rest of the Czech lands, proving the promise worthless; Britain and France guaranteed Poland on 31 March 1939.",
        "The Nazi–Soviet Pact and war: on 23 August 1939 Germany and the USSR signed a ten-year non-aggression pact with a secret protocol dividing Poland and the Baltic states. It removed the risk of a war on two fronts and made the invasion of Poland safe. Germany invaded on 1 September 1939 and Britain and France declared war on 3 September 1939. Appeasement is judged both ways: fear of bombing, incomplete rearmament, the Dominions' reluctance, American isolationism and a genuine belief that Versailles was unjust — against the charge that it fed Hitler's appetite, bought Germany more rearmament time than Britain, and threw away Czechoslovakia's defences and its 35 divisions.",
      ],
    },
    {
      id: "4-cold-war-origins", num: 4, title: "4. Who was to blame for the Cold War?",
      blurb: "Yalta and Potsdam, Soviet expansion, the Truman Doctrine, Marshall Plan, Berlin Blockade, NATO.",
      syllabus: [
        "Yalta, February 1945 (Roosevelt, Churchill, Stalin): agreement that Germany and Berlin would each be divided into four occupation zones, that war criminals would be tried, that the United Nations would be founded, and that the USSR would enter the war against Japan three months after Germany's defeat. Poland's eastern border moved west, and the Declaration on Liberated Europe promised free elections — a promise the West and Stalin read very differently.",
        "Potsdam, July–August 1945: the personnel had changed — Truman had replaced Roosevelt, who died on 12 April 1945, and Attlee replaced Churchill mid-conference after the British election. The Allies quarrelled over reparations, over Poland's new government and its Oder–Neisse border, and over Germany's future. Truman knew of the successful atomic test of 16 July 1945 and hinted at a powerful new weapon; Hiroshima followed on 6 August and Nagasaki on 9 August 1945.",
        "Soviet expansion to 1948: communist-dominated governments were installed across Eastern Europe by 'salami tactics' — Poland, Romania, Bulgaria, Hungary, Albania and, after the coup of February 1948, Czechoslovakia. Churchill's Fulton speech of 5 March 1946 declared that 'an iron curtain has descended across the Continent'. Stalin's case was security: the USSR had been invaded twice through this corridor and wanted a buffer zone.",
        "The American response: the Truman Doctrine of 12 March 1947 promised support for free peoples resisting subjugation, triggered by Britain's inability to keep propping up Greece and Turkey — the birth of containment. The Marshall Plan, announced on 5 June 1947 and funded from 1948, put about $13 billion into sixteen Western European economies. Stalin forbade Eastern Europe to take it and answered with Cominform (1947) and Comecon (1949).",
        "The Berlin Blockade, June 1948 – May 1949: the trigger was the merging of the Western zones and the introduction of a new currency, the Deutsche Mark, without Soviet agreement. Stalin cut road, rail and canal access to West Berlin from 24 June 1948; the Western allies flew in supplies for eleven months until the blockade was lifted on 12 May 1949. Neither side fired, but neither backed down.",
        "Consequences: NATO was founded on 4 April 1949 as a permanent Western military alliance and the first peacetime American commitment to Europe; Germany was formally split into the Federal Republic (May 1949) and the German Democratic Republic (October 1949); the Warsaw Pact followed on 14 May 1955, days after West Germany joined NATO. Blame is argued both ways — Soviet expansion and broken election promises, against American economic power, the atomic monopoly and the refusal to recognise legitimate Soviet security fears.",
      ],
    },
    {
      id: "5-containment", num: 5, title: "5. How effectively did the USA contain communism?",
      blurb: "The three case studies the syllabus names: Korea 1950–53, Cuba 1959–62, Vietnam 1955–75.",
      syllabus: [
        "Korea, 1950–53: North Korean forces crossed the 38th parallel on 25 June 1950. Because the USSR was boycotting the Security Council over China's seat, the UN authorised a force — overwhelmingly American, under General MacArthur. The Inchon landings of 15 September 1950 reversed the war, but the advance to the Yalu River brought Chinese forces in from October 1950; Truman sacked MacArthur in April 1951 for wanting to widen the war.",
        "Korea's outcome: the armistice of 27 July 1953 left the border almost exactly where it had started, at the 38th parallel, after roughly three million deaths. Judged as containment it worked — South Korea stayed non-communist and the UN had acted collectively. Judged as rollback it failed, and it turned the Cold War into a global, militarised confrontation.",
        "Cuba, 1959–62: Castro overthrew Batista in January 1959, nationalised American-owned property and faced a US trade embargo, which pushed him towards Moscow. The Bay of Pigs invasion of April 1961, using about 1,400 US-trained exiles, was a humiliating failure that made Castro more popular and more Soviet-dependent.",
        "The Cuban Missile Crisis, October 1962: a U-2 flight photographed Soviet missile sites on 14 October; Kennedy announced a naval blockade — called a 'quarantine' — on 22 October; after thirteen days Khrushchev agreed on 28 October to remove the missiles in return for a public American pledge not to invade Cuba and a secret promise to withdraw US Jupiter missiles from Turkey. It produced the Moscow–Washington hotline and the Partial Test Ban Treaty of 1963 — but Cuba stayed communist, so containment in the Americas had failed.",
        "Vietnam, 1955–75: after the French defeat at Dien Bien Phu in 1954 the Geneva Accords split Vietnam at the 17th parallel. The domino theory and the corrupt Diem regime drew the USA in; the Gulf of Tonkin incident of August 1964 produced the resolution that let Johnson escalate without a declaration of war. Operation Rolling Thunder and the first US combat troops both began in March 1965, and numbers peaked at around 540,000 in 1968.",
        "Why Vietnam failed: American firepower — search-and-destroy, B-52s, napalm, Agent Orange — could not beat guerrilla warfare, the Ho Chi Minh Trail or an enemy indistinguishable from civilians, and it alienated the peasantry it was meant to protect. The Tet Offensive of January 1968 was a military defeat for the Viet Cong but a psychological turning point at home, and My Lai (March 1968) destroyed what was left of moral authority. Nixon's Vietnamisation led to the ceasefire of January 1973, US withdrawal by March 1973, and the fall of Saigon on 30 April 1975.",
      ],
    },
    {
      id: "6-eastern-europe", num: 6, title: "6. How secure was the USSR's control over Eastern Europe?",
      blurb: "Hungary 1956, Czechoslovakia 1968, the Berlin Wall, Solidarity, Gorbachev and 1989.",
      syllabus: [
        "Hungary, 1956: economic hardship and resentment of Rákosi's rule produced protests in October 1956 and brought Imre Nagy to power. When Nagy announced free elections, the end of one-party rule and withdrawal from the Warsaw Pact, Soviet tanks entered Budapest on 4 November 1956. About 3,000 Hungarians were killed and around 200,000 fled; Kádár was installed and Nagy was executed in June 1958. The West, distracted by the Suez Crisis, did nothing.",
        "Czechoslovakia, 1968: Dubček replaced Novotný in January 1968 and launched 'socialism with a human face' — censorship relaxed, freer speech and travel — while promising to stay inside the Warsaw Pact. Warsaw Pact troops invaded on 20–21 August 1968 and met passive rather than armed resistance; Jan Palach burned himself to death in January 1969 and Dubček was replaced by Husák in April 1969.",
        "The Brezhnev Doctrine, announced after 1968, claimed the USSR's right to intervene in any socialist state where socialism was threatened. Comparing 1956 and 1968: both were reform movements crushed by force with no Western intervention, but Hungary saw armed fighting and a bid to leave the Warsaw Pact, whereas Czechoslovakia was a party-led reform that stayed loyal to the Pact and resisted without weapons.",
        "The Berlin Wall, built 13 August 1961: around 2.7 million East Germans, many of them young and skilled, had left through West Berlin since 1949. The Wall stopped the haemorrhage and stabilised East Germany, so in the USSR's own terms it worked — but it was also a permanent propaganda defeat, an admission that people had to be walled in.",
        "Solidarity in Poland: strikes at the Gdańsk Lenin Shipyard in August 1980, led by Lech Wałęsa, produced the Gdańsk Agreement and the first independent trade union in the Soviet bloc, with roughly 9–10 million members within a year. General Jaruzelski declared martial law on 13 December 1981 and banned it in 1982, but it survived underground, was legalised again in 1989 and swept the semi-free elections of June 1989, putting Mazowiecki in as the bloc's first non-communist prime minister.",
        "Gorbachev and collapse: from March 1985 glasnost and perestroika removed the threat that had held the satellites down, and Gorbachev abandoned the Brezhnev Doctrine. Hungary opened its border with Austria in 1989, the Berlin Wall was opened on 9 November 1989, Czechoslovakia's Velvet Revolution followed in November–December 1989 and Ceaușescu was overthrown that December. Germany reunified on 3 October 1990 and the Warsaw Pact was dissolved in July 1991.",
      ],
    },
    {
      id: "7-source-skills", num: 7, title: "7. Source skills — the whole of Paper 2",
      blurb: "Inference, provenance, cross-reference and judgement — a whole paper, and where most marks are lost.",
      syllabus: [
        "Inference, not description: a 'What can you learn…' answer must state something the source suggests but does not say outright, then support it with a quoted detail. 'The source says the League was weak' is copying; 'The source suggests the cartoonist blamed the absent Americans rather than the League itself, because the empty chair is labelled USA' is an inference.",
        "Provenance is the whole game — run NOP on every source. Nature (what kind of source is it: speech, private diary, cartoon, poster, memoir, official report?); Origin (who wrote it, when, and what were they in a position to know?); Purpose (who was meant to read it and what was it meant to make them do?). Audience and date do most of the work: a speech at a rally, a diary never meant to be read, and a memoir written twenty years later are three different kinds of evidence.",
        "Reliability is not the same as usefulness. A blatantly biased poster is unreliable about facts but extremely useful as evidence of what a government wanted people to believe. Never write a source off as 'biased so it is useless' — say what it is useless FOR and what it is good evidence OF.",
        "Cross-referencing: 'How far do these two sources agree?' is about the big message, not matching details. Compare the overall point each source makes, then look for agreement or disagreement in specifics, then explain WHY they differ using provenance — different nationality, different date, different audience, different job.",
        "Cartoons and posters: identify the artist's country and date first, then decode every label, caption and symbol, then state the big message in one sentence — the point the cartoonist wants the reader to accept. Then ask why that message was published at that moment.",
        "'How far do these sources show / provide convincing evidence that…' is the final part and carries the most marks. Group the sources: those that support the statement, those that do not, referring to each by letter. Use content AND provenance for both groups, then reach an explicit judgement about how convincing the set is overall — including which sources you trust more and why.",
      ],
    },
    {
      id: "8-germany-depth", num: 8, title: "8. Depth Study B: Germany, 1918–45",
      blurb: "ONE of five depth studies — schools choose. This is the Germany option; if yours teaches Russia, the USA or a war, skip this topic.",
      syllabus: [
        "0470 requires at least one depth study from A The First World War 1914–18, B Germany 1918–45, C Russia 1905–41, D The United States 1919–41, or E The Second World War in Europe and the Asia–Pacific 1939–c.1945 — and centres taking coursework may devise their own. Check which one your school teaches before revising this topic; everything in Topics 1–7 applies to every candidate.",
        "Was the Weimar Republic doomed from the start? The Kiel mutiny of 3 November 1918, the Kaiser's abdication on 9 November and the armistice of 11 November left the new republic carrying the blame. The 1919 constitution gave proportional representation (endless coalitions), a president elected every seven years and Article 48 emergency powers. It survived the Spartacist revolt of January 1919 from the left and the Kapp Putsch of March 1920 from the right, but the Ruhr occupation and hyperinflation of 1923 nearly finished it.",
        "Recovery and the Stresemann era, 1924–29: the Rentenmark of November 1923, the Dawes Plan of 1924 rescheduling reparations against American loans, the Locarno treaties of 1925, League membership in 1926 and the Young Plan of 1929. Cultural flowering — Bauhaus, expressionist cinema, Otto Dix, Remarque. But recovery rested on short-term US loans, and Stresemann died in October 1929, the month of the Wall Street Crash.",
        "Why Hitler could dominate Germany by 1934: the Munich Putsch of 8–9 November 1923 failed and Hitler wrote Mein Kampf in Landsberg, but the Nazis were a fringe party until the Depression — 12 seats in May 1928, 107 in September 1930, 230 and the largest party in July 1932, falling back to 196 in November 1932. With unemployment around six million, Hindenburg appointed Hitler Chancellor on 30 January 1933 on von Papen's advice that he could be controlled.",
        "Consolidation: the Reichstag Fire of 27 February 1933 and the decree that followed suspended civil rights; even so the election of 5 March 1933 gave the Nazis 288 seats and only 43.9%. The Enabling Act of 23 March 1933 let Hitler legislate without the Reichstag; trade unions were banned in May and all other parties by July 1933; the Night of the Long Knives on 30 June 1934 destroyed Röhm and the SA leadership; and when Hindenburg died on 2 August 1934 Hitler merged the offices as Führer and took the army's personal oath.",
        "Control and life under the regime: Goebbels' propaganda ministry, the Nuremberg rallies, cheap radios, book burnings, the SS and Gestapo and the camps from Dachau (March 1933). Opposition existed — Niemöller and the Confessional Church, Galen against euthanasia, the Edelweiss Pirates, the White Rose (the Scholls executed February 1943) and the July Bomb Plot of 20 July 1944. Hitler Youth and the BDM; 'Kinder, Küche, Kirche' and marriage loans for women; unemployment cut by rearmament, the RAD and the Four-Year Plan of 1936, though the figures excluded Jews, women and conscripts. Persecution ran from the 1933 boycott through the Nuremberg Laws of September 1935 and Kristallnacht on 9–10 November 1938 to the Wannsee Conference of 20 January 1942 and the murder of about six million Jews.",
      ],
    },
  ],

  flashcards: [
    { term: "Treaty of Versailles — date and place", def: "Signed 28 June 1919 in the Hall of Mirrors, Palace of Versailles. Germany was not allowed to negotiate, which is why Germans called it a Diktat." },
    { term: "Article 231", def: "The 'war guilt' clause — Germany accepted responsibility for causing the war. It was the legal basis for reparations and the term Germans resented most." },
    { term: "Reparations figure", def: "£6,600 million (132 billion gold marks), fixed in 1921 — not in the treaty itself, which left the sum to a later commission." },
    { term: "Versailles military terms", def: "Army 100,000 men, no conscription, no tanks, no submarines, no air force, navy of six battleships, Rhineland permanently demilitarised and occupied for 15 years." },
    { term: "The Big Three", def: "Clemenceau (France) — revenge and security. Wilson (USA) — Fourteen Points, self-determination, a League of Nations. Lloyd George (Britain) — a middle way: destroy the German navy and colonies but keep Germany trading." },
    { term: "The other four treaties", def: "Saint-Germain with Austria (10 Sept 1919) · Neuilly with Bulgaria (27 Nov 1919) · Trianon with Hungary (4 June 1920) · Sèvres with Turkey (10 Aug 1920), replaced by Lausanne (24 July 1923)." },
    { term: "Trianon", def: "Hungary's treaty, 4 June 1920. Transylvania to Romania, Slovakia and Ruthenia to Czechoslovakia — Hungary lost about two-thirds of its territory. Army capped at 35,000." },
    { term: "League of Nations — start and home", def: "Began 10 January 1920 under the Covenant, which was Part I of the Treaty of Versailles. Headquarters in Geneva." },
    { term: "League structure", def: "Assembly (all members, once a year, unanimous decisions) · Council (permanent members Britain, France, Italy, Japan, each with a veto) · Secretariat · Permanent Court of International Justice · International Labour Organisation." },
    { term: "Who was missing from the League", def: "The USA never joined — the Senate rejected the Treaty. Germany joined only in 1926 and left in 1933; the USSR joined in 1934. Japan left in 1933, Italy in 1937." },
    { term: "Corfu, 1923", def: "After General Tellini was murdered on Greek soil, Mussolini bombarded and occupied Corfu. The Conference of Ambassadors overruled the League and Greece — the victim — paid Italy compensation." },
    { term: "Manchurian Crisis", def: "Mukden Incident 18 September 1931; Japan overran Manchuria and created Manchukuo. The Lytton Report was adopted in February 1933 and Japan left the League in March 1933. No sanctions, no force." },
    { term: "Abyssinian Crisis", def: "Italy invaded 3 October 1935. Sanctions excluded oil, coal and steel and the Suez Canal stayed open. The leaked Hoare–Laval Pact of December 1935 destroyed the League's credibility; Addis Ababa fell in May 1936." },
    { term: "Remilitarisation of the Rhineland", def: "7 March 1936 — a bluff, with orders to withdraw if France resisted. France did nothing, and Hitler concluded the democracies would not fight." },
    { term: "Anschluss", def: "12 March 1938. Schuschnigg was forced to resign, Seyss-Inquart invited German troops in, and Austria was absorbed into the Reich — expressly forbidden by Versailles and Saint-Germain." },
    { term: "Munich Agreement", def: "29–30 September 1938 — Hitler, Chamberlain, Daladier and Mussolini handed the Sudetenland to Germany. Czechoslovakia was not in the room and the USSR was not invited." },
    { term: "15 March 1939", def: "Hitler occupied the rest of the Czech lands — the moment appeasement was proved to have failed. Britain and France guaranteed Poland on 31 March 1939." },
    { term: "Nazi–Soviet Pact", def: "23 August 1939 — a ten-year non-aggression pact with a secret protocol dividing Poland and the Baltic states. It removed the risk of a two-front war." },
    { term: "Outbreak of war", def: "Germany invaded Poland on 1 September 1939. Britain and France declared war on 3 September 1939." },
    { term: "Yalta vs Potsdam", def: "Yalta (Feb 1945): Roosevelt, Churchill, Stalin — four zones, the UN, Soviet entry against Japan, free elections promised. Potsdam (July–Aug 1945): Truman and Attlee had replaced them, and the allies quarrelled over reparations, Poland and Germany." },
    { term: "Iron Curtain speech", def: "Churchill at Fulton, Missouri, 5 March 1946 — 'an iron curtain has descended across the Continent'." },
    { term: "Truman Doctrine", def: "12 March 1947 — American support for free peoples resisting subjugation, prompted by Greece and Turkey. The birth of containment." },
    { term: "Marshall Plan", def: "Announced 5 June 1947, funded from 1948 — around $13 billion to sixteen Western European countries. Stalin banned Eastern Europe from taking it and answered with Cominform and Comecon." },
    { term: "Berlin Blockade", def: "Triggered by the new Deutsche Mark in the merged Western zones. Stalin cut land access from 24 June 1948; the airlift supplied West Berlin until the blockade was lifted on 12 May 1949." },
    { term: "NATO and the Warsaw Pact", def: "NATO founded 4 April 1949 after the blockade. The Warsaw Pact followed on 14 May 1955, days after West Germany joined NATO." },
    { term: "Korean War", def: "North Korea crossed the 38th parallel on 25 June 1950. The UN acted because the USSR was boycotting the Security Council. Inchon 15 September 1950; China intervened from October 1950; armistice 27 July 1953 on almost the original border." },
    { term: "Cuban Missile Crisis", def: "U-2 photographs 14 October 1962 · Kennedy's naval 'quarantine' 22 October · Khrushchev agreed to withdraw on 28 October, for a US pledge not to invade Cuba and a secret removal of Jupiter missiles from Turkey." },
    { term: "Vietnam turning points", def: "Geneva 1954 split at the 17th parallel · Gulf of Tonkin resolution August 1964 · Rolling Thunder and first combat troops March 1965 · Tet January 1968 · My Lai March 1968 · ceasefire January 1973 · Saigon fell 30 April 1975." },
    { term: "Hungary 1956", def: "Nagy announced free elections and withdrawal from the Warsaw Pact. Soviet tanks entered Budapest on 4 November 1956; about 3,000 died, 200,000 fled, and Nagy was executed in 1958." },
    { term: "Prague Spring", def: "Dubček's 'socialism with a human face' from January 1968. Warsaw Pact troops invaded on 20–21 August 1968; resistance was passive, and Husák replaced Dubček in April 1969." },
    { term: "Brezhnev Doctrine", def: "The claimed Soviet right to intervene in any socialist state where socialism was threatened. Gorbachev abandoned it, which is why 1989 was not another 1968." },
    { term: "The Berlin Wall", def: "Built 13 August 1961 to stop the flight of around 2.7 million East Germans since 1949; opened 9 November 1989." },
    { term: "Solidarity", def: "Born from the Gdańsk shipyard strike of August 1980 under Lech Wałęsa — the bloc's first free trade union, roughly 9–10 million members. Jaruzelski imposed martial law on 13 December 1981; Solidarity won the elections of June 1989." },
    { term: "NOP", def: "The provenance checklist: Nature (what kind of source), Origin (who, when, what could they know), Purpose (for whom, to make them do what). Every reliability mark comes from here, not from content." },
  ],

  questions: [
    // ---- Topic 1: the peace treaties ----
    {
      id: "ih10-1", topic: "1-peace-treaties",
      q: "Describe the military terms imposed on Germany by the Treaty of Versailles. [4]",
      model: "Any four separate points, one sentence each, with no explanation attached:\n1. The German army was limited to 100,000 men and conscription was banned.\n2. Germany was forbidden tanks, submarines and an air force.\n3. The navy was limited to six battleships.\n4. The Rhineland was permanently demilitarised, and Allied troops occupied it for fifteen years.\n\nExaminer's note: a (a) question is pure recall. Do not write why the terms were imposed or how Germany reacted — there are no marks for it and it costs you time you need for part (c).",
    },
    {
      id: "ih10-2", topic: "1-peace-treaties",
      q: "Which pair correctly matches a 1919–23 treaty to the country it was imposed on?",
      opts: [
        "Treaty of Trianon — Austria",
        "Treaty of Neuilly — Hungary",
        "Treaty of Saint-Germain — Austria",
        "Treaty of Sèvres — Bulgaria",
      ],
      a: "Treaty of Saint-Germain — Austria",
      model: "Saint-Germain (10 September 1919) was Austria's treaty: it broke up Austria–Hungary, banned Anschluss and capped the army at 30,000.\nThe distractors are the classic muddle: Trianon (4 June 1920) was HUNGARY's — Transylvania to Romania, about two-thirds of its territory gone. Neuilly (27 November 1919) was BULGARIA's — western Thrace to Greece, so Bulgaria lost its Aegean coast. Sèvres (10 August 1920) was TURKEY's, and it was the one treaty overturned, replaced by Lausanne on 24 July 1923.\nLearn them as a five-line table. Naming the wrong treaty in an essay wipes out the point you were making.",
    },
    {
      id: "ih10-3", topic: "1-peace-treaties",
      q: "'The Treaty of Versailles was a fair settlement.' How far do you agree with this statement? Explain your answer. [10]",
      model: "AGREE — it can be defended.\nGermany had started the war in the eyes of the victors and had done enormous damage: northern France was devastated while no fighting had touched German soil, so reparations for reconstruction were not unreasonable. Germany had itself imposed the far harsher Treaty of Brest-Litovsk on Russia in 1918, taking a third of Russia's population — so it had shown what a German victory would have looked like. The territorial losses were smaller than they sound: about 10% of land, much of it taken from others in the first place, and several transfers (North Schleswig, Eupen-Malmédy) followed plebiscites, applying Wilson's own principle of self-determination. The treaty was also a compromise between three governments with electorates demanding much more, and Clemenceau was refused the separate Rhineland state he wanted.\n\nDISAGREE — the standard case against.\nGermany was not allowed to negotiate at all, which made the settlement a Diktat and denied it legitimacy from the first day. Article 231 forced a moral confession that most Germans did not accept, and the £6,600 million bill fixed in 1921 was set after Germany had lost 16% of its coalfields and much of its heavy industry — the means of paying were removed along with the land. Self-determination was applied selectively: it created Czechoslovakia and Poland but left Germans under Polish and Czech rule, forbade Anschluss with Austria and handed the Sudetenland's Germans to a new state — which gave Hitler ready-made grievances he used from 1936 to 1939. The economic consequences fed directly into the Ruhr occupation and the hyperinflation of 1923.\n\nJUDGEMENT.\nOn balance the treaty was not fair, but the more important point is that it was not workable. Individual terms can each be defended against a 1919 standard; what cannot be defended is the combination of humiliating Germany publicly while leaving it united, populous and potentially the strongest state in Europe, and then failing to enforce the terms. A settlement severe enough to be resented but not severe enough to disable is the worst of both, which is why the treaty is fairly blamed for creating the grievances Hitler exploited — even though it was Hitler, not the treaty, who chose to go to war.",
    },
    // ---- Topic 2: the League ----
    {
      id: "ih10-4", topic: "2-league",
      q: "Explain why the League of Nations failed to stop Japanese aggression in Manchuria. [6]",
      model: "Three developed reasons — each stated, then explained, then linked to the outcome.\n\n1. The League had no armed force of its own, so it depended on member states supplying troops. Manchuria was on the other side of the world from Geneva, and neither Britain nor France was willing to send a fleet or an army to defend Chinese territory that mattered little to them. Without force, the League's condemnation cost Japan nothing.\n\n2. The League's procedures were far too slow for a fast military occupation. The Lytton Commission was sent in 1932 and did not report until September 1932, by which time Japan had completed the conquest and set up the puppet state of Manchukuo. When the League adopted the report in February 1933 it was condemning a fait accompli, and Japan simply walked out in March 1933.\n\n3. Economic sanctions were meaningless in the conditions of the Depression. Japan's main trading partner was the USA, which was not a League member and would not join a boycott; and Britain and France, with their own economies collapsing after 1929, were not prepared to lose trade to punish an aggressor. So the one weapon the League could realistically use was one no member would fire.\n\nTop-band move: finish by linking the reasons — because Japan was a permanent member of the Council with a veto, the League was being asked to punish one of its own guardians, which is why the failure was structural rather than accidental.",
    },
    {
      id: "ih10-5", topic: "2-league",
      q: "Describe the humanitarian work carried out by the League of Nations in the 1920s. [4]",
      model: "1. It resettled hundreds of thousands of refugees and prisoners of war displaced by the First World War, and issued 'Nansen passports' as identity papers for stateless people.\n2. Its Health Committee ran campaigns against epidemic diseases such as typhus and malaria and gathered international data on their spread.\n3. The International Labour Organisation worked to improve working conditions and to limit hours and child labour.\n4. Its commissions campaigned against slavery and the slave trade, freeing slaves in territories under League mandate.\n\nThis is the part of the League's record students forget — and 'To what extent was the League a success?' cannot be answered honestly without it.",
    },
    {
      id: "ih10-6", topic: "2-league",
      q: "'The Abyssinian Crisis damaged the League of Nations more than the Manchurian Crisis did.' How far do you agree with this statement? Explain your answer. [10]",
      model: "AGREE — Abyssinia did the greater damage.\nManchuria was far away and involved a country few Europeans cared about; Abyssinia was a member state of the League, invaded on 3 October 1935 by another European power, in the Mediterranean where Britain and France had fleets and could have acted. The League did act — but so feebly that the failure was worse than doing nothing: sanctions were imposed but deliberately excluded oil, coal and steel, the commodities that would actually have stopped the Italian army, and the Suez Canal, controlled by Britain, was left open to Italian troopships. Worst of all, the Hoare–Laval Pact of December 1935 revealed that the two leading League powers were secretly offering Mussolini most of Abyssinia while publicly upholding collective security. That was not weakness, it was hypocrisy, and it destroyed the League's moral authority. Haile Selassie's appeal in June 1936 was heard and ignored. After Abyssinia no one took the League seriously again, and Hitler remilitarised the Rhineland in March 1936 in the middle of the crisis.\n\nDISAGREE — Manchuria was the more important failure.\nManchuria came first, and it was the first that mattered: it established that a permanent member of the Council could seize territory by force and face nothing worse than a report. Every calculation Mussolini and Hitler made after 1933 rested on that precedent. It also cost the League a great power permanently, since Japan left in March 1933 and never returned. In that sense Abyssinia did not create the League's weakness — it merely confirmed in public what Manchuria had already proved.\n\nJUDGEMENT.\nManchuria was the more significant failure because it set the precedent, but Abyssinia was the more damaging one because it destroyed the League's credibility rather than merely exposing its limits. The distinction is worth making explicitly: Manchuria showed the League could not act far from Europe; Abyssinia showed that its two leading members would not act even where they easily could. That is why the League was finished as a peacekeeping body by 1936 — and why the Depression, which made every state put trade and self-interest first from 1929, sits underneath both crises as the deeper cause.",
    },
    // ---- Topic 3: collapse of peace ----
    {
      id: "ih10-7", topic: "3-collapse-1939",
      q: "Explain why Hitler was able to remilitarise the Rhineland in March 1936 without opposition. [6]",
      model: "1. France was politically paralysed and would not act alone. It was weeks away from a general election, with no government willing to order a mobilisation that might mean war, and its military planners insisted that any response required full mobilisation rather than a limited police action. Because France would not move without British backing, the decisive moment passed in days.\n\n2. Britain had no appetite to stop him and considerable sympathy for the German case. The widespread British view was that Hitler was 'only walking into his own back garden' — the Rhineland was German territory, and its demilitarisation was one of the Versailles terms many in Britain already thought unjust. Having signed the Anglo-German Naval Agreement in June 1935, Britain had already shown it would treat German rearmament as negotiable.\n\n3. The League and the other powers were distracted and discredited. The Abyssinian Crisis was at its height, Britain and France had just been exposed by the Hoare–Laval Pact, and Italy — a guarantor of Locarno — was now hostile to them. With the League's authority destroyed and the Stresa Front collapsed, there was no body left to organise a collective response.\n\nFinish with the consequence: because it was a bluff — German troops had orders to withdraw if France resisted — the absence of opposition taught Hitler that the democracies would not fight, which shaped everything he did up to 1939.",
    },
    {
      id: "ih10-8", topic: "3-collapse-1939",
      q: "'Appeasement was the main reason war broke out in Europe in 1939.' How far do you agree with this statement? Explain your answer. [10]",
      model: "AGREE — appeasement bears heavy responsibility.\nEach concession made the next demand more likely. Nothing was done over conscription in March 1935, and Britain then legitimised German rearmament with the Naval Agreement in June. Nothing was done over the Rhineland on 7 March 1936, when a bluff could have been called at minimal cost. Nothing was done over the Anschluss on 12 March 1938. At Munich on 29–30 September 1938 Britain and France went further and actively handed over the Sudetenland — with Czechoslovakia excluded from the room — surrendering the Czech frontier fortifications, the Skoda arms works and 35 divisions. Appeasement also convinced Stalin that the West would never make a serious anti-German alliance, which pushed him towards the Nazi–Soviet Pact of 23 August 1939. If Hitler's method was to demand and see what happened, appeasement supplied the answer every time.\n\nDISAGREE — other causes matter as much or more.\nThe deepest cause is Hitler himself: his aims — destroying Versailles, uniting all German speakers, Lebensraum in the east — required war, and no amount of firmness would have made him abandon them. Appeasement can only be blamed for failing to stop a war someone else was determined to have. Behind that stand the Treaty of Versailles, which supplied every grievance he used, and the collapse of the League after Manchuria and Abyssinia, which had already removed collective security before appeasement began. The Depression matters too, since it created the conditions for Hitler's rise and made Britain and France unwilling to rearm. And the immediate trigger was the Nazi–Soviet Pact: it removed the two-front problem and made the invasion of Poland on 1 September 1939 a safe bet.\n\nJUDGEMENT.\nAppeasement was not the main reason for the war, but it was the main reason the war came in 1939 on Hitler's terms rather than earlier on better ones. Hitler's aims were the cause; appeasement was the enabling condition. That said, the case for appeasement should be stated fairly — genuine fear of mass bombing, incomplete British rearmament, reluctant Dominions, an isolationist USA and a widespread belief that Versailles had been unjust. Chamberlain's error was not seeking peace but believing that a man who had broken every previous promise would keep the one made at Munich; that belief died on 15 March 1939 when Hitler took the rest of Czechoslovakia.",
    },
    {
      id: "ih10-9", topic: "3-collapse-1939",
      q: "Put these four events in the correct chronological order: the Anschluss · the Nazi–Soviet Pact · the remilitarisation of the Rhineland · the Munich Agreement.",
      opts: [
        "Rhineland · Anschluss · Munich Agreement · Nazi–Soviet Pact",
        "Anschluss · Rhineland · Munich Agreement · Nazi–Soviet Pact",
        "Rhineland · Munich Agreement · Anschluss · Nazi–Soviet Pact",
        "Anschluss · Munich Agreement · Rhineland · Nazi–Soviet Pact",
      ],
      a: "Rhineland · Anschluss · Munich Agreement · Nazi–Soviet Pact",
      model: "Rhineland 7 March 1936 → Anschluss 12 March 1938 → Munich Agreement 29–30 September 1938 → Nazi–Soviet Pact 23 August 1939.\nThe two March dates two years apart are what trips people up. Anchor the sequence on 1938: the Anschluss in March, Munich in September, then the occupation of the rest of Czechoslovakia on 15 March 1939, the guarantee to Poland on 31 March 1939, the Pact on 23 August, the invasion on 1 September and the declarations of war on 3 September.\nA causation answer that puts these in the wrong order collapses, because the whole argument depends on each concession preceding the next demand.",
    },
    // ---- Topic 4: Cold War origins ----
    {
      id: "ih10-10", topic: "4-cold-war-origins",
      q: "Describe what was agreed at the Yalta Conference in February 1945. [4]",
      model: "1. Germany would be divided into four occupation zones (American, British, French and Soviet), with Berlin — deep inside the Soviet zone — divided the same way.\n2. A United Nations organisation would be set up, with a founding conference to follow.\n3. The USSR would declare war on Japan three months after Germany's defeat.\n4. Poland's eastern border would move west in the USSR's favour, and the Declaration on Liberated Europe promised free elections in the liberated countries of Eastern Europe.\n\nKeep Yalta and Potsdam apart: Yalta (February 1945) was the conference of agreement, with Roosevelt, Churchill and Stalin; Potsdam (July–August 1945) was the conference of disagreement, with Truman and — from partway through — Attlee in place of two of them.",
    },
    {
      id: "ih10-11", topic: "4-cold-war-origins",
      q: "Explain why relations between the USA and the USSR worsened between the Potsdam Conference and the Berlin Blockade. [6]",
      model: "1. The election promises made at Yalta were not kept, and each side read that differently. Communist-dominated governments were imposed across Poland, Romania, Bulgaria, Hungary and Albania, and Czechoslovakia fell to a coup in February 1948. To Truman this was straightforward expansion in breach of the Declaration on Liberated Europe; to Stalin it was the security buffer the USSR had been promised in substance, having been invaded through that corridor twice in thirty years. Because both sides believed the other had broken the agreement, every later action was read in the worst light.\n\n2. The USA moved from wartime cooperation to open containment. The Truman Doctrine of 12 March 1947 committed America to supporting free peoples resisting subjugation, and the Marshall Plan announced on 5 June 1947 offered about $13 billion of aid. Stalin saw dollar imperialism — an attempt to buy Europe and pull the satellites out of the Soviet orbit — and banned Eastern Europe from taking it, answering with Cominform in 1947 and Comecon in 1949. Europe was now economically divided as well as militarily.\n\n3. The two sides' plans for Germany became irreconcilable. Stalin wanted Germany kept weak and paying reparations; the West concluded that a prosperous Germany was essential to European recovery, merged its zones and introduced a new currency, the Deutsche Mark, in June 1948 without Soviet agreement. Stalin regarded that as the unilateral creation of a new West German state and cut land access to West Berlin from 24 June 1948 to force the issue.\n\nThe trend line to state: mistrust at Potsdam over reparations and Poland became rival systems by 1947 and a direct confrontation by 1948.",
    },
    {
      id: "ih10-12", topic: "4-cold-war-origins",
      q: "'Stalin was more to blame than Truman for the start of the Cold War.' How far do you agree with this statement? Explain your answer. [10]",
      model: "AGREE — the case against Stalin.\nHe had signed the Declaration on Liberated Europe at Yalta promising free elections and then installed communist governments by force and salami tactics across Poland, Romania, Bulgaria, Hungary and Albania, culminating in the Czechoslovak coup of February 1948 that destroyed a functioning democracy. He kept an enormous army mobilised while the West demobilised. He forbade the satellites from taking Marshall aid that would have raised living standards, showing that control mattered more than recovery. And it was Stalin who took the first aggressive action against a Western position, blockading two million people in West Berlin from 24 June 1948 in an attempt to starve the Allies out.\n\nDISAGREE — the case against Truman and the West.\nAmerica ended lend-lease to the USSR abruptly in 1945 and refused the reconstruction loan Stalin asked for, while the USSR had lost perhaps 27 million people and had every reason to fear a revived Germany. Truman used the atomic bomb without warning his ally, and the Hiroshima and Nagasaki bombings of August 1945 looked to Moscow like a demonstration aimed at them as much as at Japan. The Truman Doctrine of March 1947 openly divided the world into two camps, and the Marshall Plan tied recovery to American economic influence. The Western powers, not Stalin, merged their zones and introduced a new currency in Germany unilaterally — the act that triggered the blockade — and NATO in April 1949 gave the West a permanent military alliance first.\n\nJUDGEMENT.\nStalin bears the greater share of the blame, because his actions in Eastern Europe were the ones that broke a specific written agreement and because the blockade was the first attempt to force the other side out of a position it legally held. But 'blame' is too simple a frame for what happened, and the strongest answers say so: the alliance of 1941–45 was one of necessity between systems that were ideologically incompatible, and once the common enemy was gone each side's defensive moves looked offensive to the other. Stalin's buffer zone was America's expansionism; America's containment was Stalin's encirclement. Stalin was more to blame for the specific crises; the mutual misreading was to blame for the Cold War.",
    },
    // ---- Topic 5: containment ----
    {
      id: "ih10-13", topic: "5-containment",
      q: "Describe the events of the Cuban Missile Crisis in October 1962. [4]",
      model: "1. On 14 October 1962 an American U-2 spy plane photographed Soviet nuclear missile sites being built in Cuba.\n2. On 22 October President Kennedy announced a naval blockade — officially a 'quarantine' — of Cuba and demanded the missiles' removal.\n3. Soviet ships carrying further missiles turned back before reaching the blockade line, and an American U-2 was shot down over Cuba at the height of the crisis.\n4. On 28 October Khrushchev agreed to dismantle and withdraw the missiles.\n\nSave the terms of the settlement for a (b) or (c) answer: a public American pledge not to invade Cuba, and a secret agreement to withdraw US Jupiter missiles from Turkey.",
    },
    {
      id: "ih10-14", topic: "5-containment",
      q: "Explain why the United States was unable to defeat the Viet Cong in Vietnam. [6]",
      model: "1. American tactics were the wrong instrument for the war being fought. Search-and-destroy sweeps, B-52 carpet bombing, napalm and Agent Orange were designed to destroy an enemy who could be found, but the Viet Cong dispersed into villages, tunnels and jungle and fought only when they chose. Because the enemy was indistinguishable from the civilian population, overwhelming firepower killed peasants, and each such death — My Lai in March 1968 being the extreme case — recruited more Viet Cong. The tactics therefore worked against the strategic aim of winning the population.\n\n2. The Viet Cong had advantages America could not match. They knew the terrain, needed very little to keep fighting, and were resupplied down the Ho Chi Minh Trail through Laos and Cambodia, which the USA could bomb but never close. They were fighting on their own soil for national unification, so their willingness to absorb casualties was effectively unlimited, whereas conscripted American soldiers far from home had no comparable motive.\n\n3. The war was lost politically at home. Vietnam was the first televised war, and the Tet Offensive of January 1968 — a military defeat for the Viet Cong but a shock to an American public that had been told the war was nearly won — destroyed the credibility of the government's optimism. Rising casualties, the draft and the anti-war movement made continued escalation impossible, so Nixon turned to Vietnamisation and withdrawal rather than victory.\n\nAdd the underlying point: the regime the USA was defending was corrupt and unpopular, so there was no South Vietnamese government worth fighting for — which is why Saigon fell on 30 April 1975 two years after the Americans left.",
    },
    {
      id: "ih10-15", topic: "5-containment",
      q: "'American containment of communism was more successful in Korea than in Cuba or Vietnam.' How far do you agree with this statement? Explain your answer. [10]",
      model: "AGREE — Korea was the success.\nThe stated aim was to prevent the spread of communism, and in Korea that is exactly what happened: North Korean forces crossed the 38th parallel on 25 June 1950, and by the armistice of 27 July 1953 they had been pushed back to almost exactly that line. South Korea remained non-communist, and remains so. It was also achieved with international legitimacy, since the UN Security Council authorised the force while the USSR was boycotting it, so America acted with allies rather than alone. Compare that with Cuba, where containment failed absolutely — Castro survived the trade embargo, the Bay of Pigs fiasco of April 1961 and the missile crisis, and Cuba remained a communist state ninety miles from Florida. Compare it too with Vietnam, where after a decade, some 58,000 American dead and the country's deepest political crisis since the Civil War, Saigon fell on 30 April 1975 and the whole of Vietnam became communist.\n\nDISAGREE — the comparison is not that clean.\nKorea cost around three million lives to restore a border that had not moved, and General MacArthur's push to the Yalu River provoked Chinese intervention and nearly widened the war — success only by the modest standard of restoring the status quo, and a failure by the standard of rollback that America briefly adopted. Cuba, meanwhile, produced the greatest containment achievement of all: the missiles were removed, and the crisis led directly to the hotline and the Partial Test Ban Treaty of 1963, so a nuclear war was contained even though Cuba was not. Vietnam's failure also looks different in the long run, since the neighbouring dominoes did not all fall as predicted.\n\nJUDGEMENT.\nYes, Korea was the most successful of the three, provided containment is judged by its own definition — stopping communism from spreading beyond where it already was — because it is the only case where an actual communist advance was reversed and held. But the reason matters more than the ranking: Korea worked because there was a conventional invasion across a recognised border, an identifiable enemy army, and international legal cover. Cuba and Vietnam had none of those things, which is why military containment could not be applied to a popular revolution or a guerrilla war. Containment worked where the Cold War looked like a conventional war, and failed where it did not.",
    },
    // ---- Topic 6: Eastern Europe ----
    {
      id: "ih10-16", topic: "6-eastern-europe",
      q: "Explain why the USSR crushed the Prague Spring in August 1968. [6]",
      model: "1. Dubček's reforms threatened the communist monopoly of power. 'Socialism with a human face' meant relaxing censorship, allowing freedom of speech and travel and tolerating criticism of the party. Even though Dubček insisted Czechoslovakia would stay in the Warsaw Pact, Brezhnev could see that a party which allowed free debate would eventually have to allow opposition, and the leading role of the party would be gone.\n\n2. The USSR feared the example would spread. Czechoslovakia sat at the centre of the bloc and bordered West Germany, and there were already signs of unrest in Poland and Ukraine. If reform were tolerated in Prague, other satellite populations would demand the same, and the bloc would unravel — a fear formalised as the Brezhnev Doctrine, the claimed Soviet right to intervene wherever socialism was threatened.\n\n3. Strategic and military considerations made Czechoslovakia too important to lose. It was the buffer between the USSR and NATO's forward positions in West Germany, and Soviet policy since 1945 had been to keep a defensive belt in Eastern Europe. Losing Czechoslovakia's reliability would open a hole in Warsaw Pact defences.\n\nThe supporting point: it was safe to act, because Hungary in 1956 had shown that the West would protest and do nothing — and the invasion of 20–21 August 1968 confirmed it.",
    },
    {
      id: "ih10-17", topic: "6-eastern-europe",
      q: "Describe the events in Hungary in 1956. [4]",
      model: "1. Protests and demonstrations against Soviet control broke out in Budapest in October 1956, and the statue of Stalin was pulled down.\n2. Imre Nagy replaced the hardline Rákosi as leader and formed a new government.\n3. Nagy announced free elections, the end of one-party rule, and Hungarian withdrawal from the Warsaw Pact and neutrality.\n4. Soviet tanks entered Budapest on 4 November 1956 and crushed the rising; around 3,000 Hungarians were killed, some 200,000 fled abroad, Kádár was installed as leader and Nagy was later executed.\n\nThe two dates that must be right: Nagy in October, the tanks on 4 November 1956.",
    },
    {
      id: "ih10-18", topic: "6-eastern-europe",
      q: "'Gorbachev was personally responsible for the collapse of Soviet control over Eastern Europe.' How far do you agree with this statement? Explain your answer. [10]",
      model: "AGREE — his role was decisive.\nSoviet control had rested since 1968 on one thing: the certainty that tanks would come, as they had in Budapest in 1956 and Prague in 1968. Gorbachev removed that certainty. Glasnost and perestroika from 1985 legitimised criticism inside the USSR itself, and by abandoning the Brezhnev Doctrine he told the satellite regimes they were on their own. The moment reform movements understood that the Red Army would not intervene, the calculation changed everywhere at once — which is why 1989 saw Poland's semi-free elections in June, Hungary opening its border with Austria, the Wall opened on 9 November, the Velvet Revolution in Czechoslovakia and Ceaușescu's fall, all inside a single year. He also withdrew from Afghanistan and sought arms agreements with the West, so there was no external threat left to justify the buffer zone.\n\nDISAGREE — the pressures were there long before him.\nOpposition was continuous: Berlin 1953, Hungary 1956, Czechoslovakia 1968 and, most damagingly, Solidarity, which grew from the Gdańsk strike of August 1980 to some 9–10 million members and survived Jaruzelski's martial law of 13 December 1981 underground until it could win in 1989. The Soviet economy was failing under the weight of central planning, the arms race and the cost of subsidising the satellites, which is precisely why Gorbachev attempted reform in the first place — he was responding to a crisis, not creating one. The Berlin Wall itself, built on 13 August 1961 to stop 2.7 million people leaving, was a permanent admission that the system could not hold its people voluntarily. And the ordinary Poles, Czechs, Hungarians and East Germans who went into the streets in 1989 took the risks themselves.\n\nJUDGEMENT.\nGorbachev was not responsible for the underlying causes — economic failure and the persistent refusal of Eastern Europeans to accept Soviet rule made the collapse likely sooner or later. But he was decisive in its timing and in its peacefulness. A different leader could have used force, as his predecessors had, and probably delayed the end by years at the cost of enormous bloodshed. The most accurate formulation is that the crowds of 1989 brought Soviet control down, and Gorbachev's choice not to shoot is why they succeeded.",
    },
    // ---- Topic 7: source skills (original invented sources) ----
    {
      id: "ih10-19", topic: "7-source-skills",
      q: "SOURCE A — from an editorial in a Paris daily newspaper, 10 May 1919, the week the draft terms were handed to the German delegation.\n\n'Already we are told the terms are too harsh. Too harsh! Ask the widows of Verdun. Walk through the villages of the Somme, where not one roof is left standing, and say the word harsh again. Germany began this war; Germany will pay for it, to the last franc, for as many years as are needed. Those who now preach moderation would hand back across a table everything our sons took from the enemy in the field.'\n\nSOURCE B — from the private diary of a British official attending the Paris Peace Conference, June 1919.\n\n'The Prime Minister is caught between two fires. At home the crowd wants the Kaiser hanged and Germany squeezed dry; here he must sit between a Frenchman who thinks of nothing but his frontier and an American who thinks of nothing but his League. I fear we are making a peace too severe to be forgiven and too mild to keep Germany down. In twenty years we shall be sitting in this room again.'\n\nHow far do these two sources agree? Explain your answer using details of the sources. [7]\n\n(Both sources were written for this pack in the style of Paper 2. They are not genuine documents — but answer as though the attributions were real, because that is the skill being tested.)",
      hint: "Compare the BIG MESSAGE of each source first, then the details, then explain the difference using provenance.",
      model: "THEY AGREE that the settlement being drafted is severe. Source A says so directly by rejecting the charge of harshness rather than denying it — 'already we are told the terms are too harsh' — and Source B calls the peace 'too severe to be forgiven'. Both also agree that public opinion in the victorious countries was demanding punishment: A speaks for that opinion, and B describes 'the crowd' at home wanting 'the Kaiser hanged and Germany squeezed dry'.\n\nTHEY DISAGREE fundamentally about whether that severity is right and whether it will work. A's big message is that severity is justified and should go further — the damage to France and the losses at Verdun and the Somme entitle France to make Germany pay 'to the last franc'. B's big message is the opposite: the treaty is a botched compromise that will fail, being neither generous enough to reconcile Germany nor harsh enough to disable it, and will produce another war 'in twenty years'. A is looking backwards at what Germany owes; B is looking forwards at what the treaty will cause. A treats the three leaders' aims as a moral question; B treats them as an obstacle — 'a Frenchman who thinks of nothing but his frontier and an American who thinks of nothing but his League'.\n\nWHY THEY DIFFER — this is where the top marks are. The difference is explained almost entirely by provenance. Source A is a French newspaper editorial published while the terms were still being argued over; its purpose is to whip up and represent public support for Clemenceau's demands, and it is written for readers who had four years of war fought on their own soil. It is therefore not an attempt to assess the treaty but to defend it. Source B is a private diary, written for no audience at all, by an official watching the negotiations from the inside; with nothing to gain from the opinion he records, he can afford the doubt a newspaper could not print.\n\nJUDGEMENT: they agree on the fact of severity and on the state of public opinion, but they disagree on everything that matters — justification and consequences. Given their nature and purpose that disagreement is exactly what we would expect, and it is B, being private and free of an audience, that is the better guide to what informed people privately feared.",
    },
    {
      id: "ih10-20", topic: "7-source-skills",
      q: "SOURCE C — from a speech by an American senator to a public rally in Chicago, November 1948, during the Berlin airlift.\n\n'Three years ago we were told the war was over and the boys could come home. Tonight American pilots are flying coal into a city we took from Hitler, because one man in Moscow has decided to starve two million people into surrender. There is no line left to draw behind Berlin. Step back off that runway and we shall be asked next to step back from Vienna, and after that from Paris.'\n\nSOURCE D — from an article in a Soviet newspaper, September 1948.\n\n'The Western powers speak much of feeding Berlin. They say nothing of the new money they printed without consulting us, nothing of the three zones they welded into one without consulting us, nothing of the armies they now propose to gather under an American flag. Who has broken the agreements made at Potsdam? Not the Soviet Union. We have closed a road. They have divided a country.'\n\nHow far do these sources provide convincing evidence that the Soviet Union was to blame for the Berlin Blockade? Use the sources to explain your answer. [9]\n\n(Both sources were written for this pack in the style of Paper 2 and are not genuine documents. Treat the attributions as real.)",
      hint: "Group the sources for and against the statement, use provenance on BOTH, then judge how convincing the set is overall.",
      model: "EVIDENCE THAT SUPPORTS THE STATEMENT. Source C blames the USSR unambiguously: 'one man in Moscow has decided to starve two million people into surrender'. It presents the blockade as an aggressive act against civilians and as the opening move in a sequence of expansion — Berlin, then Vienna, then Paris. Source D, unintentionally, supports the statement too, because it concedes the central fact: 'We have closed a road.' The Soviet article does not deny the blockade; it only argues about who provoked it. That admission from a hostile source is the strongest single piece of evidence here, because a source is most convincing when it concedes something against its own interest.\n\nEVIDENCE AGAINST THE STATEMENT. Source D gives a coherent case that the West acted first: the currency reform introduced without Soviet agreement, the merging of the three Western zones, and the plan for a Western military alliance. My own knowledge confirms all three — the Deutsche Mark was introduced in the Western zones in June 1948, the zones had been merged, and NATO followed in April 1949 — so this is not invention. On that reading the blockade was a response to a unilateral Western decision to build a separate West German state, and the phrase 'They have divided a country' is a fair description of an outcome, whoever intended it.\n\nHOW CONVINCING ARE THEY? Neither source is disinterested, and both must be weighed by purpose. Source C is a political speech at a rally, designed to sustain American public support for an expensive airlift; its 'Vienna, then Paris' claim is rhetoric rather than evidence, and it says nothing at all about the currency reform — an omission that suits it. Source D is an article in a state-controlled Soviet newspaper published for domestic and bloc readers; its purpose is to justify a blockade already in progress, so its selectivity runs the other way — it never mentions that the road it closed was the supply line for two million civilians. Each source is therefore useful chiefly as evidence of what each side wanted its own public to believe.\n\nJUDGEMENT. Taken together the sources provide reasonably convincing evidence that the USSR was to blame for the blockade itself, because the Soviet source admits the act and offers only justification for it. They are much less convincing on the wider question of who was to blame for the crisis, since between them they show that the currency reform came first and the blockade second. Two openly propagandist sources from opposite sides cannot settle responsibility on their own; what they establish well is the fact of the blockade and the reasoning each government used, which is exactly what partisan sources are good for.",
    },
    {
      id: "ih10-21", topic: "7-source-skills",
      q: "SOURCE E — a poster issued by the East German government, October 1961, two months after the Berlin Wall was built.\n\nThe poster shows a smiling family — mother, father and two children — standing in front of a neat, freshly built wall. Behind the wall, on the western side, a fat man in a top hat labelled 'WALL STREET' holds a bag of money in one hand and a lighted torch in the other. The caption reads: 'Our wall of peace protects the workers' home.'\n\nHow useful is this source to a historian studying why the Berlin Wall was built? Explain your answer using details of the source and your knowledge. [7]\n\n(This source was written for this pack in the style of Paper 2 and is not a genuine document. Treat the attribution as real.)",
      hint: "'Useless because it is biased' is a bottom-band answer. Say what it is useless FOR and what it is strong evidence OF.",
      model: "WHAT IT IS NOT USEFUL FOR. It is worthless as a factual account of why the Wall went up. It shows the Wall as protection against a Western aggressor — the fat capitalist with the torch — and calls it a 'wall of peace' guarding a family. My own knowledge contradicts this directly: the Wall was built on 13 August 1961 to stop East Germans leaving, after around 2.7 million had crossed into West Berlin since 1949, many of them young and skilled workers whose loss was crippling the East German economy. The poster inverts the truth entirely, since the Wall's guns and guards faced inwards, not outwards.\n\nWHAT IT IS USEFUL FOR — and this carries the marks. It is excellent evidence of how the East German regime chose to justify the Wall to its own population, and of the propaganda techniques used. The details are the argument: labelling the capitalist 'WALL STREET' shifts the blame from Moscow to America; the money bag and the torch present the West as simultaneously greedy and violent, so the Wall becomes defensive; the smiling, orderly family and the neat wall make the barrier look protective and domestic rather than military; and the word 'peace' does the crucial work of renaming an imprisonment as a shield. Its usefulness is increased by its date — issued just two months after the event — so it captures the regime's immediate public line rather than a later reconstruction.\n\nWHAT LIMITS IT. It is a single official poster, so it tells us what the government said, not what East Germans believed; it cannot show whether the propaganda was accepted, and the fact that the regime needed to make this argument at all suggests the Wall required explaining.\n\nJUDGEMENT. As evidence of the real reasons the Wall was built it is useless; as evidence of the East German government's official justification and its methods of persuasion it is very useful indeed — and a historian studying why the Wall was built needs both the reason and the official story, so the source has real value once it is used for the right question.",
    },
    // ---- Topic 8: Germany depth study ----
    {
      id: "ih10-22", topic: "8-germany-depth",
      q: "Describe the problems faced by the Weimar Republic between 1919 and 1923. [4]",
      model: "1. It was blamed for the Treaty of Versailles: the politicians who signed were branded the 'November Criminals' and the stab-in-the-back myth held that the army had been betrayed rather than defeated.\n2. It faced armed revolt from the left — the Spartacist rising in Berlin in January 1919, crushed by the Freikorps — and from the right, the Kapp Putsch of March 1920, defeated by a general strike, and the Munich Putsch of 8–9 November 1923.\n3. French and Belgian troops occupied the Ruhr in January 1923 after a reparations default, and the government's policy of passive resistance stopped production in Germany's industrial heartland.\n4. Hyperinflation in 1923 destroyed the value of the mark and wiped out the savings of the middle class.\n\nA fifth point if you need one: proportional representation produced fragmented coalitions that made stable government almost impossible.",
    },
    {
      id: "ih10-23", topic: "8-germany-depth",
      q: "Explain why Hitler was able to become Chancellor of Germany in January 1933. [6]",
      model: "1. The Depression turned a fringe party into the largest in the Reichstag. The Wall Street Crash of October 1929 caused American loans to be recalled, and unemployment reached around six million by early 1933. The Nazi vote tracks that collapse exactly: 12 seats in May 1928, 107 in September 1930, and 230 in July 1932. Because Brüning's government cut spending and ruled by presidential decree under Article 48, parliamentary democracy had visibly stopped working before Hitler was anywhere near power.\n\n2. Nazi methods converted that desperation into votes. Goebbels' propaganda offered something to every group — work and bread to the unemployed, protection from communism to businessmen and the middle class, the destruction of Versailles to nationalists, and a scapegoat in the Jews and the 'November Criminals'. Hitler's speaking, the aeroplane campaign tours and the visible discipline of the SA made the party look like the strong government a frightened electorate wanted, while SA street violence against communists made the fear of revolution seem real.\n\n3. He was finally put in office by a political miscalculation rather than by an election. The Nazi vote actually FELL to 196 seats in November 1932. Von Papen, having lost the chancellorship to Schleicher and wanting it back, persuaded Hindenburg to appoint Hitler on 30 January 1933 with himself as Vice-Chancellor and only two other Nazis in the cabinet, believing the conservatives could 'box him in' and use his popular support. Because the old elites handed him the office, Hitler gained legal authority he had never won at the ballot box.\n\nThe point that earns the top band: the Nazis were never voted into power by a majority — they were appointed, and their highest free-election share was the 37.3% of July 1932.",
    },
    {
      id: "ih10-24", topic: "8-germany-depth",
      q: "'The Nazis controlled Germany between 1933 and 1939 mainly through terror.' How far do you agree with this statement? Explain your answer. [10]",
      model: "AGREE — terror was the foundation.\nThe machinery was built immediately: the decree following the Reichstag Fire of 27 February 1933 suspended civil rights and allowed arrest without trial; Dachau opened in March 1933; the Gestapo, the SS under Himmler and the SD ran a system in which denunciation by a neighbour could mean a camp. Political opponents were removed within months — the KPD and SPD destroyed, trade unions abolished in May 1933, all other parties banned by July 1933 — and the Night of the Long Knives on 30 June 1934 showed that even senior Nazis such as Röhm were not safe. The People's Court handed down death sentences for political offences. The most telling evidence for terror is how little open opposition there was: what existed came from small groups such as the Edelweiss Pirates, the Swing Youth and later the White Rose, whose members the Scholls were executed in February 1943, precisely because open dissent was suicidal.\n\nDISAGREE — persuasion and consent mattered as much.\nGoebbels' propaganda ministry controlled press, radio, film and the arts, and cheap 'people's receivers' put the regime's voice in most homes, while the Nuremberg rallies manufactured a sense of national revival. Education, the Hitler Youth and the League of German Maidens shaped the next generation from childhood. Alongside that ran real material improvement: unemployment fell dramatically through rearmament, the National Labour Service, the autobahns and the Four-Year Plan of 1936, and Strength Through Joy offered holidays and leisure ordinary workers had never had. Many Germans also welcomed the foreign-policy successes — the Saar in 1935, the Rhineland in 1936, the Anschluss in 1938 — as the reversal of a humiliation. Much of the population supported the regime without needing to be frightened into it.\n\nJUDGEMENT.\nTerror and persuasion cannot be separated, but terror was the more fundamental because it made persuasion possible. Propaganda worked partly because there was no alternative voice, and the alternative voices had been silenced by force; the apparent popularity of the regime cannot be measured honestly in a state where dissent was fatal. It is also worth noting that the unemployment figures excluded Jews, women and conscripts, so some of the 'consent' rested on claims that were themselves propaganda. The most accurate answer is that most Germans in the 1930s did not experience the regime as terror — they experienced work, order and national pride — but that this was only possible because the minority who objected had already been removed by it.",
    },
  ],

  mistakes: [
    { mistake: "Telling the story instead of explaining the cause — a (b) 'Explain why…' answer that narrates what happened next.", fix: "Every paragraph must contain the word 'because'. Build each reason as 'X happened because … which meant … so …'. Three developed reasons beat ten narrated facts every time." },
    { mistake: "Finishing a (c) 'How far do you agree' answer without ever answering it.", fix: "Two sides is only the middle band. The final paragraph must decide, and say WHY it decides — 'X was more important than Y because…'. No judgement, no top band, however good the two sides were." },
    { mistake: "Describing what a source says instead of evaluating it.", fix: "Content alone is worth almost nothing. Run NOP on every source — Nature, Origin, Purpose — and ask 'who wrote this, when, for whom, and what did they want the reader to do?' before you write a word about what it says." },
    { mistake: "Writing 'this source is biased so it is useless'.", fix: "Bias is the evidence, not the disqualification. Say what the source is useless FOR (facts) and what it is strong evidence OF (attitudes, propaganda methods, what a government wanted believed)." },
    { mistake: "Muddling the 1919–23 treaties — putting Trianon on Austria or Neuilly on Hungary.", fix: "Learn the five as a table: Versailles–Germany · Saint-Germain–Austria · Neuilly–Bulgaria · Trianon–Hungary · Sèvres–Turkey, replaced by Lausanne 1923. Name the wrong one and the whole point is lost." },
    { mistake: "Vague dating — 'in the 1930s', 'after the war', 'later on'.", fix: "Give the month and year for every key event. 7 March 1936, 12 March 1938, 29–30 September 1938, 23 August 1939. Examiners read precise dates as evidence of secure knowledge; vague ones as evidence of the opposite." },
    { mistake: "Comparing two sources by listing what each one says in turn.", fix: "Cross-referencing means comparing the BIG MESSAGE of both, then the details, then explaining the difference using provenance. A paragraph on Source A followed by a paragraph on Source B is not a comparison." },
    { mistake: "Writing everything you know about a topic because it came up, regardless of the actual question.", fix: "Underline the command word and the focus of the question before writing. A brilliant essay on the causes of the Berlin Blockade earns nothing on a question about its consequences." },
    { mistake: "Confusing Yalta with Potsdam, or getting the participants wrong.", fix: "Yalta = February 1945 = Roosevelt, Churchill, Stalin = agreement. Potsdam = July–August 1945 = Truman and (partway through) Attlee = disagreement. Roosevelt died on 12 April 1945, between the two." },
    { mistake: "Claiming the Nazis were 'voted into power' or 'won the 1933 election'.", fix: "Their best free-election result was 37.3% in July 1932, and it fell in November 1932. Hitler was APPOINTED Chancellor on 30 January 1933 by Hindenburg on von Papen's advice, and even the 5 March 1933 election gave only 43.9%." },
    { mistake: "Treating the League of Nations as a total failure and never mentioning what it achieved.", fix: "'To what extent…' demands both sides. The Aaland Islands, Greece and Bulgaria in 1925, and the refugee, health, ILO and anti-slavery work are the success case; Vilna, Corfu, Manchuria and Abyssinia are the failure case." },
    { mistake: "Spending equal time on all three parts of a Paper 1 question.", fix: "The marks are 4, 6 and 10. Budget roughly 5, 8 and 15 minutes of a 40-minute question. Four sentences is a complete (a) — writing a page on it is where the (c) marks go to die." },
  ],

  cheat: [
    {
      heading: "Timeline 1: peace to war, 1919–1939",
      bullets: [
        "28 June 1919 Treaty of Versailles signed · 10 Sept 1919 Saint-Germain (Austria) · 27 Nov 1919 Neuilly (Bulgaria) · 4 June 1920 Trianon (Hungary) · 10 Aug 1920 Sèvres (Turkey) → 24 July 1923 Lausanne.",
        "10 Jan 1920 League of Nations begins · 1920 Vilna · 1920–21 Aaland Islands · 1923 Corfu · 1925 Greece–Bulgaria · 1926 Germany joins · 1934 USSR joins.",
        "Jan 1923 Ruhr occupation and German hyperinflation · Oct 1929 Wall Street Crash · 18 Sept 1931 Mukden Incident, Manchuria.",
        "Jan 1933 Hitler Chancellor · Oct 1933 Germany leaves the Disarmament Conference and the League · Jan 1934 German–Polish pact.",
        "Jan 1935 Saar plebiscite · March 1935 conscription announced · June 1935 Anglo-German Naval Agreement · 3 Oct 1935 Italy invades Abyssinia · Dec 1935 Hoare–Laval Pact leaked.",
        "7 March 1936 Rhineland remilitarised · Oct 1936 Rome–Berlin Axis · Nov 1936 Anti-Comintern Pact · 1936–39 Spanish Civil War.",
        "12 March 1938 Anschluss · 29–30 Sept 1938 Munich Agreement · 15 March 1939 rest of Czechoslovakia taken · 31 March 1939 guarantee to Poland · 23 Aug 1939 Nazi–Soviet Pact · 1 Sept 1939 Poland invaded · 3 Sept 1939 Britain and France declare war.",
      ],
    },
    {
      heading: "Timeline 2: the Cold War, 1945–1991",
      bullets: [
        "Feb 1945 Yalta · 12 April 1945 Roosevelt dies · July–Aug 1945 Potsdam · 6 and 9 Aug 1945 Hiroshima and Nagasaki · 5 March 1946 Fulton 'iron curtain' speech.",
        "12 March 1947 Truman Doctrine · 5 June 1947 Marshall Plan announced · Sept 1947 Cominform · Feb 1948 Czechoslovak coup.",
        "24 June 1948 Berlin Blockade begins · 12 May 1949 blockade lifted · 4 April 1949 NATO founded · 1949 Comecon; FRG (May) and GDR (Oct) created.",
        "25 June 1950 Korean War begins · 15 Sept 1950 Inchon · Oct 1950 China intervenes · April 1951 MacArthur sacked · 27 July 1953 armistice.",
        "14 May 1955 Warsaw Pact · Oct–4 Nov 1956 Hungarian Rising · Jan 1959 Castro takes power · 13 Aug 1961 Berlin Wall built · April 1961 Bay of Pigs.",
        "14–28 Oct 1962 Cuban Missile Crisis · 1963 hotline and Partial Test Ban Treaty · Aug 1964 Gulf of Tonkin · March 1965 Rolling Thunder and first US combat troops.",
        "Jan 1968 Tet Offensive · March 1968 My Lai · 20–21 Aug 1968 invasion of Czechoslovakia · Jan 1973 ceasefire · 30 April 1975 Saigon falls.",
        "Aug 1980 Gdańsk strike, Solidarity founded · 13 Dec 1981 martial law in Poland · March 1985 Gorbachev · June 1989 Polish elections · 9 Nov 1989 Wall opened · 3 Oct 1990 German reunification · July 1991 Warsaw Pact dissolved.",
      ],
    },
    {
      heading: "The five treaties at a glance — never muddle these",
      bullets: [
        "VERSAILLES (Germany, 28 June 1919): Article 231 war guilt · £6,600m reparations fixed 1921 · army 100,000, no conscription/tanks/submarines/air force, navy 6 battleships · Rhineland demilitarised, occupied 15 years · Alsace-Lorraine to France, Saar to the League for 15 years, Polish Corridor, Danzig a Free City, colonies became mandates · Anschluss forbidden.",
        "SAINT-GERMAIN (Austria, 10 Sept 1919): Austria–Hungary broken up · land to Czechoslovakia, Yugoslavia, Poland and Italy · army 30,000 · Anschluss forbidden.",
        "NEUILLY (Bulgaria, 27 Nov 1919): western Thrace to Greece, so Bulgaria lost its Aegean coastline · land to Yugoslavia and Romania · army 20,000.",
        "TRIANON (Hungary, 4 June 1920): Transylvania to Romania, Slovakia and Ruthenia to Czechoslovakia, Croatia and Slovenia to Yugoslavia · about two-thirds of its territory lost · army 35,000.",
        "SÈVRES (Turkey, 10 Aug 1920): Ottoman Empire dismantled, Smyrna to Greece, the Straits internationalised · rejected by Mustafa Kemal's nationalists.",
        "LAUSANNE (Turkey, 24 July 1923): replaced Sèvres, returning Smyrna and eastern Thrace to Turkey — the one part of the settlement successfully overturned.",
      ],
    },
    {
      heading: "The League: structure, powers, membership",
      bullets: [
        "Assembly — every member, met once a year, decisions had to be UNANIMOUS. Council — Britain, France, Italy and Japan as permanent members, each with a VETO, plus temporary members.",
        "Also: the Secretariat (civil service), the Permanent Court of International Justice at The Hague, the International Labour Organisation, and commissions for refugees, health, slavery and mandates.",
        "Three weapons, in escalating order: moral condemnation · economic sanctions · collective military force. The League had NO army of its own, so the third depended entirely on members volunteering troops.",
        "Never joined: the USA (Senate rejected the Treaty). Joined late: Germany 1926, USSR 1934. Left: Japan 1933, Germany 1933, Italy 1937; the USSR was expelled in 1939.",
        "Successes: Aaland Islands 1920–21 · Greece ordered out of Bulgaria 1925 · refugees and Nansen passports · health campaigns · ILO · anti-slavery work.",
        "Failures: Vilna 1920 · Corfu 1923 · Manchuria 1931–33 · Abyssinia 1935–36. The pattern in every one: a great power broke the rules and nobody was willing to pay the price of stopping it.",
      ],
    },
    {
      heading: "Source evaluation — the framework that earns the marks",
      bullets: [
        "NOP on every source. NATURE: speech, private letter, diary, cartoon, poster, memoir, official report, photograph — each has a different relationship to the truth. ORIGIN: who wrote it, when, and what were they actually in a position to know? PURPOSE: who was it for, and what was it meant to make them think or do?",
        "Date does heavy lifting. A source written during an event, one written the week after, and a memoir written thirty years later are three different kinds of evidence — hindsight, self-justification and immediacy all leave marks.",
        "Audience does the rest. A rally speech persuades. A private diary has no one to persuade. A state newspaper serves the state. A memoir often defends a reputation.",
        "Reliability ≠ usefulness. Every source is reliable evidence of SOMETHING — at minimum, of what its author wanted believed. Say what it is useless for and what it is strong evidence of.",
        "Cross-reference by BIG MESSAGE first, then detail, then explain the difference by provenance — different nationality, date, job, or audience.",
        "Cartoons and posters: country and date → decode every label, symbol and caption → state the big message in one sentence → ask why it was published at that moment.",
        "A source that concedes something against its own side's interest is unusually convincing. Say so when you spot one — it is a top-band observation.",
      ],
    },
    {
      heading: "Paper 2 — the five parts and what each actually wants",
      bullets: [
        "One question, one prescribed Core topic, up to seven sources, five parts, 40 marks, 1 hour 45 minutes. The parts are NOT equal — they run roughly 7–9 marks each, so check the mark next to each part and budget accordingly.",
        "'How far do these two sources agree?' — compare the big messages, not the details. State where they agree, where they differ, and explain the difference through provenance.",
        "'Why was this source published at this time?' — purpose in context. Answer with the author's intention plus the events of that exact month, not with a summary of the content.",
        "'Does Source X make Source Y surprising?' / 'Does Source X prove Source Y right?' — set the two against each other, then use provenance and your own knowledge to decide whether the clash is genuinely surprising or exactly what you would expect from those two authors.",
        "'How useful is this source to a historian studying…?' — useful for what, limited for what, and why the provenance makes it so. Never 'biased, therefore useless'.",
        "'How far do these sources provide convincing evidence that…?' — the big one. Group sources FOR and AGAINST by letter, use content AND provenance in both groups, then judge how convincing the set is overall and which sources you trust more.",
        "Reference every source by its letter. An unreferenced point cannot be credited.",
      ],
    },
    {
      heading: "Essay templates — write to the mark allocation",
      bullets: [
        "(a) DESCRIBE, 4 marks, ~5 minutes: four short factual sentences, one per mark. No reasons, no analysis, no introduction. Number them in your head as you write.",
        "(b) EXPLAIN WHY, 6 marks, ~8 minutes: three paragraphs, one reason each. Formula per paragraph — 'One reason was X. This mattered because … which meant … so …'. Support each with a specific fact or date.",
        "(c) HOW FAR / TO WHAT EXTENT, 10 marks, ~15 minutes: paragraph 1 AGREE with evidence; paragraph 2 DISAGREE with evidence; paragraph 3 JUDGEMENT that decides and justifies. Aim for two or three supported points on each side.",
        "The (c) judgement sentence stems that work: 'X was the more important because…' · 'While Y contributed, it only mattered because of X…' · 'The statement is true of the short term but not the long term, because…'",
        "Paper 4 (Alternative to Coursework) is a depth-study question in two parts: (a) an account describing the main features of the event, and (b) a discussion of the IMPORTANCE of a person, organisation, development or event — importance from different angles, then a judgement.",
        "Timing: Paper 1 is 2 hours for three questions — 40 minutes each, and stop when the time is up even mid-sentence. Two good answers and one unfinished one always beats two finished ones and a blank.",
      ],
    },
    {
      heading: "Containment scorecard and Eastern Europe compared",
      bullets: [
        "KOREA 1950–53: aim, stop the spread. Outcome, the border returned to the 38th parallel and South Korea stayed non-communist. Verdict — containment succeeded, rollback failed.",
        "CUBA 1959–62: aim, remove or isolate Castro. Outcome, the embargo, Bay of Pigs and missile crisis all left Cuba communist, though the missiles were removed. Verdict — containment failed, crisis management succeeded.",
        "VIETNAM 1955–75: aim, prevent a communist South. Outcome, Saigon fell on 30 April 1975 and Vietnam was unified under communism. Verdict — containment failed outright.",
        "HUNGARY 1956 vs CZECHOSLOVAKIA 1968 — similar: reform leader, popular support, no Western help, crushed by Soviet tanks, leader removed.",
        "Different: Hungary saw armed street fighting, around 3,000 deaths and a bid to LEAVE the Warsaw Pact; Czechoslovakia was a party-led reform that promised to STAY in the Pact and met the invasion with passive resistance.",
        "Why 1989 ended differently: Gorbachev abandoned the Brezhnev Doctrine, so the threat that had held the bloc together since 1968 was gone.",
      ],
    },
    {
      heading: "Germany 1918–45 — the depth-study spine",
      bullets: [
        "3 Nov 1918 Kiel mutiny · 9 Nov 1918 Kaiser abdicates · 11 Nov 1918 Armistice · Jan 1919 Spartacist rising · Aug 1919 Weimar Constitution (proportional representation, Article 48) · March 1920 Kapp Putsch.",
        "Jan 1923 Ruhr occupation and hyperinflation · Nov 1923 Rentenmark and the Munich Putsch (8–9 Nov) · 1924 Dawes Plan · 1925 Locarno · 1926 League membership · 1929 Young Plan · Oct 1929 Stresemann dies and the Wall Street Crash.",
        "Nazi Reichstag seats: 12 (May 1928) → 107 (Sept 1930) → 230 and largest party, 37.3% (July 1932) → 196 (Nov 1932) → 288, 43.9% (March 1933). They never won a free majority.",
        "30 Jan 1933 Hitler appointed Chancellor · 27 Feb 1933 Reichstag Fire and the decree that followed · 23 March 1933 Enabling Act · May 1933 unions banned · July 1933 all other parties banned · 30 June 1934 Night of the Long Knives · 2 Aug 1934 Hindenburg dies, Hitler becomes Führer.",
        "Control: Goebbels' propaganda ministry, radio and rallies · SS, Gestapo, SD, camps from Dachau (March 1933) · Hitler Youth and the BDM · 'Kinder, Küche, Kirche' and marriage loans · rearmament, the RAD, autobahns and the Four-Year Plan of 1936 (the unemployment figures excluded Jews, women and conscripts).",
        "Opposition: Niemöller and the Confessional Church · Galen against euthanasia · Edelweiss Pirates and Swing Youth · the White Rose (the Scholls executed Feb 1943) · the July Bomb Plot of 20 July 1944.",
        "Persecution: April 1933 boycott · Sept 1935 Nuremberg Laws · 9–10 Nov 1938 Kristallnacht · 20 Jan 1942 Wannsee Conference and the Final Solution · about six million Jews murdered.",
      ],
    },
    {
      heading: "Exam-day moves",
      bullets: [
        "Underline the command word (describe / explain why / how far) and the focus before you write anything. Then answer THAT.",
        "Every paragraph in a (b) or (c) needs at least one specific date, name or figure. Precision is what separates the top two bands from the middle.",
        "In a (c), write the judgement paragraph even if you are running out of time — three lines of judgement is worth more than another page of description.",
        "In Paper 2, quote or cite a source letter in every single point. Unreferenced assertions cannot be credited.",
        "If a source question offers you a chance to say WHY two sources differ, take it. Provenance explanations are where the marks live.",
        "Deliberately omitted from this pack: casualty figures, vote percentages and treaty clauses we could not verify with confidence, and the four depth studies this school may not teach. If a detail is not here, check your own syllabus copy and textbook before quoting it in an exam.",
      ],
    },
  ],
};
