import "server-only";
/** Receipt-backed private snapshot from the 2 October record and 4 October mailbox audit, plus the verified 8 October follow-up.
 * Dates below are record dates where a form timestamp was not independently captured.
 * Sent Items does not establish delivery. Requests and replies are not awards.
 */
export const SUPPORT_SNAPSHOT = [
  { organization: "Vercel", channel: "email", status: "sent", contribution: "Hosting sponsorship and open-source program eligibility guidance", evidence: "2 October outreach-status record: verified non-draft Outlook message to sponsorships@vercel.com, subject Vidya: hosting sponsorship and OSS program eligibility, sent 1 October 2026 20:01:25 UTC. Not proof of delivery or approval.", occurredOn: "2026-10-02", nextAction: "Prepare a costed OSS request. Do not resend the existing message.", expiry: null, amount: null, currency: null },
  { organization: "Clerk", channel: "email", status: "sent", contribution: "Onboarding guidance and project-support routing", evidence: "2 October outreach-status record: verified non-draft Outlook message to support@clerk.com, subject Vidya: onboarding guidance and routing for project support, sent 1 October 2026 20:01:26 UTC. Not proof of delivery or approval.", occurredOn: "2026-10-02", nextAction: "Existing support reply points to startup eligibility review; Enterprise migration help is not a grant. No award recorded.", expiry: null, amount: null, currency: null },
  { organization: "Clerk", channel: "email", status: "sent", contribution: "Follow-up on solo bootstrapped eligibility, launch-date meaning and alternatives", evidence: "2 October outreach-status record: reply API confirmed follow-up sending. 4 October mailbox audit retained three total Vidya sent emails and read the latest Jordan reply. No donated feature or credit approval established.", occurredOn: "2026-10-02", nextAction: "Continue the existing support thread with specific Google sign-in, recovery, branding and subdomain requirements. Do not promise free-for-life vendor support.", expiry: null, amount: null, currency: null },
  { organization: "xAI", channel: "form", status: "submitted", contribution: "Capped API credits, mentorship or referral inquiry", evidence: "2 October outreach-status record: x.ai/contact-sales confirmation, Thank you for reaching out! A member of our sales team will be in touch shortly. Screenshot xai-submission-confirmation.jpg recorded. Exact form submission time not captured; this is the record date.", occurredOn: "2026-10-02", nextAction: "Wait for inquiry response. No credit award or eligibility approval documented.", expiry: null, amount: null, currency: null },
  { organization: "Neon", channel: "form", status: "submitted", contribution: "Open-source database program review", evidence: "2 October outreach-status record: neon.com/programs/open-source receipt, We've received your application and will be in touch soon. Screenshot neon-submission-confirmation.jpg recorded. Exact submission time not captured; this is the record date.", occurredOn: "2026-10-02", nextAction: "Track existing application and document compute, storage and backup requirements. No award recorded.", expiry: null, amount: null, currency: null },
  { organization: "GitHub", channel: "form", status: "submitted", contribution: "Maintainer-support eligibility guidance for Copilot, Actions and development resources", evidence: "2 October outreach-status record: github.com/enterprise/contact confirmation Thanks for your message! Reference 98ece9344ee1e612e7090dd670f7792a9f180a5fcde5cfee169e169dc7e9ed4b and github-submission-confirmation.jpg retained. Record date, not independently captured submission time.", occurredOn: "2026-10-02", nextAction: "Prepare costed maintainer request. Enterprise contact does not establish Sponsors enrollment or approval.", expiry: null, amount: null, currency: null },
  { organization: "Clerk", channel: "email", status: "sent", contribution: "Donated paid features or renewable credits; Google Hobby production OAuth, recovery, branded authentication and cross-subdomain sessions", evidence: "8 October 2026 04:39:45 IST authorized reply; verified non-draft Sent Items message at 7 October 2026 23:09:46 UTC to support@clerk.com, subject RE: Vidya: onboarding guidance and routing for project support. Sending does not establish delivery, contract, credits or an award.", occurredOn: "2026-10-08", nextAction: "Wait for the existing thread response. Clarify exact Google OAuth and long-term support requirements; no purchase or award recorded.", expiry: null, amount: null, currency: null },
] as const;
