"use client";
import Image from "next/image";
import { useCallback, useEffect, useRef, useState } from "react";
import type { LearnerProfile } from "@/lib/types";
import type { CreationProject } from "@/lib/creation/project";
import { CIRCLE_REACTIONS, CIRCLE_REPORT_REASONS, type CircleCard, type CircleSummary } from "@/lib/circles/contract";
const reactions = { interesting: "Interesting!", creative: "Creative idea", "good-effort": "Nice effort" };
export function LearnerCircles({ learner, projects = [] }: { learner: LearnerProfile; projects?: CreationProject[] }) {
  const [circles, setCircles] = useState<CircleSummary[]>([]); const [cards, setCards] = useState<CircleCard[]>([]); const [projectId, setProjectId] = useState(projects[0]?.id ?? ""); const [status, setStatus] = useState(""); const [busy, setBusy] = useState(false); const [reason, setReason] = useState<typeof CIRCLE_REPORT_REASONS[number]>("other-concern");
  const headers = useCallback((): Record<string, string> => learner.deviceToken ? { "x-vidya-device": learner.deviceToken } : {}, [learner.deviceToken]);
  const requestSequence = useRef(0);
  const refresh = useCallback(async () => {
    const sequence = ++requestSequence.current;
    if (!learner.remoteId) return;
    try { const response = await fetch("/api/circles/learner", { headers: headers(), cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error); if (sequence !== requestSequence.current) return; setCircles(data.circles); setCards(data.cards); }
    catch (error) { if (sequence === requestSequence.current) setStatus(error instanceof Error ? error.message : "Private circles could not load."); }
  }, [learner.remoteId, headers]);
  useEffect(() => { setCircles([]); setCards([]); void refresh(); const requests = requestSequence; return () => { requests.current++; }; }, [refresh]);
  async function action(payload: unknown) {
    if (busy) return; setBusy(true);
    try { const response = await fetch("/api/circles/learner", { method: "POST", headers: { ...headers(), "content-type": "application/json" }, body: JSON.stringify(payload), cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setStatus("Updated your circle."); await refresh(); }
    catch (error) { setStatus(error instanceof Error ? error.message : "This action could not finish."); }
    finally { setBusy(false); }
  }
  return <section className="glass-card p-4"><h2 className="font-display text-xl font-bold">Your private circles</h2><p className="text-sm mt-2" style={{ color: "var(--text-muted)" }}>Share a little of what you made, when you choose. Both families approve the circle. Your parent checks a project card before your friend sees it.</p>
    {!circles.some((circle) => circle.status === "active") && <p className="text-sm mt-3">Ask a parent to invite a family you know. You can keep creating on your own.</p>}
    {circles.filter((circle) => circle.status === "active").map((circle) => <div key={circle.id} className="rounded-xl p-3 mt-4" style={{ border: "1px solid var(--border)" }}><h3 className="font-bold">You and {circle.friendAlias}</h3><p className="text-xs mt-1">Your circle nickname: {circle.alias}</p>{projects.length > 0 && <div className="mt-3"><label className="text-sm">Choose a creation<select value={projectId} onChange={(event) => setProjectId(event.target.value)} className="block w-full min-h-11 px-2 mt-1 rounded-lg" style={{ background: "var(--surface)", color: "var(--text)", border: "1px solid var(--border)" }}>{projects.map((project) => <option key={project.id} value={project.id}>{project.title}</option>)}</select></label><p className="text-xs mt-2">Share the title and first picture only. This asks your parent to approve that card.</p><button className="min-h-11 font-bold" disabled={busy || !projectId} onClick={() => void action({ action: "share", circleId: circle.id, projectId })}>Ask to share this card</button></div>}<div className="flex gap-4 flex-wrap mt-3"><button disabled={busy} className="min-h-11" onClick={() => void action({ action: "leave", circleId: circle.id })}>Leave circle</button><button disabled={busy} className="min-h-11" onClick={() => void action({ action: "block", circleId: circle.id })}>Block circle</button></div><details className="mt-2"><summary className="min-h-11">Report a concern</summary><label className="text-sm">What is bothering you?<select value={reason} onChange={(event) => setReason(event.target.value as typeof reason)} className="block w-full min-h-11 mt-2" style={{ background: "var(--surface)", color: "var(--text)" }}>{CIRCLE_REPORT_REASONS.map((value) => <option key={value} value={value}>{value.replaceAll("-", " ")}</option>)}</select></label><p className="text-xs mt-2">Reporting blocks this circle immediately. Please also tell a trusted adult.</p><button className="min-h-11 font-bold" disabled={busy} onClick={() => void action({ action: "report", circleId: circle.id, reason })}>Report and block</button></details></div>)}
    <div className="grid sm:grid-cols-2 gap-3 mt-4">{cards.map((card) => <article key={card.id} className="p-3 rounded-xl" style={{ border: "1px solid var(--border)" }}><p className="text-xs">{card.alias}{card.status === "pending" ? " · waiting for your parent's approval" : ""}</p><h3 className="font-bold mt-1">{card.title}</h3><Image unoptimized width={720} height={480} alt={card.title} className="w-full rounded-lg mt-2" src={`data:image/svg+xml;charset=utf-8,${encodeURIComponent(card.svg)}`} />{card.own && <button className="min-h-11 text-sm font-bold" disabled={busy} onClick={() => void action({ action: "unshare", cardId: card.id })}>Stop sharing this card</button>}{card.status === "approved" && <div className="flex flex-wrap gap-2 mt-2">{CIRCLE_REACTIONS.map((reaction) => <button key={reaction} className="text-xs rounded-lg min-h-11 px-2" disabled={busy} onClick={() => void action({ action: "react", cardId: card.id, reaction })} style={{ background: "var(--accent-soft)" }}>{reactions[reaction]} {card.reactions.find((item) => item.reaction === reaction)?.count || ""}</button>)}</div>}</article>)}</div><p role="status" className="text-sm mt-3">{status}</p>
  </section>;
}
