import type { Topic, SubjectId } from "../../types";

export const QUESTIONS: Partial<Record<SubjectId, Record<string, Topic>>> = {
  maths: {
    "place-value": {
      title: "Place Value & Negatives",
      icon: "🔢",
      items: [
        { q: "What is the value of the digit 7 in 4,786,231?", a: "700,000", opts: ["7,000", "70,000", "700,000", "7,000,000"], ex: "The 7 sits in the hundred-thousands place, so its value is 700,000." },
        { q: "Which is colder: -5°C or -12°C?", a: "-12°C", opts: ["-5°C", "-12°C", "They are equal", "Cannot tell"], ex: "On a number line, -12 is further left of zero than -5, so it's colder." },
        { q: "Round 47,892 to the nearest hundred.", a: "47,900", opts: ["47,800", "47,890", "47,900", "48,000"], ex: "The tens digit is 9, so we round up. 47,892 → 47,900." },
        { q: "Order from smallest to largest: -3, 5, -7, 0, 2", a: "-7, -3, 0, 2, 5", opts: ["-3, -7, 0, 2, 5", "-7, -3, 0, 2, 5", "0, -3, -7, 2, 5", "5, 2, 0, -3, -7"], ex: "Negative numbers come first, most negative leading the line." },
        { q: "What is 1,000,000 written in words?", a: "One million", opts: ["One thousand", "One hundred thousand", "One million", "Ten million"], ex: "1,000,000 = one million." },
        { q: "Temperature rises from -8°C to 3°C. By how much did it rise?", a: "11°C", opts: ["5°C", "11°C", "-5°C", "-11°C"], ex: "From -8 to 0 is 8, then 0 to 3 is 3. Total = 11°C." },
        { q: "Which is greatest: 235,478 or 235,748?", a: "235,748", opts: ["235,478", "235,748", "Equal", "Cannot compare"], ex: "Compare digits from left. The hundreds digit 7 beats 4." },
        { q: "Round 2,549 to the nearest thousand.", a: "3,000", opts: ["2,000", "2,500", "3,000", "2,550"], ex: "Hundreds digit is 5, so round up to 3,000." },
      ],
    },
    "fractions-decimals": {
      title: "Fractions, Decimals & %",
      icon: "🍕",
      items: [
        { q: "What is 3/4 as a decimal?", a: "0.75", opts: ["0.34", "0.43", "0.75", "0.34"], ex: "3 ÷ 4 = 0.75." },
        { q: "Which is bigger: 0.6 or 3/5?", a: "They are equal", opts: ["0.6", "3/5", "They are equal", "Cannot tell"], ex: "3/5 = 6/10 = 0.6, so they match." },
        { q: "What is 25% of 80?", a: "20", opts: ["15", "20", "25", "40"], ex: "25% = 1/4. A quarter of 80 = 20." },
        { q: "0.4 + 0.35 = ?", a: "0.75", opts: ["0.39", "0.75", "0.39", "0.45"], ex: "Line up the decimals: 0.40 + 0.35 = 0.75." },
        { q: "1/2 + 1/4 = ?", a: "3/4", opts: ["2/6", "1/3", "3/4", "2/4"], ex: "Same denominator: 2/4 + 1/4 = 3/4." },
        { q: "Express 0.7 as a fraction.", a: "7/10", opts: ["7/100", "7/10", "70/100", "1/7"], ex: "0.7 means 7 tenths = 7/10." },
        { q: "A pizza has 8 slices. You eat 3. What fraction is left?", a: "5/8", opts: ["3/8", "5/8", "1/2", "3/5"], ex: "8 - 3 = 5 slices left out of 8 = 5/8." },
        { q: "What is 10% of 250?", a: "25", opts: ["10", "25", "50", "100"], ex: "10% = 1/10. 250 ÷ 10 = 25." },
      ],
    },
    "multiplication-division": {
      title: "Multiplication & Division",
      icon: "✖️",
      items: [
        { q: "24 × 15 = ?", a: "360", opts: ["240", "320", "360", "390"], ex: "24 × 10 = 240, 24 × 5 = 120, total 360." },
        { q: "348 ÷ 6 = ?", a: "58", opts: ["48", "56", "58", "62"], ex: "6 × 58 = 348." },
        { q: "A box has 24 pencils. How many in 17 boxes?", a: "408", opts: ["288", "388", "408", "428"], ex: "24 × 17 = 240 + 168 = 408." },
        { q: "12² (12 squared) = ?", a: "144", opts: ["24", "100", "121", "144"], ex: "12 × 12 = 144." },
        { q: "Find all the factors of 12.", a: "1, 2, 3, 4, 6, 12", opts: ["1, 2, 3, 12", "2, 3, 4, 6", "1, 2, 3, 4, 6, 12", "1, 12"], ex: "Numbers that divide 12 exactly." },
        { q: "Next multiple of 7 after 35?", a: "42", opts: ["36", "40", "42", "49"], ex: "7 × 5 = 35, 7 × 6 = 42." },
        { q: "126 ÷ 9 = ?", a: "14", opts: ["12", "13", "14", "16"], ex: "9 × 14 = 126." },
        { q: "Product of 8 and 9?", a: "72", opts: ["63", "64", "72", "81"], ex: "8 × 9 = 72." },
      ],
    },
    geometry: {
      title: "Geometry & Shapes",
      icon: "🔷",
      items: [
        { q: "Sum of angles inside a triangle?", a: "180°", opts: ["90°", "180°", "270°", "360°"], ex: "All triangles have interior angles summing to 180°." },
        { q: "How many lines of symmetry does a square have?", a: "4", opts: ["1", "2", "4", "8"], ex: "2 diagonal + 2 straight = 4 lines of symmetry." },
        { q: "A 3D shape with 6 equal square faces?", a: "Cube", opts: ["Cuboid", "Cube", "Cylinder", "Pyramid"], ex: "Cubes have 6 identical square faces." },
        { q: "An angle of exactly 90° is called?", a: "Right angle", opts: ["Acute", "Right angle", "Obtuse", "Straight"], ex: "Right angle is like the corner of a book." },
        { q: "Faces on a cuboid?", a: "6", opts: ["4", "5", "6", "8"], ex: "Top, bottom, front, back, left, right." },
        { q: "Angle between 90° and 180°?", a: "Obtuse", opts: ["Acute", "Right", "Obtuse", "Reflex"], ex: "Obtuse = larger than right, less than straight." },
        { q: "Triangle with all sides equal?", a: "Equilateral", opts: ["Scalene", "Isosceles", "Equilateral", "Right-angled"], ex: "Equi (equal) + lateral (sides)." },
        { q: "Vertices on a triangular pyramid?", a: "4", opts: ["3", "4", "5", "6"], ex: "Tetrahedron has 4 corners." },
      ],
    },
    measurement: {
      title: "Measurement & Time",
      icon: "📏",
      items: [
        { q: "Area of rectangle 8m by 5m?", a: "40 m²", opts: ["13 m²", "26 m²", "40 m²", "80 m²"], ex: "Area = length × width = 8 × 5 = 40 m²." },
        { q: "Perimeter of a square with side 7 cm?", a: "28 cm", opts: ["14 cm", "21 cm", "28 cm", "49 cm"], ex: "4 × 7 = 28 cm." },
        { q: "How many ml in 2.5 litres?", a: "2500 ml", opts: ["25", "250", "2500", "25000"], ex: "1 L = 1000 ml, 2.5 × 1000 = 2500 ml." },
        { q: "Convert 14:35 to 12-hour clock.", a: "2:35 PM", opts: ["2:35 AM", "2:35 PM", "4:35 PM", "1:35 PM"], ex: "14:35 - 12 = 2:35 PM." },
        { q: "Minutes in 2.5 hours?", a: "150", opts: ["120", "125", "150", "180"], ex: "120 + 30 = 150 minutes." },
        { q: "Area of square with side 9 cm?", a: "81 cm²", opts: ["18", "36", "72", "81"], ex: "9 × 9 = 81 cm²." },
        { q: "1 kg = how many grams?", a: "1000 g", opts: ["10", "100", "1000", "10000"], ex: "1 kilogram = 1000 grams." },
        { q: "Movie starts 7:45 PM, runs 1 hr 30 min. End time?", a: "9:15 PM", opts: ["8:45 PM", "9:15 PM", "9:00 PM", "9:30 PM"], ex: "7:45 + 1:00 = 8:45, then +30 = 9:15 PM." },
      ],
    },
  },

  science: {
    plants: {
      title: "Plants & Life Cycle",
      icon: "🌸",
      items: [
        { q: "Male reproductive part of a flower?", a: "Stamen", opts: ["Petal", "Stamen", "Stigma", "Sepal"], ex: "Stamen makes pollen. Includes anther and filament." },
        { q: "What is pollination?", a: "Transfer of pollen from anther to stigma", opts: ["Watering a plant", "Transfer of pollen from anther to stigma", "Seed making", "Growing leaves"], ex: "First step in flower reproduction." },
        { q: "How do dandelion seeds spread?", a: "Wind", opts: ["Water", "Wind", "Animals", "Explosion"], ex: "Fluffy parachutes catch the breeze." },
        { q: "Coconut seeds spread mainly by?", a: "Water", opts: ["Wind", "Water", "Insects", "Birds"], ex: "Coconuts float across seas." },
        { q: "What attracts insects to flowers?", a: "Colour and scent", opts: ["Sharp leaves", "Colour and scent", "Loud sound", "Heat"], ex: "Bright petals plus sweet smell." },
        { q: "Where do seeds form inside a flower?", a: "Ovary", opts: ["Petal", "Anther", "Ovary", "Stem"], ex: "Ovules in the ovary become seeds after fertilisation." },
        { q: "Which is NOT a way seeds disperse?", a: "Photosynthesis", opts: ["Wind", "Water", "Animals", "Photosynthesis"], ex: "Photosynthesis = food making, not seed spreading." },
        { q: "What does a seed need to germinate?", a: "Water, warmth and air", opts: ["Only sunlight", "Only soil", "Water, warmth and air", "Only water"], ex: "Moisture, warmth and oxygen are key." },
      ],
    },
    "human-body": {
      title: "Human Body & Digestion",
      icon: "🧠",
      items: [
        { q: "Where does digestion begin?", a: "Mouth", opts: ["Stomach", "Mouth", "Small intestine", "Liver"], ex: "Chewing and saliva start digestion in the mouth." },
        { q: "Where are most nutrients absorbed?", a: "Small intestine", opts: ["Stomach", "Small intestine", "Large intestine", "Mouth"], ex: "Long and lined to absorb nutrients into blood." },
        { q: "Which vitamin do we get from sunlight?", a: "Vitamin D", opts: ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin K"], ex: "Skin makes Vitamin D in sunlight." },
        { q: "Which food group gives quick energy?", a: "Carbohydrates", opts: ["Proteins", "Fats", "Carbohydrates", "Vitamins"], ex: "Roti, rice, bread give quick energy." },
        { q: "What does the stomach do?", a: "Mixes food with acid and breaks it down", opts: ["Just stores food", "Mixes food with acid and breaks it down", "Absorbs all nutrients", "Removes waste"], ex: "Acid plus muscles churn food into thick liquid." },
        { q: "Protein-rich food example?", a: "Dal (lentils)", opts: ["Sugar", "Butter", "Dal (lentils)", "Rice"], ex: "Lentils, beans, eggs, milk are great protein sources." },
        { q: "How does fibre (roughage) help?", a: "Moves waste through the gut", opts: ["Gives energy", "Builds muscles", "Moves waste through the gut", "Makes us sleep"], ex: "Keeps digestion smooth and regular." },
        { q: "Liver's main role in digestion?", a: "Makes bile to break down fats", opts: ["Stores water", "Makes bile to break down fats", "Only filters blood", "Makes vitamins"], ex: "Bile splits big fat drops into tiny ones." },
      ],
    },
    "states-matter": {
      title: "States of Matter",
      icon: "💧",
      items: [
        { q: "Liquid → gas is called?", a: "Evaporation", opts: ["Condensation", "Evaporation", "Melting", "Freezing"], ex: "Heat lets liquid particles escape as gas." },
        { q: "Gas → liquid is called?", a: "Condensation", opts: ["Evaporation", "Condensation", "Boiling", "Freezing"], ex: "Water vapour cools to droplets, like dew." },
        { q: "In salt + water, which is the solute?", a: "Salt", opts: ["Salt", "Water", "Both", "Neither"], ex: "Solute = thing dissolved. Solvent = does the dissolving." },
        { q: "Steam from a kettle is which state?", a: "Gas", opts: ["Solid", "Liquid", "Gas", "Plasma"], ex: "Water vapour = gas state." },
        { q: "What speeds up evaporation?", a: "Higher temperature", opts: ["Lower temperature", "Higher temperature", "Less surface area", "More humidity"], ex: "Heat gives water more energy to escape." },
        { q: "Water at 0°C?", a: "Freezes", opts: ["Boils", "Freezes", "Evaporates", "Nothing"], ex: "Water turns to ice at 0°C." },
        { q: "Property of gases?", a: "Fill their container", opts: ["Fixed shape", "Fixed volume", "Fill their container", "Cannot be compressed"], ex: "Gas particles spread out fully." },
        { q: "A uniform mixture is a?", a: "Solution", opts: ["Mixture", "Solution", "Suspension", "Compound"], ex: "Solutions look the same throughout." },
      ],
    },
    forces: {
      title: "Forces & Magnetism",
      icon: "🧲",
      items: [
        { q: "Force pulling things to Earth?", a: "Gravity", opts: ["Friction", "Gravity", "Magnetism", "Push"], ex: "Gravity pulls toward Earth's centre." },
        { q: "Two north poles brought together?", a: "Repel", opts: ["Attract", "Repel", "Stick", "Nothing"], ex: "Like poles repel, opposites attract." },
        { q: "Which is magnetic?", a: "Iron", opts: ["Copper", "Iron", "Plastic", "Glass"], ex: "Iron, nickel, cobalt are magnetic." },
        { q: "Slows a book sliding across a table?", a: "Friction", opts: ["Gravity", "Friction", "Air resistance", "Magnetism"], ex: "Friction opposes motion between surfaces." },
        { q: "Air resistance is a type of?", a: "Friction", opts: ["Gravity", "Friction", "Magnetism", "Tension"], ex: "Air pushing against motion is friction." },
        { q: "What keeps a satellite in orbit?", a: "Gravity", opts: ["Friction", "Magnetism", "Gravity", "Wind"], ex: "Gravity pulls while forward motion balances." },
        { q: "Upthrust pushes objects?", a: "Up in water", opts: ["Down", "Up in water", "Stops them", "Bends them"], ex: "Buoyancy makes things float." },
        { q: "Maglev trains float using?", a: "Magnetic force", opts: ["Air pressure", "Magnetic force", "Steam", "Friction"], ex: "Magnets lift the train above the track." },
      ],
    },
    "earth-space": {
      title: "Earth & Space",
      icon: "🌍",
      items: [
        { q: "Earth's orbit around the Sun takes?", a: "About 365 days", opts: ["24 hours", "30 days", "About 365 days", "10 years"], ex: "One year = one full orbit." },
        { q: "What causes seasons?", a: "Tilt of Earth's axis", opts: ["Sun moving", "Tilt of Earth's axis", "Earth's distance", "Wind patterns"], ex: "Earth tilts ~23.5°. Different parts get more sun." },
        { q: "Closest planet to the Sun?", a: "Mercury", opts: ["Venus", "Earth", "Mercury", "Mars"], ex: "Mercury is smallest and closest." },
        { q: "Earth's natural satellite?", a: "Moon", opts: ["Sun", "Mars", "Moon", "Venus"], ex: "The Moon orbits Earth." },
        { q: "Earth spins on its axis in?", a: "24 hours", opts: ["1 hour", "12 hours", "24 hours", "365 days"], ex: "One spin = one day, causing day and night." },
        { q: "Largest planet?", a: "Jupiter", opts: ["Earth", "Saturn", "Jupiter", "Neptune"], ex: "Jupiter is huge, gas giant." },
        { q: "Red Planet?", a: "Mars", opts: ["Venus", "Mars", "Jupiter", "Mercury"], ex: "Red from iron oxide (rust)." },
        { q: "When one pole tips toward the Sun?", a: "It has long days, the other long nights", opts: ["Both dark", "Both bright", "It has long days, the other long nights", "Nothing changes"], ex: "Polar day vs polar night." },
      ],
    },
  },

  english: {
    "parts-of-speech": {
      title: "Parts of Speech",
      icon: "📚",
      items: [
        { q: "In 'She ran quickly,' which is the adverb?", a: "Quickly", opts: ["She", "Ran", "Quickly", "None"], ex: "Adverbs describe verbs. 'Quickly' tells how she ran." },
        { q: "Find the noun: 'The cat sat on the mat.'", a: "Cat and mat", opts: ["The", "Sat", "On", "Cat and mat"], ex: "Both 'cat' and 'mat' are things — nouns." },
        { q: "'Beautiful' is a/an?", a: "Adjective", opts: ["Noun", "Verb", "Adjective", "Adverb"], ex: "Adjectives describe nouns." },
        { q: "Pronoun for 'Rohan and I'?", a: "We", opts: ["He", "They", "We", "Us"], ex: "'We' is the subject pronoun including the speaker." },
        { q: "'Pune' is what kind of noun?", a: "Proper noun", opts: ["Common noun", "Proper noun", "Collective noun", "Abstract noun"], ex: "Specific place name. Always capitalised." },
        { q: "Which is a verb?", a: "Jump", opts: ["Happy", "Quickly", "Jump", "Blue"], ex: "Verbs are action words." },
        { q: "Find the adjective: 'The tall tree swayed.'", a: "Tall", opts: ["The", "Tall", "Tree", "Swayed"], ex: "'Tall' describes the tree." },
        { q: "'Honesty' is what kind of noun?", a: "Abstract noun", opts: ["Common noun", "Proper noun", "Abstract noun", "Collective noun"], ex: "Abstract nouns are ideas you can't touch." },
      ],
    },
    tenses: {
      title: "Tenses",
      icon: "⏰",
      items: [
        { q: "'She _____ to school yesterday.'", a: "Went", opts: ["Go", "Goes", "Went", "Going"], ex: "Yesterday = past tense." },
        { q: "Present continuous of 'write'?", a: "Is writing", opts: ["Writes", "Wrote", "Is writing", "Written"], ex: "is/am/are + verb-ing." },
        { q: "Past tense of 'teach'?", a: "Taught", opts: ["Teached", "Taught", "Teaching", "Teaches"], ex: "Irregular: teach → taught." },
        { q: "'They _____ for the bus right now.'", a: "Are waiting", opts: ["Wait", "Waited", "Are waiting", "Will wait"], ex: "'Right now' calls for present continuous." },
        { q: "'I _____ visit Pune next week.'", a: "Will", opts: ["Did", "Am", "Will", "Was"], ex: "Will + verb = future." },
        { q: "Past tense of 'run'?", a: "Ran", opts: ["Runned", "Ran", "Running", "Runs"], ex: "Irregular: run → ran → run." },
        { q: "'She _____ finished her homework.'", a: "Has", opts: ["Have", "Has", "Had", "Will"], ex: "Singular subject takes 'has'." },
        { q: "'We _____ a movie last Sunday.'", a: "Watched", opts: ["Watch", "Watching", "Watched", "Will watch"], ex: "Past tense, regular verb adds -ed." },
      ],
    },
    punctuation: {
      title: "Punctuation",
      icon: "✏️",
      items: [
        { q: "Which mark ends a question?", a: "?", opts: [".", "!", "?", ","], ex: "Question marks end interrogative sentences." },
        { q: "'The dog wagged ___ tail.'", a: "Its", opts: ["It's", "Its", "Its'", "Its's"], ex: "'Its' = possession. 'It's' = it is." },
        { q: "Best capitalisation: 'pune is in maharashtra.'", a: "Pune is in Maharashtra.", opts: ["pune is in Maharashtra.", "Pune is in maharashtra.", "Pune is in Maharashtra.", "PUNE IS IN MAHARASHTRA."], ex: "Sentence start + all proper nouns." },
        { q: "Commas in 'I bought apples bananas and grapes' go?", a: "After 'apples' and 'bananas'", opts: ["Only after apples", "Only after bananas", "After 'apples' and 'bananas'", "No commas"], ex: "Commas separate list items." },
        { q: "Which is correctly punctuated?", a: "Where are you going?", opts: ["Where are you going.", "Where are you going!", "Where are you going?", "where are you going"], ex: "Questions need a question mark + capital." },
        { q: "Apostrophe in 'children's books' shows?", a: "Possession", opts: ["Plural", "Contraction", "Possession", "Question"], ex: "The books belong to the children." },
        { q: "Choose the correct sentence:", a: "Aarav, Priya, and Karan went home.", opts: ["aarav, priya, and karan went home.", "Aarav Priya and Karan went home.", "Aarav, Priya, and Karan went home.", "Aarav, priya, and Karan went home."], ex: "Capitalise names, commas to separate." },
        { q: "What shows strong feeling?", a: "!", opts: [".", "!", "?", ":"], ex: "Exclamation marks show emotion." },
      ],
    },
    vocabulary: {
      title: "Vocabulary",
      icon: "💭",
      items: [
        { q: "Synonym for 'happy'?", a: "Joyful", opts: ["Sad", "Joyful", "Tired", "Angry"], ex: "Joyful, glad, cheerful all mean happy." },
        { q: "Antonym of 'ancient'?", a: "Modern", opts: ["Old", "Tired", "Modern", "Faded"], ex: "Ancient (old) vs Modern (new)." },
        { q: "'Punctual' means?", a: "On time", opts: ["Funny", "Late", "On time", "Polite"], ex: "Punctual people arrive on time." },
        { q: "A group of cattle?", a: "Herd", opts: ["Flock", "Swarm", "Herd", "Pack"], ex: "Herd of cattle, elephants, deer." },
        { q: "'Gigantic' means?", a: "Very large", opts: ["Very tiny", "Very fast", "Very large", "Very pretty"], ex: "Gigantic = huge, enormous." },
        { q: "Opposite of 'cautious'?", a: "Reckless", opts: ["Careful", "Reckless", "Smart", "Quiet"], ex: "Cautious = careful. Reckless = not careful." },
        { q: "A group of bees?", a: "Swarm", opts: ["Herd", "Pack", "Flock", "Swarm"], ex: "Swarm of bees, flock of birds." },
        { q: "Closest meaning to 'curious'?", a: "Eager to know", opts: ["Bored", "Eager to know", "Afraid", "Tired"], ex: "Curious people want to learn." },
      ],
    },
    "reading-skills": {
      title: "Reading Skills",
      icon: "📖",
      items: [
        { q: "'Setting' in a story means?", a: "Where and when it happens", opts: ["The main character", "Where and when it happens", "The problem", "The lesson"], ex: "Setting = time and place." },
        { q: "'Main idea' of a passage is?", a: "What it is mostly about", opts: ["First sentence", "What it is mostly about", "A funny detail", "Longest paragraph"], ex: "Central point, details support it." },
        { q: "To 'skim' a text means?", a: "Read quickly for the gist", opts: ["Read every word", "Read quickly for the gist", "Skip it", "Memorise it"], ex: "Skimming = fast reading for overall meaning." },
        { q: "Character's 'motivation' is?", a: "The reason they act", opts: ["Their look", "The reason they act", "Their friends", "The setting"], ex: "Motivation = why they do things." },
        { q: "Fiction is?", a: "Made-up stories", opts: ["True facts", "Made-up stories", "News reports", "Recipes"], ex: "Fiction = imaginary, non-fiction = real." },
        { q: "'Moral' of a story is?", a: "The lesson it teaches", opts: ["The funny bit", "The lesson it teaches", "The longest scene", "The first line"], ex: "Fables and tales end with a moral." },
        { q: "'Once upon a time' signals?", a: "A fairy tale", opts: ["A recipe", "A fairy tale", "A news article", "A diary"], ex: "Classic fairy tale opening." },
        { q: "A passage on making rangoli is?", a: "How-to / instructional", opts: ["A poem", "How-to / instructional", "A biography", "A mystery"], ex: "How-to texts give step-by-step instructions." },
      ],
    },
  },

  hindi: {
    "vyakaran-basics": {
      title: "व्याकरण के मूल",
      icon: "📜",
      items: [
        { q: "'लड़का' शब्द किस लिंग का है?", a: "पुल्लिंग", opts: ["स्त्रीलिंग", "पुल्लिंग", "नपुंसकलिंग", "उभयलिंग"], ex: "पुरुष जाति के शब्द पुल्लिंग कहलाते हैं।" },
        { q: "'किताबें' किस वचन में है?", a: "बहुवचन", opts: ["एकवचन", "बहुवचन", "द्विवचन", "कोई नहीं"], ex: "एक से अधिक का बोध कराने वाले शब्द बहुवचन।" },
        { q: "सर्वनाम का सही उदाहरण?", a: "मैं, तुम, वह", opts: ["राम, सीता", "लड़का, लड़की", "मैं, तुम, वह", "खाना, पीना"], ex: "सर्वनाम संज्ञा के स्थान पर प्रयोग होते हैं।" },
        { q: "'दौड़ना' शब्द है?", a: "क्रिया", opts: ["संज्ञा", "सर्वनाम", "विशेषण", "क्रिया"], ex: "कार्य बताने वाला शब्द क्रिया है।" },
        { q: "'अच्छा' किस श्रेणी का है?", a: "विशेषण", opts: ["संज्ञा", "क्रिया", "विशेषण", "अव्यय"], ex: "संज्ञा की विशेषता बताने वाला शब्द।" },
        { q: "'मुंबई' शब्द?", a: "व्यक्तिवाचक संज्ञा", opts: ["जातिवाचक", "व्यक्तिवाचक संज्ञा", "भाववाचक", "समूहवाचक"], ex: "विशेष नाम।" },
        { q: "'सेना' शब्द?", a: "समूहवाचक संज्ञा", opts: ["जातिवाचक", "व्यक्तिवाचक", "भाववाचक", "समूहवाचक संज्ञा"], ex: "समूह को दर्शाने वाले शब्द।" },
        { q: "'सुंदरता' शब्द?", a: "भाववाचक संज्ञा", opts: ["जातिवाचक", "व्यक्तिवाचक", "भाववाचक संज्ञा", "समूहवाचक"], ex: "गुण-भाव बताने वाली संज्ञा।" },
      ],
    },
    "vilom-paryayvachi": {
      title: "विलोम और पर्यायवाची",
      icon: "🔄",
      items: [
        { q: "'दिन' का विलोम?", a: "रात", opts: ["सुबह", "शाम", "रात", "दोपहर"], ex: "विलोम = उल्टा/विपरीत।" },
        { q: "'जल' का पर्यायवाची?", a: "पानी", opts: ["आग", "पानी", "हवा", "मिट्टी"], ex: "जल, पानी, नीर, अंबु।" },
        { q: "'अमीर' का विलोम?", a: "गरीब", opts: ["धनी", "गरीब", "महंगा", "ऊँचा"], ex: "धनी के विपरीत गरीब।" },
        { q: "'सूर्य' का पर्यायवाची?", a: "रवि", opts: ["चाँद", "तारा", "रवि", "बादल"], ex: "सूर्य = रवि, भानु, दिनकर।" },
        { q: "'मित्र' का विलोम?", a: "शत्रु", opts: ["भाई", "साथी", "शत्रु", "दोस्त"], ex: "दोस्त का उल्टा दुश्मन।" },
        { q: "'पुष्प' का पर्यायवाची?", a: "फूल", opts: ["फल", "फूल", "पत्ता", "जड़"], ex: "पुष्प, फूल, सुमन।" },
        { q: "'सच' का विलोम?", a: "झूठ", opts: ["सही", "ठीक", "झूठ", "साफ"], ex: "सच के विपरीत झूठ।" },
        { q: "'घर' का पर्यायवाची?", a: "मकान", opts: ["स्कूल", "मकान", "खेत", "बाग"], ex: "घर = मकान, गृह, आवास।" },
      ],
    },
    muhavare: {
      title: "मुहावरे",
      icon: "💬",
      items: [
        { q: "'नौ दो ग्यारह होना'?", a: "भाग जाना", opts: ["गिनती करना", "भाग जाना", "मिल जाना", "खुश होना"], ex: "चुपचाप भाग जाना।" },
        { q: "'आँखों का तारा'?", a: "बहुत प्यारा", opts: ["रोना", "बहुत प्यारा", "देखना", "सोना"], ex: "किसी का बहुत प्रिय व्यक्ति।" },
        { q: "'कान भरना'?", a: "चुगली करना", opts: ["सुनना", "गाना", "चुगली करना", "सोना"], ex: "गलत बात दूसरे से कहना।" },
        { q: "'हाथ पर हाथ रखना'?", a: "कुछ न करना", opts: ["मदद करना", "कुछ न करना", "ताली बजाना", "नमस्ते करना"], ex: "खाली बैठे रहना।" },
        { q: "'पीठ दिखाना'?", a: "भागना", opts: ["सोना", "मिलना", "भागना", "हँसना"], ex: "मुकाबले से डरकर भाग जाना।" },
        { q: "'दाँत खट्टे करना'?", a: "हराना", opts: ["खाना", "हँसना", "हराना", "रोना"], ex: "बुरी तरह हराना।" },
        { q: "'सिर पर चढ़ाना'?", a: "अधिक लाड़ करना", opts: ["ऊँचा उठाना", "अधिक लाड़ करना", "नमस्कार", "बात मानना"], ex: "जरूरत से ज्यादा लाड़।" },
        { q: "'नाक में दम करना'?", a: "बहुत परेशान करना", opts: ["खुश करना", "बहुत परेशान करना", "हँसाना", "सोना"], ex: "बहुत तंग करना।" },
      ],
    },
    sankhya: {
      title: "संख्या",
      icon: "🔢",
      items: [
        { q: "'पच्चीस' = ?", a: "25", opts: ["20", "25", "30", "52"], ex: "पच्चीस = 25।" },
        { q: "'सौ' = ?", a: "100", opts: ["10", "50", "100", "1000"], ex: "सौ = 100।" },
        { q: "'दो हज़ार' = ?", a: "2000", opts: ["200", "2000", "20000", "20"], ex: "दो हज़ार = 2000।" },
        { q: "'सत्तर' = ?", a: "70", opts: ["17", "70", "77", "27"], ex: "सत्तर = 70।" },
        { q: "'पचास' = ?", a: "50", opts: ["15", "50", "55", "500"], ex: "पचास = 50।" },
        { q: "'इकतीस' = ?", a: "31", opts: ["13", "31", "30", "21"], ex: "इकतीस = 31।" },
      ],
    },
  },

  marathi: {
    vyakaran: {
      title: "व्याकरण",
      icon: "📜",
      items: [
        { q: "'मुलगी' हे कोणत्या वचनात?", a: "एकवचन", opts: ["एकवचन", "अनेकवचन", "द्विवचन", "नाही"], ex: "एका व्यक्तीचा बोध = एकवचन." },
        { q: "'मुली' हे कोणत्या वचनात?", a: "अनेकवचन", opts: ["एकवचन", "अनेकवचन", "द्विवचन", "नाही"], ex: "एकापेक्षा जास्तीचा बोध." },
        { q: "सर्वनामाचे उदाहरण?", a: "मी, तू, तो", opts: ["राम, सीता", "मुलगा, मुलगी", "मी, तू, तो", "खाणे, पिणे"], ex: "नामाऐवजी वापरले जाणारे शब्द." },
        { q: "'खेळणे' हे काय?", a: "क्रियापद", opts: ["नाम", "सर्वनाम", "विशेषण", "क्रियापद"], ex: "क्रिया दाखवणारा शब्द." },
        { q: "'सुंदर' कोणता शब्द?", a: "विशेषण", opts: ["नाम", "क्रियापद", "विशेषण", "सर्वनाम"], ex: "नामाचे गुण दाखवणारा." },
        { q: "'पुणे' कोणते नाम?", a: "विशेषनाम", opts: ["सामान्यनाम", "विशेषनाम", "भाववाचक", "समूहवाचक"], ex: "विशिष्ट स्थळ." },
        { q: "'गोडवा' कोणते नाम?", a: "भाववाचक नाम", opts: ["सामान्यनाम", "विशेषनाम", "भाववाचक नाम", "समूहवाचक"], ex: "गुण-भाव दर्शविणारे." },
        { q: "'पुस्तके' कोणत्या वचनात?", a: "अनेकवचन", opts: ["एकवचन", "अनेकवचन", "द्विवचन", "नाही"], ex: "अनेक पुस्तके." },
      ],
    },
    "samanarthi-virudharthi": {
      title: "समानार्थी आणि विरुद्धार्थी",
      icon: "🔄",
      items: [
        { q: "'सूर्य' चा समानार्थी?", a: "रवी", opts: ["चंद्र", "रवी", "तारा", "ढग"], ex: "रवी, भास्कर, दिनकर." },
        { q: "'उजेड' चा विरुद्धार्थी?", a: "अंधार", opts: ["प्रकाश", "अंधार", "किरण", "दिवा"], ex: "उजेडाच्या उलट." },
        { q: "'मोठा' चा विरुद्धार्थी?", a: "लहान", opts: ["जाड", "लहान", "उंच", "रुंद"], ex: "मोठ्याच्या उलट लहान." },
        { q: "'घर' चा समानार्थी?", a: "निवास", opts: ["शाळा", "निवास", "बाग", "रस्ता"], ex: "घर = निवास, गृह." },
        { q: "'मित्र' चा विरुद्धार्थी?", a: "शत्रू", opts: ["भाऊ", "मित्र", "शत्रू", "सोबती"], ex: "मित्राच्या उलट शत्रू." },
        { q: "'पुष्प' चा समानार्थी?", a: "फूल", opts: ["फळ", "फूल", "पान", "मूळ"], ex: "पुष्प, फूल, सुमन." },
        { q: "'खरे' चा विरुद्धार्थी?", a: "खोटे", opts: ["चांगले", "खोटे", "नवीन", "जुने"], ex: "सत्याच्या उलट खोटे." },
        { q: "'पाणी' चा समानार्थी?", a: "जल", opts: ["वारा", "जल", "अग्नी", "मातीच"], ex: "पाणी = जल, उदक." },
      ],
    },
    mhani: {
      title: "म्हणी आणि वाक्प्रचार",
      icon: "💬",
      items: [
        { q: "'अति तेथे माती'?", a: "अति केल्यास नुकसान होते", opts: ["खूप काम करा", "अति केल्यास नुकसान होते", "मातीवर बसा", "धावत जा"], ex: "अतिरेक हानिकारक." },
        { q: "'नाचता येईना अंगण वाकडे'?", a: "स्वतःची चूक न मानता दुसऱ्यावर दोष", opts: ["चांगले नाचणे", "अंगण साफ", "स्वतःची चूक न मानता दुसऱ्यावर दोष", "सजावट"], ex: "स्वतःचा कमकुवतपणा दुसऱ्यावर ढकलणे." },
        { q: "'थेंबे थेंबे तळे साचे'?", a: "थोडे थोडे जमवल्याने मोठे होते", opts: ["पाऊस", "पोहणे", "थोडे थोडे जमवल्याने मोठे होते", "थेंब मोजणे"], ex: "हळूहळू मोठे यश." },
        { q: "'हात ओला तर मित्र भला'?", a: "पैसा असेल तर मित्र असतात", opts: ["हात धुणे", "स्वच्छता", "पैसा असेल तर मित्र असतात", "मित्र शोधणे"], ex: "पैसा-सत्ता असताना सगळे मित्र." },
        { q: "'अंथरूण पाहून पाय पसरावे'?", a: "ऐपतीप्रमाणे खर्च करावा", opts: ["झोपताना", "ऐपतीप्रमाणे खर्च करावा", "अंथरूण मोठे", "व्यायाम"], ex: "मर्यादेत निर्णय." },
        { q: "'बैल गेला आणि झोपा केला'?", a: "वेळ निघून गेल्यावर उपाय", opts: ["बैलाला झोपवणे", "वेळ निघून गेल्यावर उपाय", "शेतात जाणे", "घर बांधणे"], ex: "उशीरा पश्चात्ताप." },
      ],
    },
    "maharashtra-info": {
      title: "महाराष्ट्र विशेष",
      icon: "🏛️",
      items: [
        { q: "महाराष्ट्राची राजधानी?", a: "मुंबई", opts: ["पुणे", "मुंबई", "नागपूर", "नाशिक"], ex: "मुंबई ही राजधानी." },
        { q: "महाराष्ट्र दिन?", a: "१ मे", opts: ["२६ जानेवारी", "१ मे", "१५ ऑगस्ट", "२ ऑक्टोबर"], ex: "१ मे १९६० रोजी राज्याची स्थापना." },
        { q: "शिवाजी महाराजांच्या आईचे नाव?", a: "जिजाबाई", opts: ["सईबाई", "जिजाबाई", "सोयराबाई", "ताराबाई"], ex: "जिजाबाई महाराजांच्या आई." },
        { q: "पुणे शहर कोणत्या नदीच्या काठावर?", a: "मुळा-मुठा", opts: ["गोदावरी", "कृष्णा", "मुळा-मुठा", "तापी"], ex: "मुळा आणि मुठा संगम." },
        { q: "महाराष्ट्राचे राज्यफूल?", a: "ताम्हण (जारुळ)", opts: ["गुलाब", "कमळ", "ताम्हण (जारुळ)", "मोगरा"], ex: "ताम्हण/जारुळ." },
        { q: "महाराष्ट्राचे राज्यप्राणी?", a: "शेकरू", opts: ["वाघ", "सिंह", "शेकरू", "हत्ती"], ex: "शेकरू (मोठी खार)." },
      ],
    },
  },

  gk: {
    india: {
      title: "भारत",
      icon: "🇮🇳",
      items: [
        { q: "Capital of India?", a: "New Delhi", opts: ["Mumbai", "New Delhi", "Kolkata", "Chennai"], ex: "New Delhi is the capital." },
        { q: "National animal of India?", a: "Tiger", opts: ["Lion", "Elephant", "Tiger", "Peacock"], ex: "Royal Bengal Tiger." },
        { q: "National bird?", a: "Peacock", opts: ["Eagle", "Peacock", "Parrot", "Crow"], ex: "Indian Peacock." },
        { q: "How many states in India?", a: "28", opts: ["26", "28", "29", "30"], ex: "28 states + 8 UTs." },
        { q: "National flower?", a: "Lotus", opts: ["Rose", "Marigold", "Lotus", "Jasmine"], ex: "Lotus represents purity." },
        { q: "National anthem?", a: "Jana Gana Mana", opts: ["Vande Mataram", "Jana Gana Mana", "Sare Jahan Se Achha", "Hind Desh"], ex: "Written by Rabindranath Tagore." },
        { q: "Largest state by area?", a: "Rajasthan", opts: ["MP", "Maharashtra", "Rajasthan", "UP"], ex: "Rajasthan = biggest." },
        { q: "Father of the Nation?", a: "Mahatma Gandhi", opts: ["Nehru", "Mahatma Gandhi", "Bose", "Ambedkar"], ex: "Gandhi led independence movement." },
      ],
    },
    pune: {
      title: "Pune & Around",
      icon: "🏰",
      items: [
        { q: "Pune was historically the seat of?", a: "Maratha Empire", opts: ["Mughal", "Maratha Empire", "Chola", "Vijayanagar"], ex: "Maratha capital under Peshwas." },
        { q: "Famous fort, battle of Sinhagad?", a: "Sinhagad", opts: ["Raigad", "Sinhagad", "Pratapgad", "Shivneri"], ex: "Tanaji's famous battle here." },
        { q: "Peshwas' palace in Pune?", a: "Shaniwar Wada", opts: ["Aga Khan Palace", "Shaniwar Wada", "Vishrambaug Wada", "Lal Mahal"], ex: "Built in 1732." },
        { q: "Pune's IT hub?", a: "Hinjewadi", opts: ["Camp", "Hinjewadi", "Koregaon Park", "FC Road"], ex: "Rajiv Gandhi Infotech Park." },
        { q: "Shivaji Maharaj's birthplace fort?", a: "Shivneri", opts: ["Raigad", "Sinhagad", "Shivneri", "Lohagad"], ex: "Shivneri near Junnar." },
        { q: "Pune is famous for which festival?", a: "Ganesh Chaturthi", opts: ["Holi", "Diwali", "Ganesh Chaturthi", "Navratri"], ex: "Lokmanya Tilak revived public celebration in 1893." },
      ],
    },
    world: {
      title: "World Geography",
      icon: "🌐",
      items: [
        { q: "Largest continent?", a: "Asia", opts: ["Africa", "Asia", "Europe", "North America"], ex: "Asia: biggest by area and population." },
        { q: "Longest river?", a: "Nile", opts: ["Amazon", "Ganges", "Nile", "Yangtze"], ex: "Nile = 6,650 km." },
        { q: "Highest mountain?", a: "Mount Everest", opts: ["K2", "Kanchenjunga", "Mount Everest", "Annapurna"], ex: "Everest = 8,849 m." },
        { q: "Smallest country?", a: "Vatican City", opts: ["Monaco", "Vatican City", "Maldives", "Nauru"], ex: "Vatican City inside Rome." },
        { q: "Largest ocean?", a: "Pacific", opts: ["Atlantic", "Indian", "Pacific", "Arctic"], ex: "Pacific covers 1/3 of Earth." },
        { q: "Largest hot desert?", a: "Sahara", opts: ["Gobi", "Thar", "Sahara", "Kalahari"], ex: "Sahara stretches across North Africa." },
      ],
    },
    space: {
      title: "Space & Universe",
      icon: "🚀",
      items: [
        { q: "Planets in our solar system?", a: "8", opts: ["7", "8", "9", "10"], ex: "Mercury to Neptune." },
        { q: "Largest planet?", a: "Jupiter", opts: ["Earth", "Saturn", "Jupiter", "Neptune"], ex: "1000+ Earths fit inside." },
        { q: "Star at center of solar system?", a: "Sun", opts: ["Polaris", "Sirius", "Sun", "Alpha Centauri"], ex: "Yellow dwarf star." },
        { q: "Our galaxy?", a: "Milky Way", opts: ["Andromeda", "Milky Way", "Whirlpool", "Triangulum"], ex: "Spiral galaxy." },
        { q: "First Indian in space?", a: "Rakesh Sharma", opts: ["Kalpana Chawla", "Rakesh Sharma", "Sunita Williams", "Vikram Sarabhai"], ex: "Soyuz T-11 in 1984." },
        { q: "ISRO's famous Mars mission?", a: "Mangalyaan", opts: ["Chandrayaan", "Mangalyaan", "Gaganyaan", "Aditya"], ex: "Mars Orbiter, reached 2014." },
      ],
    },
    "famous-people": {
      title: "Famous People",
      icon: "🎖️",
      items: [
        { q: "Wrote India's national anthem?", a: "Rabindranath Tagore", opts: ["Bankim Chandra", "Rabindranath Tagore", "Sarojini Naidu", "Bharati"], ex: "Nobel Prize for Literature." },
        { q: "First PM of India?", a: "Jawaharlal Nehru", opts: ["Gandhi", "Jawaharlal Nehru", "Patel", "Indira"], ex: "PM since 1947." },
        { q: "Architect of the Constitution?", a: "Dr. B.R. Ambedkar", opts: ["Nehru", "Patel", "Dr. B.R. Ambedkar", "Rajagopalachari"], ex: "Chaired the drafting committee." },
        { q: "Missile Man of India?", a: "Dr. A.P.J. Abdul Kalam", opts: ["Sarabhai", "Dr. A.P.J. Abdul Kalam", "Bhabha", "C.V. Raman"], ex: "Led missile programs, became 11th President." },
        { q: "First woman PM of India?", a: "Indira Gandhi", opts: ["Sonia Gandhi", "Indira Gandhi", "Sushma Swaraj", "Pratibha Patil"], ex: "PM 1966-77 and 1980-84." },
        { q: "Father of Indian Space Programme?", a: "Vikram Sarabhai", opts: ["Bhabha", "Vikram Sarabhai", "C.V. Raman", "Kalam"], ex: "Founded ISRO in 1969." },
      ],
    },
  },
};
